// Sharp LR35902 operand/addressing grammar.
architecture_instruction = { SOI ~ architecture_ws ~ architecture_mnemonic ~ (architecture_ws1 ~ architecture_operands)? ~ architecture_ws ~ EOI }
architecture_mnemonic = { architecture_atom }
architecture_operands = { lr35902_operand ~ (architecture_ws ~ architecture_comma ~ architecture_ws ~ lr35902_operand)* }
lr35902_operand = { lr35902_element ~ (architecture_ws ~ lr35902_element)* }
lr35902_element = _{ lr35902_parenthesized | lr35902_bracketed | architecture_double_quoted | architecture_single_quoted | architecture_operator | architecture_atom }
lr35902_nested_element = _{ lr35902_parenthesized | lr35902_bracketed | architecture_double_quoted | architecture_single_quoted | architecture_comma | architecture_operator | architecture_atom }
lr35902_parenthesized = { architecture_lparen ~ architecture_ws ~ lr35902_nested_element ~ (architecture_ws ~ lr35902_nested_element)* ~ architecture_ws ~ architecture_rparen }
lr35902_bracketed = { architecture_lbracket ~ architecture_ws ~ lr35902_nested_element ~ (architecture_ws ~ lr35902_nested_element)* ~ architecture_ws ~ architecture_rbracket }
