[workspace]
resolver = "2"
members = [".", "crates/ezrac-cli"]
default-members = [".", "crates/ezrac-cli"]
exclude = ["dos"]

[package]
name = "ezra-core"
version = "0.1.35"
edition = "2024"
description = "Core compiler library for the EZRA language"
license = "BSD-3-Clause"
repository = "https://github.com/isaiahpettingill/ezrac"

[lib]
name = "ezra"

[dependencies]
dcpu = { package = "dcpu16-core", version = "0.1.0", default-features = false, optional = true }
ez80 = { version = "0.6.0", optional = true }
pic18-emulator = { version = "0.1.2", optional = true, default-features = false }
mos6502 = { version = "0.10.1", optional = true }
m6800 = { version = "0.1.0", optional = true }
mc6809-core = { version = "0.3.2", optional = true }
m68000 = { version = "0.2.3", optional = true }
hashbrown = { version = "0.15.5", default-features = false, features = ["default-hasher", "inline-more"] }
pest = { version = "2.8.7", default-features = false }
pest_derive = { version = "2.8.7", default-features = false }
toml = { version = "1.1.2", optional = true }
miniz_oxide = { version = "0.8.9", default-features = false, features = ["with-alloc"] }

[dev-dependencies]
png = "0.18.1"
libre99-core = { git = "https://github.com/isaiahpettingill/libre99.git", rev = "6c86f10bae65f4cc3bdc13289e14bb20af03ab61" }
libre99-asm = { git = "https://github.com/isaiahpettingill/libre99.git", rev = "6c86f10bae65f4cc3bdc13289e14bb20af03ab61" }
mspsim = { package = "mspsim-rs", version = "0.1.0" }
avr-emulator = "0.1.2"
w65c816 = "0.1.17"

[features]
default = [
    "std",
    "test-runner",
    "intel",
    "i8086",
    "z80",
    "lr35902",
    "avr",
    "m6800",
    "m6809",
    "m68k",
    "mos6502",
    "msp430",
    "tms9900",
    "dcpu",
    "pic18",
]
std = ["dep:toml", "pest/std", "pest_derive/std"]
no-std = []
test-runner = ["std", "dep:ez80"]
intel = []
i8086 = []
z80 = []
lr35902 = []
lsp = []
avr = []
m6800 = ["dep:m6800"]
m6809 = ["dep:mc6809-core"]
m68k = ["dep:m68000"]
mos6502 = []
mos6502-emulator = ["mos6502", "std", "test-runner", "dep:mos6502"]
msp430 = []
tms9900 = []
dcpu = ["dep:dcpu"]
pic18 = ["dep:pic18-emulator"]
