use std::collections::HashMap;

use crate::{
    asm::{AssemblyOptions, comments::with_readability_comments},
    ast::{AssignOp, BinaryOp, Expr, Type, UnaryOp},
    diagnostic::Diagnostic,
    hir::HirProgram,
    target::CpuFamily,
    tbir::{TbirDeclaration, TbirProgram, TbirStmt},
};

/// Emits the small, currently supported DCPU-16 subset from the common HIR/TBIR pipeline.
pub fn emit_dcpu_assembly_with_options(
    program: &crate::ast::Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    if options.cpu != CpuFamily::Dcpu {
        return Err(Diagnostic::new("DCPU-16 emitter requires a DCPU-16 target"));
    }
    if program.main_function().is_none() {
        return Err(Diagnostic::new(
            "DCPU-16 programs require a `main` function",
        ));
    }

    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    Emitter::new()
        .emit(&tbir)
        .map(|asm| with_readability_comments(asm, program, &options, "dcpu"))
}

struct Emitter {
    out: String,
    locals: HashMap<String, &'static str>,
    local_types: HashMap<String, Type>,
    next_register: usize,
}

impl Emitter {
    fn new() -> Self {
        Self {
            out: String::new(),
            locals: HashMap::new(),
            local_types: HashMap::new(),
            // I and J are reserved for expression temporaries.
            next_register: 0,
        }
    }

    fn emit(mut self, program: &TbirProgram) -> Result<String, Diagnostic> {
        let mut main = None;
        let inline_functions = program.optimizations.inline_function_names();
        for declaration in &program.declarations {
            match declaration {
                TbirDeclaration::Function {
                    name,
                    params,
                    return_type,
                    body,
                    ..
                } if name == "main" => {
                    if !params.is_empty() || return_type.is_some() {
                        return Err(Diagnostic::new(
                            "DCPU-16 `main` must not have parameters or a return value",
                        ));
                    }
                    main = Some(body.as_slice());
                }
                TbirDeclaration::Function {
                    name, attrs, body, ..
                } if inline_functions.contains(name)
                    || (attrs.iter().any(|attr| attr == "inline")
                        && body.iter().any(|stmt| matches!(stmt, TbirStmt::Asm { .. }))) => {}
                TbirDeclaration::Function { name, .. } => {
                    return Err(Diagnostic::new(format!(
                        "DCPU-16 emitter currently supports only `main`; function `{name}` is unsupported"
                    )));
                }
                TbirDeclaration::Object {
                    kind: crate::tbir::TbirObjectKind::Const,
                    ..
                } => {}
                TbirDeclaration::Object { name, kind } => {
                    return Err(Diagnostic::new(format!(
                        "DCPU-16 emitter does not yet support {kind:?} declaration `{name}`"
                    )));
                }
            }
        }
        let main =
            main.ok_or_else(|| Diagnostic::new("DCPU-16 programs require a `main` function"))?;

        self.line("; generated by ezrac");
        self.line("; target: DCPU-16");
        self.line("__ezra_start:");
        self.line("    jsr _main");
        self.line("__ezra_exit:");
        self.line("    set pc, __ezra_exit");
        self.line("_main:");
        self.emit_block(main)?;
        self.line("    set pc, pop");
        Ok(self.out)
    }

    fn emit_block(&mut self, statements: &[TbirStmt]) -> Result<(), Diagnostic> {
        for statement in statements {
            self.emit_stmt(statement)?;
        }
        Ok(())
    }

    fn emit_stmt(&mut self, statement: &TbirStmt) -> Result<(), Diagnostic> {
        match statement {
            TbirStmt::Let { name, ty, value } => {
                self.require_scalar_type(ty, &format!("local `{name}`"))?;
                let register = self.allocate_local(name)?;
                self.local_types.insert(name.clone(), ty.clone());
                self.emit_expr(value, register)
            }
            TbirStmt::Assign { target, op, value } => {
                let crate::ast::Place::Ident(name) = target else {
                    return Err(Diagnostic::new(
                        "DCPU-16 emitter currently supports assignment to local scalar variables only",
                    ));
                };
                let register = self.local(name)?;
                if *op == AssignOp::Set {
                    self.emit_expr(value, register)
                } else {
                    self.line(&format!("    set push, {register}"));
                    self.emit_expr(value, register)?;
                    self.line("    set j, pop");
                    let signed = type_is_signed(self.local_type(name)?);
                    self.line(&format!(
                        "    {} j, {register}",
                        assign_opcode(*op, signed)?
                    ));
                    self.line(&format!("    set {register}, j"));
                    Ok(())
                }
            }
            TbirStmt::Asm {
                inputs,
                outputs,
                lines,
                ..
            } => {
                if !outputs.is_empty() {
                    return Err(Diagnostic::new(
                        "DCPU-16 inline asm outputs are not yet supported",
                    ));
                }
                let mut operands = HashMap::new();
                for input in inputs {
                    self.require_scalar_type(
                        &input.ty,
                        &format!("inline asm input `{}`", input.name),
                    )?;
                    if input.class != "reg16" {
                        return Err(Diagnostic::new(format!(
                            "DCPU-16 inline asm input `{}` must use `reg16`",
                            input.name
                        )));
                    }
                    let register = self.local(&input.name)?;
                    if operands.insert(input.name.clone(), register).is_some() {
                        return Err(Diagnostic::new(format!(
                            "duplicate DCPU-16 inline asm operand `{}`",
                            input.name
                        )));
                    }
                }
                for line in lines {
                    let mut emitted = line.clone();
                    for (name, register) in &operands {
                        emitted = emitted.replace(&format!("{{{name}}}"), register);
                    }
                    if emitted.contains(['{', '}']) {
                        return Err(Diagnostic::new(format!(
                            "DCPU-16 inline asm has an unresolved operand placeholder in `{line}`"
                        )));
                    }
                    self.line(&format!("    {emitted}"));
                }
                Ok(())
            }
            TbirStmt::Return(None) => {
                self.line("    set pc, pop");
                Ok(())
            }
            TbirStmt::Return(Some(_)) => Err(Diagnostic::new(
                "DCPU-16 emitter does not yet support return values",
            )),
            TbirStmt::Eval(expr) => self.emit_expr(expr, "j"),
            TbirStmt::If { .. }
            | TbirStmt::While { .. }
            | TbirStmt::Loop { .. }
            | TbirStmt::Break
            | TbirStmt::Continue => Err(Diagnostic::new(
                "DCPU-16 emitter does not yet support control-flow statements",
            )),
            TbirStmt::PortWrite { port, .. } => Err(Diagnostic::new(format!(
                "DCPU-16 does not support separate port I/O `{port}`"
            ))),
        }
    }

    fn emit_expr(&mut self, expr: &Expr, destination: &str) -> Result<(), Diagnostic> {
        match expr {
            Expr::Int(value) => self.set_literal(destination, *value),
            Expr::TypedInt(value, ty) => {
                self.require_scalar_type(ty, "integer literal")?;
                self.set_literal(destination, *value)
            }
            Expr::Bool(value) => {
                self.line(&format!("    set {destination}, {}", u16::from(*value)));
                Ok(())
            }
            Expr::Char(value) => {
                self.line(&format!("    set {destination}, {value}"));
                Ok(())
            }
            Expr::Ident(name) => {
                let source = self.local(name)?;
                if source != destination {
                    self.line(&format!("    set {destination}, {source}"));
                }
                Ok(())
            }
            Expr::Cast { ty, expr } => {
                self.require_scalar_type(ty, "cast")?;
                self.emit_expr(expr, destination)
            }
            Expr::Unary { op, expr } => {
                self.emit_expr(expr, destination)?;
                match op {
                    UnaryOp::Neg => {
                        self.line("    set j, 0");
                        self.line(&format!("    sub j, {destination}"));
                        self.line(&format!("    set {destination}, j"));
                    }
                    UnaryOp::BitNot => self.line(&format!("    xor {destination}, 0xffff")),
                    UnaryOp::Not => {
                        self.line("    set j, 0");
                        self.emit_comparison(destination, "ife", "j");
                    }
                }
                Ok(())
            }
            Expr::Binary { left, op, right } => {
                self.emit_expr(left, destination)?;
                self.line(&format!("    set push, {destination}"));
                self.emit_expr(right, destination)?;
                self.line("    set j, pop");
                match op {
                    BinaryOp::Eq => self.emit_comparison(destination, "ife", "j"),
                    BinaryOp::Ne => self.emit_comparison(destination, "ifn", "j"),
                    BinaryOp::Lt => self.emit_comparison(destination, "ifl", "j"),
                    BinaryOp::Gt => self.emit_comparison(destination, "ifg", "j"),
                    BinaryOp::Le | BinaryOp::Ge | BinaryOp::And | BinaryOp::Or => {
                        return Err(Diagnostic::new(format!(
                            "DCPU-16 emitter does not yet support binary operator `{op:?}`"
                        )));
                    }
                    _ => {
                        let signed = type_is_signed(&self.expr_type(left)?);
                        self.line(&format!(
                            "    {} j, {destination}",
                            binary_opcode(*op, signed)?
                        ));
                        self.line(&format!("    set {destination}, j"));
                    }
                }
                Ok(())
            }
            _ => Err(Diagnostic::new(format!(
                "DCPU-16 emitter does not yet support expression `{expr:?}`"
            ))),
        }
    }

    /// Compares J against the current destination value and leaves a boolean in destination.
    fn emit_comparison(&mut self, destination: &str, instruction: &str, left: &str) {
        self.line(&format!("    set i, {destination}"));
        self.line(&format!("    set {destination}, 0"));
        self.line(&format!("    {instruction} {left}, i"));
        self.line(&format!("    set {destination}, 1"));
    }

    fn set_literal(&mut self, destination: &str, value: i64) -> Result<(), Diagnostic> {
        let value = u16::try_from(value).map_err(|_| {
            Diagnostic::new(format!(
                "DCPU-16 literal `{value}` is outside the 16-bit range"
            ))
        })?;
        self.line(&format!("    set {destination}, 0x{value:04x}"));
        Ok(())
    }

    fn expr_type(&self, expr: &Expr) -> Result<Type, Diagnostic> {
        match expr {
            Expr::TypedInt(_, ty) | Expr::Cast { ty, .. } => Ok(ty.clone()),
            Expr::Ident(name) => Ok(self.local_type(name)?.clone()),
            Expr::Binary { left, .. } | Expr::Unary { expr: left, .. } => self.expr_type(left),
            Expr::Int(_) | Expr::Char(_) => Ok(Type::Named("u16".to_owned())),
            Expr::Bool(_) => Ok(Type::Named("bool".to_owned())),
            _ => Err(Diagnostic::new(format!(
                "DCPU-16 emitter cannot determine the type of expression `{expr:?}`"
            ))),
        }
    }

    fn require_scalar_type(&self, ty: &Type, context: &str) -> Result<(), Diagnostic> {
        match ty {
            Type::Named(name) if matches!(name.as_str(), "bool" | "u8" | "i8" | "u16" | "i16") => {
                Ok(())
            }
            _ => Err(Diagnostic::new(format!(
                "DCPU-16 emitter supports only bool, u8, i8, u16, and i16 scalar values; unsupported {context} type `{ty:?}`"
            ))),
        }
    }

    fn allocate_local(&mut self, name: &str) -> Result<&'static str, Diagnostic> {
        const REGISTERS: [&str; 8] = ["a", "b", "c", "x", "y", "z", "i", "j"];
        if self.locals.contains_key(name) {
            return Err(Diagnostic::new(format!("duplicate DCPU-16 local `{name}`")));
        }
        let register = *REGISTERS.get(self.next_register).ok_or_else(|| {
            Diagnostic::new("DCPU-16 emitter currently supports at most six local scalar variables")
        })?;
        self.next_register += 1;
        self.locals.insert(name.to_owned(), register);
        Ok(register)
    }

    fn local(&self, name: &str) -> Result<&'static str, Diagnostic> {
        self.locals
            .get(name)
            .copied()
            .ok_or_else(|| Diagnostic::new(format!("DCPU-16 local `{name}` is not available")))
    }

    fn local_type(&self, name: &str) -> Result<&Type, Diagnostic> {
        self.local_types
            .get(name)
            .ok_or_else(|| Diagnostic::new(format!("DCPU-16 local `{name}` has no type")))
    }

    fn line(&mut self, line: &str) {
        self.out.push_str(line);
        self.out.push('\n');
    }
}

fn type_is_signed(ty: &Type) -> bool {
    matches!(ty, Type::Named(name) if matches!(name.as_str(), "i8" | "i16"))
}

fn binary_opcode(op: BinaryOp, signed: bool) -> Result<&'static str, Diagnostic> {
    match op {
        BinaryOp::Mul if signed => Ok("mli"),
        BinaryOp::Mul => Ok("mul"),
        BinaryOp::Div if signed => Ok("dvi"),
        BinaryOp::Div => Ok("div"),
        BinaryOp::Mod => Ok("mod"),
        BinaryOp::Add => Ok("add"),
        BinaryOp::Sub => Ok("sub"),
        BinaryOp::Shl => Ok("shl"),
        BinaryOp::Shr if signed => Ok("asr"),
        BinaryOp::Shr => Ok("shr"),
        BinaryOp::BitAnd => Ok("and"),
        BinaryOp::BitXor => Ok("xor"),
        BinaryOp::BitOr => Ok("bor"),
        _ => Err(Diagnostic::new(format!(
            "DCPU-16 emitter does not yet support binary operator `{op:?}`"
        ))),
    }
}

fn assign_opcode(op: AssignOp, signed: bool) -> Result<&'static str, Diagnostic> {
    match op {
        AssignOp::Add => Ok("add"),
        AssignOp::Sub => Ok("sub"),
        AssignOp::Mul if signed => Ok("mli"),
        AssignOp::Mul => Ok("mul"),
        AssignOp::Div if signed => Ok("dvi"),
        AssignOp::Div => Ok("div"),
        AssignOp::Mod => Ok("mod"),
        AssignOp::BitAnd => Ok("and"),
        AssignOp::BitOr => Ok("bor"),
        AssignOp::BitXor => Ok("xor"),
        AssignOp::Shl => Ok("shl"),
        AssignOp::Shr if signed => Ok("asr"),
        AssignOp::Shr => Ok("shr"),
        AssignOp::Set => Err(Diagnostic::new("internal DCPU-16 assignment error")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        asm::AssemblyOptions, parser::parse_program, target::CpuFamily,
        vm::assemble_subset_with_symbols_at,
    };
    use std::path::Path;

    fn emit_result(source: &str) -> Result<String, Diagnostic> {
        let program = parse_program(Path::new("dcpu.ezra"), source).unwrap();
        emit_dcpu_assembly_with_options(
            &program,
            AssemblyOptions {
                cpu: CpuFamily::Dcpu,
                ram_base: crate::target::Address24::new(0x8000),
                ..AssemblyOptions::default()
            },
        )
    }

    fn emit(source: &str) -> String {
        let assembly = emit_result(source).unwrap();
        assemble_subset_with_symbols_at(CpuFamily::Dcpu.into(), &assembly, 0)
            .unwrap_or_else(|error| panic!("{error}\n{assembly}"));
        assembly
    }

    #[test]
    fn empty_main_assembles() {
        let assembly = emit("fn main() {}");
        assert!(assembly.contains("jsr _main"));
    }

    #[test]
    fn operand_free_inline_asm_assembles() {
        let assembly =
            emit(r#"fn main() { asm volatile(clobber memory) { "set a, 0x30" "add a, 2" } }"#);
        assert!(assembly.contains("set a, 0x30"));
    }

    #[test]
    fn scalar_arithmetic_assembles() {
        let assembly = emit(
            "fn main() { let left: u16 = 0x10; let right: u16 = 2; right += left; left += right * 3 }",
        );
        assert!(assembly.contains("mul j, a"));
        assert!(assembly.contains("add j, a"));
    }

    #[test]
    fn signed_arithmetic_emits_signed_opcodes() {
        let assembly = emit(
            "fn main() { let left: i16 = 15; let right: i16 = 3; left += right; let product: i16 = left * right; let quotient: i16 = left / right; let shifted: i16 = left >> right }",
        );
        assert!(assembly.contains("mli j, c"));
        assert!(assembly.contains("dvi j, x"));
        assert!(assembly.contains("asr j, y"));
    }

    #[test]
    fn unsigned_arithmetic_emits_unsigned_opcodes() {
        let assembly = emit(
            "fn main() { let left: u16 = 15; let right: u16 = 3; left += right; let product: u16 = left * right; let quotient: u16 = left / right; let shifted: u16 = left >> right }",
        );
        assert!(assembly.contains("mul j, c"));
        assert!(assembly.contains("div j, x"));
        assert!(assembly.contains("shr j, y"));
    }

    #[test]
    fn signed_compound_assignments_emit_signed_opcodes() {
        let assembly = emit(
            "fn main() { let value: i16 = 24; let amount: i16 = 3; value *= amount; value /= amount; value >>= amount }",
        );
        assert!(assembly.contains("mli j, a"));
        assert!(assembly.contains("dvi j, a"));
        assert!(assembly.contains("asr j, a"));
    }

    #[test]
    fn explicit_inline_arguments_lower_once_left_to_right_with_typed_temps_and_nested_calls() {
        let typed_arguments = emit(
            r#"
                inline fn pair(left: u8, right: u16) {}
                fn main() { pair(3, 4) }
            "#,
        );
        assert!(!typed_arguments.contains("_pair:"), "{typed_arguments}");

        let nested = emit(
            r#"
                inline fn leaf() {}
                inline fn nested() { leaf() }
                fn main() { nested() }
            "#,
        );
        assert!(!nested.contains("_leaf:"), "{nested}");
        assert!(!nested.contains("_nested:"), "{nested}");
    }

    #[test]
    fn unsafe_conditionally_evaluated_inline_call_remains_for_backend_validation() {
        let error = emit_result(
            r#"
                inline fn guarded(value: bool) -> bool { return value }
                fn main() {
                    let flag: bool = false
                    let result: bool = flag && guarded(true)
                }
            "#,
        )
        .unwrap_err();

        assert!(
            error.message.contains("function `guarded` is unsupported"),
            "{error}"
        );
    }

    #[test]
    fn multiply_by_power_of_two_keeps_shared_shift_rewrite() {
        let assembly = emit("fn main() { let value: i16 = 7; let scaled: i16 = value * 8 }");
        assert!(assembly.contains("shl j, b"));
        assert!(!assembly.contains("mli j, b"));
        assert!(!assembly.contains("mul j, b"));
    }
}
