use std::{
    collections::{HashMap, HashSet},
    path::Path,
};

use crate::{
    asm::{
        AssemblyOptions,
        comments::{stmt_summary, with_readability_comments},
        data::terminated_text_data_line,
        reachability::{RoutineProfile, strip_unreachable_generated_routines},
    },
    ast::{
        AccessPath, AccessSegment, AssignOp, BinaryOp, Declaration, Expr, Function, Place, Program,
        Stmt, Type, UnaryOp,
    },
    declaration::unwrapped_declaration,
    diagnostic::Diagnostic,
    hir::HirProgram,
    regalloc::{
        Location, PhysReg, PhysicalRegister, RegClass, RegUnit, RegisterClass, RegisterUnit,
        SpillClass, SpillClassId, Target,
        source::{SourceLocal, allocate_source_locals},
    },
    target::CpuFamily,
    tbir::TbirProgram,
};

/// Emit DCPU-16 source from the optimized program retained by TBIR.
///
/// DCPU memory is word addressed.  Every EZRA scalar, including `u8`, occupies one
/// DCPU word; arrays and structs are sequences of words. Pointers therefore contain
/// DCPU word addresses. The call ABI passes arguments left-to-right above the return
/// address, saves J as the frame pointer, and returns scalar values in A.
pub fn emit_dcpu_assembly_with_options(
    program: &Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    if options.cpu != CpuFamily::Dcpu {
        return Err(Diagnostic::new("DCPU-16 emitter requires a DCPU-16 target"));
    }
    if program.main_function().is_none() {
        return Err(Diagnostic::new(
            "DCPU-16 programs require a `main` function",
        ));
    }
    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    Emitter::new().emit(&tbir.lowered_program).map(|assembly| {
        let assembly = strip_unreachable_generated_routines(&assembly, RoutineProfile::Dcpu);
        with_readability_comments(assembly, program, &options, "dcpu", &tbir.source_comments)
    })
}

const DCPU_LOCAL_REGISTERS: [&str; 4] = ["c", "x", "y", "z"];
const DCPU_SCALAR_CLASS: RegClass = RegClass(0);
const DCPU_STACK_SPILL_CLASS: SpillClassId = SpillClassId(0);

#[derive(Clone)]
enum BindingLocation {
    Frame(i16),
    Register(&'static str),
}

#[derive(Clone)]
struct Binding {
    location: BindingLocation,
    ty: Type,
}
#[derive(Clone)]
struct LoopLabels {
    again: String,
    done: String,
}

struct Emitter {
    out: String,
    labels: usize,
    bindings: HashMap<String, Binding>,
    locals: HashMap<String, Binding>,
    loops: Vec<LoopLabels>,
    return_label: String,
    return_type: Option<Type>,
    constants: HashMap<String, i64>,
    constant_types: HashMap<String, Type>,
    globals: HashMap<String, Type>,
    mmio: HashMap<String, (i64, Type)>,
    embeds: HashMap<String, Vec<u8>>,
    structs: HashMap<String, Vec<(String, Type)>>,
    functions: HashMap<String, Function>,
    extern_functions: HashSet<String>,
    strings: HashMap<String, String>,
    global_initializers: Vec<(String, Type, Expr)>,
}

impl Emitter {
    fn new() -> Self {
        Self {
            out: String::new(),
            labels: 0,
            bindings: HashMap::new(),
            locals: HashMap::new(),
            loops: Vec::new(),
            return_label: String::new(),
            return_type: None,
            constants: HashMap::new(),
            constant_types: HashMap::new(),
            globals: HashMap::new(),
            mmio: HashMap::new(),
            embeds: HashMap::new(),
            structs: HashMap::new(),
            functions: HashMap::new(),
            extern_functions: HashSet::new(),
            strings: HashMap::new(),
            global_initializers: Vec::new(),
        }
    }

    fn emit(mut self, program: &Program) -> Result<String, Diagnostic> {
        self.collect_declarations(program)?;
        self.line("; generated by ezrac");
        self.line("; target: DCPU-16; all EZRA storage addresses are DCPU words");
        self.line("__ezra_start:");
        self.line("    set sp, 0xffff");
        self.emit_global_initializers()?;
        self.line("    jsr _main");
        self.line("__ezra_exit:");
        self.line("    set pc, __ezra_exit");

        let functions = self.functions.values().cloned().collect::<Vec<_>>();
        for function in functions {
            self.emit_function(&function)?;
        }
        self.emit_static_data()?;
        Ok(self.out)
    }

    fn collect_declarations(&mut self, program: &Program) -> Result<(), Diagnostic> {
        for declaration in &program.declarations {
            match unwrapped_declaration(declaration) {
                Declaration::Const(value) => {
                    let constant = self.const_value(&value.value)?;
                    self.constants.insert(value.name.clone(), constant);
                    self.constant_types
                        .insert(value.name.clone(), value.ty.clone());
                }
                Declaration::Global(value) => {
                    self.globals.insert(value.name.clone(), value.ty.clone());
                    self.global_initializers.push((
                        value.name.clone(),
                        value.ty.clone(),
                        value.value.clone(),
                    ));
                }
                Declaration::Mmio(value) => {
                    self.mmio.insert(
                        value.name.clone(),
                        (self.const_value(&value.value)?, value.ty.clone()),
                    );
                }
                Declaration::Embed(value) => {
                    let bytes = match &value.source {
                        crate::ast::EmbedSource::Bytes(values) => values
                            .iter()
                            .map(|value| {
                                self.const_value(value).and_then(|v| {
                                    u8::try_from(v).map_err(|_| {
                                        Diagnostic::new("DCPU embed byte is outside 0..255")
                                    })
                                })
                            })
                            .collect::<Result<Vec<_>, _>>()?,
                        crate::ast::EmbedSource::Text(text) => text.bytes().collect(),
                        crate::ast::EmbedSource::CStr(text) => {
                            text.bytes().chain(core::iter::once(0)).collect()
                        }
                        crate::ast::EmbedSource::Repeat { value, len } => {
                            vec![
                                u8::try_from(self.const_value(value)?).map_err(|_| {
                                    Diagnostic::new("DCPU embed byte is outside 0..255")
                                })?;
                                usize::try_from(self.const_value(len)?)
                                    .map_err(|_| Diagnostic::new("DCPU embed length is invalid"))?
                            ]
                        }
                        crate::ast::EmbedSource::File(file) => {
                            let path = program
                                .source_path
                                .parent()
                                .unwrap_or_else(|| Path::new("."))
                                .join(file);
                            std::fs::read(&path).map_err(|error| {
                                Diagnostic::new(format!(
                                    "failed to read DCPU embed `{}`: {error}",
                                    path.display()
                                ))
                            })?
                        }
                    };
                    self.embeds.insert(value.name.clone(), bytes);
                }
                Declaration::Struct(value) => {
                    self.structs.insert(
                        value.name.clone(),
                        value
                            .fields
                            .iter()
                            .map(|field| (field.name.clone(), field.ty.clone()))
                            .collect(),
                    );
                }
                Declaration::Function(function) => {
                    self.functions
                        .insert(function.name.clone(), function.clone());
                }
                Declaration::ExternAsmFunction(function) => {
                    self.extern_functions.insert(function.name.clone());
                }
                Declaration::Port(port) => {
                    return Err(Diagnostic::new(format!(
                        "DCPU-16 has no separate port I/O; use MMIO or inline asm instead of port `{}`",
                        port.name
                    )));
                }
                Declaration::Alias(_)
                | Declaration::Import(_)
                | Declaration::Cfg { .. }
                | Declaration::Bank { .. } => {}
            }
        }
        Ok(())
    }

    fn emit_global_initializers(&mut self) -> Result<(), Diagnostic> {
        let initializers = self.global_initializers.clone();
        for (name, ty, value) in initializers {
            if self.is_aggregate(&ty) {
                self.emit_aggregate(&value, &ty, &format!("__ezra_global_{name}"))?;
            } else {
                self.emit_expr(&value, &ty)?;
                self.line(&format!("    set [__ezra_global_{name}], a"));
            }
        }
        Ok(())
    }

    fn emit_function(&mut self, function: &Function) -> Result<(), Diagnostic> {
        let naked = function.attrs.iter().any(|attr| attr == "naked");
        self.line(&format!("{}:", function_label(&function.name)));
        if naked {
            for stmt in &function.body {
                let Stmt::Asm {
                    inputs,
                    outputs,
                    lines,
                    ..
                } = stmt
                else {
                    return Err(Diagnostic::new(format!(
                        "naked DCPU function `{}` may contain only asm blocks",
                        function.name
                    )));
                };
                if !inputs.is_empty() || !outputs.is_empty() {
                    return Err(Diagnostic::new(
                        "naked DCPU asm cannot use compiler operands",
                    ));
                }
                for line in lines {
                    self.line(&format!("    {line}"));
                }
            }
            return Ok(());
        }
        let (locals, frame_words) = plan_locals(&function.body, self)?;
        self.locals = locals;
        self.bindings.clear();
        for (index, param) in function.params.iter().enumerate() {
            // [J+0] saved J, [J+1] return PC, then arguments in source order.
            self.bindings.insert(
                param.name.clone(),
                Binding {
                    location: BindingLocation::Frame(
                        i16::try_from(index + 2)
                            .map_err(|_| Diagnostic::new("too many DCPU parameters"))?,
                    ),
                    ty: param.ty.clone(),
                },
            );
        }
        self.return_label = self.next_label(&format!("{}_return", function.name));
        self.return_type = function.return_type.clone();
        self.line("    set push, j");
        self.line("    set j, sp");
        if frame_words != 0 {
            self.line(&format!("    sub sp, {frame_words}"));
        }
        self.emit_block(&function.body)?;
        self.line(&format!("{}:", self.return_label));
        self.line("    set sp, j");
        self.line("    set j, pop");
        self.line("    set pc, pop");
        Ok(())
    }

    fn emit_block(&mut self, body: &[Stmt]) -> Result<(), Diagnostic> {
        for stmt in body {
            self.emit_stmt(stmt)?;
        }
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<(), Diagnostic> {
        self.line(&format!("    ; source: {}", stmt_summary(stmt)));
        match stmt {
            Stmt::Let { name, ty, value } => {
                let binding = self
                    .locals
                    .get(name)
                    .cloned()
                    .ok_or_else(|| Diagnostic::new(format!("missing DCPU local `{name}`")))?;
                self.bindings.insert(name.clone(), binding.clone());
                if self.is_aggregate(ty) {
                    let base = self.binding_address_operand(&binding, name)?;
                    self.emit_aggregate(value, ty, &base)?
                } else {
                    self.emit_expr(value, ty)?;
                    self.store_binding(&binding);
                }
            }
            Stmt::Assign { target, op, value } => self.emit_assign(target, *op, value)?,
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                let otherwise = self.next_label("if_else");
                let done = self.next_label("if_end");
                if !self.emit_jump_if_false(condition, &otherwise)? {
                    self.emit_expr(condition, &Type::Named("bool".into()))?;
                    self.line("    ife a, 0");
                    self.line(&format!("    set pc, {otherwise}"));
                }
                self.emit_block(then_body)?;
                self.line(&format!("    set pc, {done}"));
                self.line(&format!("{otherwise}:"));
                self.emit_block(else_body)?;
                self.line(&format!("{done}:"));
            }
            Stmt::While { condition, body } => {
                let again = self.next_label("while");
                let done = self.next_label("while_end");
                self.loops.push(LoopLabels {
                    again: again.clone(),
                    done: done.clone(),
                });
                self.line(&format!("{again}:"));
                if !self.emit_jump_if_false(condition, &done)? {
                    self.emit_expr(condition, &Type::Named("bool".into()))?;
                    self.line("    ife a, 0");
                    self.line(&format!("    set pc, {done}"));
                }
                self.emit_block(body)?;
                self.line(&format!("    set pc, {again}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Loop { body } => {
                let again = self.next_label("loop");
                let done = self.next_label("loop_end");
                self.loops.push(LoopLabels {
                    again: again.clone(),
                    done: done.clone(),
                });
                self.line(&format!("{again}:"));
                self.emit_block(body)?;
                self.line(&format!("    set pc, {again}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Break => {
                let label = self
                    .loops
                    .last()
                    .ok_or_else(|| Diagnostic::new("break outside loop"))?
                    .done
                    .clone();
                self.line(&format!("    set pc, {label}"));
            }
            Stmt::Continue => {
                let label = self
                    .loops
                    .last()
                    .ok_or_else(|| Diagnostic::new("continue outside loop"))?
                    .again
                    .clone();
                self.line(&format!("    set pc, {label}"));
            }
            Stmt::Return(value) => {
                if let Some(value) = value {
                    let ty = self
                        .return_type
                        .clone()
                        .ok_or_else(|| Diagnostic::new("value return in void function"))?;
                    self.emit_expr(value, &ty)?;
                }
                let label = self.return_label.clone();
                self.line(&format!("    set pc, {label}"));
            }
            Stmt::Asm {
                inputs,
                outputs,
                lines,
                ..
            } => self.emit_asm(inputs, outputs, lines)?,
            Stmt::Out { port, .. } => {
                return Err(Diagnostic::new(format!(
                    "DCPU-16 does not support port write `{port}`; use MMIO or asm"
                )));
            }
            Stmt::Expr(Expr::Call { path, args }) => self.emit_call(path, args)?,
            Stmt::Expr(expr) => {
                let ty = self.expr_type(expr)?;
                if !self.is_aggregate(&ty) {
                    self.emit_expr(expr, &ty)?;
                }
            }
        }
        Ok(())
    }

    fn emit_assign(
        &mut self,
        target: &Place,
        op: AssignOp,
        value: &Expr,
    ) -> Result<(), Diagnostic> {
        let ty = self.place_type(target)?;
        if op == AssignOp::Set {
            if self.is_aggregate(&ty) {
                let base = match target {
                    Place::Ident(name) => {
                        if let Some(binding) = self.bindings.get(name).cloned() {
                            self.binding_address_operand(&binding, name)?
                        } else if self.globals.contains_key(name) {
                            format!("__ezra_global_{name}")
                        } else {
                            return Err(Diagnostic::new("aggregate assignment target is unknown"));
                        }
                    }
                    _ => {
                        return Err(Diagnostic::new(
                            "aggregate assignment requires a local or global target",
                        ));
                    }
                };
                return self.emit_aggregate(value, &ty, &base);
            }
            self.emit_expr(value, &ty)?;
            return self.store_place(target, &ty);
        }
        self.load_place(target, &ty)?;
        self.line("    set push, a");
        self.emit_expr(value, &ty)?;
        self.line("    set b, pop");
        self.emit_arithmetic(assign_binary(op), &ty)?;
        self.store_place(target, &ty)
    }

    fn emit_expr(&mut self, expr: &Expr, ty: &Type) -> Result<(), Diagnostic> {
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => self.literal("a", *value)?,
            Expr::Bool(value) => self.literal("a", i64::from(*value))?,
            Expr::Char(value) => self.literal("a", i64::from(*value))?,
            Expr::String(value) => {
                let label = self.string_label(value);
                self.line(&format!("    set a, {label}"));
            }
            Expr::Ident(name) => self.load_ident(name, ty)?,
            Expr::Field { base, field } => self.load_ident(&format!("{base}.{field}"), ty)?,
            Expr::AddressOf(name) => self.emit_named_address(name)?,
            Expr::AddressOfIndex { name, index } => {
                self.emit_named_address(name)?;
                self.line("    set push, a");
                self.emit_expr(index, &Type::Named("u16".into()))?;
                self.line("    set b, pop");
                self.line("    add a, b");
            }
            Expr::AddressOfField { base, field } => {
                self.emit_named_address(base)?;
                self.line(&format!(
                    "    add a, {}",
                    self.field_offset(&self.named_type(base)?, field)?
                ));
            }
            Expr::Index { name, index } => {
                let element = self.array_element(&self.named_type(name)?)?;
                self.emit_named_address(name)?;
                self.line("    set push, a");
                self.emit_expr(index, &Type::Named("u16".into()))?;
                self.line("    set i, pop");
                self.line("    add i, a");
                self.line("    set a, [i]");
                self.mask(&element)?;
            }
            Expr::Access(path) => {
                let ty = self.access_type(path)?;
                self.emit_access_address(path)?;
                self.line("    set a, [i]");
                self.mask(&ty)?;
            }
            Expr::AddressOfAccess(path) => {
                self.emit_access_address(path)?;
                self.line("    set a, i");
            }
            Expr::Deref(pointer) => {
                self.emit_expr(pointer, &Type::Ptr(Box::new(ty.clone())))?;
                self.line("    set a, [a]");
                self.mask(ty)?;
            }
            Expr::BankedPointer { pointer, .. } | Expr::Cast { expr: pointer, .. } => {
                self.emit_expr(pointer, ty)?
            }
            Expr::Call { path, args } => {
                self.expr_type(expr)?;
                self.emit_call(path, args)?;
            }
            Expr::Unary { op, expr } => {
                self.emit_expr(expr, ty)?;
                match op {
                    UnaryOp::Neg => {
                        self.line("    set b, 0");
                        self.line("    sub b, a");
                        self.line("    set a, b");
                    }
                    UnaryOp::BitNot => self.line("    xor a, 0xffff"),
                    UnaryOp::Not => self.boolean_compare("ife", "a", "0"),
                };
                self.mask(ty)?;
            }
            Expr::Binary { left, op, right } => self.emit_binary_expr(left, *op, right, ty)?,
            Expr::Array(_) | Expr::StructInit { .. } => {
                return Err(Diagnostic::new(
                    "aggregate value is valid only while initializing or assigning aggregate storage",
                ));
            }
            Expr::In(port) => {
                return Err(Diagnostic::new(format!(
                    "DCPU-16 has no port input `{port}`; use MMIO or asm"
                )));
            }
        }
        Ok(())
    }

    fn emit_binary_expr(
        &mut self,
        left: &Expr,
        op: BinaryOp,
        right: &Expr,
        ty: &Type,
    ) -> Result<(), Diagnostic> {
        if op == BinaryOp::And || op == BinaryOp::Or {
            let short = self.next_label("logical_short");
            let done = self.next_label("logical_end");
            self.emit_expr(left, &Type::Named("bool".into()))?;
            self.line(&format!(
                "    {} a, 0",
                if op == BinaryOp::And { "ife" } else { "ifn" }
            ));
            self.line(&format!("    set pc, {short}"));
            self.emit_expr(right, &Type::Named("bool".into()))?;
            self.line("    ifn a, 0");
            self.line("    set a, 1");
            self.line(&format!("    set pc, {done}"));
            self.line(&format!("{short}:"));
            self.literal("a", i64::from(op == BinaryOp::Or))?;
            self.line(&format!("{done}:"));
            return Ok(());
        }
        let operand_ty = if matches!(
            op,
            BinaryOp::Eq | BinaryOp::Ne | BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge
        ) {
            self.expr_type(left)?
        } else {
            ty.clone()
        };
        self.emit_expr(left, &operand_ty)?;
        if let Ok(value) = self.const_value(right) {
            let value = value as u16 & self.type_mask(&operand_ty)?;
            match op {
                BinaryOp::Eq => {
                    self.boolean_compare("ife", "a", &format!("0x{value:04x}"));
                    return Ok(());
                }
                BinaryOp::Ne => {
                    self.boolean_compare("ifn", "a", &format!("0x{value:04x}"));
                    return Ok(());
                }
                BinaryOp::Lt => {
                    self.boolean_compare(
                        if signed(&operand_ty) { "ifa" } else { "ifl" },
                        "a",
                        &format!("0x{value:04x}"),
                    );
                    return Ok(());
                }
                BinaryOp::Gt => {
                    self.boolean_compare(
                        if signed(&operand_ty) { "ifa" } else { "ifg" },
                        "a",
                        &format!("0x{value:04x}"),
                    );
                    return Ok(());
                }
                BinaryOp::Le | BinaryOp::Ge => {}
                _ => {
                    let width_mask = self.type_mask(&operand_ty)?;
                    self.emit_immediate_arithmetic(op, value, &operand_ty)?;
                    if !matches!(op, BinaryOp::BitAnd) || width_mask == u16::MAX {
                        self.mask(ty)?;
                    }
                    return Ok(());
                }
            }
        }
        self.line("    set push, a");
        self.emit_expr(right, &operand_ty)?;
        self.line("    set b, pop");
        match op {
            BinaryOp::Eq => {
                self.boolean_compare("ife", "b", "a");
                return Ok(());
            }
            BinaryOp::Ne => {
                self.boolean_compare("ifn", "b", "a");
                return Ok(());
            }
            BinaryOp::Lt => {
                self.boolean_compare(if signed(&operand_ty) { "ifa" } else { "ifl" }, "b", "a")
            }
            BinaryOp::Le => self.boolean_compare_le(&operand_ty, true),
            BinaryOp::Gt => {
                self.boolean_compare(if signed(&operand_ty) { "ifa" } else { "ifg" }, "a", "b")
            }
            BinaryOp::Ge => self.boolean_compare_le(&operand_ty, false),
            _ => self.emit_arithmetic(op, &operand_ty)?,
        }
        if !matches!(
            op,
            BinaryOp::Eq | BinaryOp::Ne | BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge
        ) {
            self.mask(ty)?;
        }
        Ok(())
    }

    fn emit_immediate_arithmetic(
        &mut self,
        op: BinaryOp,
        value: u16,
        ty: &Type,
    ) -> Result<(), Diagnostic> {
        if op == BinaryOp::BitAnd && value == 0 {
            self.line("    set a, 0");
            return Ok(());
        }
        let instruction = arithmetic_instruction(op, ty)?;
        self.line(&format!("    {instruction} a, 0x{value:04x}"));
        Ok(())
    }

    fn emit_jump_if_false(
        &mut self,
        condition: &Expr,
        false_label: &str,
    ) -> Result<bool, Diagnostic> {
        let Expr::Binary { left, op, right } = condition else {
            return Ok(false);
        };
        if !matches!(op, BinaryOp::Eq | BinaryOp::Ne) {
            return Ok(false);
        }
        let Expr::Binary {
            left: source,
            op: BinaryOp::BitAnd,
            right: mask_expr,
        } = left.as_ref()
        else {
            return Ok(false);
        };
        let (Ok(raw_mask), Ok(raw_expected)) =
            (self.const_value(mask_expr), self.const_value(right))
        else {
            return Ok(false);
        };
        let source_ty = self.expr_type(source)?;
        let width_mask = self.type_mask(&source_ty)?;
        let mask = raw_mask as u16 & width_mask;
        let expected = raw_expected as u16 & width_mask;
        let source_is_narrow = self.expr_is_width_limited(source, &source_ty)?;

        self.emit_expr(source, &source_ty)?;
        if expected == 0 {
            let instruction = if *op == BinaryOp::Eq { "ifb" } else { "ifc" };
            self.line(&format!("    {instruction} a, 0x{mask:04x}"));
            self.line(&format!("    set pc, {false_label}"));
            return Ok(true);
        }
        if mask == 0 {
            self.line("    set a, 0");
        } else if mask != width_mask || !source_is_narrow {
            self.line(&format!("    and a, 0x{mask:04x}"));
        }

        if expected & !mask != 0 {
            if *op == BinaryOp::Eq {
                self.line(&format!("    set pc, {false_label}"));
            }
            return Ok(true);
        }

        let branch = if *op == BinaryOp::Eq { "ifn" } else { "ife" };
        self.line(&format!("    {branch} a, 0x{expected:04x}"));
        self.line(&format!("    set pc, {false_label}"));
        Ok(true)
    }

    fn emit_arithmetic(&mut self, op: BinaryOp, ty: &Type) -> Result<(), Diagnostic> {
        let instruction = arithmetic_instruction(op, ty)?;
        self.line(&format!("    {instruction} b, a"));
        self.line("    set a, b");
        Ok(())
    }

    fn boolean_compare(&mut self, instruction: &str, left: &str, right: &str) {
        let yes = self.next_label("true");
        let done = self.next_label("bool_end");
        self.line(&format!("    {instruction} {left}, {right}"));
        self.line(&format!("    set pc, {yes}"));
        self.line("    set a, 0");
        self.line(&format!("    set pc, {done}"));
        self.line(&format!("{yes}:"));
        self.line("    set a, 1");
        self.line(&format!("{done}:"));
    }
    fn boolean_compare_le(&mut self, ty: &Type, less_or_equal: bool) {
        let yes = self.next_label("true");
        let done = self.next_label("bool_end");
        let strict = if signed(ty) { "ifa" } else { "ifl" };
        if less_or_equal {
            self.line(&format!("    {strict} a, b"));
        } else {
            self.line(&format!("    {strict} b, a"));
        }
        self.line(&format!("    set pc, {yes}"));
        self.line("    ife a, b");
        self.line(&format!("    set pc, {yes}"));
        self.line("    set a, 0");
        self.line(&format!("    set pc, {done}"));
        self.line(&format!("{yes}:"));
        self.line("    set a, 1");
        self.line(&format!("{done}:"));
    }

    fn emit_call(&mut self, path: &[String], args: &[Expr]) -> Result<(), Diagnostic> {
        let name = path
            .last()
            .ok_or_else(|| Diagnostic::new("empty call path"))?;
        let function = self
            .functions
            .get(name)
            .cloned()
            .or_else(|| self.functions.get(&path.join(".")).cloned());
        let params = if let Some(function) = &function {
            function.params.clone()
        } else {
            return_type_params_none(self, name, args)?
        };
        if args.len() != params.len() {
            return Err(Diagnostic::new(format!(
                "function `{name}` expects {} arguments, got {}",
                params.len(),
                args.len()
            )));
        }
        // Pushing in reverse gives the callee arguments [J+2], [J+3], ... in source order.
        for (arg, param) in args.iter().zip(params.iter()).rev() {
            self.emit_expr(arg, &param.ty)?;
            self.line("    set push, a");
        }
        self.line(&format!("    jsr {}", function_label(name)));
        if !args.is_empty() {
            self.line(&format!("    add sp, {}", args.len()));
        }
        Ok(())
    }

    fn emit_asm(
        &mut self,
        inputs: &[crate::ast::AsmInput],
        outputs: &[crate::ast::AsmOutput],
        lines: &[String],
    ) -> Result<(), Diagnostic> {
        let registers = ["b", "c", "x", "y", "z"];
        if inputs.len() + outputs.len() > registers.len() {
            return Err(Diagnostic::new(
                "DCPU inline asm supports at most five reg16 operands",
            ));
        }
        let mut operands = HashMap::new();
        for input in inputs {
            if input.class != "reg16" {
                return Err(Diagnostic::new(format!(
                    "DCPU inline asm input `{}` must use reg16",
                    input.name
                )));
            }
            self.load_ident(&input.name, &input.ty)?;
            self.line("    set push, a");
        }
        for (index, input) in inputs.iter().enumerate().rev() {
            self.line(&format!("    set {}, pop", registers[index]));
            operands.insert(input.name.clone(), registers[index]);
        }
        for (index, output) in outputs.iter().enumerate() {
            if output.class != "reg16" {
                return Err(Diagnostic::new(format!(
                    "DCPU inline asm output `{}` must use reg16",
                    output.name
                )));
            }
            operands.insert(output.name.clone(), registers[inputs.len() + index]);
        }
        for source in lines {
            let mut line = source.clone();
            for (name, register) in &operands {
                line = line.replace(&format!("{{{name}}}"), register);
            }
            if line.contains(['{', '}']) {
                return Err(Diagnostic::new(format!(
                    "DCPU inline asm has unresolved operand in `{source}`"
                )));
            }
            self.line(&format!("    {line}"));
        }
        for (index, _) in outputs.iter().enumerate() {
            self.line(&format!(
                "    set push, {}",
                registers[inputs.len() + index]
            ));
        }
        for output in outputs.iter().rev() {
            self.line("    set a, pop");
            self.store_named(&output.name, &output.ty)?;
        }
        Ok(())
    }

    fn load_ident(&mut self, name: &str, expected: &Type) -> Result<(), Diagnostic> {
        if let Some(binding) = self.bindings.get(name).cloned() {
            match binding.location {
                BindingLocation::Frame(offset) => {
                    self.line(&format!("    set a, {}", self.frame_operand(offset)));
                }
                BindingLocation::Register(register) => {
                    self.line(&format!("    set a, {register}"));
                }
            }
            return self.mask(&binding.ty);
        }
        if let Some(value) = self.constants.get(name).copied() {
            return self.literal("a", value);
        }
        if self.globals.contains_key(name) {
            self.line(&format!("    set a, [__ezra_global_{name}]"));
            return self.mask(expected);
        }
        if let Some((address, ty)) = self.mmio.get(name).cloned() {
            self.line(&format!("    set a, [0x{:04x}]", address as u16));
            return self.mask(&ty);
        }
        if self.embeds.contains_key(name) {
            self.line(&format!("    set a, __ezra_embed_{name}"));
            return Ok(());
        }
        Err(Diagnostic::new(format!("unknown DCPU value `{name}`")))
    }

    fn emit_named_address(&mut self, name: &str) -> Result<(), Diagnostic> {
        if let Some(binding) = self.bindings.get(name).cloned() {
            let BindingLocation::Frame(offset) = binding.location else {
                return Err(Diagnostic::new(format!(
                    "cannot take address of register local `{name}`"
                )));
            };
            self.line("    set a, j");
            self.line(&format!("    add a, {offset}"));
        } else if self.globals.contains_key(name) {
            self.line(&format!("    set a, __ezra_global_{name}"));
        } else if self.embeds.contains_key(name) {
            self.line(&format!("    set a, __ezra_embed_{name}"));
        } else {
            return Err(Diagnostic::new(format!("cannot take address of `{name}`")));
        }
        Ok(())
    }
    fn load_place(&mut self, place: &Place, ty: &Type) -> Result<(), Diagnostic> {
        match place {
            Place::Ident(name) => self.load_ident(name, ty),
            _ => {
                self.emit_place_address(place)?;
                self.line("    set a, [i]");
                self.mask(ty)
            }
        }
    }
    fn store_place(&mut self, place: &Place, ty: &Type) -> Result<(), Diagnostic> {
        self.mask(ty)?;
        match place {
            Place::Ident(name) => self.store_named(name, ty),
            _ => {
                self.line("    set push, a");
                self.emit_place_address(place)?;
                self.line("    set b, pop");
                self.line("    set [i], b");
                Ok(())
            }
        }
    }
    fn store_named(&mut self, name: &str, ty: &Type) -> Result<(), Diagnostic> {
        if let Some(binding) = self.bindings.get(name).cloned() {
            self.store_binding(&binding);
            Ok(())
        } else if self.globals.contains_key(name) {
            self.line(&format!("    set [__ezra_global_{name}], a"));
            Ok(())
        } else if let Some((address, _)) = self.mmio.get(name) {
            self.line(&format!("    set [0x{:04x}], a", *address as u16));
            Ok(())
        } else {
            Err(Diagnostic::new(format!(
                "unknown DCPU assignment target `{name}` of type `{ty:?}`"
            )))
        }
    }
    fn store_binding(&mut self, binding: &Binding) {
        match binding.location {
            BindingLocation::Frame(offset) => {
                self.line(&format!("    set {}, a", self.frame_operand(offset)));
            }
            BindingLocation::Register(register) => {
                self.line(&format!("    set {register}, a"));
            }
        }
    }

    fn binding_address_operand(&self, binding: &Binding, name: &str) -> Result<String, Diagnostic> {
        match binding.location {
            BindingLocation::Frame(offset) => Ok(format!("j + {offset}")),
            BindingLocation::Register(_) => Err(Diagnostic::new(format!(
                "cannot take address of register local `{name}`"
            ))),
        }
    }

    fn emit_place_address(&mut self, place: &Place) -> Result<(), Diagnostic> {
        match place {
            Place::Index { name, index } => {
                self.emit_named_address(name)?;
                self.line("    set push, a");
                self.emit_expr(index, &Type::Named("u16".into()))?;
                self.line("    set i, pop");
                self.line("    add i, a");
            }
            Place::Field { base, field } => {
                self.emit_named_address(base)?;
                self.line("    set i, a");
                self.line(&format!(
                    "    add i, {}",
                    self.field_offset(&self.named_type(base)?, field)?
                ));
            }
            Place::Access(path) => self.emit_access_address(path)?,
            Place::Deref(pointer) => {
                self.emit_expr(pointer, &Type::Ptr(Box::new(Type::Named("u16".into()))))?;
                self.line("    set i, a");
            }
            Place::Ident(name) => {
                self.emit_named_address(name)?;
                self.line("    set i, a");
            }
        }
        Ok(())
    }
    fn emit_access_address(&mut self, path: &AccessPath) -> Result<(), Diagnostic> {
        self.emit_named_address(&path.root)?;
        self.line("    set i, a");
        let mut ty = self.named_type(&path.root)?;
        for segment in &path.segments {
            match segment {
                AccessSegment::Field(field) => {
                    let offset = self.field_offset(&ty, field)?;
                    self.line(&format!("    add i, {offset}"));
                    ty = self.field_type(&ty, field)?;
                }
                AccessSegment::Index(index) => {
                    let element = self.array_element(&ty)?;
                    self.emit_expr(index, &Type::Named("u16".into()))?;
                    self.line("    add i, a");
                    ty = element;
                }
            }
        }
        Ok(())
    }

    fn emit_aggregate(&mut self, value: &Expr, ty: &Type, base: &str) -> Result<(), Diagnostic> {
        match value {
            Expr::Array(values) => {
                let element = self.array_element(ty)?;
                for (index, value) in values.iter().enumerate() {
                    self.emit_expr(value, &element)?;
                    self.line(&format!("    set [{base} + {index}], a"));
                }
            }
            Expr::StructInit { ty: named, fields } => {
                for (field, value) in fields {
                    let field_ty = self.field_type(&Type::Named(named.clone()), field)?;
                    let offset = self.field_offset(&Type::Named(named.clone()), field)?;
                    self.emit_expr(value, &field_ty)?;
                    self.line(&format!("    set [{base} + {offset}], a"));
                }
            }
            _ => {
                return Err(Diagnostic::new(
                    "aggregate initialization requires an array or struct literal",
                ));
            }
        }
        Ok(())
    }

    fn emit_static_data(&mut self) -> Result<(), Diagnostic> {
        self.line("; word-addressed static storage");
        for (name, bytes) in self.embeds.clone() {
            self.line(&format!("__ezra_embed_{name}:"));
            self.data_words(bytes.iter().map(|byte| i64::from(*byte)).collect());
        }
        for (name, ty) in self.globals.clone() {
            self.line(&format!("__ezra_global_{name}:"));
            self.data_words(vec![0; self.type_words(&ty)?]);
        }
        for (text, label) in self.strings.clone() {
            self.line(&format!("{label}:"));
            self.line(&terminated_text_data_line("dat", &text, "0"));
        }
        Ok(())
    }
    fn data_words(&mut self, values: Vec<i64>) {
        if values.is_empty() {
            self.line("    dat 0");
        } else {
            self.line(&format!(
                "    dat {}",
                values
                    .iter()
                    .map(|value| format!("0x{:04x}", *value as u16))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
    }
    fn string_label(&mut self, value: &str) -> String {
        if let Some(label) = self.strings.get(value) {
            return label.clone();
        }
        let label = self.next_label("string");
        self.strings.insert(value.to_owned(), label.clone());
        label
    }
    fn literal(&mut self, register: &str, value: i64) -> Result<(), Diagnostic> {
        if !(-32768..=65535).contains(&value) {
            return Err(Diagnostic::new(format!(
                "DCPU literal `{value}` is outside 16 bits"
            )));
        }
        self.line(&format!("    set {register}, 0x{:04x}", value as u16));
        Ok(())
    }
    fn expr_is_width_limited(&self, expr: &Expr, ty: &Type) -> Result<bool, Diagnostic> {
        let width_mask = self.type_mask(ty)?;
        if width_mask == u16::MAX {
            return Ok(true);
        }
        Ok(match expr {
            Expr::Ident(name) => self.type_mask(&self.named_type(name)?)? == width_mask,
            Expr::Index { .. } | Expr::Access(_) | Expr::Deref(_) => true,
            Expr::Unary { .. } | Expr::Binary { .. } => true,
            Expr::Int(value) | Expr::TypedInt(value, _) => *value as u16 & !width_mask == 0,
            Expr::Bool(_) | Expr::Char(_) => true,
            Expr::BankedPointer { .. }
            | Expr::Cast { .. }
            | Expr::Field { .. }
            | Expr::AddressOf(_)
            | Expr::AddressOfIndex { .. }
            | Expr::AddressOfField { .. }
            | Expr::AddressOfAccess(_)
            | Expr::String(_)
            | Expr::Call { .. }
            | Expr::In(_)
            | Expr::Array(_)
            | Expr::StructInit { .. } => false,
        })
    }
    fn type_mask(&self, ty: &Type) -> Result<u16, Diagnostic> {
        match self.resolve_type(ty)? {
            Type::Named(name) if matches!(name.as_str(), "u8" | "i8" | "bool") => Ok(0x00ff),
            Type::Named(name) if matches!(name.as_str(), "u16" | "i16") => Ok(u16::MAX),
            Type::Ptr(_) | Type::Function { .. } => Ok(u16::MAX),
            _ => {
                self.scalar_words(ty)?;
                Ok(u16::MAX)
            }
        }
    }
    fn mask(&mut self, ty: &Type) -> Result<(), Diagnostic> {
        if self.type_mask(ty)? != u16::MAX {
            self.line("    and a, 0x00ff");
        }
        Ok(())
    }
    fn frame_operand(&self, offset: i16) -> String {
        format!("[j + {offset}]")
    }
    fn next_label(&mut self, stem: &str) -> String {
        let label = format!("__ezra_{stem}_{}", self.labels);
        self.labels += 1;
        label
    }
    fn line(&mut self, text: &str) {
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn place_type(&self, place: &Place) -> Result<Type, Diagnostic> {
        match place {
            Place::Ident(name) => self.named_type(name),
            Place::Index { name, .. } => self.array_element(&self.named_type(name)?),
            Place::Field { base, field } => self.field_type(&self.named_type(base)?, field),
            Place::Access(path) => self.access_type(path),
            Place::Deref(pointer) => match self.expr_type(pointer)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
        }
    }
    fn access_type(&self, path: &AccessPath) -> Result<Type, Diagnostic> {
        let mut ty = self.named_type(&path.root)?;
        for segment in &path.segments {
            ty = match segment {
                AccessSegment::Field(field) => self.field_type(&ty, field)?,
                AccessSegment::Index(_) => self.array_element(&ty)?,
            };
        }
        Ok(ty)
    }
    fn expr_type(&self, expr: &Expr) -> Result<Type, Diagnostic> {
        match expr {
            Expr::Int(_) => Ok(Type::Named("u16".into())),
            Expr::TypedInt(_, ty) | Expr::Cast { ty, .. } => Ok(ty.clone()),
            Expr::Bool(_) => Ok(Type::Named("bool".into())),
            Expr::Char(_) | Expr::In(_) => Ok(Type::Named("u8".into())),
            Expr::String(_) => Ok(Type::Ptr(Box::new(Type::Named("u8".into())))),
            Expr::Ident(name) => self.named_type(name),
            Expr::Field { base, field } => self.field_type(&self.named_type(base)?, field),
            Expr::Index { name, .. } => self.array_element(&self.named_type(name)?),
            Expr::Access(path) => self.access_type(path),
            Expr::AddressOf(name) => Ok(Type::Ptr(Box::new(self.named_type(name)?))),
            Expr::AddressOfIndex { name, .. } => Ok(Type::Ptr(Box::new(
                self.array_element(&self.named_type(name)?)?,
            ))),
            Expr::AddressOfField { base, field } => Ok(Type::Ptr(Box::new(
                self.field_type(&self.named_type(base)?, field)?,
            ))),
            Expr::AddressOfAccess(path) => Ok(Type::Ptr(Box::new(self.access_type(path)?))),
            Expr::Deref(pointer) => match self.expr_type(pointer)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
            Expr::BankedPointer { pointer, .. }
            | Expr::Unary { expr: pointer, .. }
            | Expr::Binary { left: pointer, .. } => self.expr_type(pointer),
            Expr::Call { path, .. } => {
                let name = path.last().ok_or_else(|| Diagnostic::new("empty call"))?;
                self.functions
                    .get(name)
                    .and_then(|function| function.return_type.clone())
                    .ok_or_else(|| {
                        Diagnostic::new(format!("DCPU function `{name}` has no value return"))
                    })
            }
            Expr::Array(_) | Expr::StructInit { .. } => {
                Err(Diagnostic::new("aggregate expression has no scalar type"))
            }
        }
    }
    fn named_type(&self, name: &str) -> Result<Type, Diagnostic> {
        self.bindings
            .get(name)
            .map(|binding| binding.ty.clone())
            .or_else(|| self.globals.get(name).cloned())
            .or_else(|| self.constant_types.get(name).cloned())
            .or_else(|| self.mmio.get(name).map(|(_, ty)| ty.clone()))
            .or_else(|| {
                self.embeds
                    .get(name)
                    .map(|_| Type::Ptr(Box::new(Type::Named("u8".into()))))
            })
            .ok_or_else(|| Diagnostic::new(format!("unknown DCPU value `{name}`")))
    }
    fn resolve_type(&self, ty: &Type) -> Result<Type, Diagnostic> {
        Ok(ty.clone())
    }
    fn scalar_words(&self, ty: &Type) -> Result<usize, Diagnostic> {
        match ty {
            Type::Named(name) if matches!(name.as_str(), "bool" | "u8" | "i8" | "u16" | "i16") => {
                Ok(1)
            }
            Type::Ptr(_) | Type::Function { .. } => Ok(1),
            Type::Named(name) if self.structs.contains_key(name) => {
                Err(Diagnostic::new("struct is not scalar"))
            }
            Type::Array { .. } => Err(Diagnostic::new("array is not scalar")),
            Type::Named(name) => Err(Diagnostic::new(format!(
                "DCPU does not support type `{name}`; values must fit in one word"
            ))),
        }
    }
    fn type_words(&self, ty: &Type) -> Result<usize, Diagnostic> {
        match ty {
            Type::Array { element, len } => usize::try_from(self.const_value(len)?)
                .map_err(|_| Diagnostic::new("array length must be non-negative"))?
                .checked_mul(self.type_words(element)?)
                .ok_or_else(|| Diagnostic::new("DCPU aggregate is too large")),
            Type::Named(name) if self.structs.contains_key(name) => self.structs[name]
                .iter()
                .try_fold(
                    0usize,
                    |size, (_, field)| Ok(size + self.type_words(field)?),
                ),
            _ => self.scalar_words(ty),
        }
    }
    fn is_aggregate(&self, ty: &Type) -> bool {
        matches!(ty, Type::Array { .. })
            || matches!(ty, Type::Named(name) if self.structs.contains_key(name))
    }
    fn array_element(&self, ty: &Type) -> Result<Type, Diagnostic> {
        match ty {
            Type::Array { element, .. } => Ok((**element).clone()),
            _ => Err(Diagnostic::new("index requires an array")),
        }
    }
    fn field_type(&self, ty: &Type, field: &str) -> Result<Type, Diagnostic> {
        match ty {
            Type::Named(name) => self
                .structs
                .get(name)
                .and_then(|fields| fields.iter().find(|(candidate, _)| candidate == field))
                .map(|(_, ty)| ty.clone())
                .ok_or_else(|| Diagnostic::new(format!("unknown field `{field}`"))),
            _ => Err(Diagnostic::new("field access requires struct")),
        }
    }
    fn field_offset(&self, ty: &Type, field: &str) -> Result<usize, Diagnostic> {
        match ty {
            Type::Named(name) => {
                let fields = self
                    .structs
                    .get(name)
                    .ok_or_else(|| Diagnostic::new("field access requires struct"))?;
                let mut offset = 0;
                for (candidate, ty) in fields {
                    if candidate == field {
                        return Ok(offset);
                    }
                    offset += self.type_words(ty)?;
                }
                Err(Diagnostic::new(format!("unknown field `{field}`")))
            }
            _ => Err(Diagnostic::new("field access requires struct")),
        }
    }
    fn const_value(&self, expr: &Expr) -> Result<i64, Diagnostic> {
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => Ok(*value),
            Expr::Bool(value) => Ok(i64::from(*value)),
            Expr::Char(value) => Ok(i64::from(*value)),
            Expr::Ident(name) => self
                .constants
                .get(name)
                .copied()
                .ok_or_else(|| Diagnostic::new(format!("`{name}` is not a constant"))),
            Expr::Unary { op, expr } => Ok(match op {
                UnaryOp::Neg => self.const_value(expr)?.wrapping_neg(),
                UnaryOp::BitNot => !self.const_value(expr)?,
                UnaryOp::Not => i64::from(self.const_value(expr)? == 0),
            }),
            Expr::Binary { left, op, right } => {
                let a = self.const_value(left)?;
                let b = self.const_value(right)?;
                Ok(match op {
                    BinaryOp::Add => a.wrapping_add(b),
                    BinaryOp::Sub => a.wrapping_sub(b),
                    BinaryOp::Mul => a.wrapping_mul(b),
                    BinaryOp::Div if b != 0 => a.wrapping_div(b),
                    BinaryOp::Mod if b != 0 => a.wrapping_rem(b),
                    BinaryOp::Shl => a.wrapping_shl(b as u32),
                    BinaryOp::Shr => ((a as u64) >> b) as i64,
                    BinaryOp::BitAnd => a & b,
                    BinaryOp::BitOr => a | b,
                    BinaryOp::BitXor => a ^ b,
                    BinaryOp::Eq => i64::from(a == b),
                    BinaryOp::Ne => i64::from(a != b),
                    BinaryOp::Lt => i64::from(a < b),
                    BinaryOp::Le => i64::from(a <= b),
                    BinaryOp::Gt => i64::from(a > b),
                    BinaryOp::Ge => i64::from(a >= b),
                    BinaryOp::And => i64::from(a != 0 && b != 0),
                    BinaryOp::Or => i64::from(a != 0 || b != 0),
                    _ => 0,
                })
            }
            Expr::Cast { expr, .. } => self.const_value(expr),
            _ => Err(Diagnostic::new("expression is not constant")),
        }
    }
}

fn return_type_params_none(
    emitter: &Emitter,
    name: &str,
    args: &[Expr],
) -> Result<Vec<crate::ast::Param>, Diagnostic> {
    if emitter.extern_functions.contains(name) {
        return Err(Diagnostic::new(format!(
            "DCPU external function `{name}` has no source signature; declare a naked EZRA wrapper with the DCPU stack ABI"
        )));
    }
    Err(Diagnostic::new(format!(
        "unknown DCPU function `{name}` with {} arguments",
        args.len()
    )))
}
fn plan_locals(
    body: &[Stmt],
    emitter: &Emitter,
) -> Result<(HashMap<String, Binding>, usize), Diagnostic> {
    fn collect(
        body: &[Stmt],
        emitter: &Emitter,
        locals: &mut Vec<(String, Type)>,
        names: &mut HashSet<String>,
    ) -> Result<(), Diagnostic> {
        for stmt in body {
            match stmt {
                Stmt::Let { name, ty, .. } => {
                    if !names.insert(name.clone()) {
                        return Err(Diagnostic::new(format!("duplicate DCPU local `{name}`")));
                    }
                    emitter.type_words(ty)?;
                    locals.push((name.clone(), ty.clone()));
                }
                Stmt::If {
                    then_body,
                    else_body,
                    ..
                } => {
                    collect(then_body, emitter, locals, names)?;
                    collect(else_body, emitter, locals, names)?;
                }
                Stmt::While { body, .. } | Stmt::Loop { body } => {
                    collect(body, emitter, locals, names)?
                }
                _ => {}
            }
        }
        Ok(())
    }

    let mut declared = Vec::new();
    collect(body, emitter, &mut declared, &mut HashSet::new())?;
    let source_locals = declared
        .iter()
        .map(|(name, ty)| {
            Ok(SourceLocal::new(
                name.clone(),
                u32::try_from(emitter.type_words(ty)?)
                    .map_err(|_| Diagnostic::new("DCPU local frame is too large"))?,
                1,
                DCPU_SCALAR_CLASS,
            )
            .with_spill_classes(vec![DCPU_STACK_SPILL_CLASS])
            .with_force_memory(emitter.is_aggregate(ty)))
        })
        .collect::<Result<Vec<_>, Diagnostic>>()?;
    let allocation = allocate_source_locals(
        &dcpu_regalloc_target(),
        &source_locals,
        body,
        &[PhysReg(0), PhysReg(1), PhysReg(2), PhysReg(3)],
    )
    .map_err(|diagnostics| {
        Diagnostic::new(format!(
            "DCPU local register allocation failed: {}",
            diagnostics
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join("; ")
        ))
    })?;

    let frame_words = allocation
        .allocation
        .spill_slots
        .iter()
        .map(|slot| slot.offset + slot.size)
        .max()
        .unwrap_or(0);
    let frame_words = usize::try_from(frame_words)
        .map_err(|_| Diagnostic::new("DCPU local frame is too large"))?;
    let mut bindings = HashMap::new();
    for (name, ty) in declared {
        let vreg = allocation.locals.vreg(&name).ok_or_else(|| {
            Diagnostic::new(format!("missing DCPU local allocation for `{name}`"))
        })?;
        let location = match allocation.allocation.location(vreg) {
            Some(Location::Register(register)) => BindingLocation::Register(
                *DCPU_LOCAL_REGISTERS
                    .get(register.0)
                    .ok_or_else(|| Diagnostic::new("invalid DCPU allocated register"))?,
            ),
            Some(Location::Spill(slot_index)) => {
                let slot = allocation
                    .allocation
                    .spill_slots
                    .get(slot_index)
                    .ok_or_else(|| Diagnostic::new("invalid DCPU spill slot"))?;
                let end = slot
                    .offset
                    .checked_add(slot.size)
                    .ok_or_else(|| Diagnostic::new("DCPU local frame is too large"))?;
                BindingLocation::Frame(
                    i16::try_from(end)
                        .map_err(|_| Diagnostic::new("DCPU local frame is too large"))?
                        .checked_neg()
                        .ok_or_else(|| Diagnostic::new("DCPU local frame is too large"))?,
                )
            }
            Some(Location::Unused) | None => {
                return Err(Diagnostic::new(format!(
                    "DCPU local `{name}` has no storage allocation"
                )));
            }
        };
        bindings.insert(name, Binding { location, ty });
    }
    Ok((bindings, frame_words))
}

fn dcpu_regalloc_target() -> Target {
    Target {
        units: DCPU_LOCAL_REGISTERS
            .iter()
            .map(|name| RegisterUnit::new(*name))
            .collect(),
        registers: DCPU_LOCAL_REGISTERS
            .iter()
            .enumerate()
            .map(|(index, name)| PhysicalRegister::new(*name, vec![RegUnit(index)]))
            .collect(),
        register_classes: vec![RegisterClass::new(
            "word",
            (0..DCPU_LOCAL_REGISTERS.len()).map(PhysReg).collect(),
        )],
        spill_classes: vec![SpillClass::new("stack-words", None, 1).with_base_alignment(1)],
    }
}
fn assign_binary(op: AssignOp) -> BinaryOp {
    match op {
        AssignOp::Set => unreachable!(),
        AssignOp::Add => BinaryOp::Add,
        AssignOp::Sub => BinaryOp::Sub,
        AssignOp::Mul => BinaryOp::Mul,
        AssignOp::Div => BinaryOp::Div,
        AssignOp::Mod => BinaryOp::Mod,
        AssignOp::BitAnd => BinaryOp::BitAnd,
        AssignOp::BitOr => BinaryOp::BitOr,
        AssignOp::BitXor => BinaryOp::BitXor,
        AssignOp::Shl => BinaryOp::Shl,
        AssignOp::Shr => BinaryOp::Shr,
    }
}
fn signed(ty: &Type) -> bool {
    matches!(ty, Type::Named(name) if matches!(name.as_str(), "i8" | "i16"))
}
fn arithmetic_instruction(op: BinaryOp, ty: &Type) -> Result<&'static str, Diagnostic> {
    Ok(match op {
        BinaryOp::Add => "add",
        BinaryOp::Sub => "sub",
        BinaryOp::Mul if signed(ty) => "mli",
        BinaryOp::Mul => "mul",
        BinaryOp::Div if signed(ty) => "dvi",
        BinaryOp::Div => "div",
        BinaryOp::Mod if signed(ty) => "mdi",
        BinaryOp::Mod => "mod",
        BinaryOp::Shl => "shl",
        BinaryOp::Shr if signed(ty) => "asr",
        BinaryOp::Shr => "shr",
        BinaryOp::BitAnd => "and",
        BinaryOp::BitOr => "bor",
        BinaryOp::BitXor => "xor",
        _ => return Err(Diagnostic::new("invalid DCPU arithmetic operation")),
    })
}
fn function_label(name: &str) -> String {
    format!(
        "_{}",
        name.chars()
            .map(
                |character| if character.is_ascii_alphanumeric() || character == '_' {
                    character
                } else {
                    '_'
                }
            )
            .collect::<String>()
    )
}

#[cfg(test)]
mod tests;
