use std::collections::HashMap;

use crate::{
    asm::{AssemblyOptions, comments::with_readability_comments},
    ast::{AssignOp, BinaryOp, Expr, Type, UnaryOp},
    diagnostic::Diagnostic,
    hir::HirProgram,
    target::CpuFamily,
    tbir::{TbirDeclaration, TbirProgram, TbirStmt},
};

/// Emits the small, currently supported DCPU-16 subset from the common HIR/TBIR pipeline.
pub fn emit_dcpu_assembly_with_options(
    program: &crate::ast::Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    if options.cpu != CpuFamily::Dcpu {
        return Err(Diagnostic::new("DCPU-16 emitter requires a DCPU-16 target"));
    }
    if program.main_function().is_none() {
        return Err(Diagnostic::new(
            "DCPU-16 programs require a `main` function",
        ));
    }

    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    Emitter::new()
        .emit(&tbir)
        .map(|asm| with_readability_comments(asm, program, &options, "dcpu"))
}

struct Emitter {
    out: String,
    locals: HashMap<String, &'static str>,
    next_register: usize,
}

impl Emitter {
    fn new() -> Self {
        Self {
            out: String::new(),
            locals: HashMap::new(),
            // I and J are reserved for expression temporaries.
            next_register: 0,
        }
    }

    fn emit(mut self, program: &TbirProgram) -> Result<String, Diagnostic> {
        let mut main = None;
        for declaration in &program.declarations {
            match declaration {
                TbirDeclaration::Function {
                    name,
                    params,
                    return_type,
                    body,
                    ..
                } if name == "main" => {
                    if !params.is_empty() || return_type.is_some() {
                        return Err(Diagnostic::new(
                            "DCPU-16 `main` must not have parameters or a return value",
                        ));
                    }
                    main = Some(body.as_slice());
                }
                TbirDeclaration::Function { name, .. } => {
                    return Err(Diagnostic::new(format!(
                        "DCPU-16 emitter currently supports only `main`; function `{name}` is unsupported"
                    )));
                }
                TbirDeclaration::Object { name, kind } => {
                    return Err(Diagnostic::new(format!(
                        "DCPU-16 emitter does not yet support {kind:?} declaration `{name}`"
                    )));
                }
            }
        }
        let main =
            main.ok_or_else(|| Diagnostic::new("DCPU-16 programs require a `main` function"))?;

        self.line("; generated by ezrac");
        self.line("; target: DCPU-16");
        self.line("__ezra_start:");
        self.line("    jsr _main");
        self.line("__ezra_exit:");
        self.line("    set pc, __ezra_exit");
        self.line("_main:");
        self.emit_block(main)?;
        self.line("    set pc, pop");
        Ok(self.out)
    }

    fn emit_block(&mut self, statements: &[TbirStmt]) -> Result<(), Diagnostic> {
        for statement in statements {
            self.emit_stmt(statement)?;
        }
        Ok(())
    }

    fn emit_stmt(&mut self, statement: &TbirStmt) -> Result<(), Diagnostic> {
        match statement {
            TbirStmt::Let { name, ty, value } => {
                self.require_scalar_type(ty, &format!("local `{name}`"))?;
                let register = self.allocate_local(name)?;
                self.emit_expr(value, register)
            }
            TbirStmt::Assign { target, op, value } => {
                let crate::ast::Place::Ident(name) = target else {
                    return Err(Diagnostic::new(
                        "DCPU-16 emitter currently supports assignment to local scalar variables only",
                    ));
                };
                let register = self.local(name)?;
                if *op == AssignOp::Set {
                    self.emit_expr(value, register)
                } else {
                    self.line(&format!("    set push, {register}"));
                    self.emit_expr(value, register)?;
                    self.line("    set j, pop");
                    self.line(&format!("    {} j, {register}", assign_opcode(*op)?));
                    self.line(&format!("    set {register}, j"));
                    Ok(())
                }
            }
            TbirStmt::Asm {
                inputs,
                outputs,
                lines,
                ..
            } => {
                if !inputs.is_empty() || !outputs.is_empty() {
                    return Err(Diagnostic::new(
                        "DCPU-16 inline asm operands are not yet supported; use an operand-free asm block",
                    ));
                }
                for line in lines {
                    if line.contains(['{', '}']) {
                        return Err(Diagnostic::new(format!(
                            "DCPU-16 inline asm has an unresolved operand placeholder in `{line}`"
                        )));
                    }
                    self.line(&format!("    {line}"));
                }
                Ok(())
            }
            TbirStmt::Return(None) => {
                self.line("    set pc, pop");
                Ok(())
            }
            TbirStmt::Return(Some(_)) => Err(Diagnostic::new(
                "DCPU-16 emitter does not yet support return values",
            )),
            TbirStmt::Eval(expr) => self.emit_expr(expr, "j"),
            TbirStmt::If { .. }
            | TbirStmt::While { .. }
            | TbirStmt::Loop { .. }
            | TbirStmt::Break
            | TbirStmt::Continue => Err(Diagnostic::new(
                "DCPU-16 emitter does not yet support control-flow statements",
            )),
            TbirStmt::PortWrite { port, .. } => Err(Diagnostic::new(format!(
                "DCPU-16 does not support separate port I/O `{port}`"
            ))),
        }
    }

    fn emit_expr(&mut self, expr: &Expr, destination: &str) -> Result<(), Diagnostic> {
        match expr {
            Expr::Int(value) => self.set_literal(destination, *value),
            Expr::TypedInt(value, ty) => {
                self.require_scalar_type(ty, "integer literal")?;
                self.set_literal(destination, *value)
            }
            Expr::Bool(value) => {
                self.line(&format!("    set {destination}, {}", u16::from(*value)));
                Ok(())
            }
            Expr::Char(value) => {
                self.line(&format!("    set {destination}, {value}"));
                Ok(())
            }
            Expr::Ident(name) => {
                let source = self.local(name)?;
                if source != destination {
                    self.line(&format!("    set {destination}, {source}"));
                }
                Ok(())
            }
            Expr::Cast { ty, expr } => {
                self.require_scalar_type(ty, "cast")?;
                self.emit_expr(expr, destination)
            }
            Expr::Unary { op, expr } => {
                self.emit_expr(expr, destination)?;
                match op {
                    UnaryOp::Neg => {
                        self.line("    set j, 0");
                        self.line(&format!("    sub j, {destination}"));
                        self.line(&format!("    set {destination}, j"));
                    }
                    UnaryOp::BitNot => self.line(&format!("    xor {destination}, 0xffff")),
                    UnaryOp::Not => {
                        self.line("    set j, 0");
                        self.emit_comparison(destination, "ife", "j");
                    }
                }
                Ok(())
            }
            Expr::Binary { left, op, right } => {
                self.emit_expr(left, destination)?;
                self.line(&format!("    set push, {destination}"));
                self.emit_expr(right, destination)?;
                self.line("    set j, pop");
                match op {
                    BinaryOp::Eq => self.emit_comparison(destination, "ife", "j"),
                    BinaryOp::Ne => self.emit_comparison(destination, "ifn", "j"),
                    BinaryOp::Lt => self.emit_comparison(destination, "ifl", "j"),
                    BinaryOp::Gt => self.emit_comparison(destination, "ifg", "j"),
                    BinaryOp::Le | BinaryOp::Ge | BinaryOp::And | BinaryOp::Or => {
                        return Err(Diagnostic::new(format!(
                            "DCPU-16 emitter does not yet support binary operator `{op:?}`"
                        )));
                    }
                    _ => {
                        self.line(&format!("    {} j, {destination}", binary_opcode(*op)?));
                        self.line(&format!("    set {destination}, j"));
                    }
                }
                Ok(())
            }
            _ => Err(Diagnostic::new(format!(
                "DCPU-16 emitter does not yet support expression `{expr:?}`"
            ))),
        }
    }

    /// Compares J against the current destination value and leaves a boolean in destination.
    fn emit_comparison(&mut self, destination: &str, instruction: &str, left: &str) {
        self.line(&format!("    set i, {destination}"));
        self.line(&format!("    set {destination}, 0"));
        self.line(&format!("    {instruction} {left}, i"));
        self.line(&format!("    set {destination}, 1"));
    }

    fn set_literal(&mut self, destination: &str, value: i64) -> Result<(), Diagnostic> {
        let value = u16::try_from(value).map_err(|_| {
            Diagnostic::new(format!(
                "DCPU-16 literal `{value}` is outside the 16-bit range"
            ))
        })?;
        self.line(&format!("    set {destination}, 0x{value:04x}"));
        Ok(())
    }

    fn require_scalar_type(&self, ty: &Type, context: &str) -> Result<(), Diagnostic> {
        match ty {
            Type::Named(name) if matches!(name.as_str(), "bool" | "u8" | "i8" | "u16" | "i16") => {
                Ok(())
            }
            _ => Err(Diagnostic::new(format!(
                "DCPU-16 emitter supports only bool, u8, i8, u16, and i16 scalar values; unsupported {context} type `{ty:?}`"
            ))),
        }
    }

    fn allocate_local(&mut self, name: &str) -> Result<&'static str, Diagnostic> {
        const REGISTERS: [&str; 6] = ["a", "b", "c", "x", "y", "z"];
        if self.locals.contains_key(name) {
            return Err(Diagnostic::new(format!("duplicate DCPU-16 local `{name}`")));
        }
        let register = *REGISTERS.get(self.next_register).ok_or_else(|| {
            Diagnostic::new("DCPU-16 emitter currently supports at most six local scalar variables")
        })?;
        self.next_register += 1;
        self.locals.insert(name.to_owned(), register);
        Ok(register)
    }

    fn local(&self, name: &str) -> Result<&'static str, Diagnostic> {
        self.locals
            .get(name)
            .copied()
            .ok_or_else(|| Diagnostic::new(format!("DCPU-16 local `{name}` is not available")))
    }

    fn line(&mut self, line: &str) {
        self.out.push_str(line);
        self.out.push('\n');
    }
}

fn binary_opcode(op: BinaryOp) -> Result<&'static str, Diagnostic> {
    match op {
        BinaryOp::Mul => Ok("mul"),
        BinaryOp::Div => Ok("div"),
        BinaryOp::Mod => Ok("mod"),
        BinaryOp::Add => Ok("add"),
        BinaryOp::Sub => Ok("sub"),
        BinaryOp::Shl => Ok("shl"),
        BinaryOp::Shr => Ok("shr"),
        BinaryOp::BitAnd => Ok("and"),
        BinaryOp::BitXor => Ok("xor"),
        BinaryOp::BitOr => Ok("bor"),
        _ => Err(Diagnostic::new(format!(
            "DCPU-16 emitter does not yet support binary operator `{op:?}`"
        ))),
    }
}

fn assign_opcode(op: AssignOp) -> Result<&'static str, Diagnostic> {
    match op {
        AssignOp::Add => Ok("add"),
        AssignOp::Sub => Ok("sub"),
        AssignOp::Mul => Ok("mul"),
        AssignOp::Div => Ok("div"),
        AssignOp::Mod => Ok("mod"),
        AssignOp::BitAnd => Ok("and"),
        AssignOp::BitOr => Ok("bor"),
        AssignOp::BitXor => Ok("xor"),
        AssignOp::Shl => Ok("shl"),
        AssignOp::Shr => Ok("shr"),
        AssignOp::Set => Err(Diagnostic::new("internal DCPU-16 assignment error")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        asm::AssemblyOptions, parser::parse_program, target::CpuFamily,
        vm::assemble_subset_with_symbols_at,
    };
    use std::path::Path;

    fn emit(source: &str) -> String {
        let program = parse_program(Path::new("dcpu.ezra"), source).unwrap();
        let assembly = emit_dcpu_assembly_with_options(
            &program,
            AssemblyOptions {
                cpu: CpuFamily::Dcpu,
                ..AssemblyOptions::default()
            },
        )
        .unwrap();
        assemble_subset_with_symbols_at(CpuFamily::Dcpu.into(), &assembly, 0)
            .unwrap_or_else(|error| panic!("{error}\n{assembly}"));
        assembly
    }

    #[test]
    fn empty_main_assembles() {
        let assembly = emit("fn main() {}");
        assert!(assembly.contains("jsr _main"));
    }

    #[test]
    fn operand_free_inline_asm_assembles() {
        let assembly =
            emit(r#"fn main() { asm volatile(clobber memory) { "set a, 0x30" "add a, 2" } }"#);
        assert!(assembly.contains("set a, 0x30"));
    }

    #[test]
    fn scalar_arithmetic_assembles() {
        let assembly =
            emit("fn main() { let left: u16 = 0x10; let right: u16 = 2; left += right * 3 }");
        assert!(assembly.contains("mul j, a"));
        assert!(assembly.contains("add j, a"));
    }
}
