//! Generic Intel 8086 EZRA source emitter.
//!
//! The ABI deliberately mirrors the other small generic backends: arguments and
//! locals have compiler-owned static addresses, scalar expression results live
//! in `r0`, and a caller saves its live static frame around a call.  Pointers are
//! 16-bit offsets in the single segment established by the startup stub.

use crate::{
    asm::{AssemblyOptions, comments::with_readability_comments},
    ast::{
        AccessPath, AccessSegment, AssignOp, BinaryOp, Declaration, Expr, Function, Place, Program,
        Stmt, Type, UnaryOp,
    },
    compat::prelude::*,
    diagnostic::Diagnostic,
    hir::HirProgram,
    target::CpuFamily,
    tbir::{
        TbirProgram,
        model::{SemanticModel, Storage},
    },
};

const SCRATCH_BYTES: u32 = 8;

/// Lowers an EZRA AST through HIR and TBIR and emits strict original-8086
/// assembly.  The generated image is one flat segment; CS is copied to DS, ES,
/// and SS before static initialization and all calls are near calls.
pub fn emit_i8086_assembly_with_options(
    program: &Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    if options.cpu != CpuFamily::I8086 {
        return Err(Diagnostic::new("i8086 emitter requires an i8086 target"));
    }
    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    let model = SemanticModel::from_program(
        &tbir.lowered_program,
        16,
        options.ram_base.get(),
        options.rodata_base.get(),
        options.asset_base.get(),
    )?;
    Emitter::new(model, options.clone())
        .emit(&tbir.lowered_program)
        .map(|asm| with_readability_comments(asm, program, &options, "i8086"))
}

#[derive(Clone)]
struct Binding {
    storage: Storage,
    ty: Type,
}

#[derive(Clone)]
struct LoopLabels {
    continue_label: String,
    break_label: String,
}

enum Address {
    Direct(u32),
    Indirect,
}

struct Emitter {
    model: SemanticModel,
    options: AssemblyOptions,
    out: String,
    labels: usize,
    scopes: Vec<HashMap<String, Binding>>,
    loops: Vec<LoopLabels>,
    return_labels: Vec<String>,
    return_types: Vec<Option<Type>>,
    function_ram_bases: Vec<u32>,
    ports: HashMap<String, u8>,
    r0: Storage,
    r1: Storage,
    r2: Storage,
}

impl Emitter {
    fn new(mut model: SemanticModel, options: AssemblyOptions) -> Self {
        let r0 = model.allocate(SCRATCH_BYTES).expect("8086 result scratch");
        let r1 = model.allocate(SCRATCH_BYTES).expect("8086 rhs scratch");
        let r2 = model.allocate(SCRATCH_BYTES).expect("8086 work scratch");
        Self {
            model,
            options,
            out: String::new(),
            labels: 0,
            scopes: Vec::new(),
            loops: Vec::new(),
            return_labels: Vec::new(),
            return_types: Vec::new(),
            function_ram_bases: Vec::new(),
            ports: HashMap::new(),
            r0,
            r1,
            r2,
        }
    }

    fn emit(mut self, program: &Program) -> Result<String, Diagnostic> {
        self.collect_ports(program)?;
        self.line("; generated by ezrac");
        self.line("; target: Intel 8086 (single flat segment)");
        self.line("section .text");
        self.line("__ezra_start:");
        self.line("    cli");
        self.line("    mov ax,cs");
        self.line("    mov ds,ax");
        self.line("    mov es,ax");
        self.line("    mov ss,ax");
        self.line(&format!(
            "    mov sp,{}",
            imm(self.options.stack_top.get() & !1)
        ));
        self.line("    cld");
        self.emit_static_initializers(program)?;
        self.line("    call near _main");
        self.line("__ezra_exit:");
        self.line("    jmp near __ezra_exit");

        for declaration in &program.declarations {
            if let Declaration::Function(function) = declaration {
                self.emit_function(function)?;
            }
        }
        Ok(self.out)
    }

    fn collect_ports(&mut self, program: &Program) -> Result<(), Diagnostic> {
        for declaration in &program.declarations {
            if let Declaration::Port(port) = declaration {
                let value = self.model.const_value(&port.value)?;
                let value = u8::try_from(value).map_err(|_| {
                    Diagnostic::new(format!("8086 port `{}` is outside 0..255", port.name))
                })?;
                self.ports.insert(port.name.clone(), value);
            }
        }
        Ok(())
    }

    fn emit_static_initializers(&mut self, program: &Program) -> Result<(), Diagnostic> {
        let embeds = self.model.embeds.values().cloned().collect::<Vec<_>>();
        for embed in embeds {
            for (offset, value) in embed.bytes.into_iter().enumerate() {
                self.store_immediate(embed.storage.address + offset as u32, value);
            }
        }
        let strings = self
            .model
            .strings
            .iter()
            .map(|(value, storage)| (value.clone(), *storage))
            .collect::<Vec<_>>();
        for (value, storage) in strings {
            for (offset, byte) in value.bytes().chain(core::iter::once(0)).enumerate() {
                self.store_immediate(storage.address + offset as u32, byte);
            }
        }
        for declaration in &program.declarations {
            if let Declaration::Global(global) = declaration {
                let storage = self.model.globals[&global.name];
                self.emit_initializer(storage, &global.ty, &global.value)?;
            }
        }
        Ok(())
    }

    fn emit_function(&mut self, function: &Function) -> Result<(), Diagnostic> {
        let naked = function.attrs.iter().any(|attr| attr == "naked");
        let interrupt = function.attrs.iter().any(|attr| attr == "interrupt");
        if naked
            && function.body.iter().any(|stmt| {
                !matches!(stmt, Stmt::Asm { inputs, outputs, .. } if inputs.is_empty() && outputs.is_empty())
            })
        {
            return Err(Diagnostic::new(format!(
                "naked function `{}` may contain only asm blocks without operands",
                function.name
            )));
        }
        if interrupt && (!function.params.is_empty() || function.return_type.is_some()) {
            return Err(Diagnostic::new(format!(
                "interrupt function `{}` cannot have parameters or a return value",
                function.name
            )));
        }

        let return_label = self.next_label(&format!("{}_return", function.name));
        self.line(&format!("{}:", function_label(&function.name)));
        self.scopes.push(HashMap::new());
        self.return_labels.push(return_label.clone());
        self.return_types.push(function.return_type.clone());
        self.function_ram_bases.push(self.model.next_ram_address());
        if interrupt && !naked {
            self.line("    push ax");
            self.line("    push bx");
            self.line("    push cx");
            self.line("    push dx");
            self.line("    push si");
            self.line("    push di");
            self.line("    push bp");
            self.line("    push ds");
            self.line("    push es");
        }

        let signature = self
            .model
            .functions
            .get(&function.name)
            .cloned()
            .ok_or_else(|| Diagnostic::new(format!("unknown function `{}`", function.name)))?;
        for (param, slot) in function.params.iter().zip(signature.argument_slots) {
            let storage = self.model.allocate_type(&param.ty)?;
            self.bind(param.name.clone(), storage, param.ty.clone())?;
            self.copy(slot, storage, storage.size);
        }
        self.emit_block(&function.body)?;
        self.line(&format!("{return_label}:"));
        if interrupt {
            if !naked {
                self.line("    pop es");
                self.line("    pop ds");
                self.line("    pop bp");
                self.line("    pop di");
                self.line("    pop si");
                self.line("    pop dx");
                self.line("    pop cx");
                self.line("    pop bx");
                self.line("    pop ax");
            }
            self.line("    iret");
        } else if !naked {
            self.line("    ret");
        }
        self.function_ram_bases.pop();
        self.return_types.pop();
        self.return_labels.pop();
        self.scopes.pop();
        Ok(())
    }

    fn emit_block(&mut self, body: &[Stmt]) -> Result<(), Diagnostic> {
        for stmt in body {
            self.emit_stmt(stmt)?;
        }
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<(), Diagnostic> {
        match stmt {
            Stmt::Let { name, ty, value } => {
                let storage = self.model.allocate_type(ty)?;
                self.bind(name.clone(), storage, ty.clone())?;
                self.emit_initializer(storage, ty, value)?;
            }
            Stmt::Assign { target, op, value } => {
                let ty = self.place_type(target)?;
                let Ok(width) = self.scalar_width(&ty) else {
                    if *op != AssignOp::Set {
                        return Err(Diagnostic::new(
                            "compound assignment requires a scalar value",
                        ));
                    }
                    let size = self.model.type_size(&ty)?;
                    let temporary = self.model.allocate(size)?;
                    self.emit_initializer(temporary, &ty, value)?;
                    self.store_aggregate_place(target, temporary, size)?;
                    return Ok(());
                };
                if *op == AssignOp::Set {
                    self.emit_expr(value, &ty)?;
                } else {
                    self.load_place(target, width)?;
                    let left = self.model.allocate(u32::from(width))?;
                    self.copy(self.r0, left, u32::from(width));
                    self.emit_expr(value, &ty)?;
                    self.copy(self.r0, self.r1, u32::from(width));
                    self.copy(left, self.r0, u32::from(width));
                    self.binary(assign_binary(*op), width, type_is_signed(&ty))?;
                }
                self.store_place(target, width)?;
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                let otherwise = self.next_label("if_else");
                let done = self.next_label("if_done");
                self.emit_expr(condition, &bool_ty())?;
                self.jump_storage_zero(self.r0, 1, &otherwise);
                self.emit_block(then_body)?;
                self.line(&format!("    jmp near {done}"));
                self.line(&format!("{otherwise}:"));
                self.emit_block(else_body)?;
                self.line(&format!("{done}:"));
            }
            Stmt::While { condition, body } => {
                let head = self.next_label("while_condition");
                let done = self.next_label("while_done");
                self.loops.push(LoopLabels {
                    continue_label: head.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{head}:"));
                self.emit_expr(condition, &bool_ty())?;
                self.jump_storage_zero(self.r0, 1, &done);
                self.emit_block(body)?;
                self.line(&format!("    jmp near {head}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Loop { body } => {
                let head = self.next_label("loop_body");
                let done = self.next_label("loop_done");
                self.loops.push(LoopLabels {
                    continue_label: head.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{head}:"));
                self.emit_block(body)?;
                self.line(&format!("    jmp near {head}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Break | Stmt::Continue => {
                let labels = self
                    .loops
                    .last()
                    .ok_or_else(|| Diagnostic::new("loop control outside loop"))?;
                let target = if matches!(stmt, Stmt::Continue) {
                    &labels.continue_label
                } else {
                    &labels.break_label
                }
                .clone();
                self.line(&format!("    jmp near {target}"));
            }
            Stmt::Return(value) => {
                if let Some(value) = value {
                    let ty = self
                        .return_types
                        .last()
                        .and_then(Clone::clone)
                        .ok_or_else(|| Diagnostic::new("value return in void function"))?;
                    self.emit_expr(value, &ty)?;
                }
                let target = self.return_labels.last().expect("return label").clone();
                self.line(&format!("    jmp near {target}"));
            }
            Stmt::Asm {
                inputs,
                outputs,
                lines,
                ..
            } => self.inline_asm(inputs, outputs, lines)?,
            Stmt::Out { port, value } => {
                let port = self.port(port)?;
                self.emit_expr(value, &Type::Named("u8".to_owned()))?;
                self.load_al(self.r0.address);
                self.line(&format!("    out {},al", imm(u32::from(port))));
            }
            Stmt::Expr(expr) => {
                let ty = self
                    .expr_type(expr)
                    .unwrap_or_else(|_| Type::Named("u8".to_owned()));
                self.emit_expr(expr, &ty)?;
            }
        }
        Ok(())
    }

    fn emit_initializer(
        &mut self,
        storage: Storage,
        ty: &Type,
        value: &Expr,
    ) -> Result<(), Diagnostic> {
        match (self.model.resolved_type(ty)?, value) {
            (Type::Array { .. }, Expr::Ident(name)) => {
                let source = self.binding(name)?;
                self.copy(source.storage, storage, storage.size);
            }
            (Type::Array { element, len }, Expr::Array(values)) => {
                let element_size = self.model.type_size(&element)?;
                let len = u32::try_from(self.model.const_value(&len)?)
                    .map_err(|_| Diagnostic::new("invalid array length"))?;
                for index in 0..len {
                    let target = Storage {
                        address: storage.address + index * element_size,
                        size: element_size,
                    };
                    if let Some(value) = values.get(index as usize) {
                        self.emit_initializer(target, &element, value)?;
                    } else {
                        self.zero(target);
                    }
                }
            }
            (Type::Named(name), Expr::StructInit { fields, .. })
                if self.model.structs.contains_key(&name) =>
            {
                self.zero(storage);
                let layout = self.model.structs[&name].clone();
                for (name, value) in fields {
                    let field = layout
                        .fields
                        .get(name)
                        .ok_or_else(|| Diagnostic::new(format!("unknown field `{name}`")))?;
                    self.emit_initializer(
                        Storage {
                            address: storage.address + field.offset,
                            size: field.size,
                        },
                        &field.ty,
                        value,
                    )?;
                }
            }
            (Type::Named(name), Expr::Ident(source)) if self.model.structs.contains_key(&name) => {
                self.copy(self.binding(source)?.storage, storage, storage.size);
            }
            (resolved @ (Type::Array { .. } | Type::Named(_)), Expr::Deref(pointer)) => {
                self.emit_expr(pointer, &Type::Ptr(Box::new(resolved)))?;
                self.result_to_bx();
                self.copy_indirect_to_storage(storage, storage.size);
            }
            (resolved, _) => {
                let width = self.scalar_width(&resolved)?;
                self.emit_expr(value, &resolved)?;
                self.copy(self.r0, storage, u32::from(width));
            }
        }
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr, expected: &Type) -> Result<(), Diagnostic> {
        let width = self.scalar_width(expected)?;
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => self.load_constant(*value, width),
            Expr::Bool(value) => self.load_constant(i64::from(*value), width),
            Expr::Char(value) => self.load_constant(i64::from(*value), width),
            Expr::String(value) => {
                let storage = self.model.intern_string(value)?;
                self.load_constant(i64::from(storage.address), width);
            }
            Expr::Ident(name) => {
                if let Some(value) = self.model.constants.get(name).copied() {
                    self.load_constant(value, width);
                } else {
                    let binding = self.binding(name)?;
                    let source_width = self.scalar_width(&binding.ty)?;
                    self.copy(binding.storage, self.r0, u32::from(source_width.min(width)));
                    self.extend_result(source_width, width, type_is_signed(&binding.ty));
                }
            }
            Expr::In(port) => {
                let port = self.port(port)?;
                self.line(&format!("    in al,{}", imm(u32::from(port))));
                self.store_al(self.r0.address);
                self.extend_result(1, width, false);
            }
            Expr::AddressOf(name) => {
                self.load_constant(i64::from(self.binding(name)?.storage.address), width)
            }
            Expr::AddressOfIndex { name, index } => {
                self.named_index_address(name, index)?;
                self.bx_to_result(width);
            }
            Expr::AddressOfField { base, field } => {
                let binding = self.binding(base)?;
                let offset = self.model.field(&binding.ty, field)?.offset;
                self.load_constant(i64::from(binding.storage.address + offset), width);
            }
            Expr::AddressOfAccess(path) => {
                self.access_address(path)?;
                self.bx_to_result(width);
            }
            Expr::Index { name, index } => {
                let element = self.named_index_address(name, index)?;
                let source_width = self.scalar_width(&element)?;
                self.load_indirect(source_width);
                self.extend_result(source_width, width, type_is_signed(&element));
            }
            Expr::Field { base, field } => {
                let constant = format!("{base}.{field}");
                if let Some(value) = self.model.constants.get(&constant).copied() {
                    self.load_constant(value, width);
                } else {
                    let binding = self.binding(base)?;
                    let field = self.model.field(&binding.ty, field)?.clone();
                    let source_width = self.scalar_width(&field.ty)?;
                    self.copy(
                        Storage {
                            address: binding.storage.address + field.offset,
                            size: field.size,
                        },
                        self.r0,
                        u32::from(source_width.min(width)),
                    );
                    self.extend_result(source_width, width, type_is_signed(&field.ty));
                }
            }
            Expr::Access(path) => {
                let ty = self.access_address(path)?;
                let source_width = self.scalar_width(&ty)?;
                self.load_indirect(source_width);
                self.extend_result(source_width, width, type_is_signed(&ty));
            }
            Expr::Deref(pointer) => {
                self.emit_expr(pointer, &Type::Ptr(Box::new(expected.clone())))?;
                self.result_to_bx();
                self.load_indirect(width);
            }
            Expr::Call { path, args } => self.emit_call(path, args, expected)?,
            Expr::Unary { op, expr } => {
                self.emit_expr(expr, expected)?;
                self.unary(*op, width);
            }
            Expr::Binary { left, op, right } => {
                if matches!(op, BinaryOp::And | BinaryOp::Or) {
                    self.short_circuit(left, *op, right)?;
                    self.extend_result(1, width, false);
                    return Ok(());
                }
                let operand_ty = if is_comparison(*op) {
                    self.expr_type(left)
                        .or_else(|_| self.expr_type(right))
                        .unwrap_or_else(|_| expected.clone())
                } else {
                    expected.clone()
                };
                let operand_width = self.scalar_width(&operand_ty)?;
                self.emit_expr(left, &operand_ty)?;
                let left_value = self.model.allocate(u32::from(operand_width))?;
                self.copy(self.r0, left_value, u32::from(operand_width));
                self.emit_expr(right, &operand_ty)?;
                self.copy(self.r0, self.r1, u32::from(operand_width));
                self.copy(left_value, self.r0, u32::from(operand_width));
                if matches!(op, BinaryOp::Add | BinaryOp::Sub)
                    && let Type::Ptr(inner) = self.model.resolved_type(&operand_ty)?
                {
                    self.scale(self.r1, operand_width, self.model.type_size(&inner)?);
                }
                self.binary(*op, operand_width, type_is_signed(&operand_ty))?;
                if is_comparison(*op) {
                    self.extend_result(1, width, false);
                }
            }
            Expr::Cast { ty, expr } => {
                let source_ty = self.expr_type(expr).unwrap_or_else(|_| ty.clone());
                let source_width = self.scalar_width(&source_ty)?;
                self.emit_expr(expr, &source_ty)?;
                self.extend_result(source_width, width, type_is_signed(&source_ty));
            }
            Expr::Array(_) | Expr::StructInit { .. } => {
                return Err(Diagnostic::new("aggregate value requires storage context"));
            }
        }
        Ok(())
    }

    fn emit_call(
        &mut self,
        path: &[String],
        args: &[Expr],
        expected: &Type,
    ) -> Result<(), Diagnostic> {
        let name = path.join(".");
        match name.as_str() {
            "mem.peek8" | "ezra.mem.peek8" => {
                self.require_args(&name, args, 1)?;
                self.emit_expr(&args[0], &byte_ptr())?;
                self.result_to_bx();
                self.load_indirect(1);
                return Ok(());
            }
            "mem.poke8" | "ezra.mem.poke8" => {
                self.require_args(&name, args, 2)?;
                self.emit_expr(&args[0], &byte_ptr())?;
                let pointer = self.model.allocate(2)?;
                self.copy(self.r0, pointer, 2);
                self.emit_expr(&args[1], &Type::Named("u8".to_owned()))?;
                self.load_bx(pointer.address);
                self.load_al(self.r0.address);
                self.line("    mov [bx],al");
                return Ok(());
            }
            "mem.memcpy" | "ezra.mem.memcpy" => return self.memcpy(args),
            "mem.memset" | "ezra.mem.memset" => return self.memset(args),
            _ => {}
        }
        let resolved = resolve_function(path, &self.model)
            .ok_or_else(|| Diagnostic::new(format!("unknown function `{name}`")))?;
        let signature = self.model.functions[&resolved].clone();
        if signature.params.len() != args.len() {
            return Err(Diagnostic::new(format!(
                "function `{name}` expects {} arguments, got {}",
                signature.params.len(),
                args.len()
            )));
        }
        let mut values = Vec::with_capacity(args.len());
        for (arg, ty) in args.iter().zip(&signature.params) {
            self.emit_expr(arg, ty)?;
            let value = self.model.allocate(self.model.type_size(ty)?)?;
            self.copy(self.r0, value, value.size);
            values.push(value);
        }
        for (value, slot) in values.into_iter().zip(&signature.argument_slots) {
            self.copy(value, *slot, value.size);
        }

        let live = self.function_ram_bases.last().map(|base| Storage {
            address: *base,
            size: self.model.next_ram_address() - *base,
        });
        if let Some(live) = live {
            self.push_bytes(live);
        }
        self.line(&format!("    call near {}", function_label(&resolved)));
        let returned = signature
            .return_type
            .as_ref()
            .map(|ty| self.model.type_size(ty))
            .transpose()?
            .map(|size| self.model.allocate(size))
            .transpose()?;
        if let Some(returned) = returned {
            self.copy(self.r0, returned, returned.size);
        }
        if let Some(live) = live {
            self.pop_bytes(live);
        }
        if let Some(returned) = returned {
            self.copy(returned, self.r0, returned.size);
            let return_width = self.scalar_width(signature.return_type.as_ref().unwrap())?;
            self.extend_result(return_width, self.scalar_width(expected)?, false);
        } else {
            self.zero(self.r0);
        }
        Ok(())
    }

    fn memcpy(&mut self, args: &[Expr]) -> Result<(), Diagnostic> {
        self.require_args("mem.memcpy", args, 3)?;
        self.emit_expr(&args[0], &byte_ptr())?;
        let dst = self.model.allocate(2)?;
        self.copy(self.r0, dst, 2);
        self.emit_expr(&args[1], &byte_ptr())?;
        let src = self.model.allocate(2)?;
        self.copy(self.r0, src, 2);
        self.emit_expr(&args[2], &Type::Named("u16".to_owned()))?;
        let len = self.model.allocate(2)?;
        self.copy(self.r0, len, 2);
        let loop_label = self.next_label("memcpy_loop");
        let done = self.next_label("memcpy_done");
        self.load_si(src.address);
        self.load_di(dst.address);
        self.load_cx(len.address);
        self.line(&format!("{loop_label}:"));
        self.line(&format!("    jcxz short {done}"));
        self.line("    mov al,[si]");
        self.line("    mov [di],al");
        self.line("    inc si");
        self.line("    inc di");
        self.line("    dec cx");
        self.line(&format!("    jmp near {loop_label}"));
        self.line(&format!("{done}:"));
        self.zero(self.r0);
        Ok(())
    }

    fn memset(&mut self, args: &[Expr]) -> Result<(), Diagnostic> {
        self.require_args("mem.memset", args, 3)?;
        self.emit_expr(&args[0], &byte_ptr())?;
        let dst = self.model.allocate(2)?;
        self.copy(self.r0, dst, 2);
        self.emit_expr(&args[1], &Type::Named("u8".to_owned()))?;
        let value = self.model.allocate(1)?;
        self.copy(self.r0, value, 1);
        self.emit_expr(&args[2], &Type::Named("u16".to_owned()))?;
        let len = self.model.allocate(2)?;
        self.copy(self.r0, len, 2);
        let loop_label = self.next_label("memset_loop");
        let done = self.next_label("memset_done");
        self.load_di(dst.address);
        self.load_cx(len.address);
        self.load_al(value.address);
        self.line(&format!("{loop_label}:"));
        self.line(&format!("    jcxz short {done}"));
        self.line("    mov [di],al");
        self.line("    inc di");
        self.line("    dec cx");
        self.line(&format!("    jmp near {loop_label}"));
        self.line(&format!("{done}:"));
        self.zero(self.r0);
        Ok(())
    }

    fn require_args(&self, name: &str, args: &[Expr], count: usize) -> Result<(), Diagnostic> {
        if args.len() == count {
            Ok(())
        } else {
            Err(Diagnostic::new(format!(
                "{name} requires {count} arguments"
            )))
        }
    }

    fn unary(&mut self, op: UnaryOp, width: u8) {
        match op {
            UnaryOp::BitNot => {
                for offset in 0..u32::from(width) {
                    self.load_al(self.r0.address + offset);
                    self.line("    not al");
                    self.store_al(self.r0.address + offset);
                }
            }
            UnaryOp::Neg => self.negate(self.r0, width),
            UnaryOp::Not => {
                let yes = self.next_label("not_true");
                let done = self.next_label("not_done");
                self.jump_storage_zero(self.r0, width, &yes);
                self.load_constant(0, width);
                self.line(&format!("    jmp near {done}"));
                self.line(&format!("{yes}:"));
                self.load_constant(1, width);
                self.line(&format!("{done}:"));
            }
        }
    }

    fn binary(&mut self, op: BinaryOp, width: u8, signed: bool) -> Result<(), Diagnostic> {
        match op {
            BinaryOp::Add => self.add(width),
            BinaryOp::Sub => self.sub(width),
            BinaryOp::BitAnd | BinaryOp::BitOr | BinaryOp::BitXor => {
                for offset in 0..u32::from(width) {
                    self.load_al(self.r0.address + offset);
                    let mnemonic = match op {
                        BinaryOp::BitAnd => "and",
                        BinaryOp::BitOr => "or",
                        _ => "xor",
                    };
                    self.line(&format!(
                        "    {mnemonic} al,{}",
                        mem(self.r1.address + offset)
                    ));
                    self.store_al(self.r0.address + offset);
                }
            }
            BinaryOp::Mul => self.multiply(width, signed),
            BinaryOp::Div | BinaryOp::Mod => self.divide(width, op == BinaryOp::Mod, signed),
            BinaryOp::Shl | BinaryOp::Shr => self.shift(width, op == BinaryOp::Shr, signed),
            BinaryOp::And | BinaryOp::Or => unreachable!("short-circuited"),
            op if is_comparison(op) => self.compare(op, width, signed),
            _ => return Err(Diagnostic::new("unsupported i8086 binary operation")),
        }
        Ok(())
    }

    fn add(&mut self, width: u8) {
        self.line("    clc");
        for offset in 0..u32::from(width) {
            self.load_al(self.r0.address + offset);
            self.line(&format!("    adc al,{}", mem(self.r1.address + offset)));
            self.store_al(self.r0.address + offset);
        }
    }

    fn sub(&mut self, width: u8) {
        self.line("    clc");
        for offset in 0..u32::from(width) {
            self.load_al(self.r0.address + offset);
            self.line(&format!("    sbb al,{}", mem(self.r1.address + offset)));
            self.store_al(self.r0.address + offset);
        }
    }

    fn multiply(&mut self, width: u8, signed: bool) {
        let multiplicand = self
            .model
            .allocate(u32::from(width))
            .expect("multiply scratch");
        let multiplier = self
            .model
            .allocate(u32::from(width))
            .expect("multiply scratch");
        let negative = self.model.allocate(1).expect("multiply sign");
        self.zero(negative);
        if signed {
            self.normalize_signed(self.r0, width, negative, false);
            self.normalize_signed(self.r1, width, negative, true);
        }
        self.copy(self.r0, multiplicand, u32::from(width));
        self.copy(self.r1, multiplier, u32::from(width));
        self.zero(self.r0);
        let loop_label = self.next_label("multiply_loop");
        let done = self.next_label("multiply_done");
        self.line(&format!("{loop_label}:"));
        self.jump_storage_zero(multiplier, width, &done);
        self.copy(multiplicand, self.r1, u32::from(width));
        self.add(width);
        self.decrement(multiplier, width);
        self.line(&format!("    jmp near {loop_label}"));
        self.line(&format!("{done}:"));
        if signed {
            self.negate_if(negative, self.r0, width);
        }
    }

    fn divide(&mut self, width: u8, remainder: bool, signed: bool) {
        let quotient = self.r2;
        let quotient_negative = self.model.allocate(1).expect("divide sign");
        let remainder_negative = self.model.allocate(1).expect("divide sign");
        self.zero(quotient_negative);
        self.zero(remainder_negative);
        if signed {
            let positive = self.next_label("dividend_positive");
            self.load_al(self.r0.address + u32::from(width - 1));
            self.line("    test al,80h");
            self.branch_long("jz", &positive);
            self.toggle(quotient_negative);
            self.toggle(remainder_negative);
            self.negate(self.r0, width);
            self.line(&format!("{positive}:"));
            self.normalize_signed(self.r1, width, quotient_negative, true);
        }
        self.zero(quotient);
        let zero = self.next_label("divide_zero");
        let loop_label = self.next_label("divide_loop");
        let done = self.next_label("divide_done");
        self.jump_storage_zero(self.r1, width, &zero);
        self.line(&format!("{loop_label}:"));
        self.jump_less(self.r0, self.r1, width, &done);
        self.sub(width);
        self.increment(quotient, width);
        self.line(&format!("    jmp near {loop_label}"));
        self.line(&format!("{zero}:"));
        self.zero(self.r0);
        self.line(&format!("    jmp near {done}"));
        self.line(&format!("{done}:"));
        if !remainder {
            self.copy(quotient, self.r0, u32::from(width));
        }
        if signed {
            self.negate_if(
                if remainder {
                    remainder_negative
                } else {
                    quotient_negative
                },
                self.r0,
                width,
            );
        }
    }

    fn shift(&mut self, width: u8, right: bool, signed: bool) {
        let loop_label = self.next_label("shift_loop");
        let done = self.next_label("shift_done");
        self.load_cl(self.r1.address);
        self.line(&format!("{loop_label}:"));
        self.line("    or cl,cl");
        self.branch_long("jz", &done);
        if right {
            let top = self.r0.address + u32::from(width - 1);
            self.load_al(top);
            self.line(if signed {
                "    sar al,1"
            } else {
                "    shr al,1"
            });
            self.store_al(top);
            for offset in (0..u32::from(width - 1)).rev() {
                self.load_al(self.r0.address + offset);
                self.line("    rcr al,1");
                self.store_al(self.r0.address + offset);
            }
        } else {
            self.load_al(self.r0.address);
            self.line("    shl al,1");
            self.store_al(self.r0.address);
            for offset in 1..u32::from(width) {
                self.load_al(self.r0.address + offset);
                self.line("    rcl al,1");
                self.store_al(self.r0.address + offset);
            }
        }
        self.line("    dec cl");
        self.line(&format!("    jmp near {loop_label}"));
        self.line(&format!("{done}:"));
    }

    fn short_circuit(&mut self, left: &Expr, op: BinaryOp, right: &Expr) -> Result<(), Diagnostic> {
        let decisive = self.next_label("logical_decisive");
        let done = self.next_label("logical_done");
        self.emit_expr(left, &bool_ty())?;
        if op == BinaryOp::And {
            self.jump_storage_zero(self.r0, 1, &decisive);
        } else {
            self.jump_storage_nonzero(self.r0, 1, &decisive);
        }
        self.emit_expr(right, &bool_ty())?;
        self.line(&format!("    jmp near {done}"));
        self.line(&format!("{decisive}:"));
        self.load_constant(i64::from(op == BinaryOp::Or), 1);
        self.line(&format!("{done}:"));
        Ok(())
    }

    fn compare(&mut self, op: BinaryOp, width: u8, signed: bool) {
        if signed && !matches!(op, BinaryOp::Eq | BinaryOp::Ne) {
            let top = u32::from(width - 1);
            self.load_al(self.r0.address + top);
            self.line("    xor al,80h");
            self.store_al(self.r0.address + top);
            self.load_al(self.r1.address + top);
            self.line("    xor al,80h");
            self.store_al(self.r1.address + top);
        }
        let yes = self.next_label("compare_true");
        let no = self.next_label("compare_false");
        let done = self.next_label("compare_done");
        match op {
            BinaryOp::Eq | BinaryOp::Ne => {
                let unequal = if op == BinaryOp::Ne { &yes } else { &no };
                for offset in 0..u32::from(width) {
                    self.load_al(self.r0.address + offset);
                    self.line(&format!("    cmp al,{}", mem(self.r1.address + offset)));
                    self.branch_long("jne", unequal);
                }
                self.line(&format!(
                    "    jmp near {}",
                    if op == BinaryOp::Eq { &yes } else { &no }
                ));
            }
            BinaryOp::Lt | BinaryOp::Le => {
                self.jump_less(self.r0, self.r1, width, &yes);
                if op == BinaryOp::Le {
                    self.jump_equal(self.r0, self.r1, width, &yes);
                }
                self.line(&format!("    jmp near {no}"));
            }
            BinaryOp::Gt | BinaryOp::Ge => {
                self.jump_less(self.r0, self.r1, width, &no);
                if op == BinaryOp::Gt {
                    self.jump_equal(self.r0, self.r1, width, &no);
                }
                self.line(&format!("    jmp near {yes}"));
            }
            _ => unreachable!(),
        }
        self.line(&format!("{yes}:"));
        self.load_constant(1, 1);
        self.line(&format!("    jmp near {done}"));
        self.line(&format!("{no}:"));
        self.load_constant(0, 1);
        self.line(&format!("{done}:"));
    }

    fn load_place(&mut self, place: &Place, width: u8) -> Result<(), Diagnostic> {
        match self.place_address(place)? {
            Address::Direct(address) => self.copy(
                Storage {
                    address,
                    size: u32::from(width),
                },
                self.r0,
                u32::from(width),
            ),
            Address::Indirect => self.load_indirect(width),
        }
        Ok(())
    }

    fn store_place(&mut self, place: &Place, width: u8) -> Result<(), Diagnostic> {
        let saved = self.model.allocate(u32::from(width))?;
        self.copy(self.r0, saved, u32::from(width));
        match self.place_address(place)? {
            Address::Direct(address) => self.copy(
                saved,
                Storage {
                    address,
                    size: u32::from(width),
                },
                u32::from(width),
            ),
            Address::Indirect => self.copy_storage_to_indirect(saved, u32::from(width)),
        }
        Ok(())
    }

    fn store_aggregate_place(
        &mut self,
        place: &Place,
        source: Storage,
        size: u32,
    ) -> Result<(), Diagnostic> {
        match self.place_address(place)? {
            Address::Direct(address) => self.copy(source, Storage { address, size }, size),
            Address::Indirect => self.copy_storage_to_indirect(source, size),
        }
        Ok(())
    }

    fn place_address(&mut self, place: &Place) -> Result<Address, Diagnostic> {
        match place {
            Place::Ident(name) => Ok(Address::Direct(self.binding(name)?.storage.address)),
            Place::Index { name, index } => {
                self.named_index_address(name, index)?;
                Ok(Address::Indirect)
            }
            Place::Field { base, field } => {
                let binding = self.binding(base)?;
                Ok(Address::Direct(
                    binding.storage.address + self.model.field(&binding.ty, field)?.offset,
                ))
            }
            Place::Access(path) => {
                self.access_address(path)?;
                Ok(Address::Indirect)
            }
            Place::Deref(expr) => {
                let Type::Ptr(inner) = self.model.resolved_type(&self.expr_type(expr)?)? else {
                    return Err(Diagnostic::new("dereference requires pointer"));
                };
                self.emit_expr(expr, &Type::Ptr(inner))?;
                self.result_to_bx();
                Ok(Address::Indirect)
            }
        }
    }

    fn place_type(&self, place: &Place) -> Result<Type, Diagnostic> {
        match place {
            Place::Ident(name) => Ok(self.binding(name)?.ty),
            Place::Index { name, .. } => {
                element_type(&self.model.resolved_type(&self.binding(name)?.ty)?)
            }
            Place::Field { base, field } => {
                Ok(self.model.field(&self.binding(base)?.ty, field)?.ty.clone())
            }
            Place::Access(path) => self.access_type(path),
            Place::Deref(expr) => match self.model.resolved_type(&self.expr_type(expr)?)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
        }
    }

    fn named_index_address(&mut self, name: &str, index: &Expr) -> Result<Type, Diagnostic> {
        let binding = self.binding(name)?;
        let resolved = self.model.resolved_type(&binding.ty)?;
        let element = element_type(&resolved)?;
        let size = self.model.type_size(&element)?;
        match resolved {
            Type::Array { .. } => {
                self.line(&format!("    mov bx,{}", imm(binding.storage.address)))
            }
            Type::Ptr(_) => self.load_bx(binding.storage.address),
            _ => return Err(Diagnostic::new("indexing requires array or pointer")),
        }
        self.add_index(index, size)?;
        Ok(element)
    }

    fn access_address(&mut self, path: &AccessPath) -> Result<Type, Diagnostic> {
        let binding = self.binding(&path.root)?;
        let mut ty = self.model.resolved_type(&binding.ty)?;
        if let Type::Ptr(inner) = ty {
            self.load_bx(binding.storage.address);
            ty = *inner;
        } else {
            self.line(&format!("    mov bx,{}", imm(binding.storage.address)));
        }
        for segment in &path.segments {
            match segment {
                AccessSegment::Field(name) => {
                    let field = self.model.field(&ty, name)?.clone();
                    if field.offset != 0 {
                        self.line(&format!("    add bx,{}", imm(field.offset)));
                    }
                    ty = field.ty;
                }
                AccessSegment::Index(index) => {
                    let element = element_type(&self.model.resolved_type(&ty)?)?;
                    let size = self.model.type_size(&element)?;
                    self.add_index(index, size)?;
                    ty = element;
                }
            }
        }
        Ok(ty)
    }

    fn add_index(&mut self, index: &Expr, scale: u32) -> Result<(), Diagnostic> {
        if let Ok(index) = self.model.const_value(index) {
            let offset = u32::try_from(index)
                .ok()
                .and_then(|value| value.checked_mul(scale))
                .ok_or_else(|| Diagnostic::new("array index offset overflow"))?;
            if offset != 0 {
                self.line(&format!("    add bx,{}", imm(offset)));
            }
            return Ok(());
        }
        self.line("    push bx");
        self.emit_expr(index, &Type::Named("u16".to_owned()))?;
        self.line("    pop bx");
        self.load_ax(self.r0.address);
        if scale != 1 {
            self.line(&format!("    mov cx,{}", imm(scale)));
            self.line("    mul cx");
        }
        self.line("    add bx,ax");
        Ok(())
    }

    fn load_indirect(&mut self, width: u8) {
        for offset in 0..u32::from(width) {
            self.line(&format!("    mov al,{}", indexed_bx(offset)));
            self.store_al(self.r0.address + offset);
        }
    }

    fn copy_indirect_to_storage(&mut self, target: Storage, size: u32) {
        for offset in 0..size {
            self.line(&format!("    mov al,{}", indexed_bx(offset)));
            self.store_al(target.address + offset);
        }
    }

    fn copy_storage_to_indirect(&mut self, source: Storage, size: u32) {
        for offset in 0..size {
            self.load_al(source.address + offset);
            self.line(&format!("    mov {},al", indexed_bx(offset)));
        }
    }

    fn expr_type(&self, expr: &Expr) -> Result<Type, Diagnostic> {
        match expr {
            Expr::Int(value) => Ok(if (0..=0xff).contains(value) {
                Type::Named("u8".to_owned())
            } else if (0..=0xffff).contains(value) {
                Type::Named("u16".to_owned())
            } else {
                Type::Named("u24".to_owned())
            }),
            Expr::TypedInt(_, ty) | Expr::Cast { ty, .. } => Ok(ty.clone()),
            Expr::Bool(_) => Ok(bool_ty()),
            Expr::Char(_) | Expr::In(_) => Ok(Type::Named("u8".to_owned())),
            Expr::String(_) => Ok(byte_ptr()),
            Expr::Ident(name) => self
                .model
                .constant_types
                .get(name)
                .cloned()
                .or_else(|| self.binding(name).ok().map(|binding| binding.ty))
                .ok_or_else(|| Diagnostic::new(format!("unknown value `{name}`"))),
            Expr::Index { name, .. } => {
                element_type(&self.model.resolved_type(&self.binding(name)?.ty)?)
            }
            Expr::Field { base, field } => {
                let constant = format!("{base}.{field}");
                self.model
                    .constant_types
                    .get(&constant)
                    .cloned()
                    .map(Ok)
                    .unwrap_or_else(|| {
                        Ok(self.model.field(&self.binding(base)?.ty, field)?.ty.clone())
                    })
            }
            Expr::AddressOfIndex { name, .. } => Ok(Type::Ptr(Box::new(element_type(
                &self.model.resolved_type(&self.binding(name)?.ty)?,
            )?))),
            Expr::AddressOfField { base, field } => Ok(Type::Ptr(Box::new(
                self.model.field(&self.binding(base)?.ty, field)?.ty.clone(),
            ))),
            Expr::Access(path) => self.access_type(path),
            Expr::AddressOfAccess(path) => Ok(Type::Ptr(Box::new(self.access_type(path)?))),
            Expr::AddressOf(name) => Ok(Type::Ptr(Box::new(self.binding(name)?.ty))),
            Expr::StructInit { ty, .. } => Ok(Type::Named(ty.clone())),
            Expr::Deref(expr) => match self.model.resolved_type(&self.expr_type(expr)?)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
            Expr::Call { path, .. } => resolve_function(path, &self.model)
                .and_then(|name| self.model.functions.get(&name))
                .and_then(|signature| signature.return_type.clone())
                .ok_or_else(|| Diagnostic::new("void function has no value")),
            Expr::Unary {
                op: UnaryOp::Not, ..
            } => Ok(bool_ty()),
            Expr::Unary { expr, .. } => self.expr_type(expr),
            Expr::Binary { op, .. }
                if is_comparison(*op) || matches!(op, BinaryOp::And | BinaryOp::Or) =>
            {
                Ok(bool_ty())
            }
            Expr::Binary { left, .. } => self.expr_type(left),
            Expr::Array(_) => Err(Diagnostic::new("array type requires context")),
        }
    }

    fn access_type(&self, path: &AccessPath) -> Result<Type, Diagnostic> {
        let mut ty = self.model.resolved_type(&self.binding(&path.root)?.ty)?;
        if let Type::Ptr(inner) = ty {
            ty = *inner;
        }
        for segment in &path.segments {
            ty = match segment {
                AccessSegment::Field(name) => self.model.field(&ty, name)?.ty.clone(),
                AccessSegment::Index(_) => element_type(&self.model.resolved_type(&ty)?)?,
            };
        }
        Ok(ty)
    }

    fn inline_asm(
        &mut self,
        inputs: &[crate::ast::AsmInput],
        outputs: &[crate::ast::AsmOutput],
        lines: &[String],
    ) -> Result<(), Diagnostic> {
        let mut operands = HashMap::new();
        for name in inputs
            .iter()
            .map(|value| &value.name)
            .chain(outputs.iter().map(|value| &value.name))
        {
            operands.insert(name.clone(), mem(self.binding(name)?.storage.address));
        }
        for source in lines {
            let mut line = source.clone();
            for (name, value) in &operands {
                line = line.replace(&format!("{{{name}}}"), value);
            }
            if line.contains(['{', '}']) {
                return Err(Diagnostic::new(format!(
                    "unknown inline asm operand placeholder in `{source}`"
                )));
            }
            self.line(&format!("    {line}"));
        }
        Ok(())
    }

    fn scalar_width(&self, ty: &Type) -> Result<u8, Diagnostic> {
        let width = self.model.type_width(ty)?;
        if u32::from(width) > SCRATCH_BYTES {
            Err(Diagnostic::new(
                "scalar is too wide for i8086 emitter scratch ABI",
            ))
        } else {
            Ok(width)
        }
    }

    fn bind(&mut self, name: String, storage: Storage, ty: Type) -> Result<(), Diagnostic> {
        if self
            .scopes
            .iter()
            .rev()
            .any(|scope| scope.contains_key(&name))
        {
            return Err(Diagnostic::new(format!(
                "local `{name}` shadows an existing name"
            )));
        }
        self.scopes
            .last_mut()
            .expect("function scope")
            .insert(name, Binding { storage, ty });
        Ok(())
    }

    fn binding(&self, name: &str) -> Result<Binding, Diagnostic> {
        if let Some(binding) = self.scopes.iter().rev().find_map(|scope| scope.get(name)) {
            return Ok(binding.clone());
        }
        if let Some(storage) = self.model.globals.get(name) {
            return Ok(Binding {
                storage: *storage,
                ty: self.model.global_types[name].clone(),
            });
        }
        Err(Diagnostic::new(format!("unknown variable `{name}`")))
    }

    fn port(&self, name: &str) -> Result<u8, Diagnostic> {
        self.ports
            .get(name)
            .copied()
            .ok_or_else(|| Diagnostic::new(format!("unknown port `{name}`")))
    }

    fn copy(&mut self, source: Storage, target: Storage, size: u32) {
        for offset in 0..size {
            self.load_al(source.address + offset);
            self.store_al(target.address + offset);
        }
    }

    fn zero(&mut self, storage: Storage) {
        self.line("    xor al,al");
        for offset in 0..storage.size {
            self.store_al(storage.address + offset);
        }
    }

    fn load_constant(&mut self, value: i64, width: u8) {
        for offset in 0..u32::from(width) {
            self.line(&format!(
                "    mov al,{}",
                imm(((value as u64 >> (offset * 8)) & 0xff) as u32)
            ));
            self.store_al(self.r0.address + offset);
        }
    }

    fn extend_result(&mut self, source: u8, target: u8, signed: bool) {
        if target <= source {
            return;
        }
        if signed {
            self.load_al(self.r0.address + u32::from(source - 1));
            self.line("    sar al,1");
            self.line("    sar al,1");
            self.line("    sar al,1");
            self.line("    sar al,1");
            self.line("    sar al,1");
            self.line("    sar al,1");
            self.line("    sar al,1");
        } else {
            self.line("    xor al,al");
        }
        for offset in u32::from(source)..u32::from(target) {
            self.store_al(self.r0.address + offset);
        }
    }

    fn scale(&mut self, storage: Storage, width: u8, amount: u32) {
        if amount <= 1 {
            return;
        }
        let source = self.model.allocate(u32::from(width)).expect("scale source");
        let result = self.model.allocate(u32::from(width)).expect("scale result");
        self.copy(storage, source, u32::from(width));
        self.zero(result);
        for _ in 0..amount {
            self.copy(result, self.r0, u32::from(width));
            self.copy(source, self.r1, u32::from(width));
            self.add(width);
            self.copy(self.r0, result, u32::from(width));
        }
        self.copy(result, storage, u32::from(width));
    }

    fn negate(&mut self, storage: Storage, width: u8) {
        for offset in 0..u32::from(width) {
            self.load_al(storage.address + offset);
            self.line("    not al");
            self.store_al(storage.address + offset);
        }
        self.line("    stc");
        for offset in 0..u32::from(width) {
            self.load_al(storage.address + offset);
            self.line("    adc al,0");
            self.store_al(storage.address + offset);
        }
    }

    fn normalize_signed(&mut self, storage: Storage, width: u8, flag: Storage, toggle: bool) {
        let positive = self.next_label("signed_positive");
        self.load_al(storage.address + u32::from(width - 1));
        self.line("    test al,80h");
        self.branch_long("jz", &positive);
        if toggle {
            self.toggle(flag);
        } else {
            self.store_immediate(flag.address, 1);
        }
        self.negate(storage, width);
        self.line(&format!("{positive}:"));
    }

    fn negate_if(&mut self, flag: Storage, storage: Storage, width: u8) {
        let done = self.next_label("sign_done");
        self.jump_storage_zero(flag, 1, &done);
        self.negate(storage, width);
        self.line(&format!("{done}:"));
    }

    fn toggle(&mut self, storage: Storage) {
        self.load_al(storage.address);
        self.line("    xor al,1");
        self.store_al(storage.address);
    }

    fn increment(&mut self, storage: Storage, width: u8) {
        let done = self.next_label("increment_done");
        for offset in 0..u32::from(width) {
            self.load_al(storage.address + offset);
            self.line("    add al,1");
            self.store_al(storage.address + offset);
            self.branch_long("jne", &done);
        }
        self.line(&format!("{done}:"));
    }

    fn decrement(&mut self, storage: Storage, width: u8) {
        self.line("    clc");
        for offset in 0..u32::from(width) {
            self.load_al(storage.address + offset);
            self.line(&format!(
                "    sbb al,{}",
                if offset == 0 { "1" } else { "0" }
            ));
            self.store_al(storage.address + offset);
        }
    }

    fn jump_storage_zero(&mut self, storage: Storage, width: u8, target: &str) {
        let nonzero = self.next_label("nonzero");
        for offset in 0..u32::from(width) {
            self.load_al(storage.address + offset);
            self.line("    or al,al");
            self.branch_long("jne", &nonzero);
        }
        self.line(&format!("    jmp near {target}"));
        self.line(&format!("{nonzero}:"));
    }

    fn jump_storage_nonzero(&mut self, storage: Storage, width: u8, target: &str) {
        for offset in 0..u32::from(width) {
            self.load_al(storage.address + offset);
            self.line("    or al,al");
            self.branch_long("jne", target);
        }
    }

    fn jump_equal(&mut self, left: Storage, right: Storage, width: u8, target: &str) {
        let different = self.next_label("different");
        for offset in 0..u32::from(width) {
            self.load_al(left.address + offset);
            self.line(&format!("    cmp al,{}", mem(right.address + offset)));
            self.branch_long("jne", &different);
        }
        self.line(&format!("    jmp near {target}"));
        self.line(&format!("{different}:"));
    }

    fn jump_less(&mut self, left: Storage, right: Storage, width: u8, target: &str) {
        let done = self.next_label("ordered");
        for offset in (0..u32::from(width)).rev() {
            self.load_al(left.address + offset);
            self.line(&format!("    cmp al,{}", mem(right.address + offset)));
            self.branch_long("jb", target);
            self.branch_long("jne", &done);
        }
        self.line(&format!("{done}:"));
    }

    fn branch_long(&mut self, condition: &str, target: &str) {
        let skip = self.next_label("branch_skip");
        let inverse = match condition {
            "jz" => "jnz",
            "jnz" => "jz",
            "je" => "jne",
            "jne" => "je",
            "jb" => "jae",
            "jae" => "jb",
            "js" => "jns",
            "jns" => "js",
            _ => unreachable!("unsupported 8086 condition"),
        };
        self.line(&format!("    {inverse} short {skip}"));
        self.line(&format!("    jmp near {target}"));
        self.line(&format!("{skip}:"));
    }

    fn push_bytes(&mut self, storage: Storage) {
        for offset in 0..storage.size {
            self.load_al(storage.address + offset);
            self.line("    xor ah,ah");
            self.line("    push ax");
        }
    }

    fn pop_bytes(&mut self, storage: Storage) {
        for offset in (0..storage.size).rev() {
            self.line("    pop ax");
            self.store_al(storage.address + offset);
        }
    }

    fn result_to_bx(&mut self) {
        self.load_bx(self.r0.address);
    }
    fn bx_to_result(&mut self, width: u8) {
        self.line(&format!("    mov {},bx", mem(self.r0.address)));
        if width > 2 {
            self.line("    xor al,al");
            for offset in 2..u32::from(width) {
                self.store_al(self.r0.address + offset);
            }
        }
    }
    fn load_al(&mut self, address: u32) {
        self.line(&format!("    mov al,{}", mem(address)));
    }
    fn store_al(&mut self, address: u32) {
        self.line(&format!("    mov {},al", mem(address)));
    }
    fn store_immediate(&mut self, address: u32, value: u8) {
        self.line(&format!("    mov al,{}", imm(u32::from(value))));
        self.store_al(address);
    }
    fn load_ax(&mut self, address: u32) {
        self.line(&format!("    mov ax,{}", mem(address)));
    }
    fn load_bx(&mut self, address: u32) {
        self.line(&format!("    mov bx,{}", mem(address)));
    }
    fn load_cx(&mut self, address: u32) {
        self.line(&format!("    mov cx,{}", mem(address)));
    }
    fn load_si(&mut self, address: u32) {
        self.line(&format!("    mov si,{}", mem(address)));
    }
    fn load_di(&mut self, address: u32) {
        self.line(&format!("    mov di,{}", mem(address)));
    }
    fn load_cl(&mut self, address: u32) {
        self.line(&format!("    mov cl,{}", mem(address)));
    }

    fn next_label(&mut self, name: &str) -> String {
        let label = format!(".L_{}_{}", sanitize(name), self.labels);
        self.labels += 1;
        label
    }
    fn line(&mut self, line: &str) {
        self.out.push_str(line);
        self.out.push('\n');
    }
}

fn bool_ty() -> Type {
    Type::Named("bool".to_owned())
}
fn byte_ptr() -> Type {
    Type::Ptr(Box::new(Type::Named("u8".to_owned())))
}
fn mem(address: u32) -> String {
    format!("[{}]", imm(address))
}
fn indexed_bx(offset: u32) -> String {
    if offset == 0 {
        "[bx]".to_owned()
    } else {
        format!("[bx+{}]", imm(offset))
    }
}
fn imm(value: u32) -> String {
    format!("0{value:X}h")
}

fn element_type(ty: &Type) -> Result<Type, Diagnostic> {
    match ty {
        Type::Array { element, .. } | Type::Ptr(element) => Ok((**element).clone()),
        _ => Err(Diagnostic::new("indexing requires array or pointer")),
    }
}
fn type_is_signed(ty: &Type) -> bool {
    matches!(ty, Type::Named(name) if name.starts_with('i'))
}
fn is_comparison(op: BinaryOp) -> bool {
    matches!(
        op,
        BinaryOp::Eq | BinaryOp::Ne | BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge
    )
}
fn assign_binary(op: AssignOp) -> BinaryOp {
    match op {
        AssignOp::Add => BinaryOp::Add,
        AssignOp::Sub => BinaryOp::Sub,
        AssignOp::Mul => BinaryOp::Mul,
        AssignOp::Div => BinaryOp::Div,
        AssignOp::Mod => BinaryOp::Mod,
        AssignOp::BitAnd => BinaryOp::BitAnd,
        AssignOp::BitOr => BinaryOp::BitOr,
        AssignOp::BitXor => BinaryOp::BitXor,
        AssignOp::Shl => BinaryOp::Shl,
        AssignOp::Shr => BinaryOp::Shr,
        AssignOp::Set => unreachable!(),
    }
}
fn resolve_function(path: &[String], model: &SemanticModel) -> Option<String> {
    let qualified = path.join(".");
    if model.functions.contains_key(&qualified) {
        Some(qualified)
    } else {
        path.last()
            .filter(|name| model.functions.contains_key(*name))
            .cloned()
    }
}
fn function_label(name: &str) -> String {
    format!("_{}", sanitize(name))
}
fn sanitize(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use crate::{
        asm::AssemblyOptions,
        parser::parse_program,
        target::{Address24, AssemblerCpu, CpuFamily},
        vm::assemble_subset_with_symbols_at,
    };

    use super::*;

    fn emit(source: &str) -> String {
        let program = parse_program(Path::new("i8086-emitter-test.ezra"), source).unwrap();
        emit_i8086_assembly_with_options(
            &program,
            AssemblyOptions {
                cpu: CpuFamily::I8086,
                ram_base: Address24::new(0x4000),
                rodata_base: Address24::new(0x6000),
                asset_base: Address24::new(0x7000),
                stack_top: Address24::new(0xfffe),
                default_sdk_symbols: false,
                ..AssemblyOptions::default()
            },
        )
        .unwrap()
    }

    fn emit_and_assemble(source: &str) -> String {
        let assembly = emit(source);
        assemble_subset_with_symbols_at(AssemblerCpu::I8086, &assembly, 0)
            .unwrap_or_else(|error| panic!("{error}\n--- assembly ---\n{assembly}"));
        assembly
    }

    #[test]
    fn assembles_scalars_calls_control_flow_and_all_operators() {
        let assembly = emit_and_assemble(
            r#"
            fn twice(value: u16) -> u16 { return value * 2 }
            fn main() {
                let a: u16 = 17
                let b: u16 = twice(a)
                let c: i16 = -3
                let bits: u16 = ((b + 1) - 2) & 0xff | 0x100 ^ 3
                let shifts: u16 = (bits << 2) >> 1
                let math: u16 = shifts / 3 + shifts % 3
                let inv: u16 = ~math
                let neg: i16 = -c
                let truth: bool = !(a == b) && (a != b || a < b) && a <= b && b > a && b >= a
                if truth { a += 1 } else { a -= 1 }
                while a != 0 { a -= 1 if a == 2 { break } else { continue } }
                loop { break }
            }
        "#,
        );
        assert!(assembly.contains("call near _twice"));
        assert!(!assembly.contains("jcxz"));
        assert!(assembly.contains("rcl al,1"));
    }

    #[test]
    fn assembles_aggregates_pointers_access_and_memory_helpers() {
        let assembly = emit_and_assemble(
            r#"
            struct Pair { lo: u8 hi: u16 }
            global DATA: [u8; 4] = [1, 2, 3, 4]
            global PAIR: Pair = Pair { lo: 7, hi: 0x1234 }
            fn main() {
                let local: [u8; 4] = DATA
                let pair: Pair = PAIR
                let p: ptr<u8> = &local[0]
                let q: ptr<u16> = &pair.hi
                local[1] = *p
                pair.hi = *q
                pair.hi += 1
                let x: u8 = local[2]
                let y: u16 = pair.hi
                mem.poke8(p, mem.peek8(p))
                mem.memcpy(&DATA[0], p, 4)
                mem.memset(p, x, 4)
            }
        "#,
        );
        assert!(assembly.contains("mov al,[bx]"));
        assert!(assembly.contains("jcxz short"));
    }

    #[test]
    fn assembles_ports_inline_asm_interrupt_and_naked_functions() {
        let assembly = emit_and_assemble(
            r#"
            port UART: u8 = 0x20
            interrupt fn irq() { asm volatile(clobber memory) { "nop" } }
            naked fn raw() { asm volatile(clobber memory) { "ret" } }
            fn main() {
                let value: u8 = in UART
                out UART, value
                asm volatile(in value: u8 as reg8, out value: u8 as reg8) { "mov al,{value}" "mov {value},al" }
            }
        "#,
        );
        assert!(assembly.contains("in al,020h"));
        assert!(assembly.contains("out 020h,al"));
        assert!(assembly.contains("iret"));
    }

    #[test]
    fn recursive_calls_save_static_frames() {
        let assembly = emit_and_assemble(
            r#"
            fn gcd(a: u16, b: u16) -> u16 {
                if b == 0 { return a }
                return gcd(b, a % b)
            }
            fn main() { let value: u16 = gcd(48, 18) }
        "#,
        );
        assert!(assembly.contains("push ax"));
        assert!(assembly.contains("pop ax"));
        assert!(assembly.contains("call near _gcd"));
    }
}
