use std::collections::{HashMap, HashSet};

use crate::{
    asm::AssemblyOptions,
    ast::{AssignOp, BinaryOp, Declaration, Expr, Function, Place, Program, Stmt, Type, UnaryOp},
    diagnostic::Diagnostic,
    hir::HirProgram,
    target::CpuFamily,
    tbir::{
        TbirProgram,
        model::{SemanticModel, Storage},
    },
};

/// Emits the deliberately small, RAM-backed M6800 source ABI.
///
/// Values are one byte wide. Function arguments live in the semantic model's
/// argument slots and scalar returns use accumulator A. The backend rejects
/// constructs for which this ABI has no faithful lowering.
pub fn emit_m6800_assembly_with_options(
    program: &Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    if options.cpu != CpuFamily::M6800 {
        return Err(Diagnostic::new("M6800 emitter requires an M6800 target"));
    }
    if program.main_function().is_none() {
        return Err(Diagnostic::new("M6800 programs require a `main` function"));
    }
    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    let model = SemanticModel::from_program(
        &tbir.lowered_program,
        16,
        options.ram_base.get(),
        options.rodata_base.get(),
        options.asset_base.get(),
    )?;
    Emitter::new(model)?.emit(&tbir.lowered_program)
}

#[derive(Clone)]
struct Binding {
    storage: Storage,
    ty: Type,
}

#[derive(Clone)]
struct LoopLabels {
    continue_label: String,
    break_label: String,
}

struct Emitter {
    model: SemanticModel,
    out: String,
    labels: usize,
    scopes: Vec<HashMap<String, Binding>>,
    loops: Vec<LoopLabels>,
    return_labels: Vec<String>,
    return_types: Vec<Option<Type>>,
    r1: Storage,
}

impl Emitter {
    fn new(mut model: SemanticModel) -> Result<Self, Diagnostic> {
        let r1 = model.allocate(1)?;
        Ok(Self {
            model,
            out: String::new(),
            labels: 0,
            scopes: Vec::new(),
            loops: Vec::new(),
            return_labels: Vec::new(),
            return_types: Vec::new(),
            r1,
        })
    }

    fn emit(mut self, program: &Program) -> Result<String, Diagnostic> {
        self.reject_unsupported_declarations(program)?;
        self.reject_recursive_calls(program)?;
        self.line("; generated by ezrac");
        self.line("; target: Motorola M6800 scalar RAM ABI");
        self.line(&format!("__ezra_r1 equ {:04X}h", self.r1.address));
        self.line("__ezra_start:");
        self.emit_global_initializers(program)?;
        self.line("    jsr _main");
        self.line("__ezra_exit:");
        self.line("    bra __ezra_exit");
        for declaration in &program.declarations {
            if let Declaration::Function(function) = declaration {
                self.emit_function(function)?;
            }
        }
        Ok(self.out)
    }

    fn reject_unsupported_declarations(&self, program: &Program) -> Result<(), Diagnostic> {
        for declaration in &program.declarations {
            match declaration {
                Declaration::Port(_) | Declaration::Mmio(_) | Declaration::Embed(_) => {
                    return Err(Diagnostic::new(
                        "M6800 source emitter does not yet support ports, MMIO, or embeds",
                    ));
                }
                Declaration::ExternAsmFunction(_) => {
                    return Err(Diagnostic::new(
                        "M6800 source emitter does not yet support extern assembly functions",
                    ));
                }
                _ => {}
            }
        }
        Ok(())
    }

    fn emit_global_initializers(&mut self, program: &Program) -> Result<(), Diagnostic> {
        for declaration in &program.declarations {
            if let Declaration::Global(global) = declaration {
                self.require_scalar(&global.ty, "global")?;
                self.emit_expr(&global.value, &global.ty)?;
                self.staa(self.model.globals[&global.name].address);
            }
        }
        Ok(())
    }

    fn emit_function(&mut self, function: &Function) -> Result<(), Diagnostic> {
        if function
            .attrs
            .iter()
            .any(|attr| attr == "naked" || attr == "interrupt")
        {
            return Err(Diagnostic::new(format!(
                "M6800 source emitter does not support `{}` functions",
                function.name
            )));
        }
        for param in &function.params {
            self.require_scalar(&param.ty, "function parameter")?;
        }
        if let Some(ty) = &function.return_type {
            self.require_scalar(ty, "function return")?;
        }
        let return_label = self.next_label(&format!("{}_return", function.name));
        self.line(&format!("_{}:", function.name));
        self.scopes.push(HashMap::new());
        self.return_labels.push(return_label.clone());
        self.return_types.push(function.return_type.clone());
        let signature = self.model.functions[&function.name].clone();
        for (param, slot) in function.params.iter().zip(signature.argument_slots) {
            self.bind(param.name.clone(), slot, param.ty.clone())?;
        }
        self.emit_block(&function.body)?;
        self.line(&format!("{return_label}:"));
        self.line("    rts");
        self.return_types.pop();
        self.return_labels.pop();
        self.scopes.pop();
        Ok(())
    }

    fn emit_block(&mut self, body: &[Stmt]) -> Result<(), Diagnostic> {
        for stmt in body {
            self.emit_stmt(stmt)?;
        }
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<(), Diagnostic> {
        match stmt {
            Stmt::Let { name, ty, value } => {
                self.require_scalar(ty, "local")?;
                let storage = self.model.allocate(1)?;
                self.bind(name.clone(), storage, ty.clone())?;
                self.emit_expr(value, ty)?;
                self.staa(storage.address);
            }
            Stmt::Assign { target, op, value } => {
                let Place::Ident(name) = target else {
                    return Err(Diagnostic::new(
                        "M6800 source emitter supports assignment to scalar identifiers only",
                    ));
                };
                let binding = self.binding(name)?;
                self.require_scalar(&binding.ty, "assignment target")?;
                if *op == AssignOp::Set {
                    self.emit_expr(value, &binding.ty)?;
                } else {
                    self.ldaa(binding.storage.address);
                    self.line("    psha");
                    self.emit_expr(value, &binding.ty)?;
                    self.line("    tab");
                    self.line("    pula");
                    self.emit_assign_op(*op)?;
                }
                self.staa(binding.storage.address);
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                let otherwise = self.next_label("if_else");
                let done = self.next_label("if_end");
                self.emit_expr(condition, &bool_type())?;
                self.line("    tsta");
                self.branch_long("beq", &otherwise);
                self.emit_block(then_body)?;
                self.line(&format!("    jmp {done}"));
                self.line(&format!("{otherwise}:"));
                self.emit_block(else_body)?;
                self.line(&format!("{done}:"));
            }
            Stmt::While { condition, body } => {
                let check = self.next_label("while_check");
                let done = self.next_label("while_end");
                self.loops.push(LoopLabels {
                    continue_label: check.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{check}:"));
                self.emit_expr(condition, &bool_type())?;
                self.line("    tsta");
                self.branch_long("beq", &done);
                self.emit_block(body)?;
                self.line(&format!("    jmp {check}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Loop { body } => {
                let again = self.next_label("loop_body");
                let done = self.next_label("loop_end");
                self.loops.push(LoopLabels {
                    continue_label: again.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{again}:"));
                self.emit_block(body)?;
                self.line(&format!("    jmp {again}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Break => {
                let label = self
                    .loops
                    .last()
                    .ok_or_else(|| Diagnostic::new("break outside loop"))?
                    .break_label
                    .clone();
                self.line(&format!("    jmp {label}"));
            }
            Stmt::Continue => {
                let label = self
                    .loops
                    .last()
                    .ok_or_else(|| Diagnostic::new("continue outside loop"))?
                    .continue_label
                    .clone();
                self.line(&format!("    jmp {label}"));
            }
            Stmt::Return(value) => {
                let expected = self.return_types.last().cloned().flatten();
                match (value, expected) {
                    (Some(value), Some(ty)) => self.emit_expr(value, &ty)?,
                    (Some(_), None) => {
                        return Err(Diagnostic::new("value return in void function"));
                    }
                    (None, Some(_)) => {
                        return Err(Diagnostic::new("M6800 scalar function must return a value"));
                    }
                    (None, None) => {}
                }
                let label = self
                    .return_labels
                    .last()
                    .expect("function return label")
                    .clone();
                self.line(&format!("    jmp {label}"));
            }
            Stmt::Expr(expr) => {
                // A void call is meaningful as a statement even though it has no expression type.
                if matches!(expr, Expr::Call { .. }) {
                    self.emit_expr(expr, &u8_type())?;
                } else {
                    self.emit_expr(expr, &self.expr_type(expr)?)?;
                }
            }
            Stmt::Asm { .. } => {
                return Err(Diagnostic::new(
                    "M6800 source emitter does not support inline assembly",
                ));
            }
            Stmt::Out { .. } => {
                return Err(Diagnostic::new(
                    "M6800 source emitter does not support port I/O",
                ));
            }
        }
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr, expected: &Type) -> Result<(), Diagnostic> {
        self.require_scalar(expected, "expression")?;
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => self.ldaa_imm(*value as u8),
            Expr::Bool(value) => self.ldaa_imm(u8::from(*value)),
            Expr::Char(value) => self.ldaa_imm(*value),
            Expr::Ident(name) => {
                if let Some(value) = self.model.constants.get(name) {
                    self.ldaa_imm(*value as u8);
                } else {
                    self.ldaa(self.binding(name)?.storage.address);
                }
            }
            Expr::Unary { op, expr } => {
                self.emit_expr(expr, expected)?;
                match op {
                    UnaryOp::Neg => self.line("    nega"),
                    UnaryOp::BitNot => self.line("    coma"),
                    UnaryOp::Not => self.bool_not(),
                }
            }
            Expr::Binary { left, op, right } => {
                if matches!(op, BinaryOp::And | BinaryOp::Or) {
                    return self.emit_logical(left, *op, right);
                }
                let operand_ty = if is_comparison(*op) {
                    self.expr_type(left)?
                } else {
                    expected.clone()
                };
                self.require_scalar(&operand_ty, "binary operand")?;
                self.emit_expr(left, &operand_ty)?;
                self.line("    psha");
                self.emit_expr(right, &operand_ty)?;
                self.staa(self.r1.address);
                self.line("    pula");
                self.emit_binary(*op)?;
            }
            Expr::Call { path, args } => self.emit_call(path, args, expected)?,
            Expr::Cast { ty, expr } => {
                self.require_scalar(ty, "cast")?;
                self.emit_expr(expr, ty)?;
            }
            Expr::String(_)
            | Expr::Array(_)
            | Expr::StructInit { .. }
            | Expr::Index { .. }
            | Expr::Field { .. }
            | Expr::AddressOfIndex { .. }
            | Expr::AddressOfField { .. }
            | Expr::Access(_)
            | Expr::AddressOfAccess(_)
            | Expr::AddressOf(_)
            | Expr::Deref(_)
            | Expr::In(_) => {
                return Err(Diagnostic::new(
                    "M6800 source emitter supports scalar u8/bool expressions only",
                ));
            }
        }
        Ok(())
    }

    fn emit_call(
        &mut self,
        path: &[String],
        args: &[Expr],
        expected: &Type,
    ) -> Result<(), Diagnostic> {
        let name = path.join(".");
        let signature = self
            .model
            .functions
            .get(&name)
            .or_else(|| path.last().and_then(|n| self.model.functions.get(n)))
            .cloned()
            .ok_or_else(|| Diagnostic::new(format!("unknown function `{name}`")))?;
        if signature.params.len() != args.len() {
            return Err(Diagnostic::new(format!(
                "function `{name}` expects {} arguments, got {}",
                signature.params.len(),
                args.len()
            )));
        }
        for ((arg, ty), slot) in args
            .iter()
            .zip(&signature.params)
            .zip(&signature.argument_slots)
        {
            self.require_scalar(ty, "function argument")?;
            self.emit_expr(arg, ty)?;
            self.staa(slot.address);
        }
        self.line(&format!(
            "    jsr _{}",
            sanitize_label(path.last().unwrap_or(&name))
        ));
        if let Some(return_type) = signature.return_type {
            self.require_scalar(&return_type, "function return")?;
        } else if expected != &bool_type() && expected != &u8_type() {
            return Err(Diagnostic::new("void M6800 function used as a value"));
        }
        Ok(())
    }

    fn emit_assign_op(&mut self, op: AssignOp) -> Result<(), Diagnostic> {
        self.emit_binary(match op {
            AssignOp::Add => BinaryOp::Add, AssignOp::Sub => BinaryOp::Sub,
            AssignOp::BitAnd => BinaryOp::BitAnd, AssignOp::BitOr => BinaryOp::BitOr, AssignOp::BitXor => BinaryOp::BitXor,
            _ => return Err(Diagnostic::new("M6800 source emitter supports only +=, -=, &=, |=, and ^= compound assignments")),
        })
    }

    fn emit_binary(&mut self, op: BinaryOp) -> Result<(), Diagnostic> {
        match op {
            BinaryOp::Add => self.line("    adda >__ezra_r1"),
            BinaryOp::Sub => self.line("    suba >__ezra_r1"),
            BinaryOp::BitAnd => self.line("    anda >__ezra_r1"),
            BinaryOp::BitOr => self.line("    oraa >__ezra_r1"),
            BinaryOp::BitXor => self.line("    eora >__ezra_r1"),
            op if is_comparison(op) => self.compare(op),
            _ => {
                return Err(Diagnostic::new(
                    "M6800 source emitter does not support this binary operation",
                ));
            }
        }
        Ok(())
    }

    fn compare(&mut self, op: BinaryOp) {
        let yes = self.next_label("compare_true");
        let done = self.next_label("compare_done");
        self.line("    cmpa >__ezra_r1");
        let branch = match op {
            BinaryOp::Eq => "beq",
            BinaryOp::Ne => "bne",
            BinaryOp::Lt => "blt",
            BinaryOp::Le => "ble",
            BinaryOp::Gt => "bgt",
            BinaryOp::Ge => "bge",
            _ => unreachable!(),
        };
        self.branch_long(branch, &yes);
        self.ldaa_imm(0);
        self.line(&format!("    jmp {done}"));
        self.line(&format!("{yes}:"));
        self.ldaa_imm(1);
        self.line(&format!("{done}:"));
    }

    fn emit_logical(&mut self, left: &Expr, op: BinaryOp, right: &Expr) -> Result<(), Diagnostic> {
        let decisive = self.next_label("logical_decisive");
        let done = self.next_label("logical_done");
        self.emit_expr(left, &bool_type())?;
        self.line("    tsta");
        self.branch_long(if op == BinaryOp::And { "beq" } else { "bne" }, &decisive);
        self.emit_expr(right, &bool_type())?;
        self.line(&format!("    jmp {done}"));
        self.line(&format!("{decisive}:"));
        self.ldaa_imm(u8::from(op == BinaryOp::Or));
        self.line(&format!("{done}:"));
        Ok(())
    }

    fn bool_not(&mut self) {
        let yes = self.next_label("not_true");
        let done = self.next_label("not_done");
        self.line("    tsta");
        self.branch_long("beq", &yes);
        self.ldaa_imm(0);
        self.line(&format!("    jmp {done}"));
        self.line(&format!("{yes}:"));
        self.ldaa_imm(1);
        self.line(&format!("{done}:"));
    }

    fn expr_type(&self, expr: &Expr) -> Result<Type, Diagnostic> {
        match expr {
            Expr::Bool(_)
            | Expr::Unary {
                op: UnaryOp::Not, ..
            } => Ok(bool_type()),
            Expr::Int(_) | Expr::TypedInt(_, _) | Expr::Char(_) => Ok(u8_type()),
            Expr::Ident(name) => self
                .model
                .constant_types
                .get(name)
                .cloned()
                .or_else(|| self.binding(name).ok().map(|b| b.ty))
                .ok_or_else(|| Diagnostic::new(format!("unknown value `{name}`"))),
            Expr::Binary { left, op, .. }
                if is_comparison(*op) || matches!(op, BinaryOp::And | BinaryOp::Or) =>
            {
                Ok(bool_type())
            }
            Expr::Binary { left, .. }
            | Expr::Unary { expr: left, .. }
            | Expr::Cast { expr: left, .. } => self.expr_type(left),
            Expr::Call { path, .. } => self
                .model
                .functions
                .get(&path.join("."))
                .and_then(|s| s.return_type.clone())
                .ok_or_else(|| Diagnostic::new("void function has no value")),
            _ => Err(Diagnostic::new(
                "M6800 source emitter supports scalar u8/bool expressions only",
            )),
        }
    }

    fn require_scalar(&self, ty: &Type, context: &str) -> Result<(), Diagnostic> {
        match self.model.resolved_type(ty)? {
            Type::Named(name) if name == "u8" || name == "bool" => Ok(()),
            _ => Err(Diagnostic::new(format!(
                "M6800 source emitter supports u8 and bool {context}s only"
            ))),
        }
    }
    fn bind(&mut self, name: String, storage: Storage, ty: Type) -> Result<(), Diagnostic> {
        if self
            .scopes
            .iter()
            .rev()
            .any(|scope| scope.contains_key(&name))
        {
            return Err(Diagnostic::new(format!(
                "local `{name}` shadows an existing name"
            )));
        }
        self.scopes
            .last_mut()
            .expect("function scope")
            .insert(name, Binding { storage, ty });
        Ok(())
    }
    fn binding(&self, name: &str) -> Result<Binding, Diagnostic> {
        if let Some(binding) = self.scopes.iter().rev().find_map(|scope| scope.get(name)) {
            return Ok(binding.clone());
        }
        self.model
            .globals
            .get(name)
            .map(|storage| Binding {
                storage: *storage,
                ty: self.model.global_types[name].clone(),
            })
            .ok_or_else(|| Diagnostic::new(format!("unknown variable `{name}`")))
    }
    fn ldaa(&mut self, address: u32) {
        self.line(&format!("    ldaa >{:04X}h", address));
    }
    fn staa(&mut self, address: u32) {
        self.line(&format!("    staa >{:04X}h", address));
    }
    fn ldaa_imm(&mut self, value: u8) {
        self.line(&format!("    ldaa #{value:02X}h"));
    }
    fn branch_long(&mut self, branch: &str, target: &str) {
        let skip = self.next_label("branch_skip");
        let inverse = match branch {
            "beq" => "bne",
            "bne" => "beq",
            "blt" => "bge",
            "bge" => "blt",
            "ble" => "bgt",
            "bgt" => "ble",
            _ => unreachable!(),
        };
        self.line(&format!("    {inverse} {skip}"));
        self.line(&format!("    jmp {target}"));
        self.line(&format!("{skip}:"));
    }
    fn next_label(&mut self, prefix: &str) -> String {
        let label = format!("__ezra_{prefix}_{}", self.labels);
        self.labels += 1;
        label
    }
    fn line(&mut self, line: &str) {
        self.out.push_str(line);
        self.out.push('\n');
    }

    fn reject_recursive_calls(&self, program: &Program) -> Result<(), Diagnostic> {
        let functions: HashSet<_> = program
            .declarations
            .iter()
            .filter_map(|d| {
                if let Declaration::Function(f) = d {
                    Some(f.name.as_str())
                } else {
                    None
                }
            })
            .collect();
        for declaration in &program.declarations {
            if let Declaration::Function(function) = declaration {
                let mut calls = Vec::new();
                collect_calls(&function.body, &mut calls);
                if calls.iter().any(|call| call == &function.name) {
                    return Err(Diagnostic::new(format!(
                        "M6800 source emitter does not support recursive function `{}`",
                        function.name
                    )));
                }
                if calls.iter().any(|call| {
                    functions.contains(call.as_str())
                        && call != &function.name
                        && calls_function(program, call, &function.name, &mut HashSet::new())
                }) {
                    return Err(Diagnostic::new(
                        "M6800 source emitter does not support recursive call cycles",
                    ));
                }
            }
        }
        Ok(())
    }
}

fn collect_calls(body: &[Stmt], calls: &mut Vec<String>) {
    for stmt in body {
        match stmt {
            Stmt::Expr(expr) => collect_expr_calls(expr, calls),
            Stmt::Let { value, .. } | Stmt::Return(Some(value)) => collect_expr_calls(value, calls),
            Stmt::Assign { value, .. } | Stmt::Out { value, .. } => {
                collect_expr_calls(value, calls)
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                collect_expr_calls(condition, calls);
                collect_calls(then_body, calls);
                collect_calls(else_body, calls);
            }
            Stmt::While { condition, body } => {
                collect_expr_calls(condition, calls);
                collect_calls(body, calls);
            }
            Stmt::Loop { body } => collect_calls(body, calls),
            _ => {}
        }
    }
}
fn collect_expr_calls(expr: &Expr, calls: &mut Vec<String>) {
    match expr {
        Expr::Call { path, args } => {
            calls.push(path.join("."));
            for arg in args {
                collect_expr_calls(arg, calls);
            }
        }
        Expr::Unary { expr, .. } | Expr::Cast { expr, .. } => collect_expr_calls(expr, calls),
        Expr::Binary { left, right, .. } => {
            collect_expr_calls(left, calls);
            collect_expr_calls(right, calls);
        }
        _ => {}
    }
}
fn calls_function(program: &Program, from: &str, wanted: &str, seen: &mut HashSet<String>) -> bool {
    if !seen.insert(from.to_owned()) {
        return false;
    }
    let Some(function) = program.declarations.iter().find_map(|d| match d {
        Declaration::Function(f) if f.name == from => Some(f),
        _ => None,
    }) else {
        return false;
    };
    let mut calls = Vec::new();
    collect_calls(&function.body, &mut calls);
    calls
        .iter()
        .any(|call| call == wanted || calls_function(program, call, wanted, seen))
}
fn is_comparison(op: BinaryOp) -> bool {
    matches!(
        op,
        BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge | BinaryOp::Eq | BinaryOp::Ne
    )
}
fn u8_type() -> Type {
    Type::Named("u8".to_owned())
}
fn bool_type() -> Type {
    Type::Named("bool".to_owned())
}
fn sanitize_label(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::emit_m6800_assembly_with_options;
    use crate::{
        asm::AssemblyOptions,
        parser::parse_program,
        target::{Address24, AssemblerCpu, CpuFamily},
        vm::assemble_subset_with_symbols_at,
    };

    fn m6800_options() -> AssemblyOptions {
        AssemblyOptions {
            cpu: CpuFamily::M6800,
            ram_base: Address24::new(0xA000),
            rodata_base: Address24::new(0x8000),
            asset_base: Address24::new(0xC000),
            ..AssemblyOptions::default()
        }
    }

    #[test]
    fn emits_assemblable_scalar_globals_locals_and_control_flow() {
        let program = parse_program(
            Path::new("m6800_test.ezra"),
            r#"
                global counter: u8 = 1
                global enabled: bool = true

                fn main() {
                    let value: u8 = counter + 2
                    if enabled && value == 3 { counter = value }
                    while counter < 5 { counter += 1 }
                }
            "#,
        )
        .unwrap();
        let assembly = emit_m6800_assembly_with_options(&program, m6800_options()).unwrap();

        assert!(assembly.contains("_main:"), "{assembly}");
        assert!(assembly.contains("adda >__ezra_r1"), "{assembly}");
        assemble_subset_with_symbols_at(AssemblerCpu::M6800, &assembly, 0)
            .unwrap_or_else(|error| panic!("{error}\n{assembly}"));
    }

    #[test]
    fn rejects_wide_scalar_storage() {
        let program = parse_program(
            Path::new("m6800_test.ezra"),
            "fn main() { let wide: u16 = 1 }",
        )
        .unwrap();
        let error = emit_m6800_assembly_with_options(&program, m6800_options()).unwrap_err();
        assert!(error.message.contains("u8 and bool"));
    }
}
