use std::collections::{HashMap, HashSet};

use crate::{
    asm::{
        AssemblyOptions,
        comments::with_readability_comments,
        reachability::{RoutineProfile, strip_unreachable_generated_routines},
    },
    ast::{AssignOp, BinaryOp, Declaration, Expr, Function, Place, Program, Stmt, Type, UnaryOp},
    diagnostic::Diagnostic,
    hir::HirProgram,
    regalloc::{
        Location, PhysReg, PhysicalRegister, RegClass, RegUnit, RegisterClass, RegisterUnit,
        SpillClass, SpillClassId, Target,
        source::{SourceLocal, allocate_source_locals},
    },
    target::CpuFamily,
    tbir::{
        TbirProgram,
        model::{SemanticModel, Storage},
    },
};

/// Emits the deliberately small, RAM-backed M6800 source ABI.
///
/// Values are one byte wide. Function arguments live in the semantic model's
/// argument slots and scalar returns use accumulator A. The backend rejects
/// constructs for which this ABI has no faithful lowering.
pub fn emit_m6800_assembly_with_options(
    program: &Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    if options.cpu != CpuFamily::M6800 {
        return Err(Diagnostic::new("M6800 emitter requires an M6800 target"));
    }
    if program.main_function().is_none() {
        return Err(Diagnostic::new("M6800 programs require a `main` function"));
    }
    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    let model = SemanticModel::from_program(
        &tbir.lowered_program,
        16,
        options.ram_base.get(),
        options.rodata_base.get(),
        options.asset_base.get(),
    )?;
    Emitter::new(model, CpuFamily::M6800)?
        .emit(&tbir.lowered_program)
        .map(|asm| {
            let asm = strip_unreachable_generated_routines(&asm, RoutineProfile::M6800);
            with_readability_comments(asm, program, &options, "m6800", &tbir.source_comments)
        })
}

#[cfg(feature = "m6809")]
/// Emits the shared scalar source ABI for Motorola M6809.
///
/// M6809 accepts the M6800 accumulator spelling used by this backend while
/// TBIR still sees the concrete M6809 target and applies its normal passes.
pub fn emit_m6809_assembly_with_options(
    program: &Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    if options.cpu != CpuFamily::M6809 {
        return Err(Diagnostic::new("M6809 emitter requires an M6809 target"));
    }
    if program.main_function().is_none() {
        return Err(Diagnostic::new("M6809 programs require a `main` function"));
    }
    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    let model = SemanticModel::from_program(
        &tbir.lowered_program,
        16,
        options.ram_base.get(),
        options.rodata_base.get(),
        options.asset_base.get(),
    )?;
    Emitter::new(model, CpuFamily::M6809)?
        .emit(&tbir.lowered_program)
        .map(|asm| {
            let asm = strip_unreachable_generated_routines(&asm, RoutineProfile::M6800);
            let asm = asm.replace(
                "; target: Motorola M6800 scalar RAM ABI",
                "; target: Motorola M6809 scalar RAM ABI",
            );
            with_readability_comments(asm, program, &options, "m6809", &tbir.source_comments)
        })
}

#[derive(Clone)]
struct Binding {
    storage: Storage,
    ty: Type,
}

#[derive(Clone)]
struct LoopLabels {
    continue_label: String,
    break_label: String,
}

struct Emitter {
    model: SemanticModel,
    cpu: CpuFamily,
    out: String,
    labels: usize,
    scopes: Vec<HashMap<String, Binding>>,
    loops: Vec<LoopLabels>,
    return_labels: Vec<String>,
    return_types: Vec<Option<Type>>,
    local_plans: Vec<HashMap<String, Binding>>,
    r1: Storage,
}

impl Emitter {
    fn new(mut model: SemanticModel, cpu: CpuFamily) -> Result<Self, Diagnostic> {
        let r1 = model.allocate(1)?;
        Ok(Self {
            model,
            cpu,
            out: String::new(),
            labels: 0,
            scopes: Vec::new(),
            loops: Vec::new(),
            return_labels: Vec::new(),
            return_types: Vec::new(),
            local_plans: Vec::new(),
            r1,
        })
    }

    fn emit(mut self, program: &Program) -> Result<String, Diagnostic> {
        self.reject_unsupported_declarations(program)?;
        self.reject_recursive_calls(program)?;
        self.line("; generated by ezrac");
        self.line("; target: Motorola M6800 scalar RAM ABI");
        self.line(&format!("__ezra_r1 equ {:04X}h", self.r1.address));
        self.line("__ezra_start:");
        self.emit_global_initializers(program)?;
        self.line("    jsr _main");
        self.line("__ezra_exit:");
        self.line("    bra __ezra_exit");
        for declaration in &program.declarations {
            if let Declaration::Function(function) = declaration {
                self.emit_function(function)?;
            }
        }
        Ok(self.out)
    }

    fn reject_unsupported_declarations(&self, program: &Program) -> Result<(), Diagnostic> {
        for declaration in &program.declarations {
            match declaration {
                Declaration::Port(_) | Declaration::Mmio(_) | Declaration::Embed(_) => {
                    return Err(Diagnostic::new(
                        "M6800 source emitter does not yet support ports, MMIO, or embeds",
                    ));
                }
                Declaration::ExternAsmFunction(_) => {
                    return Err(Diagnostic::new(
                        "M6800 source emitter does not yet support extern assembly functions",
                    ));
                }
                _ => {}
            }
        }
        Ok(())
    }

    fn emit_global_initializers(&mut self, program: &Program) -> Result<(), Diagnostic> {
        for declaration in &program.declarations {
            if let Declaration::Global(global) = declaration {
                self.require_scalar(&global.ty, "global")?;
                self.emit_expr(&global.value, &global.ty)?;
                self.staa(self.model.globals[&global.name].address);
            }
        }
        Ok(())
    }

    fn emit_function(&mut self, function: &Function) -> Result<(), Diagnostic> {
        if function
            .attrs
            .iter()
            .any(|attr| attr == "naked" || attr == "interrupt")
        {
            return Err(Diagnostic::new(format!(
                "M6800 source emitter does not support `{}` functions",
                function.name
            )));
        }
        for param in &function.params {
            self.require_scalar(&param.ty, "function parameter")?;
        }
        if let Some(ty) = &function.return_type {
            self.require_scalar(ty, "function return")?;
        }
        let local_plan = plan_function_locals(function, &mut self.model, self.cpu)?;
        let return_label = self.next_label(&format!("{}_return", function.name));
        self.line(&format!("_{}:", function.name));
        self.scopes.push(HashMap::new());
        self.return_labels.push(return_label.clone());
        self.return_types.push(function.return_type.clone());
        self.local_plans.push(local_plan);
        let signature = self.model.functions[&function.name].clone();
        for (param, slot) in function.params.iter().zip(signature.argument_slots) {
            self.bind(param.name.clone(), slot, param.ty.clone())?;
        }
        self.emit_block(&function.body)?;
        self.line(&format!("{return_label}:"));
        self.line("    rts");
        self.return_types.pop();
        self.return_labels.pop();
        self.local_plans.pop();
        self.scopes.pop();
        Ok(())
    }

    fn emit_block(&mut self, body: &[Stmt]) -> Result<(), Diagnostic> {
        for stmt in body {
            self.emit_stmt(stmt)?;
        }
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<(), Diagnostic> {
        match stmt {
            Stmt::Let { name, ty, value } => {
                self.require_scalar(ty, "local")?;
                let storage = self
                    .local_plans
                    .last()
                    .and_then(|locals| locals.get(name))
                    .map(|binding| binding.storage)
                    .ok_or_else(|| {
                        Diagnostic::new(format!("missing allocation for local `{name}`"))
                    })?;
                self.bind(name.clone(), storage, ty.clone())?;
                self.emit_expr(value, ty)?;
                self.staa(storage.address);
            }
            Stmt::Assign { target, op, value } => {
                let Place::Ident(name) = target else {
                    return Err(Diagnostic::new(
                        "M6800 source emitter supports assignment to scalar identifiers only",
                    ));
                };
                let binding = self.binding(name)?;
                self.require_scalar(&binding.ty, "assignment target")?;
                if *op == AssignOp::Set {
                    self.emit_expr(value, &binding.ty)?;
                } else {
                    self.ldaa(binding.storage.address);
                    self.push_a();
                    self.emit_expr(value, &binding.ty)?;
                    self.transfer_a_to_b();
                    self.pull_a();
                    self.emit_assign_op(*op)?;
                }
                self.staa(binding.storage.address);
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                let otherwise = self.next_label("if_else");
                let done = self.next_label("if_end");
                if !self.emit_jump_if_false(condition, &otherwise)? {
                    self.emit_expr(condition, &bool_type())?;
                    self.line("    tsta");
                    self.branch_long("beq", &otherwise);
                }
                self.emit_block(then_body)?;
                self.line(&format!("    jmp {done}"));
                self.line(&format!("{otherwise}:"));
                self.emit_block(else_body)?;
                self.line(&format!("{done}:"));
            }
            Stmt::While { condition, body } => {
                let check = self.next_label("while_check");
                let done = self.next_label("while_end");
                self.loops.push(LoopLabels {
                    continue_label: check.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{check}:"));
                if !self.emit_jump_if_false(condition, &done)? {
                    self.emit_expr(condition, &bool_type())?;
                    self.line("    tsta");
                    self.branch_long("beq", &done);
                }
                self.emit_block(body)?;
                self.line(&format!("    jmp {check}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Loop { body } => {
                let again = self.next_label("loop_body");
                let done = self.next_label("loop_end");
                self.loops.push(LoopLabels {
                    continue_label: again.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{again}:"));
                self.emit_block(body)?;
                self.line(&format!("    jmp {again}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Break => {
                let label = self
                    .loops
                    .last()
                    .ok_or_else(|| Diagnostic::new("break outside loop"))?
                    .break_label
                    .clone();
                self.line(&format!("    jmp {label}"));
            }
            Stmt::Continue => {
                let label = self
                    .loops
                    .last()
                    .ok_or_else(|| Diagnostic::new("continue outside loop"))?
                    .continue_label
                    .clone();
                self.line(&format!("    jmp {label}"));
            }
            Stmt::Return(value) => {
                let expected = self.return_types.last().cloned().flatten();
                match (value, expected) {
                    (Some(value), Some(ty)) => self.emit_expr(value, &ty)?,
                    (Some(_), None) => {
                        return Err(Diagnostic::new("value return in void function"));
                    }
                    (None, Some(_)) => {
                        return Err(Diagnostic::new("M6800 scalar function must return a value"));
                    }
                    (None, None) => {}
                }
                let label = self
                    .return_labels
                    .last()
                    .expect("function return label")
                    .clone();
                self.line(&format!("    jmp {label}"));
            }
            Stmt::Expr(expr) => {
                // A void call is meaningful as a statement even though it has no expression type.
                if matches!(expr, Expr::Call { .. }) {
                    self.emit_expr(expr, &u8_type())?;
                } else {
                    self.emit_expr(expr, &self.expr_type(expr)?)?;
                }
            }
            Stmt::Asm { .. } => {
                return Err(Diagnostic::new(
                    "M6800 source emitter does not support inline assembly",
                ));
            }
            Stmt::Out { .. } => {
                return Err(Diagnostic::new(
                    "M6800 source emitter does not support port I/O",
                ));
            }
        }
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr, expected: &Type) -> Result<(), Diagnostic> {
        self.require_scalar(expected, "expression")?;
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => self.ldaa_imm(*value as u8),
            Expr::Bool(value) => self.ldaa_imm(u8::from(*value)),
            Expr::Char(value) => self.ldaa_imm(*value),
            Expr::Ident(name) => {
                if let Some(value) = self.model.constants.get(name) {
                    self.ldaa_imm(*value as u8);
                } else {
                    self.ldaa(self.binding(name)?.storage.address);
                }
            }
            Expr::Unary { op, expr } => {
                self.emit_expr(expr, expected)?;
                match op {
                    UnaryOp::Neg => self.line("    nega"),
                    UnaryOp::BitNot => self.line("    coma"),
                    UnaryOp::Not => self.bool_not(),
                }
            }
            Expr::Binary { left, op, right } => {
                if matches!(op, BinaryOp::And | BinaryOp::Or) {
                    return self.emit_logical(left, *op, right);
                }
                let operand_ty = if is_comparison(*op) {
                    self.expr_type(left)?
                } else {
                    expected.clone()
                };
                self.require_scalar(&operand_ty, "binary operand")?;
                if matches!(op, BinaryOp::Shl | BinaryOp::Shr)
                    && let Some(count) = self.constant_shift_count(right)
                {
                    self.emit_expr(left, &operand_ty)?;
                    self.emit_constant_shift(*op, count, &operand_ty)?;
                    return Ok(());
                }
                self.emit_expr(left, &operand_ty)?;
                self.push_a();
                self.emit_expr(right, &operand_ty)?;
                self.staa(self.r1.address);
                self.pull_a();
                self.emit_binary(*op)?;
            }
            Expr::Call { path, args } => self.emit_call(path, args, expected)?,
            Expr::Cast { ty, expr } => {
                self.require_scalar(ty, "cast")?;
                self.emit_expr(expr, ty)?;
            }
            Expr::BankedPointer { pointer, .. } => self.emit_expr(pointer, expected)?,
            Expr::String(_)
            | Expr::Array(_)
            | Expr::StructInit { .. }
            | Expr::Index { .. }
            | Expr::Field { .. }
            | Expr::AddressOfIndex { .. }
            | Expr::AddressOfField { .. }
            | Expr::Access(_)
            | Expr::AddressOfAccess(_)
            | Expr::AddressOf(_)
            | Expr::Deref(_)
            | Expr::In(_) => {
                return Err(Diagnostic::new(
                    "M6800 source emitter supports scalar u8/bool expressions only",
                ));
            }
        }
        Ok(())
    }

    fn emit_call(
        &mut self,
        path: &[String],
        args: &[Expr],
        expected: &Type,
    ) -> Result<(), Diagnostic> {
        let name = path.join(".");
        let signature = self
            .model
            .functions
            .get(&name)
            .or_else(|| path.last().and_then(|n| self.model.functions.get(n)))
            .cloned()
            .ok_or_else(|| Diagnostic::new(format!("unknown function `{name}`")))?;
        if signature.params.len() != args.len() {
            return Err(Diagnostic::new(format!(
                "function `{name}` expects {} arguments, got {}",
                signature.params.len(),
                args.len()
            )));
        }
        for ((arg, ty), slot) in args
            .iter()
            .zip(&signature.params)
            .zip(&signature.argument_slots)
        {
            self.require_scalar(ty, "function argument")?;
            self.emit_expr(arg, ty)?;
            self.staa(slot.address);
        }
        self.line(&format!(
            "    jsr _{}",
            sanitize_label(path.last().unwrap_or(&name))
        ));
        if let Some(return_type) = signature.return_type {
            self.require_scalar(&return_type, "function return")?;
        } else if expected != &bool_type() && expected != &u8_type() {
            return Err(Diagnostic::new("void M6800 function used as a value"));
        }
        Ok(())
    }

    fn emit_assign_op(&mut self, op: AssignOp) -> Result<(), Diagnostic> {
        self.emit_binary(match op {
            AssignOp::Add => BinaryOp::Add, AssignOp::Sub => BinaryOp::Sub,
            AssignOp::BitAnd => BinaryOp::BitAnd, AssignOp::BitOr => BinaryOp::BitOr, AssignOp::BitXor => BinaryOp::BitXor,
            _ => return Err(Diagnostic::new("M6800 source emitter supports only +=, -=, &=, |=, and ^= compound assignments")),
        })
    }

    fn constant_shift_count(&self, expr: &Expr) -> Option<u32> {
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => u32::try_from(*value).ok(),
            Expr::Ident(name) => self
                .model
                .constants
                .get(name)
                .and_then(|value| u32::try_from(*value).ok()),
            Expr::Cast { expr, .. } => self.constant_shift_count(expr),
            _ => None,
        }
    }

    fn emit_constant_shift(
        &mut self,
        op: BinaryOp,
        count: u32,
        ty: &Type,
    ) -> Result<(), Diagnostic> {
        let instruction = match op {
            BinaryOp::Shl => "    asla",
            BinaryOp::Shr if self.type_is_signed(ty)? => "    asra",
            BinaryOp::Shr => "    lsra",
            _ => unreachable!("constant shift called for a non-shift operation"),
        };
        for _ in 0..count.min(8) {
            self.line(instruction);
        }
        Ok(())
    }

    fn emit_binary(&mut self, op: BinaryOp) -> Result<(), Diagnostic> {
        match op {
            BinaryOp::Add => self.line("    adda >__ezra_r1"),
            BinaryOp::Sub => self.line("    suba >__ezra_r1"),
            BinaryOp::Mul if self.cpu == CpuFamily::M6809 => {
                self.transfer_a_to_b();
                self.line("    ldab >__ezra_r1");
                self.line("    mul");
                self.line("    tfr b,a");
            }
            BinaryOp::Mul => {
                return Err(Diagnostic::new(
                    "M6800 source emitter does not support non-strength-reduced multiplication",
                ));
            }
            BinaryOp::BitAnd => self.line("    anda >__ezra_r1"),
            BinaryOp::BitOr => self.line("    oraa >__ezra_r1"),
            BinaryOp::BitXor => self.line("    eora >__ezra_r1"),
            op if is_comparison(op) => self.compare(op),
            _ => {
                return Err(Diagnostic::new(
                    "M6800 source emitter does not support this binary operation",
                ));
            }
        }
        Ok(())
    }

    fn compare(&mut self, op: BinaryOp) {
        let yes = self.next_label("compare_true");
        let done = self.next_label("compare_done");
        self.line("    cmpa >__ezra_r1");
        let branch = match op {
            BinaryOp::Eq => "beq",
            BinaryOp::Ne => "bne",
            BinaryOp::Lt => "blt",
            BinaryOp::Le => "ble",
            BinaryOp::Gt => "bgt",
            BinaryOp::Ge => "bge",
            _ => unreachable!(),
        };
        self.branch_long(branch, &yes);
        self.ldaa_imm(0);
        self.line(&format!("    jmp {done}"));
        self.line(&format!("{yes}:"));
        self.ldaa_imm(1);
        self.line(&format!("{done}:"));
    }

    fn emit_jump_if_false(
        &mut self,
        condition: &Expr,
        false_label: &str,
    ) -> Result<bool, Diagnostic> {
        let Expr::Binary { left, op, right } = condition else {
            return Ok(false);
        };
        if !matches!(op, BinaryOp::Eq | BinaryOp::Ne) {
            return Ok(false);
        }
        let Expr::Binary {
            left: source,
            op: BinaryOp::BitAnd,
            right: mask_expr,
        } = left.as_ref()
        else {
            return Ok(false);
        };
        let (Ok(mask), Ok(expected)) = (
            self.model.const_value(mask_expr),
            self.model.const_value(right),
        ) else {
            return Ok(false);
        };
        let (Ok(mask), Ok(expected)) = (u8::try_from(mask), u8::try_from(expected)) else {
            return Ok(false);
        };
        if !mask.is_power_of_two() || (expected != 0 && expected != mask) {
            return Ok(false);
        }

        let source_ty = self.expr_type(source)?;
        self.require_scalar(&source_ty, "bit-test operand")?;
        self.emit_expr(source, &source_ty)?;
        self.line(&format!("    bita #{mask:02X}h"));
        let branch = if (*op == BinaryOp::Eq) == (expected == 0) {
            "bne"
        } else {
            "beq"
        };
        self.branch_long(branch, false_label);
        Ok(true)
    }

    fn emit_logical(&mut self, left: &Expr, op: BinaryOp, right: &Expr) -> Result<(), Diagnostic> {
        let decisive = self.next_label("logical_decisive");
        let done = self.next_label("logical_done");
        self.emit_expr(left, &bool_type())?;
        self.line("    tsta");
        self.branch_long(if op == BinaryOp::And { "beq" } else { "bne" }, &decisive);
        self.emit_expr(right, &bool_type())?;
        self.line(&format!("    jmp {done}"));
        self.line(&format!("{decisive}:"));
        self.ldaa_imm(u8::from(op == BinaryOp::Or));
        self.line(&format!("{done}:"));
        Ok(())
    }

    fn bool_not(&mut self) {
        let yes = self.next_label("not_true");
        let done = self.next_label("not_done");
        self.line("    tsta");
        self.branch_long("beq", &yes);
        self.ldaa_imm(0);
        self.line(&format!("    jmp {done}"));
        self.line(&format!("{yes}:"));
        self.ldaa_imm(1);
        self.line(&format!("{done}:"));
    }

    fn expr_type(&self, expr: &Expr) -> Result<Type, Diagnostic> {
        match expr {
            Expr::Bool(_)
            | Expr::Unary {
                op: UnaryOp::Not, ..
            } => Ok(bool_type()),
            Expr::Int(_) | Expr::TypedInt(_, _) | Expr::Char(_) => Ok(u8_type()),
            Expr::Ident(name) => self
                .model
                .constant_types
                .get(name)
                .cloned()
                .or_else(|| self.binding(name).ok().map(|b| b.ty))
                .ok_or_else(|| Diagnostic::new(format!("unknown value `{name}`"))),
            Expr::Binary { left, op, .. }
                if is_comparison(*op) || matches!(op, BinaryOp::And | BinaryOp::Or) =>
            {
                Ok(bool_type())
            }
            Expr::Binary { left, .. }
            | Expr::Unary { expr: left, .. }
            | Expr::Cast { expr: left, .. } => self.expr_type(left),
            Expr::Call { path, .. } => self
                .model
                .functions
                .get(&path.join("."))
                .and_then(|s| s.return_type.clone())
                .ok_or_else(|| Diagnostic::new("void function has no value")),
            _ => Err(Diagnostic::new(
                "M6800 source emitter supports scalar u8/bool expressions only",
            )),
        }
    }

    fn require_scalar(&self, ty: &Type, context: &str) -> Result<(), Diagnostic> {
        match self.model.resolved_type(ty)? {
            Type::Named(name) if name == "u8" || name == "i8" || name == "bool" => Ok(()),
            _ => Err(Diagnostic::new(format!(
                "M6800 source emitter supports 8-bit integer and bool {context}s only"
            ))),
        }
    }

    fn type_is_signed(&self, ty: &Type) -> Result<bool, Diagnostic> {
        Ok(matches!(
            self.model.resolved_type(ty)?,
            Type::Named(name) if name == "i8"
        ))
    }
    fn bind(&mut self, name: String, storage: Storage, ty: Type) -> Result<(), Diagnostic> {
        if self
            .scopes
            .iter()
            .rev()
            .any(|scope| scope.contains_key(&name))
        {
            return Err(Diagnostic::new(format!(
                "local `{name}` shadows an existing name"
            )));
        }
        self.scopes
            .last_mut()
            .expect("function scope")
            .insert(name, Binding { storage, ty });
        Ok(())
    }
    fn binding(&self, name: &str) -> Result<Binding, Diagnostic> {
        if let Some(binding) = self.scopes.iter().rev().find_map(|scope| scope.get(name)) {
            return Ok(binding.clone());
        }
        self.model
            .globals
            .get(name)
            .map(|storage| Binding {
                storage: *storage,
                ty: self.model.global_types[name].clone(),
            })
            .ok_or_else(|| Diagnostic::new(format!("unknown variable `{name}`")))
    }
    fn push_a(&mut self) {
        if self.cpu == CpuFamily::M6809 {
            self.line("    pshs a");
        } else {
            self.line("    psha");
        }
    }

    fn pull_a(&mut self) {
        if self.cpu == CpuFamily::M6809 {
            self.line("    puls a");
        } else {
            self.line("    pula");
        }
    }

    fn transfer_a_to_b(&mut self) {
        if self.cpu == CpuFamily::M6809 {
            self.line("    tfr a,b");
        } else {
            self.line("    tab");
        }
    }

    fn ldaa(&mut self, address: u32) {
        self.line(&format!("    ldaa >{:04X}h", address));
    }
    fn staa(&mut self, address: u32) {
        self.line(&format!("    staa >{:04X}h", address));
    }
    fn ldaa_imm(&mut self, value: u8) {
        self.line(&format!("    ldaa #{value:02X}h"));
    }
    fn branch_long(&mut self, branch: &str, target: &str) {
        let skip = self.next_local_label("branch_skip");
        let inverse = match branch {
            "beq" => "bne",
            "bne" => "beq",
            "blt" => "bge",
            "bge" => "blt",
            "ble" => "bgt",
            "bgt" => "ble",
            _ => unreachable!(),
        };
        self.line(&format!("    {inverse} {skip}"));
        self.line(&format!("    jmp {target}"));
        self.line(&format!("{skip}:"));
    }
    fn next_label(&mut self, prefix: &str) -> String {
        let label = format!("__ezra_{prefix}_{}", self.labels);
        self.labels += 1;
        label
    }
    fn next_local_label(&mut self, prefix: &str) -> String {
        let label = format!("m6800_{prefix}_{}", self.labels);
        self.labels += 1;
        label
    }
    fn line(&mut self, line: &str) {
        self.out.push_str(line);
        self.out.push('\n');
    }

    fn reject_recursive_calls(&self, program: &Program) -> Result<(), Diagnostic> {
        let functions: HashSet<_> = program
            .declarations
            .iter()
            .filter_map(|d| {
                if let Declaration::Function(f) = d {
                    Some(f.name.as_str())
                } else {
                    None
                }
            })
            .collect();
        for declaration in &program.declarations {
            if let Declaration::Function(function) = declaration {
                let mut calls = Vec::new();
                collect_calls(&function.body, &mut calls);
                if calls.iter().any(|call| call == &function.name) {
                    return Err(Diagnostic::new(format!(
                        "M6800 source emitter does not support recursive function `{}`",
                        function.name
                    )));
                }
                if calls.iter().any(|call| {
                    functions.contains(call.as_str())
                        && call != &function.name
                        && calls_function(program, call, &function.name, &mut HashSet::new())
                }) {
                    return Err(Diagnostic::new(
                        "M6800 source emitter does not support recursive call cycles",
                    ));
                }
            }
        }
        Ok(())
    }
}

#[cfg(test)]
const M6800_BYTE_CLASS: RegClass = RegClass(0);
const M6800_LOCAL_CLASS: RegClass = RegClass(1);
const M6800_STATIC_SPILL_CLASS: SpillClassId = SpillClassId(0);

fn m6800_local_target(cpu: CpuFamily) -> Target {
    let mut registers = vec![
        PhysicalRegister::new("a", vec![RegUnit(0)]),
        PhysicalRegister::new("b", vec![RegUnit(1)]),
    ];
    if cpu == CpuFamily::M6809 {
        registers.push(PhysicalRegister::new("d", vec![RegUnit(0), RegUnit(1)]));
    }
    Target {
        units: vec![RegisterUnit::new("a"), RegisterUnit::new("b")],
        registers,
        register_classes: vec![
            RegisterClass::new("accumulator-byte", vec![PhysReg(0), PhysReg(1)]),
            RegisterClass::new("memory-local", Vec::new()),
        ],
        spill_classes: vec![
            SpillClass::new("static", None, 0).for_register_classes(vec![M6800_LOCAL_CLASS]),
        ],
    }
}

fn plan_function_locals(
    function: &Function,
    model: &mut SemanticModel,
    cpu: CpuFamily,
) -> Result<HashMap<String, Binding>, Diagnostic> {
    let mut source_locals = Vec::new();
    let mut local_types = HashMap::new();
    collect_source_locals(&function.body, &mut source_locals, &mut local_types)?;
    let clobbers = (0..m6800_local_target(cpu).registers.len())
        .map(PhysReg)
        .collect::<Vec<_>>();
    let planned = allocate_source_locals(
        &m6800_local_target(cpu),
        &source_locals,
        &function.body,
        &clobbers,
    )
    .map_err(regalloc_diagnostic)?;
    let spill_bytes = planned
        .allocation
        .spill_slots
        .iter()
        .map(|slot| slot.offset.saturating_add(slot.size))
        .max()
        .unwrap_or(0);
    let spill_region = model.allocate(spill_bytes)?;
    let mut bindings = HashMap::new();
    for (name, ty) in local_types {
        let vreg = planned
            .locals
            .vreg(&name)
            .ok_or_else(|| Diagnostic::new(format!("missing allocation for local `{name}`")))?;
        let Location::Spill(slot_index) = planned.allocation.location(vreg).ok_or_else(|| {
            Diagnostic::new(format!("source allocator did not place local `{name}`"))
        })?
        else {
            return Err(Diagnostic::new(format!(
                "M6800 local `{name}` was not allocated to static memory"
            )));
        };
        let slot = planned
            .allocation
            .spill_slots
            .get(slot_index)
            .ok_or_else(|| Diagnostic::new(format!("invalid spill slot for local `{name}`")))?;
        debug_assert_eq!(slot.class, M6800_STATIC_SPILL_CLASS);
        bindings.insert(
            name,
            Binding {
                storage: Storage {
                    address: spill_region.address + slot.offset,
                    size: slot.size,
                },
                ty,
            },
        );
    }
    Ok(bindings)
}

fn collect_source_locals(
    body: &[Stmt],
    locals: &mut Vec<SourceLocal>,
    local_types: &mut HashMap<String, Type>,
) -> Result<(), Diagnostic> {
    for stmt in body {
        match stmt {
            Stmt::Let { name, ty, .. } => {
                if local_types.insert(name.clone(), ty.clone()).is_some() {
                    return Err(Diagnostic::new(format!("duplicate local `{name}`")));
                }
                locals.push(
                    SourceLocal::new(name.clone(), 1, 1, M6800_LOCAL_CLASS)
                        .with_spill_classes(vec![M6800_STATIC_SPILL_CLASS]),
                );
            }
            Stmt::If {
                then_body,
                else_body,
                ..
            } => {
                collect_source_locals(then_body, locals, local_types)?;
                collect_source_locals(else_body, locals, local_types)?;
            }
            Stmt::While { body, .. } | Stmt::Loop { body } => {
                collect_source_locals(body, locals, local_types)?;
            }
            _ => {}
        }
    }
    Ok(())
}

fn regalloc_diagnostic(diagnostics: Vec<crate::regalloc::Diagnostic>) -> Diagnostic {
    Diagnostic::new(
        diagnostics
            .into_iter()
            .map(|diagnostic| diagnostic.message)
            .collect::<Vec<_>>()
            .join("; "),
    )
}

fn collect_calls(body: &[Stmt], calls: &mut Vec<String>) {
    for stmt in body {
        match stmt {
            Stmt::Expr(expr) => collect_expr_calls(expr, calls),
            Stmt::Let { value, .. } | Stmt::Return(Some(value)) => collect_expr_calls(value, calls),
            Stmt::Assign { value, .. } | Stmt::Out { value, .. } => {
                collect_expr_calls(value, calls)
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                collect_expr_calls(condition, calls);
                collect_calls(then_body, calls);
                collect_calls(else_body, calls);
            }
            Stmt::While { condition, body } => {
                collect_expr_calls(condition, calls);
                collect_calls(body, calls);
            }
            Stmt::Loop { body } => collect_calls(body, calls),
            _ => {}
        }
    }
}
fn collect_expr_calls(expr: &Expr, calls: &mut Vec<String>) {
    match expr {
        Expr::Call { path, args } => {
            calls.push(path.join("."));
            for arg in args {
                collect_expr_calls(arg, calls);
            }
        }
        Expr::Unary { expr, .. } | Expr::Cast { expr, .. } => collect_expr_calls(expr, calls),
        Expr::Binary { left, right, .. } => {
            collect_expr_calls(left, calls);
            collect_expr_calls(right, calls);
        }
        _ => {}
    }
}
fn calls_function(program: &Program, from: &str, wanted: &str, seen: &mut HashSet<String>) -> bool {
    if !seen.insert(from.to_owned()) {
        return false;
    }
    let Some(function) = program.declarations.iter().find_map(|d| match d {
        Declaration::Function(f) if f.name == from => Some(f),
        _ => None,
    }) else {
        return false;
    };
    let mut calls = Vec::new();
    collect_calls(&function.body, &mut calls);
    calls
        .iter()
        .any(|call| call == wanted || calls_function(program, call, wanted, seen))
}
fn is_comparison(op: BinaryOp) -> bool {
    matches!(
        op,
        BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge | BinaryOp::Eq | BinaryOp::Ne
    )
}
fn u8_type() -> Type {
    Type::Named("u8".to_owned())
}
fn bool_type() -> Type {
    Type::Named("bool".to_owned())
}
fn sanitize_label(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::emit_m6800_assembly_with_options;
    #[cfg(feature = "m6809")]
    use super::emit_m6809_assembly_with_options;
    use crate::{
        asm::AssemblyOptions,
        parser::parse_program,
        regalloc::PhysReg,
        target::{Address24, AssemblerCpu, CpuFamily},
        vm::{
            TestImage, TestRunOptions, TestRunner, assemble_subset_at,
            assemble_subset_with_symbols_at,
        },
    };

    fn m6800_options() -> AssemblyOptions {
        AssemblyOptions {
            cpu: CpuFamily::M6800,
            ram_base: Address24::new(0xA000),
            rodata_base: Address24::new(0x8000),
            asset_base: Address24::new(0xC000),
            ..AssemblyOptions::default()
        }
    }

    #[cfg(feature = "m6809")]
    fn m6809_options() -> AssemblyOptions {
        AssemblyOptions {
            cpu: CpuFamily::M6809,
            ram_base: Address24::new(0xA000),
            rodata_base: Address24::new(0x8000),
            asset_base: Address24::new(0xC000),
            ..AssemblyOptions::default()
        }
    }

    #[test]
    fn local_target_models_accumulators_and_uses_memory_only_locals() {
        let m6800 = super::m6800_local_target(CpuFamily::M6800);
        assert_eq!(
            m6800.register_classes[super::M6800_BYTE_CLASS.0]
                .registers
                .len(),
            2
        );
        assert!(
            m6800.register_classes[super::M6800_LOCAL_CLASS.0]
                .registers
                .is_empty()
        );
        assert!(!m6800.registers_alias(PhysReg(0), PhysReg(1)));

        let m6809 = super::m6800_local_target(CpuFamily::M6809);
        assert_eq!(m6809.registers[2].name, "d");
        assert!(m6809.registers_alias(PhysReg(0), PhysReg(2)));
        assert!(m6809.registers_alias(PhysReg(1), PhysReg(2)));
    }

    fn local_initializer_address(assembly: &str, value: u8) -> String {
        let marker = format!("    ldaa #{value:02X}h\n    staa >");
        let rest = assembly
            .split_once(&marker)
            .unwrap_or_else(|| panic!("missing local initializer {value:02X}\n{assembly}"))
            .1;
        rest[..4].to_owned()
    }

    fn assert_reuses_memory_local(assembly: &str, cpu: AssemblerCpu) {
        assert_eq!(
            local_initializer_address(assembly, 0x11),
            local_initializer_address(assembly, 0x22),
            "{assembly}"
        );
        assemble_subset_with_symbols_at(cpu, assembly, 0)
            .unwrap_or_else(|error| panic!("{error}\n{assembly}"));
    }

    #[test]
    fn colors_nonoverlapping_m6800_locals_into_one_static_byte() {
        let program = parse_program(
            Path::new("m6800_spill_reuse.ezra"),
            r#"
                global sink: u8 = 0
                fn main() {
                    let first: u8 = 0x11
                    sink = first
                    let second: u8 = 0x22
                    sink = second
                }
            "#,
        )
        .unwrap();
        let assembly = emit_m6800_assembly_with_options(&program, m6800_options()).unwrap();
        assert_reuses_memory_local(&assembly, AssemblerCpu::M6800);
    }

    #[cfg(feature = "m6809")]
    #[test]
    fn colors_nonoverlapping_m6809_locals_into_one_static_byte() {
        let program = parse_program(
            Path::new("m6809_spill_reuse.ezra"),
            r#"
                global sink: u8 = 0
                fn main() {
                    let first: u8 = 0x11
                    sink = first
                    let second: u8 = 0x22
                    sink = second
                }
            "#,
        )
        .unwrap();
        let assembly = emit_m6809_assembly_with_options(&program, m6809_options()).unwrap();
        assert_reuses_memory_local(&assembly, AssemblerCpu::M6809);
    }

    #[test]
    fn emits_assemblable_scalar_globals_locals_and_control_flow() {
        let program = parse_program(
            Path::new("m6800_test.ezra"),
            r#"
                global counter: u8 = 1
                global enabled: bool = true

                fn main() {
                    let value: u8 = counter + 2
                    if enabled && value == 3 { counter = value }
                    while counter < 5 { counter += 1 }
                }
            "#,
        )
        .unwrap();
        let assembly = emit_m6800_assembly_with_options(&program, m6800_options()).unwrap();

        assert!(assembly.contains("_main:"), "{assembly}");
        assert!(assembly.contains("adda >__ezra_r1"), "{assembly}");
        assemble_subset_with_symbols_at(AssemblerCpu::M6800, &assembly, 0)
            .unwrap_or_else(|error| panic!("{error}\n{assembly}"));
    }

    #[cfg(feature = "m6809")]
    #[test]
    fn m6809_source_uses_tbir_strength_reduction_and_assembles() {
        let program = parse_program(
            Path::new("m6809_tbir_test.ezra"),
            "fn shift(value: u8) -> u8 { return value * 8 } fn scale(value: u8) -> u8 { return value * 3 } fn main() { let shifted: u8 = shift(1) let scaled: u8 = scale(3) }",
        )
        .unwrap();
        let assembly = emit_m6809_assembly_with_options(&program, m6809_options()).unwrap();
        assert!(assembly.contains("    asla\n"), "{assembly}");
        assert!(assembly.contains("    mul\n"), "{assembly}");
        assert!(assembly.contains("target: Motorola M6809"), "{assembly}");
        assemble_subset_with_symbols_at(AssemblerCpu::M6809, &assembly, 0)
            .unwrap_or_else(|error| panic!("{error}\n{assembly}"));
    }

    #[test]
    fn emits_original_m6800_constant_shift_instructions_and_strength_reduces_multiply() {
        let program = parse_program(
            Path::new("m6800_shift_test.ezra"),
            r#"
                fn left(value: u8) -> u8 { return value << 2 }
                fn unsigned_right(value: u8) -> u8 { return value >> 3 }
                fn signed_right(value: i8) -> i8 { return value >> 2 }
                fn times_eight(value: u8) -> u8 { return value * 8 }
                fn main() {
                    let left_value: u8 = left(1)
                    let unsigned_value: u8 = unsigned_right(1)
                    let signed_value: i8 = signed_right(1i8)
                    let times_eight_value: u8 = times_eight(1)
                }
            "#,
        )
        .unwrap();
        let assembly = emit_m6800_assembly_with_options(&program, m6800_options()).unwrap();

        assert_eq!(assembly.matches("    asla\n").count(), 5, "{assembly}");
        assert_eq!(assembly.matches("    lsra\n").count(), 3, "{assembly}");
        assert_eq!(assembly.matches("    asra\n").count(), 2, "{assembly}");
        assert!(!assembly.contains("    mul"), "{assembly}");
        assemble_subset_with_symbols_at(AssemblerCpu::M6800, &assembly, 0)
            .unwrap_or_else(|error| panic!("{error}\n{assembly}"));
    }

    fn run_main_result(source: &str) -> u8 {
        let program = parse_program(Path::new("m6800_shift_runtime.ezra"), source).unwrap();
        let assembly = emit_m6800_assembly_with_options(&program, m6800_options()).unwrap();
        let assembly = assembly.replace(
            "__ezra_exit:\n    bra __ezra_exit\n",
            "__ezra_exit:\n    staa >FFF1h\n    ldaa #01h\n    staa >FFF2h\n",
        );
        let bytes = assemble_subset_at(CpuFamily::M6800, &assembly, 0).unwrap();
        let run = TestRunner::default()
            .run(
                &TestImage {
                    cpu_family: CpuFamily::M6800,
                    base_addr: 0,
                    bytes,
                },
                &TestRunOptions {
                    instruction_budget: 200,
                    initial_ports: Vec::new(),
                    initial_memory: Vec::new(),
                    stack_top: 0x01ff,
                },
            )
            .unwrap();
        assert!(run.halted, "{assembly}");
        run.result_code
    }

    #[test]
    fn executes_constant_shifts_and_multiply_strength_reduction() {
        assert_eq!(
            run_main_result("global value: u8 = 0x23 fn main() -> u8 { return value << 3 }"),
            0x18
        );
        assert_eq!(
            run_main_result("global value: u8 = 0x90 fn main() -> u8 { return value >> 3 }"),
            0x12
        );
        assert_eq!(
            run_main_result("global value: i8 = -64 fn main() -> i8 { return value >> 3 }"),
            0xf8
        );
        assert_eq!(
            run_main_result("global value: u8 = 0x23 fn main() -> u8 { return value * 8 }"),
            0x18
        );
    }

    #[test]
    fn explicit_inline_assembles_typed_arguments_nested_helpers_and_safe_fallbacks() {
        let source = r#"
            global sequence: u8 = 0
            global first_seen: u8 = 0
            global second_seen: u8 = 0

            fn next() -> u8 {
                sequence += 1
                return sequence
            }

            inline fn record_pair(first: u8, second: u8) {
                first_seen = first
                second_seen = second
            }

            inline fn nested_pair(first: u8, second: u8) {
                record_pair(first, second)
            }

            inline fn ready() -> bool {
                sequence += 1
                return sequence < 5
            }

            fn main() -> u8 {
                nested_pair(next(), next())
                let short_circuit: bool = false && ready()
                while ready() {}
                return second_seen
            }
        "#;
        let program = parse_program(Path::new("m6800_inline_test.ezra"), source).unwrap();
        let assembly = emit_m6800_assembly_with_options(&program, m6800_options()).unwrap();

        assemble_subset_with_symbols_at(AssemblerCpu::M6800, &assembly, 0)
            .unwrap_or_else(|error| panic!("{error}\n{assembly}"));
        assert_eq!(assembly.matches("jsr _next").count(), 2, "{assembly}");
        assert!(!assembly.contains("jsr _record_pair"), "{assembly}");
        assert!(!assembly.contains("jsr _nested_pair"), "{assembly}");
        assert!(!assembly.contains("_record_pair:"), "{assembly}");
        assert!(!assembly.contains("_nested_pair:"), "{assembly}");
        assert!(assembly.contains("_ready:"), "{assembly}");
        assert_eq!(assembly.matches("jsr _ready").count(), 1, "{assembly}");
    }

    #[test]
    fn lowers_single_bit_mask_branches_to_bita_without_skipping_evaluation() {
        let program = parse_program(
            Path::new("m6800_bit_test.ezra"),
            r#"
                global calls: u8 = 0

                fn next() -> u8 {
                    calls += 1
                    return calls
                }

                fn main() -> u8 {
                    if (next() & 1) == 0 { calls += 2 }
                    while (next() & 2) != 0 { break }
                    return calls
                }
            "#,
        )
        .unwrap();
        let assembly = emit_m6800_assembly_with_options(&program, m6800_options()).unwrap();

        assert_eq!(assembly.matches("    bita #01h\n").count(), 1, "{assembly}");
        assert_eq!(assembly.matches("    bita #02h\n").count(), 1, "{assembly}");
        assert_eq!(assembly.matches("jsr _next").count(), 2, "{assembly}");
        assert!(!assembly.contains("anda >__ezra_r1"), "{assembly}");
        assemble_subset_with_symbols_at(AssemblerCpu::M6800, &assembly, 0)
            .unwrap_or_else(|error| panic!("{error}\n{assembly}"));
    }

    #[test]
    fn rejects_wide_scalar_storage() {
        let program = parse_program(
            Path::new("m6800_test.ezra"),
            "fn main() -> u16 { let wide: u16 = 1 return wide }",
        )
        .unwrap();
        let error = emit_m6800_assembly_with_options(&program, m6800_options()).unwrap_err();
        assert!(error.message.contains("8-bit integer and bool"));
    }
}
