use std::collections::HashMap;

use crate::{
    asm::{AssemblyOptions, comments::with_readability_comments},
    ast::{
        AccessPath, AccessSegment, AssignOp, BinaryOp, Declaration, Expr, Function, Place, Program,
        Stmt, Type, UnaryOp,
    },
    diagnostic::Diagnostic,
    hir::HirProgram,
    target::CpuFamily,
    tbir::{
        TbirProgram,
        model::{SemanticModel, Storage},
    },
};

/// Emit code for the generic 68000 target.
///
/// Values are evaluated in D0, with D1 as the binary-operation scratch
/// register. Arguments live in target-owned static slots, which keeps the
/// first ABI simple while allowing ordinary EZRA calls without a platform SDK.
pub fn emit_m68k_assembly_with_options(
    program: &Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    if options.cpu != CpuFamily::M68k {
        return Err(Diagnostic::new("M68k emitter requires an m68k target"));
    }
    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    let model = SemanticModel::from_program(
        &tbir.lowered_program,
        24,
        options.ram_base.get(),
        options.rodata_base.get(),
        options.asset_base.get(),
    )?;
    Emitter::new(model, options.clone())
        .emit(&tbir.lowered_program)
        .map(|asm| with_readability_comments(asm, program, &options, "m68k"))
}

#[derive(Clone)]
struct Binding {
    storage: Storage,
    ty: Type,
}

#[derive(Clone)]
struct LoopLabels {
    continue_label: String,
    break_label: String,
}

struct Emitter {
    model: SemanticModel,
    options: AssemblyOptions,
    out: String,
    labels: usize,
    scopes: Vec<HashMap<String, Binding>>,
    loops: Vec<LoopLabels>,
    return_labels: Vec<String>,
    return_types: Vec<Option<Type>>,
    function_ram_bases: Vec<u32>,
}

impl Emitter {
    fn new(model: SemanticModel, options: AssemblyOptions) -> Self {
        Self {
            model,
            options,
            out: String::new(),
            labels: 0,
            scopes: Vec::new(),
            loops: Vec::new(),
            return_labels: Vec::new(),
            return_types: Vec::new(),
            function_ram_bases: Vec::new(),
        }
    }

    fn emit(mut self, program: &Program) -> Result<String, Diagnostic> {
        self.line("; generated by ezrac");
        self.line("; target: Motorola 68000");
        self.line("section .text");
        self.line("__ezra_start:");
        self.line(&format!(
            "    move.l #${:06X},sp",
            self.options.stack_top.get()
        ));
        self.emit_static_initializers(program)?;
        self.line("    jsr _main");
        self.line("__ezra_exit:");
        self.line("    bra __ezra_exit");
        for declaration in &program.declarations {
            if let Declaration::Function(function) = declaration {
                self.emit_function(function)?;
            }
        }
        let mut strings = self
            .model
            .strings
            .iter()
            .map(|(value, storage)| (storage.address, value.clone()))
            .collect::<Vec<_>>();
        strings.sort_by_key(|(address, _)| *address);
        if !strings.is_empty() {
            self.line("section .rodata");
            for (_, value) in strings {
                self.emit_data_bytes(value.bytes().chain(std::iter::once(0)).collect());
            }
        }
        let mut embeds = self.model.embeds.values().cloned().collect::<Vec<_>>();
        embeds.sort_by_key(|embed| embed.storage.address);
        if !embeds.is_empty() {
            self.line("section .assets");
            for embed in embeds {
                self.emit_data_bytes(embed.bytes);
            }
        }
        Ok(self.out)
    }

    fn emit_static_initializers(&mut self, program: &Program) -> Result<(), Diagnostic> {
        for declaration in &program.declarations {
            let Declaration::Global(global) = declaration else {
                continue;
            };
            let storage = self.model.globals[&global.name];
            let ty = self.model.resolved_type(&global.ty)?;
            self.emit_initializer(storage, &ty, &global.value)?;
        }
        Ok(())
    }

    fn emit_function(&mut self, function: &Function) -> Result<(), Diagnostic> {
        let naked = function.attrs.iter().any(|attr| attr == "naked");
        let interrupt = function.attrs.iter().any(|attr| attr == "interrupt");
        if naked
            && function.body.iter().any(|stmt| {
                !matches!(stmt, Stmt::Asm { inputs, outputs, .. } if inputs.is_empty() && outputs.is_empty())
            })
        {
            return Err(Diagnostic::new(format!(
                "naked function `{}` may contain only asm blocks without operands",
                function.name
            )));
        }
        if interrupt && (!function.params.is_empty() || function.return_type.is_some()) {
            return Err(Diagnostic::new(format!(
                "interrupt function `{}` cannot have parameters or a return value",
                function.name
            )));
        }
        let return_label = self.next_label(&format!("{}_return", function.name));
        self.line(&format!("{}:", function_label(&function.name)));
        self.scopes.push(HashMap::new());
        self.return_labels.push(return_label.clone());
        self.function_ram_bases.push(self.model.next_ram_address());
        self.return_types.push(
            function
                .return_type
                .as_ref()
                .map(|ty| self.model.resolved_type(ty))
                .transpose()?,
        );
        let signature = self.model.functions[&function.name].clone();
        if interrupt && !naked {
            for register in (0..8)
                .map(|index| format!("d{index}"))
                .chain((0..7).map(|index| format!("a{index}")))
            {
                self.line(&format!("    move.l {register},-(sp)"));
            }
        }
        for (param, slot) in function.params.iter().zip(signature.argument_slots) {
            let ty = self.model.resolved_type(&param.ty)?;
            let storage = self.model.allocate_type(&ty)?;
            self.bind(param.name.clone(), storage, ty.clone())?;
            if self.model.type_width(&ty).is_ok() {
                self.load_d0(slot, &ty)?;
                self.store_d0(storage, &ty)?;
            } else {
                self.copy(slot, storage, storage.size);
            }
        }
        self.emit_block(&function.body)?;
        self.line(&format!("{return_label}:"));
        if interrupt {
            if !naked {
                for register in (0..7)
                    .rev()
                    .map(|index| format!("a{index}"))
                    .chain((0..8).rev().map(|index| format!("d{index}")))
                {
                    self.line(&format!("    move.l (sp)+,{register}"));
                }
            }
            self.line("    rte");
        } else if !naked {
            self.line("    rts");
        }
        self.return_types.pop();
        self.return_labels.pop();
        self.function_ram_bases.pop();
        self.scopes.pop();
        Ok(())
    }

    fn emit_block(&mut self, body: &[Stmt]) -> Result<(), Diagnostic> {
        for stmt in body {
            self.emit_stmt(stmt)?;
        }
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<(), Diagnostic> {
        match stmt {
            Stmt::Let { name, ty, value } => {
                let ty = self.model.resolved_type(ty)?;
                let storage = self.model.allocate_type(&ty)?;
                self.bind(name.clone(), storage, ty.clone())?;
                self.emit_initializer(storage, &ty, value)?;
            }
            Stmt::Assign { target, op, value } => {
                let ty = self.place_type(target)?;
                if self.model.type_width(&ty).is_err() {
                    if *op != AssignOp::Set {
                        return Err(Diagnostic::new(
                            "compound assignment requires a scalar value",
                        ));
                    }
                    let storage = self.model.allocate_type(&ty)?;
                    self.emit_initializer(storage, &ty, value)?;
                    self.store_aggregate_place(target, storage, storage.size)?;
                    return Ok(());
                }
                if *op == AssignOp::Set {
                    self.emit_expr(value, &ty)?;
                } else {
                    self.load_place(target, &ty)?;
                    self.line(&format!("    move.{} d0,d1", size_suffix(&ty)?));
                    self.emit_expr(value, &ty)?;
                    self.line(&format!("    move.{} d0,d2", size_suffix(&ty)?));
                    self.line(&format!("    move.{} d1,d0", size_suffix(&ty)?));
                    self.emit_binary(assign_binary(*op), &ty)?;
                }
                self.store_place(target, &ty)?;
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                let otherwise = self.next_label("if_else");
                let done = self.next_label("if_end");
                self.emit_expr(condition, &Type::Named("bool".to_owned()))?;
                self.line("    tst.b d0");
                self.line(&format!("    beq {otherwise}"));
                self.emit_block(then_body)?;
                self.line(&format!("    bra {done}"));
                self.line(&format!("{otherwise}:"));
                self.emit_block(else_body)?;
                self.line(&format!("{done}:"));
            }
            Stmt::While { condition, body } => {
                let check = self.next_label("while_check");
                let done = self.next_label("while_end");
                self.loops.push(LoopLabels {
                    continue_label: check.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{check}:"));
                self.emit_expr(condition, &Type::Named("bool".to_owned()))?;
                self.line("    tst.b d0");
                self.line(&format!("    beq {done}"));
                self.emit_block(body)?;
                self.line(&format!("    bra {check}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Loop { body } => {
                let again = self.next_label("loop");
                let done = self.next_label("loop_end");
                self.loops.push(LoopLabels {
                    continue_label: again.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{again}:"));
                self.emit_block(body)?;
                self.line(&format!("    bra {again}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Break => self.jump_loop(false)?,
            Stmt::Continue => self.jump_loop(true)?,
            Stmt::Return(value) => {
                if let Some(value) = value {
                    let ty = self
                        .return_types
                        .last()
                        .and_then(Clone::clone)
                        .ok_or_else(|| Diagnostic::new("value return in void function"))?;
                    self.emit_expr(value, &ty)?;
                }
                let label = self
                    .return_labels
                    .last()
                    .expect("function return label")
                    .clone();
                self.line(&format!("    bra {label}"));
            }
            Stmt::Asm {
                inputs,
                outputs,
                lines,
                ..
            } => self.emit_inline_asm(inputs, outputs, lines)?,
            Stmt::Out { port, .. } => {
                return Err(Diagnostic::new(format!(
                    "M68k does not support separate port I/O `{port}`; use mmio instead"
                )));
            }
            Stmt::Expr(expr) => {
                if let Expr::Call { path, .. } = expr {
                    self.emit_call(path, expr_call_args(expr)?, None)?;
                } else {
                    let ty = self.expr_type(expr)?;
                    self.emit_expr(expr, &ty)?;
                }
            }
        }
        Ok(())
    }

    fn emit_initializer(
        &mut self,
        storage: Storage,
        ty: &Type,
        value: &Expr,
    ) -> Result<(), Diagnostic> {
        let resolved = self.model.resolved_type(ty)?;
        match (resolved, value) {
            (Type::Array { .. }, Expr::Ident(name)) => {
                let source = self.binding(name)?;
                self.copy(source.storage, storage, storage.size);
            }
            (Type::Array { element, len }, Expr::Array(values)) => {
                let element_size = self.model.type_size(&element)?;
                let len = u32::try_from(self.model.const_value(&len)?)
                    .map_err(|_| Diagnostic::new("invalid array length"))?;
                for index in 0..len {
                    let element_storage = Storage {
                        address: storage.address + index * element_size,
                        size: element_size,
                    };
                    if let Some(value) = values.get(index as usize) {
                        self.emit_initializer(element_storage, &element, value)?;
                    } else {
                        self.zero(element_storage);
                    }
                }
            }
            (Type::Named(name), Expr::StructInit { fields, .. })
                if self.model.structs.contains_key(&name) =>
            {
                self.zero(storage);
                let layout = self.model.structs[&name].clone();
                for (field_name, value) in fields {
                    let field = layout
                        .fields
                        .get(field_name)
                        .ok_or_else(|| Diagnostic::new(format!("unknown field `{field_name}`")))?;
                    self.emit_initializer(
                        Storage {
                            address: storage.address + field.offset,
                            size: field.size,
                        },
                        &field.ty,
                        value,
                    )?;
                }
            }
            (Type::Named(name), Expr::Ident(source)) if self.model.structs.contains_key(&name) => {
                let source = self.binding(source)?;
                self.copy(source.storage, storage, storage.size);
            }
            (resolved @ (Type::Array { .. } | Type::Named(_)), Expr::Deref(pointer)) => {
                self.emit_expr(pointer, &Type::Ptr(Box::new(resolved)))?;
                self.line("    move.l d0,a0");
                self.copy_from_a0(storage, storage.size);
            }
            (_, value) => {
                self.emit_expr(value, ty)?;
                self.store_d0(storage, ty)?;
            }
        }
        Ok(())
    }

    fn jump_loop(&mut self, continue_loop: bool) -> Result<(), Diagnostic> {
        let labels = self
            .loops
            .last()
            .ok_or_else(|| {
                Diagnostic::new(if continue_loop {
                    "continue outside loop"
                } else {
                    "break outside loop"
                })
            })?
            .clone();
        self.line(&format!(
            "    bra {}",
            if continue_loop {
                labels.continue_label
            } else {
                labels.break_label
            }
        ));
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr, expected: &Type) -> Result<(), Diagnostic> {
        self.require_scalar(expected)?;
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => self.load_constant(*value, expected)?,
            Expr::Bool(value) => self.load_constant(i64::from(*value), expected)?,
            Expr::Char(value) => self.load_constant(i64::from(*value), expected)?,
            Expr::String(value) => {
                let storage = self.model.intern_string(value)?;
                self.load_constant(i64::from(storage.address), expected)?;
            }
            Expr::Ident(name) => {
                if let Some(value) = self.model.constants.get(name).copied() {
                    self.load_constant(value, expected)?;
                } else {
                    let binding = self.binding(name)?;
                    self.load_d0(binding.storage, &binding.ty)?;
                }
            }
            Expr::Field { base, field } => {
                let constant = format!("{base}.{field}");
                if let Some(value) = self.model.constants.get(&constant).copied() {
                    self.load_constant(value, expected)?;
                } else {
                    let binding = self.binding(base)?;
                    let field = self.model.field(&binding.ty, field)?.clone();
                    self.load_d0(
                        Storage {
                            address: binding.storage.address + field.offset,
                            size: field.size,
                        },
                        &field.ty,
                    )?;
                }
            }
            Expr::Index { name, index } => {
                let element = self.emit_named_index_address(name, index)?;
                self.load_from_a0(&element)?;
            }
            Expr::Access(path) => {
                let ty = self.emit_access_address(path)?;
                self.load_from_a0(&ty)?;
            }
            Expr::AddressOf(name) => {
                let binding = self.binding(name)?;
                self.load_constant(i64::from(binding.storage.address), expected)?;
            }
            Expr::AddressOfIndex { name, index } => {
                self.emit_named_index_address(name, index)?;
                self.line("    move.l a0,d0");
            }
            Expr::AddressOfField { base, field } => {
                let binding = self.binding(base)?;
                let field = self.model.field(&binding.ty, field)?;
                self.load_constant(i64::from(binding.storage.address + field.offset), expected)?;
            }
            Expr::AddressOfAccess(path) => {
                self.emit_access_address(path)?;
                self.line("    move.l a0,d0");
            }
            Expr::Call { path, args } => self.emit_call(path, args, Some(expected))?,
            Expr::Unary { op, expr } => {
                self.emit_expr(expr, expected)?;
                match op {
                    UnaryOp::Neg => self.line(&format!("    neg.{} d0", size_suffix(expected)?)),
                    UnaryOp::BitNot => self.line(&format!("    not.{} d0", size_suffix(expected)?)),
                    UnaryOp::Not => self.boolean_from_test("beq", expected)?,
                }
            }
            Expr::Binary { left, op, right } => {
                if matches!(op, BinaryOp::And | BinaryOp::Or) {
                    self.emit_logical(left, *op, right)?;
                    return Ok(());
                }
                let operand_ty = if is_comparison(*op) {
                    self.expr_type(left)?
                } else {
                    expected.clone()
                };
                self.emit_expr(left, &operand_ty)?;
                self.line(&format!("    move.{} d0,d1", size_suffix(&operand_ty)?));
                self.emit_expr(right, &operand_ty)?;
                self.line(&format!("    move.{} d0,d2", size_suffix(&operand_ty)?));
                if matches!(op, BinaryOp::Add | BinaryOp::Sub)
                    && let Type::Ptr(element) = self.model.resolved_type(&operand_ty)?
                {
                    let size = self.model.type_size(&element)?;
                    if size > 1 {
                        self.line(&format!("    mulu #${size:X},d2"));
                    }
                }
                self.line(&format!("    move.{} d1,d0", size_suffix(&operand_ty)?));
                self.emit_binary(*op, &operand_ty)?;
            }
            Expr::Cast { ty, expr } => {
                let ty = self.model.resolved_type(ty)?;
                self.require_scalar(&ty)?;
                self.emit_expr(expr, &ty)?;
            }
            Expr::Deref(pointer) => {
                let pointer_ty = self.expr_type(pointer)?;
                let Type::Ptr(inner) = self.model.resolved_type(&pointer_ty)? else {
                    return Err(Diagnostic::new("dereference requires pointer"));
                };
                self.require_scalar(&inner)?;
                self.emit_expr(pointer, &pointer_ty)?;
                self.line("    move.l d0,a0");
                self.load_from_a0(&inner)?;
            }
            Expr::In(port) => {
                return Err(Diagnostic::new(format!(
                    "M68k does not support separate port I/O `{port}`; use mmio instead"
                )));
            }
            Expr::Array(_) | Expr::StructInit { .. } => {
                return Err(Diagnostic::new(
                    "aggregate value requires a storage context",
                ));
            }
        }
        Ok(())
    }

    fn emit_binary(&mut self, op: BinaryOp, ty: &Type) -> Result<(), Diagnostic> {
        let size = size_suffix(ty)?;
        if scalar_width(ty)? == 3 && matches!(op, BinaryOp::Mul | BinaryOp::Div | BinaryOp::Mod) {
            return if op == BinaryOp::Mul {
                self.emit_wide_multiply(type_is_signed(ty))
            } else {
                self.emit_wide_divide(op == BinaryOp::Mod, type_is_signed(ty))
            };
        }
        match op {
            BinaryOp::Add => self.line(&format!("    add.{size} d2,d0")),
            BinaryOp::Sub => self.line(&format!("    sub.{size} d2,d0")),
            BinaryOp::BitAnd => self.line(&format!("    and.{size} d2,d0")),
            BinaryOp::BitOr => self.line(&format!("    or.{size} d2,d0")),
            BinaryOp::BitXor => self.line(&format!("    eor.{size} d2,d0")),
            BinaryOp::Shl => self.line(&format!("    lsl.{size} d2,d0")),
            BinaryOp::Shr => self.line(&format!(
                "    {}.{size} d2,d0",
                if type_is_signed(ty) { "asr" } else { "lsr" }
            )),
            BinaryOp::Mul => {
                if size == "b" {
                    return Err(Diagnostic::new(
                        "M68k multiplication requires u16 or i16 values",
                    ));
                }
                self.line(if type_is_signed(ty) {
                    "    muls d2,d0"
                } else {
                    "    mulu d2,d0"
                });
            }
            BinaryOp::Div | BinaryOp::Mod => {
                if size == "b" {
                    return Err(Diagnostic::new("M68k division requires u16 or i16 values"));
                }
                self.line(if type_is_signed(ty) {
                    "    divs d2,d0"
                } else {
                    "    divu d2,d0"
                });
                if op == BinaryOp::Mod {
                    self.line("    swap d0");
                }
            }
            BinaryOp::Eq
            | BinaryOp::Ne
            | BinaryOp::Lt
            | BinaryOp::Le
            | BinaryOp::Gt
            | BinaryOp::Ge => {
                self.line(&format!("    cmp.{size} d2,d0"));
                self.boolean_from_branch(comparison_branch(op, type_is_signed(ty)))?;
            }
            BinaryOp::And | BinaryOp::Or => unreachable!(),
        }
        if !is_comparison(op) {
            self.normalize_d0(ty)?;
        }
        Ok(())
    }

    fn emit_wide_multiply(&mut self, signed: bool) -> Result<(), Diagnostic> {
        let loop_label = self.next_label("mul_u24_loop");
        let skip = self.next_label("mul_u24_skip");
        let done = self.next_label("mul_u24_done");
        let positive_left = self.next_label("mul_u24_left_positive");
        let positive_right = self.next_label("mul_u24_right_positive");
        let positive_result = self.next_label("mul_u24_result_positive");
        self.line("    moveq #0,d5");
        if signed {
            self.line("    tst.l d0");
            self.line(&format!("    bpl {positive_left}"));
            self.line("    neg.l d0");
            self.line("    moveq #1,d5");
            self.line(&format!("{positive_left}:"));
            self.line("    tst.l d2");
            self.line(&format!("    bpl {positive_right}"));
            self.line("    neg.l d2");
            self.line("    eori.b #1,d5");
            self.line(&format!("{positive_right}:"));
        }
        self.line("    move.l d0,d3");
        self.line("    move.l d2,d4");
        self.line("    moveq #0,d1");
        self.line(&format!("{loop_label}:"));
        self.line("    tst.l d4");
        self.line(&format!("    beq {done}"));
        self.line("    move.l d4,d6");
        self.line("    andi.l #1,d6");
        self.line(&format!("    beq {skip}"));
        self.line("    add.l d3,d1");
        self.line(&format!("{skip}:"));
        self.line("    lsl.l #1,d3");
        self.line("    lsr.l #1,d4");
        self.line(&format!("    bra {loop_label}"));
        self.line(&format!("{done}:"));
        self.line("    move.l d1,d0");
        if signed {
            self.line("    tst.b d5");
            self.line(&format!("    beq {positive_result}"));
            self.line("    neg.l d0");
            self.line(&format!("{positive_result}:"));
        }
        self.normalize_d0(&Type::Named(if signed { "i24" } else { "u24" }.to_owned()))
    }

    fn emit_wide_divide(&mut self, remainder: bool, signed: bool) -> Result<(), Diagnostic> {
        let divisor_zero = self.next_label("div_u24_zero");
        let loop_label = self.next_label("div_u24_loop");
        let done = self.next_label("div_u24_done");
        let positive_left = self.next_label("div_u24_left_positive");
        let positive_right = self.next_label("div_u24_right_positive");
        let positive_result = self.next_label("div_u24_result_positive");
        self.line("    moveq #0,d5");
        if signed {
            self.line("    tst.l d0");
            self.line(&format!("    bpl {positive_left}"));
            self.line("    neg.l d0");
            self.line("    moveq #1,d5");
            self.line(&format!("{positive_left}:"));
            self.line("    tst.l d2");
            self.line(&format!("    bpl {positive_right}"));
            self.line("    neg.l d2");
            self.line("    eori.b #1,d5");
            self.line(&format!("{positive_right}:"));
        }
        self.line("    tst.l d2");
        self.line(&format!("    beq {divisor_zero}"));
        self.line("    moveq #0,d1");
        self.line(&format!("{loop_label}:"));
        self.line("    cmp.l d2,d0");
        self.line(&format!("    bcs {done}"));
        self.line("    sub.l d2,d0");
        self.line("    addq.l #1,d1");
        self.line(&format!("    bra {loop_label}"));
        self.line(&format!("{divisor_zero}:"));
        self.line("    moveq #0,d0");
        self.line(&format!("    bra {done}"));
        self.line(&format!("{done}:"));
        if !remainder {
            self.line("    move.l d1,d0");
        }
        if signed {
            self.line("    tst.b d5");
            self.line(&format!("    beq {positive_result}"));
            self.line("    neg.l d0");
            self.line(&format!("{positive_result}:"));
        }
        self.normalize_d0(&Type::Named(if signed { "i24" } else { "u24" }.to_owned()))
    }

    fn emit_logical(&mut self, left: &Expr, op: BinaryOp, right: &Expr) -> Result<(), Diagnostic> {
        let decisive = self.next_label("logical_decisive");
        let done = self.next_label("logical_done");
        let bool_ty = Type::Named("bool".to_owned());
        self.emit_expr(left, &bool_ty)?;
        self.line("    tst.b d0");
        self.line(&format!(
            "    {} {decisive}",
            if op == BinaryOp::And { "beq" } else { "bne" }
        ));
        self.emit_expr(right, &bool_ty)?;
        self.line(&format!("    bra {done}"));
        self.line(&format!("{decisive}:"));
        self.line(&format!(
            "    moveq #{},d0",
            if op == BinaryOp::And { 0 } else { 1 }
        ));
        self.line(&format!("{done}:"));
        Ok(())
    }

    fn emit_call(
        &mut self,
        path: &[String],
        args: &[Expr],
        expected: Option<&Type>,
    ) -> Result<(), Diagnostic> {
        let name = path.join(".");
        match name.as_str() {
            "mem.peek8" | "ezra.mem.peek8" => {
                self.emit_expr(&args[0], &Type::Ptr(Box::new(Type::Named("u8".to_owned()))))?;
                self.line("    move.l d0,a0");
                self.line("    move.b (a0),d0");
                return Ok(());
            }
            "mem.poke8" | "ezra.mem.poke8" => {
                self.emit_expr(&args[0], &Type::Ptr(Box::new(Type::Named("u8".to_owned()))))?;
                self.line("    move.l d0,a0");
                self.emit_expr(&args[1], &Type::Named("u8".to_owned()))?;
                self.line("    move.b d0,(a0)");
                return Ok(());
            }
            "mem.memcpy" | "ezra.mem.memcpy" => {
                self.emit_memcpy(args)?;
                return Ok(());
            }
            "mem.memset" | "ezra.mem.memset" => {
                self.emit_memset(args)?;
                return Ok(());
            }
            _ => {}
        }
        let signature = self
            .model
            .functions
            .get(&name)
            .or_else(|| {
                path.last()
                    .and_then(|short| self.model.functions.get(short))
            })
            .cloned()
            .ok_or_else(|| Diagnostic::new(format!("unknown function `{name}`")))?;
        if signature.params.len() != args.len() {
            return Err(Diagnostic::new(format!(
                "function `{name}` expects {} arguments, got {}",
                signature.params.len(),
                args.len()
            )));
        }
        for ((arg, ty), slot) in args
            .iter()
            .zip(&signature.params)
            .zip(signature.argument_slots)
        {
            let ty = self.model.resolved_type(ty)?;
            self.emit_expr(arg, &ty)?;
            self.store_d0(slot, &ty)?;
        }
        let saved = self.function_ram_bases.last().map(|base| Storage {
            address: *base,
            size: self.model.next_ram_address() - *base,
        });
        if let Some(saved) = saved {
            for offset in 0..saved.size {
                self.line(&format!("    move.b ${:06X},-(sp)", saved.address + offset));
            }
        }
        self.line(&format!("    jsr {}", function_label(&name)));
        if let Some(saved) = saved {
            self.line("    move.l d0,d6");
            for offset in (0..saved.size).rev() {
                self.line(&format!("    move.b (sp)+,${:06X}", saved.address + offset));
            }
            self.line("    move.l d6,d0");
        }
        if let Some(expected) = expected {
            if signature.return_type.is_none() {
                self.line("    moveq #0,d0");
            } else {
                self.require_scalar(expected)?;
            }
        }
        Ok(())
    }

    fn emit_memcpy(&mut self, args: &[Expr]) -> Result<(), Diagnostic> {
        if args.len() != 3 {
            return Err(Diagnostic::new("mem.memcpy requires three arguments"));
        }
        let pointer = Type::Ptr(Box::new(Type::Named("u8".to_owned())));
        self.emit_expr(&args[0], &pointer)?;
        self.line("    move.l d0,a0");
        self.emit_expr(&args[1], &pointer)?;
        self.line("    move.l d0,a1");
        self.emit_expr(&args[2], &Type::Named("u24".to_owned()))?;
        self.line("    move.l d0,d2");
        let loop_label = self.next_label("memcpy_loop");
        let done = self.next_label("memcpy_done");
        self.line(&format!("{loop_label}:"));
        self.line("    tst.l d2");
        self.line(&format!("    beq {done}"));
        self.line("    move.b (a1)+,d0");
        self.line("    move.b d0,(a0)+");
        self.line("    subq.l #1,d2");
        self.line(&format!("    bra {loop_label}"));
        self.line(&format!("{done}:"));
        self.line("    moveq #0,d0");
        Ok(())
    }

    fn emit_memset(&mut self, args: &[Expr]) -> Result<(), Diagnostic> {
        if args.len() != 3 {
            return Err(Diagnostic::new("mem.memset requires three arguments"));
        }
        let pointer = Type::Ptr(Box::new(Type::Named("u8".to_owned())));
        self.emit_expr(&args[0], &pointer)?;
        self.line("    move.l d0,a0");
        self.emit_expr(&args[1], &Type::Named("u8".to_owned()))?;
        self.line("    move.b d0,d1");
        self.emit_expr(&args[2], &Type::Named("u24".to_owned()))?;
        self.line("    move.l d0,d2");
        let loop_label = self.next_label("memset_loop");
        let done = self.next_label("memset_done");
        self.line(&format!("{loop_label}:"));
        self.line("    tst.l d2");
        self.line(&format!("    beq {done}"));
        self.line("    move.b d1,(a0)+");
        self.line("    subq.l #1,d2");
        self.line(&format!("    bra {loop_label}"));
        self.line(&format!("{done}:"));
        self.line("    moveq #0,d0");
        Ok(())
    }

    fn load_place(&mut self, place: &Place, ty: &Type) -> Result<(), Diagnostic> {
        match place {
            Place::Ident(name) => self.load_d0(self.binding(name)?.storage, ty),
            Place::Index { name, index } => {
                self.emit_named_index_address(name, index)?;
                self.load_from_a0(ty)
            }
            Place::Field { base, field } => {
                let binding = self.binding(base)?;
                let field = self.model.field(&binding.ty, field)?.clone();
                self.load_d0(
                    Storage {
                        address: binding.storage.address + field.offset,
                        size: field.size,
                    },
                    ty,
                )
            }
            Place::Access(path) => {
                self.emit_access_address(path)?;
                self.load_from_a0(ty)
            }
            Place::Deref(expr) => {
                let pointer_ty = self.expr_type(expr)?;
                self.emit_expr(expr, &pointer_ty)?;
                self.line("    move.l d0,a0");
                self.line(&format!("    move.{} (a0),d0", size_suffix(ty)?));
                Ok(())
            }
        }
    }

    fn store_place(&mut self, place: &Place, ty: &Type) -> Result<(), Diagnostic> {
        match place {
            Place::Ident(name) => self.store_d0(self.binding(name)?.storage, ty),
            Place::Index { name, index } => {
                self.line(&format!("    move.{} d0,d3", size_suffix(ty)?));
                self.emit_named_index_address(name, index)?;
                self.line(&format!("    move.{} d3,d0", size_suffix(ty)?));
                self.store_to_a0(ty)
            }
            Place::Field { base, field } => {
                let binding = self.binding(base)?;
                let field = self.model.field(&binding.ty, field)?.clone();
                self.store_d0(
                    Storage {
                        address: binding.storage.address + field.offset,
                        size: field.size,
                    },
                    ty,
                )
            }
            Place::Access(path) => {
                self.line(&format!("    move.{} d0,d3", size_suffix(ty)?));
                self.emit_access_address(path)?;
                self.line(&format!("    move.{} d3,d0", size_suffix(ty)?));
                self.store_to_a0(ty)
            }
            Place::Deref(expr) => {
                self.line(&format!("    move.{} d0,d3", size_suffix(ty)?));
                let pointer_ty = self.expr_type(expr)?;
                self.emit_expr(expr, &pointer_ty)?;
                self.line("    move.l d0,a0");
                self.line(&format!("    move.{} d3,(a0)", size_suffix(ty)?));
                Ok(())
            }
        }
    }

    fn store_aggregate_place(
        &mut self,
        place: &Place,
        source: Storage,
        size: u32,
    ) -> Result<(), Diagnostic> {
        match place {
            Place::Ident(name) => {
                let destination = self.binding(name)?;
                self.copy(source, destination.storage, size);
            }
            Place::Index { name, index } => {
                self.emit_named_index_address(name, index)?;
                self.copy_to_a0(source, size);
            }
            Place::Field { base, field } => {
                let binding = self.binding(base)?;
                let field = self.model.field(&binding.ty, field)?;
                self.copy(
                    source,
                    Storage {
                        address: binding.storage.address + field.offset,
                        size,
                    },
                    size,
                );
            }
            Place::Access(path) => {
                self.emit_access_address(path)?;
                self.copy_to_a0(source, size);
            }
            Place::Deref(expr) => {
                let pointer_ty = self.expr_type(expr)?;
                self.emit_expr(expr, &pointer_ty)?;
                self.line("    move.l d0,a0");
                self.copy_to_a0(source, size);
            }
        }
        Ok(())
    }

    fn place_type(&self, place: &Place) -> Result<Type, Diagnostic> {
        match place {
            Place::Ident(name) => Ok(self.binding(name)?.ty),
            Place::Index { name, .. } => {
                element_type(&self.model.resolved_type(&self.binding(name)?.ty)?)
            }
            Place::Field { base, field } => {
                Ok(self.model.field(&self.binding(base)?.ty, field)?.ty.clone())
            }
            Place::Access(path) => self.access_type(path),
            Place::Deref(expr) => match self.model.resolved_type(&self.expr_type(expr)?)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
        }
    }

    fn emit_named_index_address(&mut self, name: &str, index: &Expr) -> Result<Type, Diagnostic> {
        let binding = self.binding(name)?;
        let resolved = self.model.resolved_type(&binding.ty)?;
        let element = element_type(&resolved)?;
        let element_size = self.model.type_size(&element)?;
        match resolved {
            Type::Array { .. } => {
                self.line(&format!("    move.l #${:06X},a0", binding.storage.address));
            }
            Type::Ptr(_) => {
                self.load_d0(binding.storage, &binding.ty)?;
                self.line("    move.l d0,a0");
            }
            _ => return Err(Diagnostic::new("indexing requires array or pointer")),
        }
        self.add_index_to_a0(index, element_size)?;
        Ok(element)
    }

    fn emit_access_address(&mut self, path: &AccessPath) -> Result<Type, Diagnostic> {
        let binding = self.binding(&path.root)?;
        let mut ty = self.model.resolved_type(&binding.ty)?;
        if let Type::Ptr(inner) = ty {
            self.load_d0(binding.storage, &binding.ty)?;
            self.line("    move.l d0,a0");
            ty = *inner;
        } else {
            self.line(&format!("    move.l #${:06X},a0", binding.storage.address));
        }
        for segment in &path.segments {
            match segment {
                AccessSegment::Field(name) => {
                    let field = self.model.field(&ty, name)?.clone();
                    if field.offset != 0 {
                        self.line(&format!("    lea {}(a0),a0", field.offset));
                    }
                    ty = field.ty;
                }
                AccessSegment::Index(index) => {
                    let element = element_type(&self.model.resolved_type(&ty)?)?;
                    self.add_index_to_a0(index, self.model.type_size(&element)?)?;
                    ty = element;
                }
            }
        }
        Ok(ty)
    }

    fn add_index_to_a0(&mut self, index: &Expr, element_size: u32) -> Result<(), Diagnostic> {
        if let Ok(index) = self.model.const_value(index) {
            let offset = u32::try_from(index)
                .ok()
                .and_then(|index| index.checked_mul(element_size))
                .ok_or_else(|| Diagnostic::new("array index offset overflow"))?;
            if offset != 0 {
                self.line(&format!("    lea {offset}(a0),a0"));
            }
            return Ok(());
        }
        self.emit_expr(index, &Type::Named("u24".to_owned()))?;
        if element_size > 1 {
            self.line(&format!("    mulu #${element_size:X},d0"));
        }
        self.line("    adda.l d0,a0");
        Ok(())
    }

    fn load_from_a0(&mut self, ty: &Type) -> Result<(), Diagnostic> {
        if scalar_width(ty)? == 3 {
            self.line("    moveq #0,d0");
            self.line("    move.b (a0),d0");
            self.line("    lsl.l #8,d0");
            self.line("    move.b 1(a0),d0");
            self.line("    lsl.l #8,d0");
            self.line("    move.b 2(a0),d0");
            self.normalize_d0(ty)?;
        } else {
            self.line(&format!("    move.{} (a0),d0", size_suffix(ty)?));
        }
        Ok(())
    }

    fn store_to_a0(&mut self, ty: &Type) -> Result<(), Diagnostic> {
        if scalar_width(ty)? == 3 {
            self.line("    move.l d0,d1");
            self.line("    lsr.l #8,d1");
            self.line("    lsr.l #8,d1");
            self.line("    move.b d1,(a0)");
            self.line("    move.l d0,d1");
            self.line("    lsr.l #8,d1");
            self.line("    move.b d1,1(a0)");
            self.line("    move.b d0,2(a0)");
        } else {
            self.line(&format!("    move.{} d0,(a0)", size_suffix(ty)?));
        }
        Ok(())
    }

    fn copy(&mut self, source: Storage, target: Storage, size: u32) {
        for offset in 0..size {
            self.line(&format!("    move.b ${:06X},d0", source.address + offset));
            self.line(&format!("    move.b d0,${:06X}", target.address + offset));
        }
    }

    fn zero(&mut self, storage: Storage) {
        self.line("    moveq #0,d0");
        for offset in 0..storage.size {
            self.line(&format!("    move.b d0,${:06X}", storage.address + offset));
        }
    }

    fn copy_from_a0(&mut self, target: Storage, size: u32) {
        for offset in 0..size {
            self.line(&format!("    move.b {offset}(a0),d0"));
            self.line(&format!("    move.b d0,${:06X}", target.address + offset));
        }
    }

    fn copy_to_a0(&mut self, source: Storage, size: u32) {
        for offset in 0..size {
            self.line(&format!("    move.b ${:06X},d0", source.address + offset));
            self.line(&format!("    move.b d0,{offset}(a0)"));
        }
    }

    fn expr_type(&self, expr: &Expr) -> Result<Type, Diagnostic> {
        match expr {
            Expr::Int(value) => Ok(if (0..=0xFF).contains(value) {
                Type::Named("u8".to_owned())
            } else {
                Type::Named("u16".to_owned())
            }),
            Expr::TypedInt(_, ty) | Expr::Cast { ty, .. } => self.model.resolved_type(ty),
            Expr::Bool(_) => Ok(Type::Named("bool".to_owned())),
            Expr::Char(_) | Expr::In(_) => Ok(Type::Named("u8".to_owned())),
            Expr::String(_) => Ok(Type::Ptr(Box::new(Type::Named("u8".to_owned())))),
            Expr::Ident(name) => self
                .model
                .constant_types
                .get(name)
                .cloned()
                .or_else(|| self.binding(name).ok().map(|binding| binding.ty))
                .ok_or_else(|| Diagnostic::new(format!("unknown value `{name}`"))),
            Expr::Index { name, .. } => {
                element_type(&self.model.resolved_type(&self.binding(name)?.ty)?)
            }
            Expr::Field { base, field } => self
                .model
                .constant_types
                .get(&format!("{base}.{field}"))
                .cloned()
                .or_else(|| {
                    self.model
                        .field(&self.binding(base).ok()?.ty, field)
                        .ok()
                        .map(|field| field.ty.clone())
                })
                .ok_or_else(|| Diagnostic::new(format!("unknown field `{field}"))),
            Expr::AddressOfIndex { name, .. } => Ok(Type::Ptr(Box::new(element_type(
                &self.model.resolved_type(&self.binding(name)?.ty)?,
            )?))),
            Expr::AddressOfField { base, field } => Ok(Type::Ptr(Box::new(
                self.model.field(&self.binding(base)?.ty, field)?.ty.clone(),
            ))),
            Expr::Access(path) => self.access_type(path),
            Expr::AddressOfAccess(path) => Ok(Type::Ptr(Box::new(self.access_type(path)?))),
            Expr::AddressOf(name) => Ok(Type::Ptr(Box::new(self.binding(name)?.ty))),
            Expr::StructInit { ty, .. } => Ok(Type::Named(ty.clone())),
            Expr::Call { path, .. } => self
                .model
                .functions
                .get(&path.join("."))
                .or_else(|| path.last().and_then(|name| self.model.functions.get(name)))
                .and_then(|signature| signature.return_type.clone())
                .ok_or_else(|| Diagnostic::new("void function has no value")),
            Expr::Unary {
                op: UnaryOp::Not, ..
            } => Ok(Type::Named("bool".to_owned())),
            Expr::Unary { expr, .. } => self.expr_type(expr),
            Expr::Deref(expr) => match self.model.resolved_type(&self.expr_type(expr)?)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
            Expr::Binary { left, op, .. }
                if is_comparison(*op) || matches!(op, BinaryOp::And | BinaryOp::Or) =>
            {
                Ok(Type::Named("bool".to_owned()))
            }
            Expr::Binary { left, .. } => self.expr_type(left),
            Expr::Array(_) => Err(Diagnostic::new("array type requires context")),
        }
    }

    fn access_type(&self, path: &AccessPath) -> Result<Type, Diagnostic> {
        let mut ty = self.model.resolved_type(&self.binding(&path.root)?.ty)?;
        if let Type::Ptr(inner) = ty {
            ty = *inner;
        }
        for segment in &path.segments {
            ty = match segment {
                AccessSegment::Field(name) => self.model.field(&ty, name)?.ty.clone(),
                AccessSegment::Index(_) => element_type(&self.model.resolved_type(&ty)?)?,
            };
        }
        Ok(ty)
    }

    fn emit_inline_asm(
        &mut self,
        inputs: &[crate::ast::AsmInput],
        outputs: &[crate::ast::AsmOutput],
        lines: &[String],
    ) -> Result<(), Diagnostic> {
        let mut operands = HashMap::new();
        for operand in inputs
            .iter()
            .map(|input| &input.name)
            .chain(outputs.iter().map(|output| &output.name))
        {
            operands.insert(
                operand.clone(),
                format!("${:06X}", self.binding(operand)?.storage.address),
            );
        }
        for line in lines {
            let mut emitted = line.clone();
            for (name, value) in &operands {
                emitted = emitted.replace(&format!("{{{name}}}"), value);
            }
            if emitted.contains(['{', '}']) {
                return Err(Diagnostic::new(format!(
                    "unknown inline asm operand placeholder in `{line}`"
                )));
            }
            self.line(&format!("    {emitted}"));
        }
        Ok(())
    }

    fn boolean_from_test(&mut self, branch: &str, ty: &Type) -> Result<(), Diagnostic> {
        self.line(&format!("    tst.{} d0", size_suffix(ty)?));
        self.boolean_from_branch(branch)
    }

    fn boolean_from_branch(&mut self, branch: &str) -> Result<(), Diagnostic> {
        let yes = self.next_label("true");
        let done = self.next_label("bool_done");
        self.line(&format!("    {branch} {yes}"));
        self.line("    moveq #0,d0");
        self.line(&format!("    bra {done}"));
        self.line(&format!("{yes}:"));
        self.line("    moveq #1,d0");
        self.line(&format!("{done}:"));
        Ok(())
    }

    fn load_constant(&mut self, value: i64, ty: &Type) -> Result<(), Diagnostic> {
        let (size, mask) = match size_suffix(ty)? {
            "b" => ("b", 0xFF),
            "w" => ("w", 0xFFFF),
            "l" => ("l", 0xFF_FFFF),
            _ => unreachable!(),
        };
        self.line(&format!("    move.{size} #${:X},d0", (value as u64) & mask));
        self.normalize_d0(ty)?;
        Ok(())
    }

    fn load_d0(&mut self, storage: Storage, ty: &Type) -> Result<(), Diagnostic> {
        if scalar_width(ty)? == 3 {
            self.line("    moveq #0,d0");
            self.line(&format!("    move.b ${:06X},d0", storage.address));
            self.line("    lsl.l #8,d0");
            self.line(&format!("    move.b ${:06X},d0", storage.address + 1));
            self.line("    lsl.l #8,d0");
            self.line(&format!("    move.b ${:06X},d0", storage.address + 2));
            self.normalize_d0(ty)?;
            return Ok(());
        }
        self.line(&format!(
            "    move.{} ${:06X},d0",
            size_suffix(ty)?,
            storage.address
        ));
        Ok(())
    }

    fn store_d0(&mut self, storage: Storage, ty: &Type) -> Result<(), Diagnostic> {
        if scalar_width(ty)? == 3 {
            self.line("    move.l d0,d1");
            self.line("    lsr.l #8,d1");
            self.line("    lsr.l #8,d1");
            self.line(&format!("    move.b d1,${:06X}", storage.address));
            self.line("    move.l d0,d1");
            self.line("    lsr.l #8,d1");
            self.line(&format!("    move.b d1,${:06X}", storage.address + 1));
            self.line(&format!("    move.b d0,${:06X}", storage.address + 2));
            return Ok(());
        }
        self.line(&format!(
            "    move.{} d0,${:06X}",
            size_suffix(ty)?,
            storage.address
        ));
        Ok(())
    }

    fn require_scalar(&self, ty: &Type) -> Result<(), Diagnostic> {
        size_suffix(ty)
            .map(|_| ())
            .map_err(|_| Diagnostic::new("M68k source backend does not support this scalar type"))
    }

    fn normalize_d0(&mut self, ty: &Type) -> Result<(), Diagnostic> {
        if scalar_width(ty)? != 3 {
            return Ok(());
        }
        self.line("    andi.l #$FFFFFF,d0");
        if type_is_signed(ty) {
            let positive = self.next_label("i24_positive");
            self.line("    move.l d0,d1");
            self.line("    andi.l #$800000,d1");
            self.line(&format!("    beq {positive}"));
            self.line("    ori.l #$FF000000,d0");
            self.line(&format!("{positive}:"));
        }
        Ok(())
    }

    fn bind(&mut self, name: String, storage: Storage, ty: Type) -> Result<(), Diagnostic> {
        if self
            .scopes
            .iter()
            .rev()
            .any(|scope| scope.contains_key(&name))
        {
            return Err(Diagnostic::new(format!(
                "local `{name}` shadows an existing name"
            )));
        }
        let ty = self.model.resolved_type(&ty)?;
        self.scopes
            .last_mut()
            .expect("function scope")
            .insert(name, Binding { storage, ty });
        Ok(())
    }

    fn binding(&self, name: &str) -> Result<Binding, Diagnostic> {
        if let Some(binding) = self.scopes.iter().rev().find_map(|scope| scope.get(name)) {
            return Ok(binding.clone());
        }
        if let Some(storage) = self.model.globals.get(name) {
            return Ok(Binding {
                storage: *storage,
                ty: self.model.resolved_type(&self.model.global_types[name])?,
            });
        }
        if let Some((address, ty, _)) = self.model.mmio.get(name) {
            return Ok(Binding {
                storage: Storage {
                    address: *address,
                    size: self.model.type_size(ty)?,
                },
                ty: ty.clone(),
            });
        }
        Err(Diagnostic::new(format!("unknown variable `{name}`")))
    }

    fn next_label(&mut self, name: &str) -> String {
        let label = format!("__ezra_{}_{}", sanitize(name), self.labels);
        self.labels += 1;
        label
    }

    fn line(&mut self, line: &str) {
        self.out.push_str(line);
        self.out.push('\n');
    }

    fn emit_data_bytes(&mut self, bytes: Vec<u8>) {
        for chunk in bytes.chunks(16) {
            let values = chunk
                .iter()
                .map(|byte| format!("0x{byte:02X}"))
                .collect::<Vec<_>>()
                .join(", ");
            self.line(&format!("    db {values}"));
        }
    }
}

fn expr_call_args(expr: &Expr) -> Result<&[Expr], Diagnostic> {
    match expr {
        Expr::Call { args, .. } => Ok(args),
        _ => Err(Diagnostic::new("expected function call")),
    }
}

fn size_suffix(ty: &Type) -> Result<&'static str, Diagnostic> {
    match ty {
        Type::Named(name) if matches!(name.as_str(), "u8" | "i8" | "bool") => Ok("b"),
        Type::Named(name) if matches!(name.as_str(), "u16" | "i16") => Ok("w"),
        Type::Named(name) if matches!(name.as_str(), "u24" | "i24" | "ptr24") => Ok("l"),
        Type::Ptr(_) => Ok("l"),
        _ => Err(Diagnostic::new("unsupported M68k scalar type")),
    }
}

fn scalar_width(ty: &Type) -> Result<u8, Diagnostic> {
    Ok(match size_suffix(ty)? {
        "b" => 1,
        "w" => 2,
        "l" => 3,
        _ => unreachable!(),
    })
}

fn element_type(ty: &Type) -> Result<Type, Diagnostic> {
    match ty {
        Type::Array { element, .. } | Type::Ptr(element) => Ok((**element).clone()),
        _ => Err(Diagnostic::new("indexing requires array or pointer")),
    }
}

fn type_is_signed(ty: &Type) -> bool {
    matches!(ty, Type::Named(name) if name.starts_with('i'))
}
fn is_comparison(op: BinaryOp) -> bool {
    matches!(
        op,
        BinaryOp::Eq | BinaryOp::Ne | BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge
    )
}
fn comparison_branch(op: BinaryOp, signed: bool) -> &'static str {
    match (op, signed) {
        (BinaryOp::Eq, _) => "beq",
        (BinaryOp::Ne, _) => "bne",
        (BinaryOp::Lt, true) => "blt",
        (BinaryOp::Le, true) => "ble",
        (BinaryOp::Gt, true) => "bgt",
        (BinaryOp::Ge, true) => "bge",
        (BinaryOp::Lt, false) => "bcs",
        (BinaryOp::Le, false) => "bls",
        (BinaryOp::Gt, false) => "bhi",
        (BinaryOp::Ge, false) => "bcc",
        _ => unreachable!(),
    }
}
fn assign_binary(op: AssignOp) -> BinaryOp {
    match op {
        AssignOp::Add => BinaryOp::Add,
        AssignOp::Sub => BinaryOp::Sub,
        AssignOp::Mul => BinaryOp::Mul,
        AssignOp::Div => BinaryOp::Div,
        AssignOp::Mod => BinaryOp::Mod,
        AssignOp::BitAnd => BinaryOp::BitAnd,
        AssignOp::BitOr => BinaryOp::BitOr,
        AssignOp::BitXor => BinaryOp::BitXor,
        AssignOp::Shl => BinaryOp::Shl,
        AssignOp::Shr => BinaryOp::Shr,
        AssignOp::Set => unreachable!(),
    }
}
fn function_label(name: &str) -> String {
    format!("_{}", sanitize(name))
}
fn sanitize(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        asm::AssemblyOptions,
        parser::parse_program,
        target::{AssemblerCpu, CpuFamily},
        vm::assemble_subset_with_symbols_at,
    };
    use std::path::Path;

    #[test]
    fn emits_and_assembles_scalar_control_flow() {
        let program = parse_program(
            Path::new("test.ezra"),
            r#"
            global counter: u16 = 1
            fn add(value: u16) -> u16 { return value + counter }
            fn main() { let result: u16 = add(2); if result == 3 { counter += result } }
        "#,
        )
        .unwrap();
        let assembly = emit_m68k_assembly_with_options(
            &program,
            AssemblyOptions {
                cpu: CpuFamily::M68k,
                ..AssemblyOptions::default()
            },
        )
        .unwrap();
        assert!(assembly.contains("move.l #$F00000,sp"), "{assembly}");
        assert!(assembly.contains("jsr _add"), "{assembly}");
        assemble_subset_with_symbols_at(AssemblerCpu::M68k, &assembly, 0x010040).unwrap();
    }

    #[test]
    fn emits_and_assembles_pointer_aggregate_and_string_operations() {
        let program = parse_program(
            Path::new("test.ezra"),
            r#"
            struct Pair { left: u8 right: u8 }
            global bytes: [u8; 3] = [1, 2, 3]
            global pair: Pair = Pair { left: 4, right: 5 }
            fn main() {
                let pointer: ptr<u8> = &bytes[0]
                *pointer = 9
                let value: u8 = bytes[0] ^ pair.left
                let shifted: u8 = value << 1
                let text: ptr<u8> = "ok"
                let first: u8 = *text
            }
        "#,
        )
        .unwrap();
        let assembly = emit_m68k_assembly_with_options(
            &program,
            AssemblyOptions {
                cpu: CpuFamily::M68k,
                ..AssemblyOptions::default()
            },
        )
        .unwrap();
        assert!(assembly.contains("eor.b d2,d0"), "{assembly}");
        assert!(assembly.contains("lsl.b d2,d0"), "{assembly}");
        assemble_subset_with_symbols_at(AssemblerCpu::M68k, &assembly, 0x010040).unwrap();
    }

    #[test]
    fn emits_and_assembles_u24_arithmetic() {
        let program = parse_program(
            Path::new("test.ezra"),
            r#"
            fn main() {
                let left: u24 = 0x010001
                let right: u24 = 3
                let product: u24 = left * right
                let quotient: u24 = product / right
                let remainder: u24 = product % right
                let signed_left: i24 = -9
                let signed_right: i24 = 2
                let signed_quotient: i24 = signed_left / signed_right
            }
        "#,
        )
        .unwrap();
        let assembly = emit_m68k_assembly_with_options(
            &program,
            AssemblyOptions {
                cpu: CpuFamily::M68k,
                ..AssemblyOptions::default()
            },
        )
        .unwrap();
        assert!(assembly.contains("__ezra_mul_u24_loop"), "{assembly}");
        assert!(assembly.contains("__ezra_div_u24_loop"), "{assembly}");
        assemble_subset_with_symbols_at(AssemblerCpu::M68k, &assembly, 0x010040).unwrap();
    }

    #[test]
    fn emits_and_assembles_memory_helpers() {
        let program = parse_program(
            Path::new("test.ezra"),
            r#"
            global bytes: [u8; 4] = [0, 0, 0, 0]
            fn main() {
                let pointer: ptr<u8> = &bytes[0]
                mem.poke8(pointer, 0x2A)
                let value: u8 = mem.peek8(pointer)
                mem.memset(pointer, 0, 4)
                mem.memcpy(pointer, pointer, 4)
            }
        "#,
        )
        .unwrap();
        let assembly = emit_m68k_assembly_with_options(
            &program,
            AssemblyOptions {
                cpu: CpuFamily::M68k,
                ..AssemblyOptions::default()
            },
        )
        .unwrap();
        assert!(assembly.contains("__ezra_memcpy_loop"), "{assembly}");
        assert!(assembly.contains("__ezra_memset_loop"), "{assembly}");
        assemble_subset_with_symbols_at(AssemblerCpu::M68k, &assembly, 0x010040).unwrap();
    }

    #[test]
    fn preserves_static_locals_across_recursive_calls() {
        let program = parse_program(
            Path::new("test.ezra"),
            r#"
            fn count(value: u8) -> u8 {
                if value == 0 { return 0 }
                let next: u8 = value - 1
                return count(next) + 1
            }
            fn main() { let result: u8 = count(3) }
        "#,
        )
        .unwrap();
        let assembly = emit_m68k_assembly_with_options(
            &program,
            AssemblyOptions {
                cpu: CpuFamily::M68k,
                ..AssemblyOptions::default()
            },
        )
        .unwrap();
        assert!(assembly.contains("move.b $040"), "{assembly}");
        assert!(assembly.contains("-(sp)"), "{assembly}");
        assemble_subset_with_symbols_at(AssemblerCpu::M68k, &assembly, 0x010040).unwrap();
    }
}
