use std::collections::HashMap;

use crate::{
    asm::{
        AssemblyOptions,
        comments::{stmt_summary, with_readability_comments},
        data::{ByteLiteralStyle, byte_data_lines, terminated_text_data_line},
        reachability::{RoutineProfile, strip_unreachable_generated_routines},
    },
    ast::{
        AccessPath, AccessSegment, AssignOp, BinaryOp, Declaration, Expr, Function, Place, Program,
        Stmt, Type, UnaryOp,
    },
    diagnostic::Diagnostic,
    hir::HirProgram,
    regalloc::{
        Location, PhysReg, PhysicalRegister, RegClass, RegUnit, RegisterClass, RegisterUnit,
        SpillClass, SpillClassId, Target,
        source::{SourceLocal, allocate_source_locals},
    },
    target::CpuFamily,
    tbir::{
        TbirProgram,
        model::{SemanticModel, Storage},
    },
};

/// Emit code for the generic 68000 target.
///
/// Values are evaluated in D0, with D1 as the binary-operation scratch
/// register. Arguments live in target-owned static slots, which keeps the
/// first ABI simple while allowing ordinary EZRA calls without a platform SDK.
pub fn emit_m68k_assembly_with_options(
    program: &Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    if options.cpu != CpuFamily::M68k {
        return Err(Diagnostic::new("M68k emitter requires an m68k target"));
    }
    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    let model = SemanticModel::from_program(
        &tbir.lowered_program,
        24,
        options.ram_base.get(),
        options.rodata_base.get(),
        options.asset_base.get(),
    )?;
    Emitter::new(model, options.clone())
        .emit(&tbir.lowered_program)
        .map(|asm| {
            let asm = strip_unreachable_generated_routines(&asm, RoutineProfile::M68k);
            with_readability_comments(asm, program, &options, "m68k", &tbir.source_comments)
        })
}

#[derive(Clone, Copy)]
enum BindingLocation {
    Memory(Storage),
    AddressRegister(u8),
}

#[derive(Clone)]
struct Binding {
    location: BindingLocation,
    ty: Type,
    volatile: bool,
}

impl Binding {
    fn memory(&self) -> Result<Storage, Diagnostic> {
        match self.location {
            BindingLocation::Memory(storage) => Ok(storage),
            BindingLocation::AddressRegister(register) => Err(Diagnostic::new(format!(
                "address-register local in a{register} does not have memory storage"
            ))),
        }
    }
}

#[derive(Clone)]
struct LoopLabels {
    continue_label: String,
    break_label: String,
}

struct Emitter {
    model: SemanticModel,
    options: AssemblyOptions,
    out: String,
    labels: usize,
    scopes: Vec<HashMap<String, Binding>>,
    loops: Vec<LoopLabels>,
    return_labels: Vec<String>,
    return_types: Vec<Option<Type>>,
    function_ram_bases: Vec<u32>,
    local_plans: Vec<HashMap<String, Binding>>,
}

impl Emitter {
    fn new(model: SemanticModel, options: AssemblyOptions) -> Self {
        Self {
            model,
            options,
            out: String::new(),
            labels: 0,
            scopes: Vec::new(),
            loops: Vec::new(),
            return_labels: Vec::new(),
            return_types: Vec::new(),
            function_ram_bases: Vec::new(),
            local_plans: Vec::new(),
        }
    }

    fn emit(mut self, program: &Program) -> Result<String, Diagnostic> {
        self.line("; generated by ezrac");
        self.line("; target: Motorola 68000");
        self.line("section .text");
        self.line("__ezra_start:");
        self.line(&format!(
            "    move.l #${:06X},sp",
            self.options.stack_top.get()
        ));
        self.emit_static_initializers(program)?;
        self.line("    jsr _main");
        self.line("__ezra_exit:");
        self.line("    bra __ezra_exit");
        for declaration in &program.declarations {
            if let Declaration::Function(function) = declaration {
                self.emit_function(function)?;
            }
        }
        let mut strings = self
            .model
            .strings
            .iter()
            .map(|(value, storage)| (storage.address, value.clone()))
            .collect::<Vec<_>>();
        strings.sort_by_key(|(address, _)| *address);
        if !strings.is_empty() {
            self.line("section .rodata");
            for (_, value) in strings {
                self.emit_text_data(&value);
            }
        }
        let mut embeds = self.model.embeds.values().cloned().collect::<Vec<_>>();
        embeds.sort_by_key(|embed| embed.storage.address);
        if !embeds.is_empty() {
            self.line("section .assets");
            for embed in embeds {
                self.emit_data_bytes(embed.bytes);
            }
        }
        Ok(self.out)
    }

    fn emit_static_initializers(&mut self, program: &Program) -> Result<(), Diagnostic> {
        for declaration in &program.declarations {
            let Declaration::Global(global) = declaration else {
                continue;
            };
            let storage = self.model.globals[&global.name];
            let ty = self.model.resolved_type(&global.ty)?;
            self.emit_initializer(storage, &ty, &global.value)?;
        }
        Ok(())
    }

    fn emit_function(&mut self, function: &Function) -> Result<(), Diagnostic> {
        let naked = function.attrs.iter().any(|attr| attr == "naked");
        let interrupt = function.attrs.iter().any(|attr| attr == "interrupt");
        if naked
            && function.body.iter().any(|stmt| {
                !matches!(stmt, Stmt::Asm { inputs, outputs, .. } if inputs.is_empty() && outputs.is_empty())
            })
        {
            return Err(Diagnostic::new(format!(
                "naked function `{}` may contain only asm blocks without operands",
                function.name
            )));
        }
        if interrupt && (!function.params.is_empty() || function.return_type.is_some()) {
            return Err(Diagnostic::new(format!(
                "interrupt function `{}` cannot have parameters or a return value",
                function.name
            )));
        }
        let function_ram_base = self.model.next_ram_address();
        let local_plan = plan_function_locals(function, &mut self.model)?;
        let return_label = self.next_label(&format!("{}_return", function.name));
        self.line(&format!("{}:", function_label(&function.name)));
        self.scopes.push(HashMap::new());
        self.return_labels.push(return_label.clone());
        self.function_ram_bases.push(function_ram_base);
        self.local_plans.push(local_plan);
        self.return_types.push(
            function
                .return_type
                .as_ref()
                .map(|ty| self.model.resolved_type(ty))
                .transpose()?,
        );
        let signature = self.model.functions[&function.name].clone();
        if interrupt && !naked {
            for register in (0..8)
                .map(|index| format!("d{index}"))
                .chain((0..7).map(|index| format!("a{index}")))
            {
                self.line(&format!("    move.l {register},-(sp)"));
            }
        }
        for (param, slot) in function.params.iter().zip(signature.argument_slots) {
            let ty = self.model.resolved_type(&param.ty)?;
            let storage = self.model.allocate_type(&ty)?;
            self.bind_memory(param.name.clone(), storage, ty.clone())?;
            if self.model.type_width(&ty).is_ok() {
                self.load_d0(slot, &ty)?;
                self.store_d0(storage, &ty)?;
            } else {
                self.copy(slot, storage, storage.size);
            }
        }
        self.emit_block(&function.body)?;
        self.line(&format!("{return_label}:"));
        if interrupt {
            if !naked {
                for register in (0..7)
                    .rev()
                    .map(|index| format!("a{index}"))
                    .chain((0..8).rev().map(|index| format!("d{index}")))
                {
                    self.line(&format!("    move.l (sp)+,{register}"));
                }
            }
            self.line("    rte");
        } else if !naked {
            self.line("    rts");
        }
        self.return_types.pop();
        self.return_labels.pop();
        self.function_ram_bases.pop();
        self.local_plans.pop();
        self.scopes.pop();
        Ok(())
    }

    fn emit_block(&mut self, body: &[Stmt]) -> Result<(), Diagnostic> {
        for stmt in body {
            self.emit_stmt(stmt)?;
        }
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<(), Diagnostic> {
        self.line(&format!("    ; source: {}", stmt_summary(stmt)));
        match stmt {
            Stmt::Let { name, ty, value } => {
                let ty = self.model.resolved_type(ty)?;
                let binding = self
                    .local_plans
                    .last()
                    .and_then(|locals| locals.get(name))
                    .cloned()
                    .ok_or_else(|| {
                        Diagnostic::new(format!("missing allocation for local `{name}`"))
                    })?;
                self.bind(name.clone(), binding.clone())?;
                match binding.location {
                    BindingLocation::Memory(storage) => {
                        self.emit_initializer(storage, &ty, value)?
                    }
                    BindingLocation::AddressRegister(register) => {
                        debug_assert!(matches!(ty, Type::Ptr(_)));
                        self.emit_expr(value, &ty)?;
                        self.line(&format!("    move.l d0,a{register}"));
                    }
                }
            }
            Stmt::Assign { target, op, value } => {
                let ty = self.place_type(target)?;
                if self.model.type_width(&ty).is_err() {
                    if *op != AssignOp::Set {
                        return Err(Diagnostic::new(
                            "compound assignment requires a scalar value",
                        ));
                    }
                    let storage = self.model.allocate_type(&ty)?;
                    self.emit_initializer(storage, &ty, value)?;
                    self.store_aggregate_place(target, storage, storage.size)?;
                    return Ok(());
                }
                if matches!(op, AssignOp::Shl | AssignOp::Shr)
                    && let Some(count) = self.constant_shift_count(value)
                    && self.emit_memory_shift_assignment(target, &ty, *op, count)?
                {
                    return Ok(());
                }
                if *op == AssignOp::Set {
                    self.emit_expr(value, &ty)?;
                } else if self.emit_local_single_bit_compound_assignment(target, &ty, *op, value)? {
                    return Ok(());
                } else {
                    self.load_place(target, &ty)?;
                    self.line(&format!("    move.{} d0,d1", size_suffix(&ty)?));
                    self.emit_expr(value, &ty)?;
                    self.line(&format!("    move.{} d0,d2", size_suffix(&ty)?));
                    self.line(&format!("    move.{} d1,d0", size_suffix(&ty)?));
                    self.emit_binary(assign_binary(*op), &ty)?;
                }
                self.store_place(target, &ty)?;
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                let otherwise = self.next_label("if_else");
                let done = self.next_label("if_end");
                let false_label = if else_body.is_empty() {
                    &done
                } else {
                    &otherwise
                };
                if !self.emit_jump_if_false(condition, false_label)? {
                    self.emit_expr(condition, &Type::Named("bool".to_owned()))?;
                    self.line("    tst.b d0");
                    self.line(&format!("    beq {false_label}"));
                }
                self.emit_block(then_body)?;
                self.line(&format!("    bra {done}"));
                self.line(&format!("{otherwise}:"));
                self.emit_block(else_body)?;
                self.line(&format!("{done}:"));
            }
            Stmt::While { condition, body } => {
                let check = self.next_label("while_check");
                let done = self.next_label("while_end");
                self.loops.push(LoopLabels {
                    continue_label: check.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{check}:"));
                if !self.emit_jump_if_false(condition, &done)? {
                    self.emit_expr(condition, &Type::Named("bool".to_owned()))?;
                    self.line("    tst.b d0");
                    self.line(&format!("    beq {done}"));
                }
                self.emit_block(body)?;
                self.line(&format!("    bra {check}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Loop { body } => {
                let again = self.next_label("loop");
                let done = self.next_label("loop_end");
                self.loops.push(LoopLabels {
                    continue_label: again.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{again}:"));
                self.emit_block(body)?;
                self.line(&format!("    bra {again}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Break => self.jump_loop(false)?,
            Stmt::Continue => self.jump_loop(true)?,
            Stmt::Return(value) => {
                if let Some(value) = value {
                    let ty = self
                        .return_types
                        .last()
                        .and_then(Clone::clone)
                        .ok_or_else(|| Diagnostic::new("value return in void function"))?;
                    self.emit_expr(value, &ty)?;
                }
                let label = self
                    .return_labels
                    .last()
                    .expect("function return label")
                    .clone();
                self.line(&format!("    bra {label}"));
            }
            Stmt::Asm {
                inputs,
                outputs,
                lines,
                ..
            } => self.emit_inline_asm(inputs, outputs, lines)?,
            Stmt::Out { port, .. } => {
                return Err(Diagnostic::new(format!(
                    "M68k does not support separate port I/O `{port}`; use mmio instead"
                )));
            }
            Stmt::Expr(expr) => {
                if let Expr::Call { path, .. } = expr {
                    self.emit_call(path, expr_call_args(expr)?, None)?;
                } else {
                    let ty = self.expr_type(expr)?;
                    self.emit_expr(expr, &ty)?;
                }
            }
        }
        Ok(())
    }

    fn emit_initializer(
        &mut self,
        storage: Storage,
        ty: &Type,
        value: &Expr,
    ) -> Result<(), Diagnostic> {
        let resolved = self.model.resolved_type(ty)?;
        match (resolved, value) {
            (Type::Array { .. }, Expr::Ident(name)) => {
                let source = self.binding(name)?;
                self.copy(source.memory()?, storage, storage.size);
            }
            (Type::Array { element, len }, Expr::Array(values)) => {
                let element_size = self.model.type_size(&element)?;
                let len = u32::try_from(self.model.const_value(&len)?)
                    .map_err(|_| Diagnostic::new("invalid array length"))?;
                for index in 0..len {
                    let element_storage = Storage {
                        address: storage.address + index * element_size,
                        size: element_size,
                    };
                    if let Some(value) = values.get(index as usize) {
                        self.emit_initializer(element_storage, &element, value)?;
                    } else {
                        self.zero(element_storage);
                    }
                }
            }
            (Type::Named(name), Expr::StructInit { fields, .. })
                if self.model.structs.contains_key(&name) =>
            {
                self.zero(storage);
                let layout = self.model.structs[&name].clone();
                for (field_name, value) in fields {
                    let field = layout
                        .fields
                        .get(field_name)
                        .ok_or_else(|| Diagnostic::new(format!("unknown field `{field_name}`")))?;
                    self.emit_initializer(
                        Storage {
                            address: storage.address + field.offset,
                            size: field.size,
                        },
                        &field.ty,
                        value,
                    )?;
                }
            }
            (Type::Named(name), Expr::Ident(source)) if self.model.structs.contains_key(&name) => {
                let source = self.binding(source)?;
                self.copy(source.memory()?, storage, storage.size);
            }
            (resolved @ (Type::Array { .. } | Type::Named(_)), Expr::Deref(pointer)) => {
                self.emit_expr(pointer, &Type::Ptr(Box::new(resolved)))?;
                self.line("    move.l d0,a0");
                self.copy_from_a0(storage, storage.size);
            }
            (_, value) => {
                self.emit_expr(value, ty)?;
                self.store_d0(storage, ty)?;
            }
        }
        Ok(())
    }

    fn jump_loop(&mut self, continue_loop: bool) -> Result<(), Diagnostic> {
        let labels = self
            .loops
            .last()
            .ok_or_else(|| {
                Diagnostic::new(if continue_loop {
                    "continue outside loop"
                } else {
                    "break outside loop"
                })
            })?
            .clone();
        self.line(&format!(
            "    bra {}",
            if continue_loop {
                labels.continue_label
            } else {
                labels.break_label
            }
        ));
        Ok(())
    }

    fn emit_memory_shift_assignment(
        &mut self,
        target: &Place,
        ty: &Type,
        op: AssignOp,
        count: u32,
    ) -> Result<bool, Diagnostic> {
        let Place::Ident(name) = target else {
            return Ok(false);
        };
        let binding = self.binding(name)?;
        if binding.volatile || scalar_width(ty)? != 2 || !should_use_memory_shift(count) {
            return Ok(false);
        }
        let instruction = match (op, type_is_signed(ty)) {
            (AssignOp::Shl, _) => "lsl",
            (AssignOp::Shr, true) => "asr",
            (AssignOp::Shr, false) => "lsr",
            _ => return Ok(false),
        };
        self.line(&format!(
            "    {instruction} ${:06X}",
            binding.memory()?.address
        ));
        Ok(true)
    }

    fn emit_local_single_bit_compound_assignment(
        &mut self,
        target: &Place,
        ty: &Type,
        op: AssignOp,
        value: &Expr,
    ) -> Result<bool, Diagnostic> {
        let Place::Ident(name) = target else {
            return Ok(false);
        };
        let Some(binding) = self
            .scopes
            .iter()
            .rev()
            .find_map(|scope| scope.get(name))
            .cloned()
        else {
            return Ok(false);
        };
        let ty = self.model.resolved_type(ty)?;
        if !matches!(ty, Type::Named(ref name) if matches!(name.as_str(), "u8" | "u16" | "u24" | "u32"))
        {
            return Ok(false);
        }
        let Ok(mask) = self.model.const_value(value) else {
            return Ok(false);
        };
        let width = scalar_width(&ty)?;
        let width_mask = (1_u64 << (u32::from(width) * 8)) - 1;
        let mask = (mask as u64) & width_mask;
        let bit_mask = match op {
            AssignOp::BitOr | AssignOp::BitXor if mask.is_power_of_two() => mask,
            AssignOp::BitAnd if (!mask & width_mask).is_power_of_two() => !mask & width_mask,
            _ => return Ok(false),
        };
        let bit = bit_mask.trailing_zeros();
        let byte_offset = u32::from(width - 1) - bit / 8;
        let instruction = match op {
            AssignOp::BitOr => "bset",
            AssignOp::BitAnd => "bclr",
            AssignOp::BitXor => "bchg",
            _ => unreachable!(),
        };
        self.line(&format!(
            "    {instruction} #{},${:06X}",
            bit % 8,
            binding.memory()?.address + byte_offset
        ));
        Ok(true)
    }

    fn emit_jump_if_false(
        &mut self,
        condition: &Expr,
        false_label: &str,
    ) -> Result<bool, Diagnostic> {
        let Expr::Binary { left, op, right } = condition else {
            return Ok(false);
        };
        if !matches!(op, BinaryOp::Eq | BinaryOp::Ne) {
            return Ok(false);
        }
        let Expr::Binary {
            left: source,
            op: BinaryOp::BitAnd,
            right: mask_expr,
        } = left.as_ref()
        else {
            return Ok(false);
        };
        let (Ok(mask), Ok(expected)) = (
            self.model.const_value(mask_expr),
            self.model.const_value(right),
        ) else {
            return Ok(false);
        };
        let source_ty = self.model.resolved_type(&self.expr_type(source)?)?;
        let width = scalar_width(&source_ty)?;
        let width_mask = (1_u64 << (u32::from(width) * 8)) - 1;
        let Ok(mask) = u64::try_from(mask) else {
            return Ok(false);
        };
        let Ok(expected) = u64::try_from(expected) else {
            return Ok(false);
        };
        if mask == 0
            || mask > width_mask
            || expected > width_mask
            || (expected != 0 && expected != mask)
        {
            return Ok(false);
        }

        self.emit_expr(source, &source_ty)?;
        let branch = if (*op == BinaryOp::Eq) == (expected == 0) {
            "bne"
        } else {
            "beq"
        };
        if mask.is_power_of_two() {
            let bit = mask.trailing_zeros();
            self.line(&format!("    btst #{bit},d0"));
        } else {
            let size = size_suffix(&source_ty)?;
            self.line(&format!("    andi.{size} #${mask:X},d0"));
            if expected == mask {
                self.line(&format!("    cmpi.{size} #${mask:X},d0"));
            }
        }
        self.line(&format!("    {branch} {false_label}"));
        Ok(true)
    }

    fn emit_expr(&mut self, expr: &Expr, expected: &Type) -> Result<(), Diagnostic> {
        self.require_scalar(expected)?;
        if self.emit_byte_swap_combine(expr, expected)? {
            return Ok(());
        }
        if self.emit_rotate_combine(expr, expected)? {
            return Ok(());
        }
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => self.load_constant(*value, expected)?,
            Expr::Bool(value) => self.load_constant(i64::from(*value), expected)?,
            Expr::Char(value) => self.load_constant(i64::from(*value), expected)?,
            Expr::String(value) => {
                let storage = self.model.intern_string(value)?;
                self.load_constant(i64::from(storage.address), expected)?;
            }
            Expr::Ident(name) => {
                if let Some(value) = self.model.constants.get(name).copied() {
                    self.load_constant(value, expected)?;
                } else {
                    let binding = self.binding(name)?;
                    let source_ty = binding.ty.clone();
                    self.load_binding_d0(&binding)?;
                    self.convert_d0(&source_ty, expected)?;
                }
            }
            Expr::Field { base, field } => {
                let constant = format!("{base}.{field}");
                if let Some(value) = self.model.constants.get(&constant).copied() {
                    self.load_constant(value, expected)?;
                } else {
                    let binding = self.binding(base)?;
                    let field = self.model.field(&binding.ty, field)?.clone();
                    self.load_d0(
                        Storage {
                            address: binding.memory()?.address + field.offset,
                            size: field.size,
                        },
                        &field.ty,
                    )?;
                    self.convert_d0(&field.ty, expected)?;
                }
            }
            Expr::Index { name, index } => {
                let element = self.emit_named_index_address(name, index)?;
                self.load_from_a0(&element)?;
                self.convert_d0(&element, expected)?;
            }
            Expr::Access(path) => {
                let ty = self.emit_access_address(path)?;
                self.load_from_a0(&ty)?;
                self.convert_d0(&ty, expected)?;
            }
            Expr::AddressOf(name) => {
                let binding = self.binding(name)?;
                self.load_constant(i64::from(binding.memory()?.address), expected)?;
            }
            Expr::AddressOfIndex { name, index } => {
                self.emit_named_index_address(name, index)?;
                self.line("    move.l a0,d0");
            }
            Expr::AddressOfField { base, field } => {
                let binding = self.binding(base)?;
                let field = self.model.field(&binding.ty, field)?;
                self.load_constant(
                    i64::from(binding.memory()?.address + field.offset),
                    expected,
                )?;
            }
            Expr::AddressOfAccess(path) => {
                self.emit_access_address(path)?;
                self.line("    move.l a0,d0");
            }
            Expr::Call { path, args } => self.emit_call(path, args, Some(expected))?,
            Expr::Unary { op, expr } => {
                self.emit_expr(expr, expected)?;
                match op {
                    UnaryOp::Neg => self.line(&format!("    neg.{} d0", size_suffix(expected)?)),
                    UnaryOp::BitNot => self.line(&format!("    not.{} d0", size_suffix(expected)?)),
                    UnaryOp::Not => self.boolean_from_test("beq", expected)?,
                }
            }
            Expr::Binary { left, op, right } => {
                if matches!(op, BinaryOp::And | BinaryOp::Or) {
                    self.emit_logical(left, *op, right)?;
                    return Ok(());
                }
                let operand_ty = if is_comparison(*op) {
                    self.expr_type(left)?
                } else {
                    expected.clone()
                };
                self.emit_expr(left, &operand_ty)?;
                if matches!(op, BinaryOp::Shl | BinaryOp::Shr)
                    && let Some(count) = self.constant_shift_count(right)
                {
                    self.emit_constant_shift(*op, &operand_ty, count)?;
                    return Ok(());
                }
                self.line("    move.l d0,-(sp)");
                self.emit_expr(right, &operand_ty)?;
                self.line(&format!("    move.{} d0,d2", size_suffix(&operand_ty)?));
                if matches!(op, BinaryOp::Add | BinaryOp::Sub)
                    && let Type::Ptr(element) = self.model.resolved_type(&operand_ty)?
                {
                    let size = self.model.type_size(&element)?;
                    if size > 1 {
                        self.line(&format!("    mulu #${size:X},d2"));
                    }
                }
                self.line("    move.l (sp)+,d0");
                self.emit_binary(*op, &operand_ty)?;
            }
            Expr::Cast { ty, expr } => {
                let ty = self.model.resolved_type(ty)?;
                let source_ty = self.model.resolved_type(&self.expr_type(expr)?)?;
                self.require_scalar(&source_ty)?;
                self.require_scalar(&ty)?;
                self.emit_expr(expr, &source_ty)?;
                self.convert_d0(&source_ty, &ty)?;
            }
            Expr::BankedPointer { pointer, .. } => self.emit_expr(pointer, expected)?,
            Expr::Deref(pointer) => {
                let pointer_ty = self.expr_type(pointer)?;
                let Type::Ptr(inner) = self.model.resolved_type(&pointer_ty)? else {
                    return Err(Diagnostic::new("dereference requires pointer"));
                };
                self.require_scalar(&inner)?;
                self.emit_expr(pointer, &pointer_ty)?;
                self.line("    move.l d0,a0");
                self.load_from_a0(&inner)?;
                self.convert_d0(&inner, expected)?;
            }
            Expr::In(port) => {
                return Err(Diagnostic::new(format!(
                    "M68k does not support separate port I/O `{port}`; use mmio instead"
                )));
            }
            Expr::Array(_) | Expr::StructInit { .. } => {
                return Err(Diagnostic::new(
                    "aggregate value requires a storage context",
                ));
            }
        }
        Ok(())
    }

    fn constant_shift_count(&self, expr: &Expr) -> Option<u32> {
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => u32::try_from(*value).ok(),
            Expr::Ident(name) => self
                .model
                .constants
                .get(name)
                .and_then(|value| u32::try_from(*value).ok()),
            Expr::Cast { expr, .. } => self.constant_shift_count(expr),
            _ => None,
        }
    }

    fn emit_rotate_combine(&mut self, expr: &Expr, expected: &Type) -> Result<bool, Diagnostic> {
        let expected = self.model.resolved_type(expected)?;
        let width = scalar_width(&expected)?;
        if !matches!(width, 1 | 2 | 4) {
            return Ok(false);
        }
        let bits = u32::from(width) * 8;
        let Some((source, left_count)) =
            match_rotate(expr, bits, |value| self.constant_shift_count(value))
        else {
            return Ok(false);
        };
        if !self.can_reuse_without_memory_effects(source) {
            return Ok(false);
        }
        let source_ty = self.model.resolved_type(&self.expr_type(source)?)?;
        if scalar_width(&source_ty)? != width {
            return Ok(false);
        }

        self.emit_expr(source, &source_ty)?;
        if width == 4 && left_count == 16 {
            self.line("    swap d0");
        } else {
            let right_count = bits - left_count;
            let (instruction, mut count) = if left_count <= right_count {
                ("rol", left_count)
            } else {
                ("ror", right_count)
            };
            let suffix = size_suffix(&source_ty)?;
            while count > 8 {
                self.line(&format!("    {instruction}.{suffix} #8,d0"));
                count -= 8;
            }
            if count != 0 {
                self.line(&format!("    {instruction}.{suffix} #{count},d0"));
            }
        }
        self.convert_d0(&source_ty, &expected)?;
        Ok(true)
    }

    fn emit_byte_swap_combine(&mut self, expr: &Expr, expected: &Type) -> Result<bool, Diagnostic> {
        let expected = self.model.resolved_type(expected)?;
        let width = scalar_width(&expected)?;
        if !matches!(width, 2 | 4) {
            return Ok(false);
        }
        let mut terms = Vec::new();
        flatten_bit_or(expr, &mut terms);
        let source = if width == 2 {
            match_u16_byte_swap(&terms, |value| self.constant_shift_count(value))
        } else {
            match_u32_byte_swap(&terms, |value| self.constant_shift_count(value))
        };
        let Some(source) = source else {
            return Ok(false);
        };
        if !self.can_reuse_without_memory_effects(source) {
            return Ok(false);
        }
        let source_ty = self.model.resolved_type(&self.expr_type(source)?)?;
        if scalar_width(&source_ty)? != width {
            return Ok(false);
        }
        self.emit_expr(source, &source_ty)?;
        if width == 2 {
            self.line("    ror.w #8,d0");
        } else {
            self.line("    ror.w #8,d0");
            self.line("    swap d0");
            self.line("    ror.w #8,d0");
        }
        self.convert_d0(&source_ty, &expected)?;
        Ok(true)
    }

    fn can_reuse_without_memory_effects(&self, expr: &Expr) -> bool {
        match expr {
            Expr::Int(_)
            | Expr::TypedInt(_, _)
            | Expr::Bool(_)
            | Expr::Char(_)
            | Expr::String(_)
            | Expr::AddressOf(_)
            | Expr::AddressOfIndex { .. }
            | Expr::AddressOfField { .. }
            | Expr::AddressOfAccess(_) => true,
            Expr::Ident(name) => !self.model.mmio.contains_key(name),
            Expr::Unary { expr, .. }
            | Expr::BankedPointer { pointer: expr, .. }
            | Expr::Cast { expr, .. } => self.can_reuse_without_memory_effects(expr),
            Expr::Binary { left, right, .. } => {
                self.can_reuse_without_memory_effects(left)
                    && self.can_reuse_without_memory_effects(right)
            }
            Expr::Field { .. }
            | Expr::Index { .. }
            | Expr::Access(_)
            | Expr::Deref(_)
            | Expr::Call { .. }
            | Expr::In(_)
            | Expr::Array(_)
            | Expr::StructInit { .. } => false,
        }
    }

    fn emit_constant_shift(
        &mut self,
        op: BinaryOp,
        ty: &Type,
        count: u32,
    ) -> Result<(), Diagnostic> {
        let width = scalar_width(ty)?;
        let bits = u32::from(width) * 8;
        if count == 0 {
            return Ok(());
        }
        if count >= bits {
            if op == BinaryOp::Shr && type_is_signed(ty) {
                self.extend_signed_to_long(ty)?;
                for _ in 0..width {
                    self.line("    asr.l #8,d0");
                }
            } else {
                self.line("    moveq #0,d0");
            }
            return Ok(());
        }
        if count == 16 && matches!(width, 3 | 4) {
            self.emit_word_boundary_shift(op, ty)?;
            return Ok(());
        }
        let instruction = match op {
            BinaryOp::Shl => "lsl",
            BinaryOp::Shr if type_is_signed(ty) => "asr",
            BinaryOp::Shr => "lsr",
            _ => unreachable!("constant shift called for a non-shift operation"),
        };
        let suffix = size_suffix(ty)?;
        let mut remaining = count;
        while remaining > 8 {
            self.line(&format!("    {instruction}.{suffix} #8,d0"));
            remaining -= 8;
        }
        if remaining != 0 {
            self.line(&format!("    {instruction}.{suffix} #{remaining},d0"));
        }
        self.normalize_d0(ty)?;
        Ok(())
    }

    fn emit_word_boundary_shift(&mut self, op: BinaryOp, ty: &Type) -> Result<(), Diagnostic> {
        let width = scalar_width(ty)?;
        match (op, width, type_is_signed(ty)) {
            (BinaryOp::Shl, 4, _) => {
                self.line("    swap d0");
                self.line("    clr.w d0");
            }
            (BinaryOp::Shl, 3, _) => {
                self.line("    swap d0");
                self.line("    andi.l #$FFFF00,d0");
            }
            (BinaryOp::Shr, 4, true) => {
                self.line("    swap d0");
                self.line("    ext.l d0");
            }
            (BinaryOp::Shr, 4, false) => {
                self.line("    swap d0");
                self.line("    andi.l #$FFFF,d0");
            }
            (BinaryOp::Shr, 3, true) => {
                self.line("    swap d0");
                self.line("    ext.w d0");
                self.line("    ext.l d0");
            }
            (BinaryOp::Shr, 3, false) => {
                self.line("    swap d0");
                self.line("    andi.l #$FF,d0");
            }
            _ => unreachable!("word boundary shift called for an unsupported type"),
        }
        self.normalize_d0(ty)
    }

    fn convert_d0(&mut self, source: &Type, target: &Type) -> Result<(), Diagnostic> {
        let source = self.model.resolved_type(source)?;
        let target = self.model.resolved_type(target)?;
        let source_width = scalar_width(&source)?;
        let target_width = scalar_width(&target)?;
        if source_width == target_width {
            return Ok(());
        }
        if source_width > target_width {
            self.line(&format!("    andi.l #${:X},d0", width_mask(target_width)));
            if target_width == 3 {
                self.normalize_d0(&target)?;
            }
            return Ok(());
        }
        if type_is_signed(&source) {
            match source_width {
                1 => {
                    self.line("    ext.w d0");
                    if target_width >= 3 {
                        self.line("    ext.l d0");
                    }
                }
                2 => {
                    if target_width >= 3 {
                        self.line("    ext.l d0");
                    }
                }
                3 => self.normalize_d0(&source)?,
                _ => unreachable!(),
            }
        } else {
            self.line(&format!("    andi.l #${:X},d0", width_mask(source_width)));
        }
        if target_width == 3 {
            self.normalize_d0(&target)?;
        }
        Ok(())
    }

    fn extend_signed_to_long(&mut self, ty: &Type) -> Result<(), Diagnostic> {
        match scalar_width(ty)? {
            1 => {
                self.line("    ext.w d0");
                self.line("    ext.l d0");
            }
            2 => self.line("    ext.l d0"),
            3 => self.normalize_d0(ty)?,
            4 => {}
            _ => unreachable!(),
        }
        Ok(())
    }

    fn emit_binary(&mut self, op: BinaryOp, ty: &Type) -> Result<(), Diagnostic> {
        let size = size_suffix(ty)?;
        if scalar_width(ty)? >= 3 && matches!(op, BinaryOp::Mul | BinaryOp::Div | BinaryOp::Mod) {
            return if op == BinaryOp::Mul {
                self.emit_wide_multiply(ty)
            } else {
                self.emit_wide_divide(op == BinaryOp::Mod, ty)
            };
        }
        match op {
            BinaryOp::Add => self.line(&format!("    add.{size} d2,d0")),
            BinaryOp::Sub => self.line(&format!("    sub.{size} d2,d0")),
            BinaryOp::BitAnd => self.line(&format!("    and.{size} d2,d0")),
            BinaryOp::BitOr => self.line(&format!("    or.{size} d2,d0")),
            BinaryOp::BitXor => self.line(&format!("    eor.{size} d2,d0")),
            BinaryOp::Shl => self.line(&format!("    lsl.{size} d2,d0")),
            BinaryOp::Shr => self.line(&format!(
                "    {}.{size} d2,d0",
                if type_is_signed(ty) { "asr" } else { "lsr" }
            )),
            BinaryOp::Mul => {
                if size == "b" {
                    if type_is_signed(ty) {
                        self.line("    ext.w d0");
                        self.line("    ext.w d2");
                    } else {
                        self.line("    andi.w #$FF,d0");
                        self.line("    andi.w #$FF,d2");
                    }
                }
                self.line(if type_is_signed(ty) {
                    "    muls.w d2,d0"
                } else {
                    "    mulu.w d2,d0"
                });
            }
            BinaryOp::Div | BinaryOp::Mod => {
                if size == "b" {
                    return Err(Diagnostic::new("M68k division requires u16 or i16 values"));
                }
                let zero = self.next_label("div_u16_zero");
                let done = self.next_label("div_u16_done");
                self.line("    tst.w d2");
                self.line(&format!("    beq {zero}"));
                if type_is_signed(ty) {
                    self.line("    ext.l d0");
                    self.line("    divs d2,d0");
                } else {
                    self.line("    andi.l #$FFFF,d0");
                    self.line("    divu d2,d0");
                }
                if op == BinaryOp::Mod {
                    self.line("    swap d0");
                }
                self.line(&format!("    bra {done}"));
                self.line(&format!("{zero}:"));
                self.line("    moveq #0,d0");
                self.line(&format!("{done}:"));
            }
            BinaryOp::Eq
            | BinaryOp::Ne
            | BinaryOp::Lt
            | BinaryOp::Le
            | BinaryOp::Gt
            | BinaryOp::Ge => {
                self.line(&format!("    cmp.{size} d2,d0"));
                self.boolean_from_branch(comparison_branch(op, type_is_signed(ty)))?;
            }
            BinaryOp::And | BinaryOp::Or => unreachable!(),
        }
        if !is_comparison(op) {
            self.normalize_d0(ty)?;
        }
        Ok(())
    }

    fn emit_wide_multiply(&mut self, ty: &Type) -> Result<(), Diagnostic> {
        let signed = type_is_signed(ty);
        let width = scalar_width(ty)? * 8;
        let loop_label = self.next_label(&format!("mul_u{width}_loop"));
        let skip = self.next_label(&format!("mul_u{width}_skip"));
        let done = self.next_label(&format!("mul_u{width}_done"));
        let positive_left = self.next_label(&format!("mul_u{width}_left_positive"));
        let positive_right = self.next_label(&format!("mul_u{width}_right_positive"));
        let positive_result = self.next_label(&format!("mul_u{width}_result_positive"));
        self.line("    moveq #0,d5");
        if signed {
            self.line("    tst.l d0");
            self.line(&format!("    bpl {positive_left}"));
            self.line("    neg.l d0");
            self.line("    moveq #1,d5");
            self.line(&format!("{positive_left}:"));
            self.line("    tst.l d2");
            self.line(&format!("    bpl {positive_right}"));
            self.line("    neg.l d2");
            self.line("    eori.b #1,d5");
            self.line(&format!("{positive_right}:"));
        }
        self.line("    move.l d0,d3");
        self.line("    move.l d2,d4");
        self.line("    moveq #0,d1");
        self.line(&format!("{loop_label}:"));
        self.line("    tst.l d4");
        self.line(&format!("    beq {done}"));
        self.line("    move.l d4,d6");
        self.line("    andi.l #1,d6");
        self.line(&format!("    beq {skip}"));
        self.line("    add.l d3,d1");
        self.line(&format!("{skip}:"));
        self.line("    lsl.l #1,d3");
        self.line("    lsr.l #1,d4");
        self.line(&format!("    bra {loop_label}"));
        self.line(&format!("{done}:"));
        self.line("    move.l d1,d0");
        if signed {
            self.line("    tst.b d5");
            self.line(&format!("    beq {positive_result}"));
            self.line("    neg.l d0");
            self.line(&format!("{positive_result}:"));
        }
        self.normalize_d0(ty)
    }

    fn emit_wide_divide(&mut self, remainder: bool, ty: &Type) -> Result<(), Diagnostic> {
        let signed = type_is_signed(ty);
        let width = scalar_width(ty)? * 8;
        let divisor_zero = self.next_label(&format!("div_u{width}_zero"));
        let loop_label = self.next_label(&format!("div_u{width}_loop"));
        let result_ready = self.next_label(&format!("div_u{width}_result_ready"));
        let done = self.next_label(&format!("div_u{width}_done"));
        let positive_left = self.next_label(&format!("div_u{width}_left_positive"));
        let positive_right = self.next_label(&format!("div_u{width}_right_positive"));
        let positive_result = self.next_label(&format!("div_u{width}_result_positive"));
        self.line("    moveq #0,d5");
        if signed {
            self.line("    tst.l d0");
            self.line(&format!("    bpl {positive_left}"));
            self.line("    neg.l d0");
            // Bit 0 is the quotient sign; bit 1 is the dividend/remainder sign.
            self.line("    moveq #3,d5");
            self.line(&format!("{positive_left}:"));
            self.line("    tst.l d2");
            self.line(&format!("    bpl {positive_right}"));
            self.line("    neg.l d2");
            self.line("    eori.b #1,d5");
            self.line(&format!("{positive_right}:"));
        }
        self.line("    tst.l d2");
        self.line(&format!("    beq {divisor_zero}"));
        self.line("    moveq #0,d1");
        self.line(&format!("    moveq #{width},d4"));
        self.line(&format!("{loop_label}:"));
        self.line("    move.l d0,d6");
        self.line("    rol.l #1,d6");
        self.line("    andi.l #1,d6");
        self.line("    move.l d1,d3");
        self.line("    rol.l #1,d3");
        self.line("    andi.l #1,d3");
        self.line("    add.l d0,d0");
        self.line("    add.l d1,d1");
        self.line("    add.l d6,d1");
        self.line("    move.l d1,d6");
        self.line("    eori.l #$80000000,d6");
        self.line("    move.l d2,d7");
        self.line("    eori.l #$80000000,d7");
        self.line("    cmp.l d7,d6");
        self.line("    sge d6");
        self.line("    andi.l #1,d6");
        self.line("    or.l d3,d6");
        self.line("    neg.l d6");
        self.line("    move.l d2,d3");
        self.line("    and.l d6,d3");
        self.line("    sub.l d3,d1");
        self.line("    andi.l #1,d6");
        self.line("    add.l d6,d0");
        self.line("    subq.w #1,d4");
        self.line(&format!("    bne {loop_label}"));
        if remainder {
            self.line("    move.l d1,d0");
        }
        self.line(&format!("    bra {result_ready}"));
        self.line(&format!("{divisor_zero}:"));
        self.line("    moveq #0,d0");
        self.line(&format!("    bra {done}"));
        self.line(&format!("{result_ready}:"));
        if signed {
            self.line(&format!("    btst #{},d5", if remainder { 1 } else { 0 }));
            self.line(&format!("    beq {positive_result}"));
            self.line("    neg.l d0");
            self.line(&format!("{positive_result}:"));
        }
        self.line(&format!("{done}:"));
        self.normalize_d0(ty)
    }

    fn emit_logical(&mut self, left: &Expr, op: BinaryOp, right: &Expr) -> Result<(), Diagnostic> {
        let decisive = self.next_label("logical_decisive");
        let done = self.next_label("logical_done");
        let bool_ty = Type::Named("bool".to_owned());
        self.emit_expr(left, &bool_ty)?;
        self.line("    tst.b d0");
        self.line(&format!(
            "    {} {decisive}",
            if op == BinaryOp::And { "beq" } else { "bne" }
        ));
        self.emit_expr(right, &bool_ty)?;
        self.line(&format!("    bra {done}"));
        self.line(&format!("{decisive}:"));
        self.line(&format!(
            "    moveq #{},d0",
            if op == BinaryOp::And { 0 } else { 1 }
        ));
        self.line(&format!("{done}:"));
        Ok(())
    }

    fn emit_call(
        &mut self,
        path: &[String],
        args: &[Expr],
        expected: Option<&Type>,
    ) -> Result<(), Diagnostic> {
        let name = path.join(".");
        match name.as_str() {
            "mem.peek8" | "ezra.mem.peek8" => {
                self.emit_expr(&args[0], &Type::Ptr(Box::new(Type::Named("u8".to_owned()))))?;
                self.line("    move.l d0,a0");
                self.line("    move.b (a0),d0");
                return Ok(());
            }
            "mem.poke8" | "ezra.mem.poke8" => {
                self.emit_expr(&args[0], &Type::Ptr(Box::new(Type::Named("u8".to_owned()))))?;
                self.line("    move.l d0,a0");
                self.emit_expr(&args[1], &Type::Named("u8".to_owned()))?;
                self.line("    move.b d0,(a0)");
                return Ok(());
            }
            "mem.memcpy" | "ezra.mem.memcpy" => {
                self.emit_memcpy(args)?;
                return Ok(());
            }
            "mem.memset" | "ezra.mem.memset" => {
                self.emit_memset(args)?;
                return Ok(());
            }
            _ => {}
        }
        let signature = self
            .model
            .functions
            .get(&name)
            .or_else(|| {
                path.last()
                    .and_then(|short| self.model.functions.get(short))
            })
            .cloned()
            .ok_or_else(|| Diagnostic::new(format!("unknown function `{name}`")))?;
        if signature.params.len() != args.len() {
            return Err(Diagnostic::new(format!(
                "function `{name}` expects {} arguments, got {}",
                signature.params.len(),
                args.len()
            )));
        }
        for ((arg, ty), slot) in args
            .iter()
            .zip(&signature.params)
            .zip(signature.argument_slots)
        {
            let ty = self.model.resolved_type(ty)?;
            self.emit_expr(arg, &ty)?;
            self.store_d0(slot, &ty)?;
        }
        let saved = self
            .function_ram_bases
            .last()
            .map(|base| Storage {
                address: *base,
                size: self.model.next_ram_address() - *base,
            })
            .map(|live| self.live_storage_segments(live, args))
            .unwrap_or_default();
        for storage in &saved {
            for offset in 0..storage.size {
                self.line(&format!(
                    "    move.b ${:06X},-(sp)",
                    storage.address + offset
                ));
            }
        }
        self.line(&format!("    jsr {}", function_label(&name)));
        if !saved.is_empty() {
            self.line("    move.l d0,d6");
            for storage in saved.iter().rev() {
                for offset in (0..storage.size).rev() {
                    self.line(&format!(
                        "    move.b (sp)+,${:06X}",
                        storage.address + offset
                    ));
                }
            }
            self.line("    move.l d6,d0");
        }
        if let Some(expected) = expected {
            if signature.return_type.is_none() {
                self.line("    moveq #0,d0");
            } else {
                self.require_scalar(expected)?;
            }
        }
        Ok(())
    }

    fn emit_memcpy(&mut self, args: &[Expr]) -> Result<(), Diagnostic> {
        if args.len() != 3 {
            return Err(Diagnostic::new("mem.memcpy requires three arguments"));
        }
        let pointer = Type::Ptr(Box::new(Type::Named("u8".to_owned())));
        self.emit_expr(&args[0], &pointer)?;
        self.line("    move.l d0,a0");
        self.emit_expr(&args[1], &pointer)?;
        self.line("    move.l d0,a1");
        self.emit_expr(&args[2], &Type::Named("u24".to_owned()))?;
        self.line("    move.l d0,d2");
        let loop_label = self.next_label("memcpy_loop");
        let done = self.next_label("memcpy_done");
        self.line(&format!("{loop_label}:"));
        self.line("    tst.l d2");
        self.line(&format!("    beq {done}"));
        self.line("    move.b (a1)+,d0");
        self.line("    move.b d0,(a0)+");
        self.line("    subq.l #1,d2");
        self.line(&format!("    bra {loop_label}"));
        self.line(&format!("{done}:"));
        self.line("    moveq #0,d0");
        Ok(())
    }

    fn emit_memset(&mut self, args: &[Expr]) -> Result<(), Diagnostic> {
        if args.len() != 3 {
            return Err(Diagnostic::new("mem.memset requires three arguments"));
        }
        let pointer = Type::Ptr(Box::new(Type::Named("u8".to_owned())));
        self.emit_expr(&args[0], &pointer)?;
        self.line("    move.l d0,a0");
        self.emit_expr(&args[1], &Type::Named("u8".to_owned()))?;
        self.line("    move.b d0,d1");
        self.emit_expr(&args[2], &Type::Named("u24".to_owned()))?;
        self.line("    move.l d0,d2");
        let loop_label = self.next_label("memset_loop");
        let done = self.next_label("memset_done");
        self.line(&format!("{loop_label}:"));
        self.line("    tst.l d2");
        self.line(&format!("    beq {done}"));
        self.line("    move.b d1,(a0)+");
        self.line("    subq.l #1,d2");
        self.line(&format!("    bra {loop_label}"));
        self.line(&format!("{done}:"));
        self.line("    moveq #0,d0");
        Ok(())
    }

    fn load_place(&mut self, place: &Place, ty: &Type) -> Result<(), Diagnostic> {
        match place {
            Place::Ident(name) => self.load_binding_d0(&self.binding(name)?),
            Place::Index { name, index } => {
                self.emit_named_index_address(name, index)?;
                self.load_from_a0(ty)
            }
            Place::Field { base, field } => {
                let binding = self.binding(base)?;
                let field = self.model.field(&binding.ty, field)?.clone();
                self.load_d0(
                    Storage {
                        address: binding.memory()?.address + field.offset,
                        size: field.size,
                    },
                    ty,
                )
            }
            Place::Access(path) => {
                self.emit_access_address(path)?;
                self.load_from_a0(ty)
            }
            Place::Deref(expr) => {
                let pointer_ty = self.expr_type(expr)?;
                self.emit_expr(expr, &pointer_ty)?;
                self.line("    move.l d0,a0");
                self.line(&format!("    move.{} (a0),d0", size_suffix(ty)?));
                Ok(())
            }
        }
    }

    fn store_place(&mut self, place: &Place, ty: &Type) -> Result<(), Diagnostic> {
        match place {
            Place::Ident(name) => self.store_binding_d0(&self.binding(name)?),
            Place::Index { name, index } => {
                self.line(&format!("    move.{} d0,d3", size_suffix(ty)?));
                self.emit_named_index_address(name, index)?;
                self.line(&format!("    move.{} d3,d0", size_suffix(ty)?));
                self.store_to_a0(ty)
            }
            Place::Field { base, field } => {
                let binding = self.binding(base)?;
                let field = self.model.field(&binding.ty, field)?.clone();
                self.store_d0(
                    Storage {
                        address: binding.memory()?.address + field.offset,
                        size: field.size,
                    },
                    ty,
                )
            }
            Place::Access(path) => {
                self.line(&format!("    move.{} d0,d3", size_suffix(ty)?));
                self.emit_access_address(path)?;
                self.line(&format!("    move.{} d3,d0", size_suffix(ty)?));
                self.store_to_a0(ty)
            }
            Place::Deref(expr) => {
                self.line(&format!("    move.{} d0,d3", size_suffix(ty)?));
                let pointer_ty = self.expr_type(expr)?;
                self.emit_expr(expr, &pointer_ty)?;
                self.line("    move.l d0,a0");
                self.line(&format!("    move.{} d3,(a0)", size_suffix(ty)?));
                Ok(())
            }
        }
    }

    fn store_aggregate_place(
        &mut self,
        place: &Place,
        source: Storage,
        size: u32,
    ) -> Result<(), Diagnostic> {
        match place {
            Place::Ident(name) => {
                let destination = self.binding(name)?;
                self.copy(source, destination.memory()?, size);
            }
            Place::Index { name, index } => {
                self.emit_named_index_address(name, index)?;
                self.copy_to_a0(source, size);
            }
            Place::Field { base, field } => {
                let binding = self.binding(base)?;
                let field = self.model.field(&binding.ty, field)?;
                self.copy(
                    source,
                    Storage {
                        address: binding.memory()?.address + field.offset,
                        size,
                    },
                    size,
                );
            }
            Place::Access(path) => {
                self.emit_access_address(path)?;
                self.copy_to_a0(source, size);
            }
            Place::Deref(expr) => {
                let pointer_ty = self.expr_type(expr)?;
                self.emit_expr(expr, &pointer_ty)?;
                self.line("    move.l d0,a0");
                self.copy_to_a0(source, size);
            }
        }
        Ok(())
    }

    fn place_type(&self, place: &Place) -> Result<Type, Diagnostic> {
        match place {
            Place::Ident(name) => Ok(self.binding(name)?.ty),
            Place::Index { name, .. } => {
                element_type(&self.model.resolved_type(&self.binding(name)?.ty)?)
            }
            Place::Field { base, field } => {
                Ok(self.model.field(&self.binding(base)?.ty, field)?.ty.clone())
            }
            Place::Access(path) => self.access_type(path),
            Place::Deref(expr) => match self.model.resolved_type(&self.expr_type(expr)?)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
        }
    }

    fn emit_named_index_address(&mut self, name: &str, index: &Expr) -> Result<Type, Diagnostic> {
        let binding = self.binding(name)?;
        let resolved = self.model.resolved_type(&binding.ty)?;
        let element = element_type(&resolved)?;
        let element_size = self.model.type_size(&element)?;
        match resolved {
            Type::Array { .. } => {
                self.line(&format!(
                    "    move.l #${:06X},a0",
                    binding.memory()?.address
                ));
            }
            Type::Ptr(_) => match binding.location {
                BindingLocation::Memory(storage) => {
                    self.load_d0(storage, &binding.ty)?;
                    self.line("    move.l d0,a0");
                }
                BindingLocation::AddressRegister(register) => {
                    self.line(&format!("    move.l a{register},a0"));
                }
            },
            _ => return Err(Diagnostic::new("indexing requires array or pointer")),
        }
        self.add_index_to_a0(index, element_size)?;
        Ok(element)
    }

    fn emit_access_address(&mut self, path: &AccessPath) -> Result<Type, Diagnostic> {
        let binding = self.binding(&path.root)?;
        let mut ty = self.model.resolved_type(&binding.ty)?;
        if let Type::Ptr(inner) = ty {
            match binding.location {
                BindingLocation::Memory(storage) => {
                    self.load_d0(storage, &binding.ty)?;
                    self.line("    move.l d0,a0");
                }
                BindingLocation::AddressRegister(register) => {
                    self.line(&format!("    move.l a{register},a0"));
                }
            }
            ty = *inner;
        } else {
            self.line(&format!(
                "    move.l #${:06X},a0",
                binding.memory()?.address
            ));
        }
        for segment in &path.segments {
            match segment {
                AccessSegment::Field(name) => {
                    let field = self.model.field(&ty, name)?.clone();
                    if field.offset != 0 {
                        self.line(&format!("    lea {}(a0),a0", field.offset));
                    }
                    ty = field.ty;
                }
                AccessSegment::Index(index) => {
                    let element = element_type(&self.model.resolved_type(&ty)?)?;
                    self.add_index_to_a0(index, self.model.type_size(&element)?)?;
                    ty = element;
                }
            }
        }
        Ok(ty)
    }

    fn add_index_to_a0(&mut self, index: &Expr, element_size: u32) -> Result<(), Diagnostic> {
        if let Ok(index) = self.model.const_value(index) {
            let offset = u32::try_from(index)
                .ok()
                .and_then(|index| index.checked_mul(element_size))
                .ok_or_else(|| Diagnostic::new("array index offset overflow"))?;
            if offset != 0 {
                self.line(&format!("    lea {offset}(a0),a0"));
            }
            return Ok(());
        }
        self.emit_expr(index, &Type::Named("u24".to_owned()))?;
        if element_size > 1 {
            self.line(&format!("    mulu #${element_size:X},d0"));
        }
        self.line("    adda.l d0,a0");
        Ok(())
    }

    fn load_from_a0(&mut self, ty: &Type) -> Result<(), Diagnostic> {
        if scalar_width(ty)? == 3 {
            self.line("    moveq #0,d0");
            self.line("    move.b (a0),d0");
            self.line("    lsl.l #8,d0");
            self.line("    move.b 1(a0),d0");
            self.line("    lsl.l #8,d0");
            self.line("    move.b 2(a0),d0");
            self.normalize_d0(ty)?;
        } else {
            self.line(&format!("    move.{} (a0),d0", size_suffix(ty)?));
        }
        Ok(())
    }

    fn store_to_a0(&mut self, ty: &Type) -> Result<(), Diagnostic> {
        if scalar_width(ty)? == 3 {
            self.line("    move.l d0,d1");
            self.line("    lsr.l #8,d1");
            self.line("    lsr.l #8,d1");
            self.line("    move.b d1,(a0)");
            self.line("    move.l d0,d1");
            self.line("    lsr.l #8,d1");
            self.line("    move.b d1,1(a0)");
            self.line("    move.b d0,2(a0)");
        } else {
            self.line(&format!("    move.{} d0,(a0)", size_suffix(ty)?));
        }
        Ok(())
    }

    fn live_storage_segments(&self, live: Storage, args: &[Expr]) -> Vec<Storage> {
        let mut excluded = args
            .iter()
            .filter_map(|arg| match arg {
                // The callee can mutate this storage through its pointer parameter.
                // Restoring a pre-call snapshot would discard that mutation.
                Expr::AddressOf(name) => self
                    .binding(name)
                    .ok()
                    .and_then(|binding| binding.memory().ok()),
                _ => None,
            })
            .filter_map(|storage| {
                let start = storage.address.max(live.address);
                let end = storage
                    .address
                    .saturating_add(storage.size)
                    .min(live.address.saturating_add(live.size));
                (start < end).then_some((start, end))
            })
            .collect::<Vec<_>>();
        excluded.sort_unstable();

        let mut saved = Vec::new();
        let mut cursor = live.address;
        for (start, end) in excluded {
            if start > cursor {
                saved.push(Storage {
                    address: cursor,
                    size: start - cursor,
                });
            }
            cursor = cursor.max(end);
        }
        let live_end = live.address.saturating_add(live.size);
        if cursor < live_end {
            saved.push(Storage {
                address: cursor,
                size: live_end - cursor,
            });
        }
        saved
    }

    fn copy(&mut self, source: Storage, target: Storage, size: u32) {
        for offset in 0..size {
            self.line(&format!("    move.b ${:06X},d0", source.address + offset));
            self.line(&format!("    move.b d0,${:06X}", target.address + offset));
        }
    }

    fn zero(&mut self, storage: Storage) {
        self.line("    moveq #0,d0");
        for offset in 0..storage.size {
            self.line(&format!("    move.b d0,${:06X}", storage.address + offset));
        }
    }

    fn copy_from_a0(&mut self, target: Storage, size: u32) {
        for offset in 0..size {
            self.line(&format!("    move.b {offset}(a0),d0"));
            self.line(&format!("    move.b d0,${:06X}", target.address + offset));
        }
    }

    fn copy_to_a0(&mut self, source: Storage, size: u32) {
        for offset in 0..size {
            self.line(&format!("    move.b ${:06X},d0", source.address + offset));
            self.line(&format!("    move.b d0,{offset}(a0)"));
        }
    }

    fn expr_type(&self, expr: &Expr) -> Result<Type, Diagnostic> {
        match expr {
            Expr::Int(value) => Ok(if (0..=0xFF).contains(value) {
                Type::Named("u8".to_owned())
            } else {
                Type::Named("u16".to_owned())
            }),
            Expr::TypedInt(_, ty) | Expr::Cast { ty, .. } => self.model.resolved_type(ty),
            Expr::Bool(_) => Ok(Type::Named("bool".to_owned())),
            Expr::Char(_) | Expr::In(_) => Ok(Type::Named("u8".to_owned())),
            Expr::String(_) => Ok(Type::Ptr(Box::new(Type::Named("u8".to_owned())))),
            Expr::Ident(name) => self
                .model
                .constant_types
                .get(name)
                .cloned()
                .or_else(|| self.binding(name).ok().map(|binding| binding.ty))
                .ok_or_else(|| Diagnostic::new(format!("unknown value `{name}`"))),
            Expr::Index { name, .. } => {
                element_type(&self.model.resolved_type(&self.binding(name)?.ty)?)
            }
            Expr::Field { base, field } => self
                .model
                .constant_types
                .get(&format!("{base}.{field}"))
                .cloned()
                .or_else(|| {
                    self.model
                        .field(&self.binding(base).ok()?.ty, field)
                        .ok()
                        .map(|field| field.ty.clone())
                })
                .ok_or_else(|| Diagnostic::new(format!("unknown field `{field}"))),
            Expr::AddressOfIndex { name, .. } => Ok(Type::Ptr(Box::new(element_type(
                &self.model.resolved_type(&self.binding(name)?.ty)?,
            )?))),
            Expr::AddressOfField { base, field } => Ok(Type::Ptr(Box::new(
                self.model.field(&self.binding(base)?.ty, field)?.ty.clone(),
            ))),
            Expr::Access(path) => self.access_type(path),
            Expr::AddressOfAccess(path) => Ok(Type::Ptr(Box::new(self.access_type(path)?))),
            Expr::AddressOf(name) => Ok(Type::Ptr(Box::new(self.binding(name)?.ty))),
            Expr::StructInit { ty, .. } => Ok(Type::Named(ty.clone())),
            Expr::Call { path, .. } => self
                .model
                .functions
                .get(&path.join("."))
                .or_else(|| path.last().and_then(|name| self.model.functions.get(name)))
                .and_then(|signature| signature.return_type.clone())
                .ok_or_else(|| Diagnostic::new("void function has no value")),
            Expr::Unary {
                op: UnaryOp::Not, ..
            } => Ok(Type::Named("bool".to_owned())),
            Expr::Unary { expr, .. } => self.expr_type(expr),
            Expr::BankedPointer { pointer, .. } => self.expr_type(pointer),
            Expr::Deref(expr) => match self.model.resolved_type(&self.expr_type(expr)?)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
            Expr::Binary { left, op, .. }
                if is_comparison(*op) || matches!(op, BinaryOp::And | BinaryOp::Or) =>
            {
                Ok(Type::Named("bool".to_owned()))
            }
            Expr::Binary { left, .. } => self.expr_type(left),
            Expr::Array(_) => Err(Diagnostic::new("array type requires context")),
        }
    }

    fn access_type(&self, path: &AccessPath) -> Result<Type, Diagnostic> {
        let mut ty = self.model.resolved_type(&self.binding(&path.root)?.ty)?;
        if let Type::Ptr(inner) = ty {
            ty = *inner;
        }
        for segment in &path.segments {
            ty = match segment {
                AccessSegment::Field(name) => self.model.field(&ty, name)?.ty.clone(),
                AccessSegment::Index(_) => element_type(&self.model.resolved_type(&ty)?)?,
            };
        }
        Ok(ty)
    }

    fn emit_inline_asm(
        &mut self,
        inputs: &[crate::ast::AsmInput],
        outputs: &[crate::ast::AsmOutput],
        lines: &[String],
    ) -> Result<(), Diagnostic> {
        let mut operands = HashMap::new();
        for operand in inputs
            .iter()
            .map(|input| &input.name)
            .chain(outputs.iter().map(|output| &output.name))
        {
            operands.insert(
                operand.clone(),
                format!("${:06X}", self.binding(operand)?.memory()?.address),
            );
        }
        for line in lines {
            let mut emitted = line.clone();
            for (name, value) in &operands {
                emitted = emitted.replace(&format!("{{{name}}}"), value);
            }
            if emitted.contains(['{', '}']) {
                return Err(Diagnostic::new(format!(
                    "unknown inline asm operand placeholder in `{line}`"
                )));
            }
            self.line(&format!("    {emitted}"));
        }
        Ok(())
    }

    fn boolean_from_test(&mut self, branch: &str, ty: &Type) -> Result<(), Diagnostic> {
        self.line(&format!("    tst.{} d0", size_suffix(ty)?));
        self.boolean_from_branch(branch)
    }

    fn boolean_from_branch(&mut self, branch: &str) -> Result<(), Diagnostic> {
        let yes = self.next_label("true");
        let done = self.next_label("bool_done");
        self.line(&format!("    {branch} {yes}"));
        self.line("    moveq #0,d0");
        self.line(&format!("    bra {done}"));
        self.line(&format!("{yes}:"));
        self.line("    moveq #1,d0");
        self.line(&format!("{done}:"));
        Ok(())
    }

    fn load_constant(&mut self, value: i64, ty: &Type) -> Result<(), Diagnostic> {
        let (size, mask) = match scalar_width(ty)? {
            1 => ("b", 0xFF),
            2 => ("w", 0xFFFF),
            3 => ("l", 0xFF_FFFF),
            4 => ("l", 0xFFFF_FFFF),
            _ => unreachable!(),
        };
        self.line(&format!("    move.{size} #${:X},d0", (value as u64) & mask));
        self.normalize_d0(ty)?;
        Ok(())
    }

    fn load_d0(&mut self, storage: Storage, ty: &Type) -> Result<(), Diagnostic> {
        if scalar_width(ty)? == 3 {
            self.line("    moveq #0,d0");
            self.line(&format!("    move.b ${:06X}.l,d0", storage.address));
            self.line("    lsl.l #8,d0");
            self.line(&format!("    move.b ${:06X}.l,d0", storage.address + 1));
            self.line("    lsl.l #8,d0");
            self.line(&format!("    move.b ${:06X}.l,d0", storage.address + 2));
            self.normalize_d0(ty)?;
            return Ok(());
        }
        self.line(&format!(
            "    move.{} ${:06X}.l,d0",
            size_suffix(ty)?,
            storage.address
        ));
        Ok(())
    }

    fn load_binding_d0(&mut self, binding: &Binding) -> Result<(), Diagnostic> {
        match binding.location {
            BindingLocation::Memory(storage) => self.load_d0(storage, &binding.ty),
            BindingLocation::AddressRegister(register) => {
                if !matches!(binding.ty, Type::Ptr(_)) {
                    return Err(Diagnostic::new(format!(
                        "non-pointer local was allocated to address register a{register}"
                    )));
                }
                self.line(&format!("    move.l a{register},d0"));
                self.normalize_d0(&binding.ty)
            }
        }
    }

    fn store_binding_d0(&mut self, binding: &Binding) -> Result<(), Diagnostic> {
        match binding.location {
            BindingLocation::Memory(storage) => self.store_d0(storage, &binding.ty),
            BindingLocation::AddressRegister(register) => {
                if !matches!(binding.ty, Type::Ptr(_)) {
                    return Err(Diagnostic::new(format!(
                        "non-pointer local was allocated to address register a{register}"
                    )));
                }
                self.line(&format!("    move.l d0,a{register}"));
                Ok(())
            }
        }
    }

    fn store_d0(&mut self, storage: Storage, ty: &Type) -> Result<(), Diagnostic> {
        if scalar_width(ty)? == 3 {
            self.line("    move.l d0,d1");
            self.line("    lsr.l #8,d1");
            self.line("    lsr.l #8,d1");
            self.line(&format!("    move.b d1,${:06X}.l", storage.address));
            self.line("    move.l d0,d1");
            self.line("    lsr.l #8,d1");
            self.line(&format!("    move.b d1,${:06X}.l", storage.address + 1));
            self.line(&format!("    move.b d0,${:06X}.l", storage.address + 2));
            return Ok(());
        }
        self.line(&format!(
            "    move.{} d0,${:06X}.l",
            size_suffix(ty)?,
            storage.address
        ));
        Ok(())
    }

    fn require_scalar(&self, ty: &Type) -> Result<(), Diagnostic> {
        size_suffix(ty)
            .map(|_| ())
            .map_err(|_| Diagnostic::new("M68k source backend does not support this scalar type"))
    }

    fn normalize_d0(&mut self, ty: &Type) -> Result<(), Diagnostic> {
        if scalar_width(ty)? != 3 {
            return Ok(());
        }
        self.line("    andi.l #$FFFFFF,d0");
        if type_is_signed(ty) {
            let positive = self.next_label("i24_positive");
            self.line("    move.l d0,d1");
            self.line("    andi.l #$800000,d1");
            self.line(&format!("    beq {positive}"));
            self.line("    ori.l #$FF000000,d0");
            self.line(&format!("{positive}:"));
        }
        Ok(())
    }

    fn bind_memory(&mut self, name: String, storage: Storage, ty: Type) -> Result<(), Diagnostic> {
        let ty = self.model.resolved_type(&ty)?;
        self.bind(
            name,
            Binding {
                location: BindingLocation::Memory(storage),
                ty,
                volatile: false,
            },
        )
    }

    fn bind(&mut self, name: String, binding: Binding) -> Result<(), Diagnostic> {
        if self
            .scopes
            .iter()
            .rev()
            .any(|scope| scope.contains_key(&name))
        {
            return Err(Diagnostic::new(format!(
                "local `{name}` shadows an existing name"
            )));
        }
        self.scopes
            .last_mut()
            .expect("function scope")
            .insert(name, binding);
        Ok(())
    }

    fn binding(&self, name: &str) -> Result<Binding, Diagnostic> {
        if let Some(binding) = self.scopes.iter().rev().find_map(|scope| scope.get(name)) {
            return Ok(binding.clone());
        }
        if let Some(storage) = self.model.globals.get(name) {
            return Ok(Binding {
                location: BindingLocation::Memory(*storage),
                ty: self.model.resolved_type(&self.model.global_types[name])?,
                volatile: false,
            });
        }
        if let Some((address, ty, volatile)) = self.model.mmio.get(name) {
            return Ok(Binding {
                location: BindingLocation::Memory(Storage {
                    address: *address,
                    size: self.model.type_size(ty)?,
                }),
                ty: ty.clone(),
                volatile: *volatile,
            });
        }
        Err(Diagnostic::new(format!("unknown variable `{name}`")))
    }

    fn next_label(&mut self, name: &str) -> String {
        let label = format!("__ezra_{}_{}", sanitize(name), self.labels);
        self.labels += 1;
        label
    }

    fn line(&mut self, line: &str) {
        self.out.push_str(line);
        self.out.push('\n');
    }

    fn emit_data_bytes(&mut self, bytes: Vec<u8>) {
        for line in byte_data_lines("db", &bytes, ByteLiteralStyle::HexPrefix, 16) {
            self.line(&line);
        }
    }

    fn emit_text_data(&mut self, value: &str) {
        self.line(&terminated_text_data_line("db", value, "0"));
    }
}

const M68K_ADDRESS_REGISTERS: [u8; 5] = [2, 3, 4, 5, 6];
const M68K_POINTER_CLASS: RegClass = RegClass(0);
const M68K_MEMORY_CLASS: RegClass = RegClass(1);
const M68K_STATIC_SPILL_CLASS: SpillClassId = SpillClassId(0);

fn m68k_local_target() -> Target {
    Target {
        units: M68K_ADDRESS_REGISTERS
            .iter()
            .map(|register| RegisterUnit::new(format!("a{register}")))
            .collect(),
        registers: M68K_ADDRESS_REGISTERS
            .iter()
            .enumerate()
            .map(|(unit, register)| {
                PhysicalRegister::new(format!("a{register}"), vec![RegUnit(unit)])
            })
            .collect(),
        register_classes: vec![
            RegisterClass::new(
                "pointer-address",
                (0..M68K_ADDRESS_REGISTERS.len()).map(PhysReg).collect(),
            ),
            RegisterClass::new("memory-local", Vec::new()),
        ],
        spill_classes: vec![
            SpillClass::new("static", None, 0)
                .for_register_classes(vec![M68K_POINTER_CLASS, M68K_MEMORY_CLASS]),
        ],
    }
}

fn plan_function_locals(
    function: &Function,
    model: &mut SemanticModel,
) -> Result<HashMap<String, Binding>, Diagnostic> {
    let mut source_locals = Vec::new();
    let mut local_types = HashMap::new();
    collect_source_locals(&function.body, model, &mut source_locals, &mut local_types)?;
    let clobbers = (0..M68K_ADDRESS_REGISTERS.len())
        .map(PhysReg)
        .collect::<Vec<_>>();
    let planned = allocate_source_locals(
        &m68k_local_target(),
        &source_locals,
        &function.body,
        &clobbers,
    )
    .map_err(regalloc_diagnostic)?;
    let spill_bytes = planned
        .allocation
        .spill_slots
        .iter()
        .map(|slot| slot.offset.saturating_add(slot.size))
        .max()
        .unwrap_or(0);
    let spill_region = model.allocate(spill_bytes)?;
    let mut bindings = HashMap::new();
    for (name, ty) in local_types {
        let vreg = planned
            .locals
            .vreg(&name)
            .ok_or_else(|| Diagnostic::new(format!("missing allocation for local `{name}`")))?;
        let location = match planned.allocation.location(vreg) {
            Some(Location::Register(register)) => {
                if !matches!(ty, Type::Ptr(_)) {
                    return Err(Diagnostic::new(format!(
                        "non-pointer local `{name}` was allocated to an address register"
                    )));
                }
                let register = *M68K_ADDRESS_REGISTERS.get(register.0).ok_or_else(|| {
                    Diagnostic::new(format!("invalid M68k local register for `{name}`"))
                })?;
                BindingLocation::AddressRegister(register)
            }
            Some(Location::Spill(slot_index)) => {
                let slot = planned
                    .allocation
                    .spill_slots
                    .get(slot_index)
                    .ok_or_else(|| Diagnostic::new(format!("invalid spill slot for `{name}`")))?;
                debug_assert_eq!(slot.class, M68K_STATIC_SPILL_CLASS);
                BindingLocation::Memory(Storage {
                    address: spill_region.address + slot.offset,
                    size: slot.size,
                })
            }
            Some(Location::Unused) | None => {
                return Err(Diagnostic::new(format!(
                    "source allocator did not place local `{name}`"
                )));
            }
        };
        bindings.insert(
            name,
            Binding {
                location,
                ty,
                volatile: false,
            },
        );
    }
    Ok(bindings)
}

fn collect_source_locals(
    body: &[Stmt],
    model: &SemanticModel,
    locals: &mut Vec<SourceLocal>,
    local_types: &mut HashMap<String, Type>,
) -> Result<(), Diagnostic> {
    for stmt in body {
        match stmt {
            Stmt::Let { name, ty, .. } => {
                let ty = model.resolved_type(ty)?;
                let pointer = matches!(ty, Type::Ptr(_));
                let class = if pointer {
                    M68K_POINTER_CLASS
                } else {
                    M68K_MEMORY_CLASS
                };
                if local_types.insert(name.clone(), ty.clone()).is_some() {
                    return Err(Diagnostic::new(format!("duplicate local `{name}`")));
                }
                locals.push(
                    SourceLocal::new(name.clone(), model.type_size(&ty)?, 1, class)
                        .with_spill_classes(vec![M68K_STATIC_SPILL_CLASS])
                        .with_force_memory(!pointer),
                );
            }
            Stmt::If {
                then_body,
                else_body,
                ..
            } => {
                collect_source_locals(then_body, model, locals, local_types)?;
                collect_source_locals(else_body, model, locals, local_types)?;
            }
            Stmt::While { body, .. } | Stmt::Loop { body } => {
                collect_source_locals(body, model, locals, local_types)?;
            }
            _ => {}
        }
    }
    Ok(())
}

fn regalloc_diagnostic(diagnostics: Vec<crate::regalloc::Diagnostic>) -> Diagnostic {
    Diagnostic::new(
        diagnostics
            .into_iter()
            .map(|diagnostic| diagnostic.message)
            .collect::<Vec<_>>()
            .join("; "),
    )
}

fn expr_call_args(expr: &Expr) -> Result<&[Expr], Diagnostic> {
    match expr {
        Expr::Call { args, .. } => Ok(args),
        _ => Err(Diagnostic::new("expected function call")),
    }
}

fn size_suffix(ty: &Type) -> Result<&'static str, Diagnostic> {
    match ty {
        Type::Named(name) if matches!(name.as_str(), "u8" | "i8" | "bool") => Ok("b"),
        Type::Named(name) if matches!(name.as_str(), "u16" | "i16") => Ok("w"),
        Type::Named(name) if matches!(name.as_str(), "u24" | "i24" | "ptr" | "u32" | "i32") => {
            Ok("l")
        }
        Type::Ptr(_) => Ok("l"),
        _ => Err(Diagnostic::new("unsupported M68k scalar type")),
    }
}

fn scalar_width(ty: &Type) -> Result<u8, Diagnostic> {
    match ty {
        Type::Named(name) if matches!(name.as_str(), "u8" | "i8" | "bool") => Ok(1),
        Type::Named(name) if matches!(name.as_str(), "u16" | "i16") => Ok(2),
        Type::Named(name) if matches!(name.as_str(), "u24" | "i24" | "ptr") => Ok(3),
        Type::Named(name) if matches!(name.as_str(), "u32" | "i32") => Ok(4),
        Type::Ptr(_) => Ok(3),
        _ => Err(Diagnostic::new("unsupported M68k scalar type")),
    }
}

fn width_mask(width: u8) -> u32 {
    match width {
        1 => 0xFF,
        2 => 0xFFFF,
        3 => 0xFF_FFFF,
        4 => 0xFFFF_FFFF,
        _ => unreachable!(),
    }
}

fn should_use_memory_shift(count: u32) -> bool {
    if count == 0 {
        return false;
    }
    let memory_cycles = 20 * count;
    let register_cycles = 28 + 8 + 2 * count;
    memory_cycles < register_cycles
}

fn match_rotate<'a, F>(expr: &'a Expr, bits: u32, shift_count: F) -> Option<(&'a Expr, u32)>
where
    F: Fn(&Expr) -> Option<u32>,
{
    let Expr::Binary {
        left,
        op: BinaryOp::BitOr,
        right,
    } = expr
    else {
        return None;
    };
    let shifted = |expr: &'a Expr| {
        let Expr::Binary { left, op, right } = expr else {
            return None;
        };
        matches!(op, BinaryOp::Shl | BinaryOp::Shr)
            .then(|| (left.as_ref(), *op, shift_count(right)))
            .and_then(|(source, op, count)| count.map(|count| (source, op, count)))
    };
    let first = shifted(left)?;
    let second = shifted(right)?;
    let (left_shift, right_shift) = match (first.1, second.1) {
        (BinaryOp::Shl, BinaryOp::Shr) => (first, second),
        (BinaryOp::Shr, BinaryOp::Shl) => (second, first),
        _ => return None,
    };
    (left_shift.0 == right_shift.0
        && left_shift.2 != 0
        && right_shift.2 != 0
        && left_shift.2 < bits
        && left_shift.2 + right_shift.2 == bits)
        .then_some((left_shift.0, left_shift.2))
}

fn flatten_bit_or<'a>(expr: &'a Expr, terms: &mut Vec<&'a Expr>) {
    if let Expr::Binary {
        left,
        op: BinaryOp::BitOr,
        right,
    } = expr
    {
        flatten_bit_or(left, terms);
        flatten_bit_or(right, terms);
    } else {
        terms.push(expr);
    }
}

fn shifted_mask_term<'a, F>(
    expr: &'a Expr,
    shift_count: F,
) -> Option<(&'a Expr, BinaryOp, u32, Option<u64>)>
where
    F: Fn(&Expr) -> Option<u32>,
{
    let Expr::Binary { left, op, right } = expr else {
        return None;
    };
    if !matches!(op, BinaryOp::Shl | BinaryOp::Shr) {
        return None;
    }
    let count = shift_count(right)?;
    let (source, mask) = match left.as_ref() {
        Expr::Binary {
            left: source,
            op: BinaryOp::BitAnd,
            right: mask,
        } => (
            source.as_ref(),
            Some(u64::try_from(const_expr_value(mask)?).ok()?),
        ),
        _ => (left.as_ref(), None),
    };
    Some((source, *op, count, mask))
}

fn const_expr_value(expr: &Expr) -> Option<i64> {
    match expr {
        Expr::Int(value) | Expr::TypedInt(value, _) => Some(*value),
        _ => None,
    }
}

fn match_u16_byte_swap<'a, F>(terms: &[&'a Expr], shift_count: F) -> Option<&'a Expr>
where
    F: Fn(&Expr) -> Option<u32> + Copy,
{
    if terms.len() != 2 {
        return None;
    }
    let mut left_source = None;
    let mut right_source = None;
    for term in terms {
        let (source, op, count, mask) = shifted_mask_term(term, shift_count)?;
        if count != 8 {
            return None;
        }
        match (op, mask) {
            (BinaryOp::Shl, None | Some(0xFF) | Some(0xFFFF)) if left_source.is_none() => {
                left_source = Some(source)
            }
            (BinaryOp::Shr, None | Some(0xFF00) | Some(0xFFFF)) if right_source.is_none() => {
                right_source = Some(source)
            }
            _ => return None,
        }
    }
    let left_source = left_source?;
    let right_source = right_source?;
    (left_source == right_source).then_some(left_source)
}

fn match_u32_byte_swap<'a, F>(terms: &[&'a Expr], shift_count: F) -> Option<&'a Expr>
where
    F: Fn(&Expr) -> Option<u32> + Copy,
{
    if terms.len() != 4 {
        return None;
    }
    let expected = [
        (BinaryOp::Shl, 24_u32, 0xFF_u64),
        (BinaryOp::Shl, 8_u32, 0xFF00_u64),
        (BinaryOp::Shr, 8_u32, 0xFF0000_u64),
        (BinaryOp::Shr, 24_u32, 0xFF000000_u64),
    ];
    let mut source = None;
    let mut found = [false; 4];
    for term in terms {
        let (term_source, op, count, Some(mask)) = shifted_mask_term(term, shift_count)? else {
            return None;
        };
        let Some(index) =
            expected
                .iter()
                .position(|(expected_op, expected_count, expected_mask)| {
                    *expected_op == op && *expected_count == count && *expected_mask == mask
                })
        else {
            return None;
        };
        if found[index] {
            return None;
        }
        found[index] = true;
        if let Some(source) = source {
            if source != term_source {
                return None;
            }
        } else {
            source = Some(term_source);
        }
    }
    found.into_iter().all(|found| found).then_some(source?)
}

fn element_type(ty: &Type) -> Result<Type, Diagnostic> {
    match ty {
        Type::Array { element, .. } | Type::Ptr(element) => Ok((**element).clone()),
        _ => Err(Diagnostic::new("indexing requires array or pointer")),
    }
}

fn type_is_signed(ty: &Type) -> bool {
    matches!(ty, Type::Named(name) if name.starts_with('i'))
}
fn is_comparison(op: BinaryOp) -> bool {
    matches!(
        op,
        BinaryOp::Eq | BinaryOp::Ne | BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge
    )
}
fn comparison_branch(op: BinaryOp, signed: bool) -> &'static str {
    match (op, signed) {
        (BinaryOp::Eq, _) => "beq",
        (BinaryOp::Ne, _) => "bne",
        (BinaryOp::Lt, true) => "blt",
        (BinaryOp::Le, true) => "ble",
        (BinaryOp::Gt, true) => "bgt",
        (BinaryOp::Ge, true) => "bge",
        (BinaryOp::Lt, false) => "bcs",
        (BinaryOp::Le, false) => "bls",
        (BinaryOp::Gt, false) => "bhi",
        (BinaryOp::Ge, false) => "bcc",
        _ => unreachable!(),
    }
}
fn assign_binary(op: AssignOp) -> BinaryOp {
    match op {
        AssignOp::Add => BinaryOp::Add,
        AssignOp::Sub => BinaryOp::Sub,
        AssignOp::Mul => BinaryOp::Mul,
        AssignOp::Div => BinaryOp::Div,
        AssignOp::Mod => BinaryOp::Mod,
        AssignOp::BitAnd => BinaryOp::BitAnd,
        AssignOp::BitOr => BinaryOp::BitOr,
        AssignOp::BitXor => BinaryOp::BitXor,
        AssignOp::Shl => BinaryOp::Shl,
        AssignOp::Shr => BinaryOp::Shr,
        AssignOp::Set => unreachable!(),
    }
}
fn function_label(name: &str) -> String {
    format!("_{}", sanitize(name))
}
fn sanitize(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests;
