use std::collections::{HashMap, HashSet};

use crate::{
    asm::{AssemblyOptions, comments::with_readability_comments},
    ast::{
        AccessPath, AccessSegment, AssignOp, BinaryOp, Declaration, Expr, Function, Place, Program,
        Stmt, Type, UnaryOp,
    },
    diagnostic::Diagnostic,
    hir::HirProgram,
    tbir::{
        TbirProgram,
        model::{SemanticModel, Storage},
    },
};

const POINTER_ZP: u32 = 0xF0;

pub fn emit_mos6502_assembly_with_options(
    program: &Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    let model = SemanticModel::from_program(
        &tbir.lowered_program,
        16,
        options.ram_base.get(),
        options.rodata_base.get(),
        options.asset_base.get(),
    )?;
    Emitter::new(model, options.clone())
        .emit(&tbir.lowered_program)
        .map(|asm| with_readability_comments(asm, program, &options, "mos6502"))
}

#[derive(Clone)]
struct Binding {
    storage: Storage,
    ty: Type,
}

#[derive(Clone)]
struct LoopLabels {
    continue_label: String,
    break_label: String,
}

struct Emitter {
    model: SemanticModel,
    out: String,
    labels: usize,
    scopes: Vec<HashMap<String, Binding>>,
    loops: Vec<LoopLabels>,
    return_labels: Vec<String>,
    return_types: Vec<Option<Type>>,
    function_ram_bases: Vec<u32>,
    r0: Storage,
    r1: Storage,
    r2: Storage,
    c64_executable: bool,
}

impl Emitter {
    fn new(mut model: SemanticModel, options: AssemblyOptions) -> Self {
        let r0 = model.allocate(3).expect("6502 result scratch allocation");
        let r1 = model.allocate(3).expect("6502 rhs scratch allocation");
        let r2 = model.allocate(3).expect("6502 work scratch allocation");
        Self {
            model,
            out: String::new(),
            labels: 0,
            scopes: Vec::new(),
            loops: Vec::new(),
            return_labels: Vec::new(),
            return_types: Vec::new(),
            function_ram_bases: Vec::new(),
            r0,
            r1,
            r2,
            c64_executable: options.c64_executable,
        }
    }

    fn emit(mut self, program: &Program) -> Result<String, Diagnostic> {
        self.line("; generated by ezrac");
        self.line("; target: MOS 6502");
        self.line("section .text");
        self.line("__ezra_start:");
        self.line("    cld");
        self.line("    ldx #$FF");
        self.line("    txs");
        self.emit_static_initializers(program)?;
        self.line("    jsr _main");
        self.line("__ezra_exit:");
        if self.c64_executable {
            self.line("    jmp $A474"); // BASIC warm start.
        } else {
            self.line("    jmp __ezra_exit");
        }

        let emitted_functions = reachable_function_names(program, &self.model);
        for declaration in &program.declarations {
            if let Declaration::Function(function) = declaration
                && emitted_functions.contains(&function.name)
            {
                self.emit_function(function)?;
            }
        }
        for section in [".header", ".rodata", ".data", ".bss", ".assets", ".scratch"] {
            self.line(&format!("section {section}"));
        }
        Ok(self.out)
    }

    fn emit_static_initializers(&mut self, program: &Program) -> Result<(), Diagnostic> {
        let embeds = self.model.embeds.values().cloned().collect::<Vec<_>>();
        for embed in embeds {
            for (offset, byte) in embed.bytes.iter().copied().enumerate() {
                self.lda_imm(byte);
                self.sta(embed.storage.address + offset as u32);
            }
        }
        let strings = self
            .model
            .strings
            .iter()
            .map(|(value, storage)| (value.clone(), *storage))
            .collect::<Vec<_>>();
        for (value, storage) in strings {
            for (offset, byte) in value.bytes().chain(std::iter::once(0)).enumerate() {
                self.lda_imm(byte);
                self.sta(storage.address + offset as u32);
            }
        }
        for declaration in &program.declarations {
            if let Declaration::Global(global) = declaration {
                let storage = self.model.globals[&global.name];
                self.emit_initializer(storage, &global.ty, &global.value)?;
            }
        }
        Ok(())
    }

    fn emit_function(&mut self, function: &Function) -> Result<(), Diagnostic> {
        let return_label = self.next_label(&format!("{}_return", function.name));
        let naked = function.attrs.iter().any(|attr| attr == "naked");
        let interrupt = function.attrs.iter().any(|attr| attr == "interrupt");
        if interrupt && (!function.params.is_empty() || function.return_type.is_some()) {
            return Err(Diagnostic::new(format!(
                "interrupt function `{}` cannot have parameters or a return value",
                function.name
            )));
        }
        if naked
            && function.body.iter().any(|stmt| {
                !matches!(
                    stmt,
                    Stmt::Asm {
                        inputs,
                        outputs,
                        ..
                    } if inputs.is_empty() && outputs.is_empty()
                )
            })
        {
            return Err(Diagnostic::new(format!(
                "naked function `{}` may contain only asm blocks without operands",
                function.name
            )));
        }
        self.line(&format!("{}:", function_label(&function.name)));
        self.scopes.push(HashMap::new());
        self.return_labels.push(return_label.clone());
        self.return_types.push(function.return_type.clone());
        self.function_ram_bases.push(self.model.next_ram_address());

        if interrupt && !naked {
            self.line("    pha");
            self.line("    txa");
            self.line("    pha");
            self.line("    tya");
            self.line("    pha");
        }
        let signature = self
            .model
            .functions
            .get(&function.name)
            .cloned()
            .ok_or_else(|| Diagnostic::new(format!("unknown function `{}`", function.name)))?;
        for (index, param) in function.params.iter().enumerate() {
            let storage = self.model.allocate_type(&param.ty)?;
            self.bind(param.name.clone(), storage, param.ty.clone())?;
            self.copy(
                signature.argument_slots[index],
                storage,
                self.model.type_size(&param.ty)?,
            );
        }
        self.emit_block(&function.body)?;
        self.line(&format!("{return_label}:"));
        if interrupt {
            if !naked {
                self.line("    pla");
                self.line("    tay");
                self.line("    pla");
                self.line("    tax");
                self.line("    pla");
            }
            self.line("    rti");
        } else if !naked {
            self.line("    rts");
        }

        self.return_types.pop();
        self.return_labels.pop();
        self.function_ram_bases.pop();
        self.scopes.pop();
        Ok(())
    }

    fn emit_block(&mut self, body: &[Stmt]) -> Result<(), Diagnostic> {
        for stmt in body {
            self.emit_stmt(stmt)?;
        }
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<(), Diagnostic> {
        match stmt {
            Stmt::Let { name, ty, value } => {
                let storage = self.model.allocate_type(ty)?;
                self.bind(name.clone(), storage, ty.clone())?;
                self.emit_initializer(storage, ty, value)?;
            }
            Stmt::Assign { target, op, value } => {
                let ty = self.place_type(target)?;
                let Ok(width) = self.model.type_width(&ty) else {
                    if *op != AssignOp::Set {
                        return Err(Diagnostic::new(
                            "compound assignment requires a scalar value",
                        ));
                    }
                    let size = self.model.type_size(&ty)?;
                    let temporary = self.model.allocate(size)?;
                    self.emit_initializer(temporary, &ty, value)?;
                    self.emit_store_aggregate_place(target, temporary, size)?;
                    return Ok(());
                };
                if *op == AssignOp::Set {
                    self.emit_expr(value, &ty)?;
                } else {
                    self.emit_load_place(target, width)?;
                    let left = self.model.allocate(u32::from(width))?;
                    self.copy(self.r0, left, u32::from(width));
                    self.emit_expr(value, &ty)?;
                    self.copy(self.r0, self.r1, u32::from(width));
                    self.copy(left, self.r0, u32::from(width));
                    self.emit_binary_op(assign_binary(*op), width, false)?;
                }
                self.emit_store_place(target, width)?;
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                let else_label = self.next_label("if_else");
                let end_label = self.next_label("if_end");
                self.emit_expr(condition, &Type::Named("bool".to_owned()))?;
                self.jump_if_zero(self.r0.address, &else_label);
                self.emit_block(then_body)?;
                self.line(&format!("    jmp {end_label}"));
                self.line(&format!("{else_label}:"));
                self.emit_block(else_body)?;
                self.line(&format!("{end_label}:"));
            }
            Stmt::While { condition, body } => {
                let condition_label = self.next_label("while_condition");
                let break_label = self.next_label("while_end");
                self.loops.push(LoopLabels {
                    continue_label: condition_label.clone(),
                    break_label: break_label.clone(),
                });
                self.line(&format!("{condition_label}:"));
                self.emit_expr(condition, &Type::Named("bool".to_owned()))?;
                self.jump_if_zero(self.r0.address, &break_label);
                self.emit_block(body)?;
                self.line(&format!("    jmp {condition_label}"));
                self.line(&format!("{break_label}:"));
                self.loops.pop();
            }
            Stmt::Loop { body } => {
                let continue_label = self.next_label("loop_body");
                let break_label = self.next_label("loop_end");
                self.loops.push(LoopLabels {
                    continue_label: continue_label.clone(),
                    break_label: break_label.clone(),
                });
                self.line(&format!("{continue_label}:"));
                self.emit_block(body)?;
                self.line(&format!("    jmp {continue_label}"));
                self.line(&format!("{break_label}:"));
                self.loops.pop();
            }
            Stmt::Break => {
                let label = self
                    .loops
                    .last()
                    .ok_or_else(|| Diagnostic::new("break outside loop"))?
                    .break_label
                    .clone();
                self.line(&format!("    jmp {label}"));
            }
            Stmt::Continue => {
                let label = self
                    .loops
                    .last()
                    .ok_or_else(|| Diagnostic::new("continue outside loop"))?
                    .continue_label
                    .clone();
                self.line(&format!("    jmp {label}"));
            }
            Stmt::Return(value) => {
                if let Some(value) = value {
                    let ty = self
                        .return_types
                        .last()
                        .and_then(Clone::clone)
                        .ok_or_else(|| Diagnostic::new("value return in void function"))?;
                    self.emit_expr(value, &ty)?;
                }
                let label = self
                    .return_labels
                    .last()
                    .expect("function return label")
                    .clone();
                self.line(&format!("    jmp {label}"));
            }
            Stmt::Asm {
                inputs,
                outputs,
                lines,
                ..
            } => self.emit_inline_asm(inputs, outputs, lines)?,
            Stmt::Out { port, .. } => {
                return Err(Diagnostic::new(format!(
                    "MOS 6502 does not support separate port I/O `{port}`; use mmio instead"
                )));
            }
            Stmt::Expr(expr) => {
                let ty = self.expr_type(expr).unwrap_or(Type::Named("u8".to_owned()));
                self.emit_expr(expr, &ty)?;
            }
        }
        Ok(())
    }

    fn emit_initializer(
        &mut self,
        storage: Storage,
        ty: &Type,
        value: &Expr,
    ) -> Result<(), Diagnostic> {
        match (self.model.resolved_type(ty)?, value) {
            (Type::Array { .. }, Expr::Ident(name)) => {
                let source = self.binding(name)?;
                self.copy(source.storage, storage, storage.size);
            }
            (Type::Array { element, len }, Expr::Array(values)) => {
                let element_size = self.model.type_size(&element)?;
                let len = u32::try_from(self.model.const_value(&len)?)
                    .map_err(|_| Diagnostic::new("invalid array length"))?;
                for index in 0..len {
                    let target = Storage {
                        address: storage.address + index * element_size,
                        size: element_size,
                    };
                    if let Some(value) = values.get(index as usize) {
                        self.emit_initializer(target, &element, value)?;
                    } else {
                        self.zero(target);
                    }
                }
            }
            (Type::Named(name), Expr::StructInit { fields, .. })
                if self.model.structs.contains_key(&name) =>
            {
                self.zero(storage);
                let layout = self.model.structs[&name].clone();
                for (field_name, value) in fields {
                    let field = layout
                        .fields
                        .get(field_name)
                        .ok_or_else(|| Diagnostic::new(format!("unknown field `{field_name}`")))?;
                    self.emit_initializer(
                        Storage {
                            address: storage.address + field.offset,
                            size: field.size,
                        },
                        &field.ty,
                        value,
                    )?;
                }
            }
            (Type::Named(name), Expr::Ident(source)) if self.model.structs.contains_key(&name) => {
                let source = self.binding(source)?;
                self.copy(source.storage, storage, storage.size);
            }
            (resolved @ (Type::Array { .. } | Type::Named(_)), Expr::Deref(pointer)) => {
                self.emit_expr(pointer, &Type::Ptr(Box::new(resolved)))?;
                self.copy_result_to_zp();
                self.copy_indirect_to_storage(storage, storage.size);
            }
            (resolved, _) => {
                let width = self.model.type_width(&resolved)?;
                self.emit_expr(value, &resolved)?;
                self.copy(self.r0, storage, u32::from(width));
            }
        }
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr, expected: &Type) -> Result<(), Diagnostic> {
        let width = self.model.type_width(expected)?;
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => self.load_constant(*value, width),
            Expr::Bool(value) => self.load_constant(i64::from(*value), width),
            Expr::Char(value) => self.load_constant(i64::from(*value), width),
            Expr::String(value) => {
                let storage = self.model.intern_string(value)?;
                self.load_constant(i64::from(storage.address), width);
            }
            Expr::Ident(name) => {
                if let Some(value) = self.model.constants.get(name).copied() {
                    self.load_constant(value, width);
                } else {
                    let binding = self.binding(name)?;
                    let source_width = self.model.type_width(&binding.ty)?;
                    self.copy(binding.storage, self.r0, u32::from(source_width));
                    self.extend_result(source_width, width, type_is_signed(&binding.ty));
                }
            }
            Expr::In(port) => {
                return Err(Diagnostic::new(format!(
                    "MOS 6502 does not support separate port I/O `{port}`; use mmio instead"
                )));
            }
            Expr::AddressOf(name) => {
                let binding = self.binding(name)?;
                self.load_constant(i64::from(binding.storage.address), width);
            }
            Expr::AddressOfIndex { name, index } => {
                self.emit_named_index_address(name, index)?;
                self.copy_zp_to_result(width);
            }
            Expr::AddressOfField { base, field } => {
                let binding = self.binding(base)?;
                let field = self.model.field(&binding.ty, field)?;
                self.load_constant(i64::from(binding.storage.address + field.offset), width);
            }
            Expr::AddressOfAccess(path) => {
                let (_, _) = self.emit_access_address(path)?;
                self.copy_zp_to_result(width);
            }
            Expr::Index { name, index } => {
                let element = self.emit_named_index_address(name, index)?;
                let element_width = self.model.type_width(&element)?;
                self.load_indirect(element_width);
                self.extend_result(element_width, width, false);
            }
            Expr::Field { base, field } => {
                let constant_name = format!("{base}.{field}");
                if let Some(value) = self.model.constants.get(&constant_name).copied() {
                    self.load_constant(value, width);
                } else {
                    let binding = self.binding(base)?;
                    let field = self.model.field(&binding.ty, field)?.clone();
                    let source_width = self.model.type_width(&field.ty)?;
                    self.copy(
                        Storage {
                            address: binding.storage.address + field.offset,
                            size: field.size,
                        },
                        self.r0,
                        u32::from(source_width),
                    );
                    self.extend_result(source_width, width, type_is_signed(&field.ty));
                }
            }
            Expr::Access(path) => {
                let (ty, _) = self.emit_access_address(path)?;
                let source_width = self.model.type_width(&ty)?;
                self.load_indirect(source_width);
                self.extend_result(source_width, width, false);
            }
            Expr::Deref(pointer) => {
                self.emit_expr(pointer, &Type::Ptr(Box::new(expected.clone())))?;
                self.copy_result_to_zp();
                self.load_indirect(width);
            }
            Expr::Call { path, args } => self.emit_call(path, args, expected)?,
            Expr::Unary { op, expr } => {
                self.emit_expr(expr, expected)?;
                self.emit_unary(*op, width);
            }
            Expr::Binary { left, op, right } => {
                if matches!(op, BinaryOp::And | BinaryOp::Or) {
                    self.emit_short_circuit(left, *op, right)?;
                    self.extend_result(1, width, false);
                    return Ok(());
                }
                let operand_ty = if is_comparison(*op) || matches!(op, BinaryOp::And | BinaryOp::Or)
                {
                    self.expr_type(left)
                        .or_else(|_| self.expr_type(right))
                        .unwrap_or(expected.clone())
                } else {
                    expected.clone()
                };
                let operand_width = self.model.type_width(&operand_ty)?;
                self.emit_expr(left, &operand_ty)?;
                let left_storage = self.model.allocate(u32::from(operand_width))?;
                self.copy(self.r0, left_storage, u32::from(operand_width));
                self.emit_expr(right, &operand_ty)?;
                self.copy(self.r0, self.r1, u32::from(operand_width));
                self.copy(left_storage, self.r0, u32::from(operand_width));
                if matches!(op, BinaryOp::Add | BinaryOp::Sub)
                    && let Type::Ptr(inner) = self.model.resolved_type(&operand_ty)?
                {
                    self.scale_storage(self.r1, operand_width, self.model.type_size(&inner)?);
                }
                self.emit_binary_op(*op, operand_width, type_is_signed(&operand_ty))?;
                if is_comparison(*op) || matches!(op, BinaryOp::And | BinaryOp::Or) {
                    self.extend_result(1, width, false);
                }
            }
            Expr::Cast { ty, expr } => {
                let source_ty = self.expr_type(expr).unwrap_or_else(|_| ty.clone());
                let source_width = self.model.type_width(&source_ty)?;
                self.emit_expr(expr, &source_ty)?;
                self.extend_result(source_width, width, type_is_signed(&source_ty));
            }
            Expr::Array(_) | Expr::StructInit { .. } => {
                return Err(Diagnostic::new("aggregate value requires storage context"));
            }
        }
        Ok(())
    }

    fn emit_call(
        &mut self,
        path: &[String],
        args: &[Expr],
        expected: &Type,
    ) -> Result<(), Diagnostic> {
        let name = path.join(".");
        match name.as_str() {
            "mem.peek8" | "ezra.mem.peek8" => {
                self.emit_expr(&args[0], &Type::Ptr(Box::new(Type::Named("u8".to_owned()))))?;
                self.copy_result_to_zp();
                self.load_indirect(1);
                return Ok(());
            }
            "mem.poke8" | "ezra.mem.poke8" => {
                self.emit_expr(&args[0], &Type::Ptr(Box::new(Type::Named("u8".to_owned()))))?;
                let destination = self.model.allocate(2)?;
                self.copy(self.r0, destination, 2);
                self.emit_expr(&args[1], &Type::Named("u8".to_owned()))?;
                self.set_zp_from_storage(POINTER_ZP, destination);
                self.lda(self.r0.address);
                self.line(&format!("    ldy #$00"));
                self.line(&format!("    sta (${:02X}),y", POINTER_ZP));
                return Ok(());
            }
            "mem.memcpy" | "ezra.mem.memcpy" => {
                self.emit_memcpy(args)?;
                return Ok(());
            }
            "mem.memset" | "ezra.mem.memset" => {
                self.emit_memset(args)?;
                return Ok(());
            }
            _ => {}
        }
        let signature = self
            .model
            .functions
            .get(&name)
            .or_else(|| {
                path.last()
                    .and_then(|short| self.model.functions.get(short))
            })
            .cloned()
            .ok_or_else(|| Diagnostic::new(format!("unknown function `{name}`")))?;
        if signature.params.len() != args.len() {
            return Err(Diagnostic::new(format!(
                "function `{name}` expects {} arguments, got {}",
                signature.params.len(),
                args.len()
            )));
        }
        let mut evaluated_args = Vec::with_capacity(args.len());
        for (index, arg) in args.iter().enumerate() {
            let ty = &signature.params[index];
            self.emit_expr(arg, ty)?;
            let storage = self.model.allocate(self.model.type_size(ty)?)?;
            self.copy(self.r0, storage, storage.size);
            evaluated_args.push(storage);
        }
        for (storage, argument_slot) in evaluated_args.into_iter().zip(&signature.argument_slots) {
            self.copy(storage, *argument_slot, storage.size);
        }
        let saved = self.function_ram_bases.last().map(|base| Storage {
            address: *base,
            size: self.model.next_ram_address() - *base,
        });
        if let Some(saved) = saved {
            for offset in 0..saved.size {
                self.lda(saved.address + offset);
                self.line("    pha");
            }
        }
        self.line(&format!("    jsr {}", function_label(&name)));
        let return_storage = signature
            .return_type
            .as_ref()
            .map(|ty| self.model.type_size(ty))
            .transpose()?
            .map(|size| self.model.allocate(size))
            .transpose()?;
        if let Some(return_storage) = return_storage {
            self.copy(self.r0, return_storage, return_storage.size);
        }
        if let Some(saved) = saved {
            for offset in (0..saved.size).rev() {
                self.line("    pla");
                self.sta(saved.address + offset);
            }
        }
        if let Some(return_storage) = return_storage {
            self.copy(return_storage, self.r0, return_storage.size);
        }
        if signature.return_type.is_none() {
            self.zero(self.r0);
        } else {
            let return_width = self
                .model
                .type_width(signature.return_type.as_ref().unwrap())?;
            self.extend_result(return_width, self.model.type_width(expected)?, false);
        }
        Ok(())
    }

    fn emit_memcpy(&mut self, args: &[Expr]) -> Result<(), Diagnostic> {
        if args.len() != 3 {
            return Err(Diagnostic::new("mem.memcpy requires three arguments"));
        }
        let pointer = Type::Ptr(Box::new(Type::Named("u8".to_owned())));
        self.emit_expr(&args[0], &pointer)?;
        let destination = self.model.allocate(2)?;
        self.copy(self.r0, destination, 2);
        self.emit_expr(&args[1], &pointer)?;
        let source = self.model.allocate(2)?;
        self.copy(self.r0, source, 2);
        self.emit_expr(&args[2], &Type::Named("u16".to_owned()))?;
        let length = self.model.allocate(2)?;
        self.copy(self.r0, length, 2);
        let loop_label = self.next_label("memcpy_loop");
        let done = self.next_label("memcpy_done");
        self.set_zp_from_storage(POINTER_ZP, source);
        self.set_zp_from_storage(POINTER_ZP + 2, destination);
        self.line(&format!("{loop_label}:"));
        self.jump_storage_zero(length, 2, &done);
        self.line("    ldy #$00");
        self.line(&format!("    lda (${:02X}),y", POINTER_ZP));
        self.line(&format!("    sta (${:02X}),y", POINTER_ZP + 2));
        self.increment_zp(POINTER_ZP);
        self.increment_zp(POINTER_ZP + 2);
        self.decrement(length, 2);
        self.line(&format!("    jmp {loop_label}"));
        self.line(&format!("{done}:"));
        self.zero(self.r0);
        Ok(())
    }

    fn emit_memset(&mut self, args: &[Expr]) -> Result<(), Diagnostic> {
        if args.len() != 3 {
            return Err(Diagnostic::new("mem.memset requires three arguments"));
        }
        let pointer = Type::Ptr(Box::new(Type::Named("u8".to_owned())));
        self.emit_expr(&args[0], &pointer)?;
        let destination = self.model.allocate(2)?;
        self.copy(self.r0, destination, 2);
        self.emit_expr(&args[1], &Type::Named("u8".to_owned()))?;
        let value = self.model.allocate(1)?;
        self.copy(self.r0, value, 1);
        self.emit_expr(&args[2], &Type::Named("u16".to_owned()))?;
        let length = self.model.allocate(2)?;
        self.copy(self.r0, length, 2);
        let loop_label = self.next_label("memset_loop");
        let done = self.next_label("memset_done");
        self.set_zp_from_storage(POINTER_ZP, destination);
        self.line(&format!("{loop_label}:"));
        self.jump_storage_zero(length, 2, &done);
        self.lda(value.address);
        self.line("    ldy #$00");
        self.line(&format!("    sta (${:02X}),y", POINTER_ZP));
        self.increment_zp(POINTER_ZP);
        self.decrement(length, 2);
        self.line(&format!("    jmp {loop_label}"));
        self.line(&format!("{done}:"));
        self.zero(self.r0);
        Ok(())
    }

    fn emit_binary_op(&mut self, op: BinaryOp, width: u8, signed: bool) -> Result<(), Diagnostic> {
        match op {
            BinaryOp::Add => self.add(width),
            BinaryOp::Sub => self.sub(width),
            BinaryOp::BitAnd | BinaryOp::BitOr | BinaryOp::BitXor => {
                for offset in 0..u32::from(width) {
                    self.lda(self.r0.address + offset);
                    let mnemonic = match op {
                        BinaryOp::BitAnd => "and",
                        BinaryOp::BitOr => "ora",
                        BinaryOp::BitXor => "eor",
                        _ => unreachable!(),
                    };
                    self.line(&format!("    {mnemonic} ${:04X}", self.r1.address + offset));
                    self.sta(self.r0.address + offset);
                }
            }
            BinaryOp::Mul => self.multiply(width, signed),
            BinaryOp::Div | BinaryOp::Mod => self.divide(width, op == BinaryOp::Mod, signed),
            BinaryOp::Shl | BinaryOp::Shr => self.shift(width, op == BinaryOp::Shr, signed),
            BinaryOp::And | BinaryOp::Or => self.logical(op),
            op if is_comparison(op) => self.compare(op, width, signed),
            _ => return Err(Diagnostic::new("unsupported 6502 binary operation")),
        }
        Ok(())
    }

    fn emit_unary(&mut self, op: UnaryOp, width: u8) {
        match op {
            UnaryOp::BitNot => {
                for offset in 0..u32::from(width) {
                    self.lda(self.r0.address + offset);
                    self.line("    eor #$FF");
                    self.sta(self.r0.address + offset);
                }
            }
            UnaryOp::Neg => {
                for offset in 0..u32::from(width) {
                    self.lda(self.r0.address + offset);
                    self.line("    eor #$FF");
                    self.sta(self.r0.address + offset);
                }
                self.line("    clc");
                for offset in 0..u32::from(width) {
                    self.lda(self.r0.address + offset);
                    self.line(&format!(
                        "    adc #${:02X}",
                        if offset == 0 { 1 } else { 0 }
                    ));
                    self.sta(self.r0.address + offset);
                }
            }
            UnaryOp::Not => {
                let true_label = self.next_label("not_true");
                let done = self.next_label("not_done");
                self.jump_if_zero(self.r0.address, &true_label);
                self.load_constant(0, 1);
                self.line(&format!("    jmp {done}"));
                self.line(&format!("{true_label}:"));
                self.load_constant(1, 1);
                self.line(&format!("{done}:"));
            }
        }
    }

    fn add(&mut self, width: u8) {
        self.line("    clc");
        for offset in 0..u32::from(width) {
            self.lda(self.r0.address + offset);
            self.line(&format!("    adc ${:04X}", self.r1.address + offset));
            self.sta(self.r0.address + offset);
        }
    }

    fn sub(&mut self, width: u8) {
        self.line("    sec");
        for offset in 0..u32::from(width) {
            self.lda(self.r0.address + offset);
            self.line(&format!("    sbc ${:04X}", self.r1.address + offset));
            self.sta(self.r0.address + offset);
        }
    }

    fn multiply(&mut self, width: u8, signed: bool) {
        let loop_label = self.next_label("mul_loop");
        let done = self.next_label("mul_done");
        let multiplicand = self
            .model
            .allocate(u32::from(width))
            .expect("multiply scratch");
        let multiplier = self
            .model
            .allocate(u32::from(width))
            .expect("multiply scratch");
        let negative = self.model.allocate(1).expect("multiply sign");
        self.zero(negative);
        if signed {
            self.normalize_signed_operand(self.r0, width, negative, false);
            self.normalize_signed_operand(self.r1, width, negative, true);
        }
        self.copy(self.r0, multiplicand, u32::from(width));
        self.copy(self.r1, multiplier, u32::from(width));
        self.zero(self.r0);
        self.line(&format!("{loop_label}:"));
        self.jump_storage_zero(multiplier, width, &done);
        self.copy(multiplicand, self.r1, u32::from(width));
        self.add(width);
        self.decrement(multiplier, width);
        self.line(&format!("    jmp {loop_label}"));
        self.line(&format!("{done}:"));
        if signed {
            self.negate_if_flag(self.r0, width, negative);
        }
    }

    fn divide(&mut self, width: u8, remainder: bool, signed: bool) {
        let loop_label = self.next_label("div_loop");
        let done = self.next_label("div_done");
        let zero = self.next_label("div_zero");
        let quotient_negative = self.model.allocate(1).expect("division sign");
        let remainder_negative = self.model.allocate(1).expect("division sign");
        self.zero(quotient_negative);
        self.zero(remainder_negative);
        if signed {
            self.lda(self.r0.address + u32::from(width - 1));
            let dividend_positive = self.next_label("dividend_positive");
            self.branch_long("bpl", &dividend_positive);
            self.toggle(quotient_negative);
            self.toggle(remainder_negative);
            self.negate_storage(self.r0, width);
            self.line(&format!("{dividend_positive}:"));
            self.normalize_signed_operand(self.r1, width, quotient_negative, true);
        }
        self.zero(self.r2);
        self.jump_storage_zero(self.r1, width, &zero);
        self.line(&format!("{loop_label}:"));
        self.jump_if_less(self.r0, self.r1, width, &done);
        self.sub(width);
        self.increment(self.r2, width);
        self.line(&format!("    jmp {loop_label}"));
        self.line(&format!("{zero}:"));
        self.zero(self.r0);
        self.line(&format!("    jmp {done}"));
        self.line(&format!("{done}:"));
        if !remainder {
            self.copy(self.r2, self.r0, u32::from(width));
        }
        if signed {
            self.negate_if_flag(
                self.r0,
                width,
                if remainder {
                    remainder_negative
                } else {
                    quotient_negative
                },
            );
        }
    }

    fn shift(&mut self, width: u8, right: bool, signed: bool) {
        let loop_label = self.next_label("shift_loop");
        let done = self.next_label("shift_done");
        self.line(&format!("{loop_label}:"));
        self.jump_if_zero(self.r1.address, &done);
        if right {
            if signed {
                self.lda(self.r0.address + u32::from(width - 1));
                self.line("    asl a");
            } else {
                self.line("    clc");
            }
            for offset in (0..u32::from(width)).rev() {
                self.line(&format!("    ror ${:04X}", self.r0.address + offset));
            }
        } else {
            self.line("    clc");
            for offset in 0..u32::from(width) {
                self.line(&format!("    rol ${:04X}", self.r0.address + offset));
            }
        }
        self.line(&format!("    dec ${:04X}", self.r1.address));
        self.line(&format!("    jmp {loop_label}"));
        self.line(&format!("{done}:"));
    }

    fn logical(&mut self, op: BinaryOp) {
        let true_label = self.next_label("logic_true");
        let false_label = self.next_label("logic_false");
        let done = self.next_label("logic_done");
        match op {
            BinaryOp::And => {
                self.jump_if_zero(self.r0.address, &false_label);
                self.jump_if_zero(self.r1.address, &false_label);
                self.line(&format!("    jmp {true_label}"));
            }
            BinaryOp::Or => {
                self.jump_if_nonzero(self.r0.address, &true_label);
                self.jump_if_nonzero(self.r1.address, &true_label);
                self.line(&format!("    jmp {false_label}"));
            }
            _ => unreachable!(),
        }
        self.line(&format!("{true_label}:"));
        self.load_constant(1, 1);
        self.line(&format!("    jmp {done}"));
        self.line(&format!("{false_label}:"));
        self.load_constant(0, 1);
        self.line(&format!("{done}:"));
    }

    fn emit_short_circuit(
        &mut self,
        left: &Expr,
        op: BinaryOp,
        right: &Expr,
    ) -> Result<(), Diagnostic> {
        let decisive = self.next_label("logical_decisive");
        let done = self.next_label("logical_done");
        let bool_type = Type::Named("bool".to_owned());
        self.emit_expr(left, &bool_type)?;
        match op {
            BinaryOp::And => self.jump_if_zero(self.r0.address, &decisive),
            BinaryOp::Or => self.jump_if_nonzero(self.r0.address, &decisive),
            _ => unreachable!(),
        }
        self.emit_expr(right, &bool_type)?;
        self.line(&format!("    jmp {done}"));
        self.line(&format!("{decisive}:"));
        self.load_constant(i64::from(op == BinaryOp::Or), 1);
        self.line(&format!("{done}:"));
        Ok(())
    }

    fn compare(&mut self, op: BinaryOp, width: u8, signed: bool) {
        let true_label = self.next_label("compare_true");
        let false_label = self.next_label("compare_false");
        let done = self.next_label("compare_done");
        if signed && !matches!(op, BinaryOp::Eq | BinaryOp::Ne) {
            let top = u32::from(width - 1);
            self.lda(self.r0.address + top);
            self.line("    eor #$80");
            self.sta(self.r0.address + top);
            self.lda(self.r1.address + top);
            self.line("    eor #$80");
            self.sta(self.r1.address + top);
        }
        match op {
            BinaryOp::Eq | BinaryOp::Ne => {
                for offset in 0..u32::from(width) {
                    self.lda(self.r0.address + offset);
                    self.line(&format!("    cmp ${:04X}", self.r1.address + offset));
                    self.branch_long(
                        "bne",
                        if op == BinaryOp::Ne {
                            &true_label
                        } else {
                            &false_label
                        },
                    );
                }
                self.line(&format!(
                    "    jmp {}",
                    if op == BinaryOp::Eq {
                        &true_label
                    } else {
                        &false_label
                    }
                ));
            }
            BinaryOp::Lt | BinaryOp::Le => {
                self.jump_if_less(self.r0, self.r1, width, &true_label);
                if op == BinaryOp::Le {
                    self.jump_if_equal(self.r0, self.r1, width, &true_label);
                }
                self.line(&format!("    jmp {false_label}"));
            }
            BinaryOp::Gt | BinaryOp::Ge => {
                self.jump_if_less(self.r0, self.r1, width, &false_label);
                if op == BinaryOp::Gt {
                    self.jump_if_equal(self.r0, self.r1, width, &false_label);
                }
                self.line(&format!("    jmp {true_label}"));
            }
            _ => unreachable!(),
        }
        self.line(&format!("{true_label}:"));
        self.load_constant(1, 1);
        self.line(&format!("    jmp {done}"));
        self.line(&format!("{false_label}:"));
        self.load_constant(0, 1);
        self.line(&format!("{done}:"));
    }

    fn emit_load_place(&mut self, place: &Place, width: u8) -> Result<(), Diagnostic> {
        match self.place_address(place)? {
            Address::Direct(address) => self.copy(
                Storage {
                    address,
                    size: u32::from(width),
                },
                self.r0,
                u32::from(width),
            ),
            Address::Indirect => self.load_indirect(width),
        }
        Ok(())
    }

    fn emit_store_place(&mut self, place: &Place, width: u8) -> Result<(), Diagnostic> {
        let saved = self.model.allocate(u32::from(width))?;
        self.copy(self.r0, saved, u32::from(width));
        match self.place_address(place)? {
            Address::Direct(address) => self.copy(
                saved,
                Storage {
                    address,
                    size: u32::from(width),
                },
                u32::from(width),
            ),
            Address::Indirect => {
                for offset in 0..u32::from(width) {
                    self.lda(saved.address + offset);
                    self.line(&format!("    ldy #${offset:02X}"));
                    self.line(&format!("    sta (${:02X}),y", POINTER_ZP));
                }
            }
        }
        Ok(())
    }

    fn emit_store_aggregate_place(
        &mut self,
        place: &Place,
        source: Storage,
        size: u32,
    ) -> Result<(), Diagnostic> {
        match self.place_address(place)? {
            Address::Direct(address) => self.copy(source, Storage { address, size }, size),
            Address::Indirect => {
                for offset in 0..size {
                    self.lda(source.address + offset);
                    self.line("    ldy #$00");
                    self.line(&format!("    sta (${:02X}),y", POINTER_ZP));
                    if offset + 1 < size {
                        self.increment_zp(POINTER_ZP);
                    }
                }
            }
        }
        Ok(())
    }

    fn copy_indirect_to_storage(&mut self, storage: Storage, size: u32) {
        for offset in 0..size {
            self.line("    ldy #$00");
            self.line(&format!("    lda (${:02X}),y", POINTER_ZP));
            self.sta(storage.address + offset);
            if offset + 1 < size {
                self.increment_zp(POINTER_ZP);
            }
        }
    }

    fn place_address(&mut self, place: &Place) -> Result<Address, Diagnostic> {
        match place {
            Place::Ident(name) => {
                let binding = self.binding(name)?;
                Ok(Address::Direct(binding.storage.address))
            }
            Place::Index { name, index } => {
                self.emit_named_index_address(name, index)?;
                Ok(Address::Indirect)
            }
            Place::Field { base, field } => {
                let binding = self.binding(base)?;
                let layout = self.model.field(&binding.ty, field)?;
                Ok(Address::Direct(binding.storage.address + layout.offset))
            }
            Place::Access(path) => {
                self.emit_access_address(path)?;
                Ok(Address::Indirect)
            }
            Place::Deref(expr) => {
                let Type::Ptr(inner) = self.model.resolved_type(&self.expr_type(expr)?)? else {
                    return Err(Diagnostic::new("dereference requires pointer"));
                };
                self.emit_expr(expr, &Type::Ptr(inner.clone()))?;
                self.copy_result_to_zp();
                Ok(Address::Indirect)
            }
        }
    }

    fn place_type(&self, place: &Place) -> Result<Type, Diagnostic> {
        match place {
            Place::Ident(name) => Ok(self.binding(name)?.ty),
            Place::Index { name, .. } => {
                element_type(&self.model.resolved_type(&self.binding(name)?.ty)?)
            }
            Place::Field { base, field } => {
                Ok(self.model.field(&self.binding(base)?.ty, field)?.ty.clone())
            }
            Place::Access(path) => self.access_type(path),
            Place::Deref(expr) => match self.model.resolved_type(&self.expr_type(expr)?)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
        }
    }

    fn emit_named_index_address(&mut self, name: &str, index: &Expr) -> Result<Type, Diagnostic> {
        let binding = self.binding(name)?;
        let resolved = self.model.resolved_type(&binding.ty)?;
        let element = element_type(&resolved)?;
        let element_size = self.model.type_size(&element)?;
        match resolved {
            Type::Array { .. } => self.set_pointer(binding.storage.address),
            Type::Ptr(_) => {
                self.copy(binding.storage, self.r0, 2);
                self.copy_result_to_zp();
            }
            _ => return Err(Diagnostic::new("indexing requires array or pointer")),
        }
        self.add_index_to_pointer(index, element_size)?;
        Ok(element)
    }

    fn emit_access_address(&mut self, path: &AccessPath) -> Result<(Type, bool), Diagnostic> {
        let binding = self.binding(&path.root)?;
        let mut ty = self.model.resolved_type(&binding.ty)?;
        match &ty {
            Type::Ptr(_) => {
                self.copy(binding.storage, self.r0, 2);
                self.copy_result_to_zp();
                if let Type::Ptr(inner) = ty {
                    ty = *inner;
                }
            }
            _ => self.set_pointer(binding.storage.address),
        }
        for segment in &path.segments {
            match segment {
                AccessSegment::Field(name) => {
                    let field = self.model.field(&ty, name)?.clone();
                    self.add_pointer_constant(field.offset);
                    ty = field.ty;
                }
                AccessSegment::Index(index) => {
                    let element = element_type(&self.model.resolved_type(&ty)?)?;
                    let size = self.model.type_size(&element)?;
                    self.add_index_to_pointer(index, size)?;
                    ty = element;
                }
            }
        }
        Ok((ty, true))
    }

    fn add_index_to_pointer(&mut self, index: &Expr, element_size: u32) -> Result<(), Diagnostic> {
        if let Ok(index) = self.model.const_value(index) {
            let offset = u32::try_from(index)
                .ok()
                .and_then(|index| index.checked_mul(element_size))
                .ok_or_else(|| Diagnostic::new("array index offset overflow"))?;
            self.add_pointer_constant(offset);
            return Ok(());
        }
        let saved_lo = self.model.allocate(2)?;
        self.lda(POINTER_ZP);
        self.sta(saved_lo.address);
        self.lda(POINTER_ZP + 1);
        self.sta(saved_lo.address + 1);
        self.emit_expr(index, &Type::Named("u16".to_owned()))?;
        self.lda(saved_lo.address);
        self.sta(POINTER_ZP);
        self.lda(saved_lo.address + 1);
        self.sta(POINTER_ZP + 1);
        let loop_label = self.next_label("index_scale");
        let done = self.next_label("index_done");
        self.line(&format!("{loop_label}:"));
        self.jump_storage_zero(self.r0, 2, &done);
        self.add_pointer_constant(element_size);
        self.decrement(self.r0, 2);
        self.line(&format!("    jmp {loop_label}"));
        self.line(&format!("{done}:"));
        Ok(())
    }

    fn expr_type(&self, expr: &Expr) -> Result<Type, Diagnostic> {
        match expr {
            Expr::Int(value) => Ok(if (0..=0xFF).contains(value) {
                Type::Named("u8".to_owned())
            } else if (0..=0xFFFF).contains(value) {
                Type::Named("u16".to_owned())
            } else {
                Type::Named("u24".to_owned())
            }),
            Expr::TypedInt(_, ty) | Expr::Cast { ty, .. } => Ok(ty.clone()),
            Expr::Bool(_) => Ok(Type::Named("bool".to_owned())),
            Expr::Char(_) | Expr::In(_) => Ok(Type::Named("u8".to_owned())),
            Expr::String(_) => Ok(Type::Ptr(Box::new(Type::Named("u8".to_owned())))),
            Expr::Ident(name) => self
                .model
                .constant_types
                .get(name)
                .cloned()
                .or_else(|| self.binding(name).ok().map(|binding| binding.ty))
                .ok_or_else(|| Diagnostic::new(format!("unknown value `{name}`"))),
            Expr::Index { name, .. } => {
                element_type(&self.model.resolved_type(&self.binding(name)?.ty)?)
            }
            Expr::Field { base, field } => {
                let constant_name = format!("{base}.{field}");
                if let Some(ty) = self.model.constant_types.get(&constant_name) {
                    Ok(ty.clone())
                } else {
                    Ok(self.model.field(&self.binding(base)?.ty, field)?.ty.clone())
                }
            }
            Expr::AddressOfIndex { name, .. } => Ok(Type::Ptr(Box::new(element_type(
                &self.model.resolved_type(&self.binding(name)?.ty)?,
            )?))),
            Expr::AddressOfField { base, field } => Ok(Type::Ptr(Box::new(
                self.model.field(&self.binding(base)?.ty, field)?.ty.clone(),
            ))),
            Expr::Access(path) => self.access_type(path),
            Expr::AddressOfAccess(path) => Ok(Type::Ptr(Box::new(self.access_type(path)?))),
            Expr::AddressOf(name) => Ok(Type::Ptr(Box::new(self.binding(name)?.ty))),
            Expr::StructInit { ty, .. } => Ok(Type::Named(ty.clone())),
            Expr::Deref(expr) => match self.model.resolved_type(&self.expr_type(expr)?)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
            Expr::Call { path, .. } => self
                .model
                .functions
                .get(&path.join("."))
                .or_else(|| path.last().and_then(|name| self.model.functions.get(name)))
                .and_then(|signature| signature.return_type.clone())
                .ok_or_else(|| Diagnostic::new("void function has no value")),
            Expr::Unary {
                op: UnaryOp::Not, ..
            } => Ok(Type::Named("bool".to_owned())),
            Expr::Unary { expr, .. } => self.expr_type(expr),
            Expr::Binary { left, op, .. }
                if is_comparison(*op) || matches!(op, BinaryOp::And | BinaryOp::Or) =>
            {
                let _ = left;
                Ok(Type::Named("bool".to_owned()))
            }
            Expr::Binary { left, .. } => self.expr_type(left),
            Expr::Array(_) => Err(Diagnostic::new("array type requires context")),
        }
    }

    fn access_type(&self, path: &AccessPath) -> Result<Type, Diagnostic> {
        let mut ty = self.model.resolved_type(&self.binding(&path.root)?.ty)?;
        if let Type::Ptr(inner) = ty {
            ty = *inner;
        }
        for segment in &path.segments {
            ty = match segment {
                AccessSegment::Field(name) => self.model.field(&ty, name)?.ty.clone(),
                AccessSegment::Index(_) => element_type(&self.model.resolved_type(&ty)?)?,
            };
        }
        Ok(ty)
    }

    fn emit_inline_asm(
        &mut self,
        inputs: &[crate::ast::AsmInput],
        outputs: &[crate::ast::AsmOutput],
        lines: &[String],
    ) -> Result<(), Diagnostic> {
        let mut operands = HashMap::new();
        for input in inputs {
            let binding = self.binding(&input.name)?;
            operands.insert(
                input.name.clone(),
                format!("${:04X}", binding.storage.address),
            );
        }
        for output in outputs {
            let binding = self.binding(&output.name)?;
            operands.insert(
                output.name.clone(),
                format!("${:04X}", binding.storage.address),
            );
        }
        for line in lines {
            let mut emitted = line.clone();
            for (name, value) in &operands {
                emitted = emitted.replace(&format!("{{{name}}}"), value);
            }
            if emitted.contains(['{', '}']) {
                return Err(Diagnostic::new(format!(
                    "unknown inline asm operand placeholder in `{line}`"
                )));
            }
            self.line(&format!("    {emitted}"));
        }
        Ok(())
    }

    fn bind(&mut self, name: String, storage: Storage, ty: Type) -> Result<(), Diagnostic> {
        if self
            .scopes
            .iter()
            .rev()
            .any(|scope| scope.contains_key(&name))
        {
            return Err(Diagnostic::new(format!(
                "local `{name}` shadows an existing name"
            )));
        }
        self.scopes
            .last_mut()
            .expect("function scope")
            .insert(name, Binding { storage, ty });
        Ok(())
    }

    fn binding(&self, name: &str) -> Result<Binding, Diagnostic> {
        if let Some(binding) = self.scopes.iter().rev().find_map(|scope| scope.get(name)) {
            return Ok(binding.clone());
        }
        if let Some(storage) = self.model.globals.get(name) {
            return Ok(Binding {
                storage: *storage,
                ty: self.model.global_types[name].clone(),
            });
        }
        Err(Diagnostic::new(format!("unknown variable `{name}`")))
    }

    fn copy(&mut self, source: Storage, target: Storage, size: u32) {
        for offset in 0..size {
            self.lda(source.address + offset);
            self.sta(target.address + offset);
        }
    }

    fn zero(&mut self, storage: Storage) {
        self.lda_imm(0);
        for offset in 0..storage.size {
            self.sta(storage.address + offset);
        }
    }

    fn load_constant(&mut self, value: i64, width: u8) {
        for offset in 0..u32::from(width) {
            self.lda_imm(((value as u64 >> (offset * 8)) & 0xFF) as u8);
            self.sta(self.r0.address + offset);
        }
    }

    fn extend_result(&mut self, source_width: u8, target_width: u8, signed: bool) {
        if target_width <= source_width {
            return;
        }
        if signed {
            let positive = self.next_label("extend_positive");
            let done = self.next_label("extend_done");
            self.lda(self.r0.address + u32::from(source_width - 1));
            self.branch_long("bpl", &positive);
            self.lda_imm(0xFF);
            self.line(&format!("    jmp {done}"));
            self.line(&format!("{positive}:"));
            self.lda_imm(0);
            self.line(&format!("{done}:"));
        } else {
            self.lda_imm(0);
        }
        for offset in u32::from(source_width)..u32::from(target_width) {
            self.sta(self.r0.address + offset);
        }
    }

    fn scale_storage(&mut self, storage: Storage, width: u8, scale: u32) {
        if scale <= 1 {
            return;
        }
        let source = self
            .model
            .allocate(u32::from(width))
            .expect("pointer scale source");
        let result = self
            .model
            .allocate(u32::from(width))
            .expect("pointer scale result");
        self.copy(storage, source, u32::from(width));
        self.zero(result);
        for _ in 0..scale {
            self.copy(result, self.r0, u32::from(width));
            self.copy(source, self.r1, u32::from(width));
            self.add(width);
            self.copy(self.r0, result, u32::from(width));
        }
        self.copy(result, storage, u32::from(width));
    }

    fn normalize_signed_operand(
        &mut self,
        storage: Storage,
        width: u8,
        negative: Storage,
        toggle_sign: bool,
    ) {
        let positive = self.next_label("signed_positive");
        self.lda(storage.address + u32::from(width - 1));
        self.branch_long("bpl", &positive);
        if toggle_sign {
            self.toggle(negative);
        } else {
            self.lda_imm(1);
            self.sta(negative.address);
        }
        self.negate_storage(storage, width);
        self.line(&format!("{positive}:"));
    }

    fn negate_if_flag(&mut self, storage: Storage, width: u8, flag: Storage) {
        let done = self.next_label("sign_done");
        self.jump_if_zero(flag.address, &done);
        self.negate_storage(storage, width);
        self.line(&format!("{done}:"));
    }

    fn negate_storage(&mut self, storage: Storage, width: u8) {
        for offset in 0..u32::from(width) {
            self.lda(storage.address + offset);
            self.line("    eor #$FF");
            self.sta(storage.address + offset);
        }
        self.line("    clc");
        for offset in 0..u32::from(width) {
            self.lda(storage.address + offset);
            self.line(&format!(
                "    adc #${:02X}",
                if offset == 0 { 1 } else { 0 }
            ));
            self.sta(storage.address + offset);
        }
    }

    fn toggle(&mut self, storage: Storage) {
        self.lda(storage.address);
        self.line("    eor #$01");
        self.sta(storage.address);
    }

    fn set_zp_from_storage(&mut self, zero_page: u32, storage: Storage) {
        self.lda(storage.address);
        self.sta(zero_page);
        self.lda(storage.address + 1);
        self.sta(zero_page + 1);
    }

    fn increment_zp(&mut self, zero_page: u32) {
        let done = self.next_label("pointer_incremented");
        self.line(&format!("    inc ${zero_page:02X}"));
        self.branch_long("bne", &done);
        self.line(&format!("    inc ${:02X}", zero_page + 1));
        self.line(&format!("{done}:"));
    }

    fn set_pointer(&mut self, address: u32) {
        self.lda_imm(address as u8);
        self.sta(POINTER_ZP);
        self.lda_imm((address >> 8) as u8);
        self.sta(POINTER_ZP + 1);
    }

    fn add_pointer_constant(&mut self, value: u32) {
        self.line("    clc");
        self.lda(POINTER_ZP);
        self.line(&format!("    adc #${:02X}", value as u8));
        self.sta(POINTER_ZP);
        self.lda(POINTER_ZP + 1);
        self.line(&format!("    adc #${:02X}", (value >> 8) as u8));
        self.sta(POINTER_ZP + 1);
    }

    fn copy_result_to_zp(&mut self) {
        self.lda(self.r0.address);
        self.sta(POINTER_ZP);
        self.lda(self.r0.address + 1);
        self.sta(POINTER_ZP + 1);
    }

    fn copy_zp_to_result(&mut self, width: u8) {
        self.lda(POINTER_ZP);
        self.sta(self.r0.address);
        self.lda(POINTER_ZP + 1);
        self.sta(self.r0.address + 1);
        for offset in 2..u32::from(width) {
            self.lda_imm(0);
            self.sta(self.r0.address + offset);
        }
    }

    fn load_indirect(&mut self, width: u8) {
        for offset in 0..u32::from(width) {
            self.line(&format!("    ldy #${offset:02X}"));
            self.line(&format!("    lda (${:02X}),y", POINTER_ZP));
            self.sta(self.r0.address + offset);
        }
    }

    fn increment(&mut self, storage: Storage, width: u8) {
        let done = self.next_label("increment_done");
        for offset in 0..u32::from(width) {
            self.line(&format!("    inc ${:04X}", storage.address + offset));
            self.branch_long("bne", &done);
        }
        self.line(&format!("{done}:"));
    }

    fn decrement(&mut self, storage: Storage, width: u8) {
        self.line("    sec");
        for offset in 0..u32::from(width) {
            self.lda(storage.address + offset);
            self.line(&format!(
                "    sbc #${:02X}",
                if offset == 0 { 1 } else { 0 }
            ));
            self.sta(storage.address + offset);
        }
    }

    fn jump_storage_zero(&mut self, storage: Storage, width: u8, label: &str) {
        let nonzero = self.next_label("nonzero");
        for offset in 0..u32::from(width) {
            self.jump_if_nonzero(storage.address + offset, &nonzero);
        }
        self.line(&format!("    jmp {label}"));
        self.line(&format!("{nonzero}:"));
    }

    fn jump_if_equal(&mut self, left: Storage, right: Storage, width: u8, label: &str) {
        let different = self.next_label("different");
        for offset in 0..u32::from(width) {
            self.lda(left.address + offset);
            self.line(&format!("    cmp ${:04X}", right.address + offset));
            self.branch_long("bne", &different);
        }
        self.line(&format!("    jmp {label}"));
        self.line(&format!("{different}:"));
    }

    fn jump_if_less(&mut self, left: Storage, right: Storage, width: u8, label: &str) {
        let done = self.next_label("compare_ordered");
        for offset in (0..u32::from(width)).rev() {
            self.lda(left.address + offset);
            self.line(&format!("    cmp ${:04X}", right.address + offset));
            self.branch_long("bcc", label);
            self.branch_long("bne", &done);
        }
        self.line(&format!("{done}:"));
    }

    fn jump_if_zero(&mut self, address: u32, label: &str) {
        self.lda(address);
        self.branch_long("beq", label);
    }

    fn jump_if_nonzero(&mut self, address: u32, label: &str) {
        self.lda(address);
        self.branch_long("bne", label);
    }

    fn branch_long(&mut self, branch: &str, target: &str) {
        let skip = self.next_label("branch_skip");
        let inverse = match branch {
            "beq" => "bne",
            "bne" => "beq",
            "bcc" => "bcs",
            "bcs" => "bcc",
            "bpl" => "bmi",
            "bmi" => "bpl",
            _ => unreachable!("unsupported branch"),
        };
        self.line(&format!("    {inverse} {skip}"));
        self.line(&format!("    jmp {target}"));
        self.line(&format!("{skip}:"));
    }

    fn lda(&mut self, address: u32) {
        self.line(&format!("    lda ${address:04X}"));
    }

    fn sta(&mut self, address: u32) {
        self.line(&format!("    sta ${address:04X}"));
    }

    fn lda_imm(&mut self, value: u8) {
        self.line(&format!("    lda #${value:02X}"));
    }

    fn next_label(&mut self, name: &str) -> String {
        let label = format!(".L_{}_{}", sanitize(name), self.labels);
        self.labels += 1;
        label
    }

    fn line(&mut self, line: &str) {
        self.out.push_str(line);
        self.out.push('\n');
    }
}

enum Address {
    Direct(u32),
    Indirect,
}

fn element_type(ty: &Type) -> Result<Type, Diagnostic> {
    match ty {
        Type::Array { element, .. } | Type::Ptr(element) => Ok((**element).clone()),
        _ => Err(Diagnostic::new("indexing requires array or pointer")),
    }
}

fn type_is_signed(ty: &Type) -> bool {
    matches!(ty, Type::Named(name) if name.starts_with('i'))
}

fn is_comparison(op: BinaryOp) -> bool {
    matches!(
        op,
        BinaryOp::Eq | BinaryOp::Ne | BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge
    )
}

fn assign_binary(op: AssignOp) -> BinaryOp {
    match op {
        AssignOp::Add => BinaryOp::Add,
        AssignOp::Sub => BinaryOp::Sub,
        AssignOp::Mul => BinaryOp::Mul,
        AssignOp::Div => BinaryOp::Div,
        AssignOp::Mod => BinaryOp::Mod,
        AssignOp::BitAnd => BinaryOp::BitAnd,
        AssignOp::BitOr => BinaryOp::BitOr,
        AssignOp::BitXor => BinaryOp::BitXor,
        AssignOp::Shl => BinaryOp::Shl,
        AssignOp::Shr => BinaryOp::Shr,
        AssignOp::Set => unreachable!(),
    }
}

fn reachable_function_names(program: &Program, model: &SemanticModel) -> HashSet<String> {
    let mut graph = HashMap::new();
    let mut roots = vec!["main".to_owned()];

    for declaration in &program.declarations {
        match declaration {
            Declaration::Function(function) => {
                let mut calls = Vec::new();
                collect_stmt_calls(&function.body, &mut calls);
                graph.insert(
                    function.name.clone(),
                    calls
                        .into_iter()
                        .filter_map(|path| resolve_called_function(&path, model))
                        .collect::<Vec<_>>(),
                );
                if function
                    .attrs
                    .iter()
                    .any(|attr| attr == "naked" || attr == "interrupt")
                {
                    roots.push(function.name.clone());
                }
            }
            Declaration::Global(global) => {
                let mut calls = Vec::new();
                collect_expr_calls(&global.value, &mut calls);
                roots.extend(
                    calls
                        .into_iter()
                        .filter_map(|path| resolve_called_function(&path, model)),
                );
            }
            _ => {}
        }
    }

    let mut reachable = HashSet::new();
    let mut pending = roots;
    while let Some(name) = pending.pop() {
        if !reachable.insert(name.clone()) {
            continue;
        }
        if let Some(calls) = graph.get(&name) {
            pending.extend(calls.iter().cloned());
        }
    }
    reachable
}

fn resolve_called_function(path: &[String], model: &SemanticModel) -> Option<String> {
    let qualified = path.join(".");
    if model.functions.contains_key(&qualified) {
        Some(qualified)
    } else {
        path.last()
            .filter(|name| model.functions.contains_key(*name))
            .cloned()
    }
}

fn collect_stmt_calls(stmts: &[Stmt], calls: &mut Vec<Vec<String>>) {
    for stmt in stmts {
        match stmt {
            Stmt::Let { value, .. } | Stmt::Return(Some(value)) | Stmt::Expr(value) => {
                collect_expr_calls(value, calls);
            }
            Stmt::Assign { target, value, .. } => {
                collect_place_calls(target, calls);
                collect_expr_calls(value, calls);
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                collect_expr_calls(condition, calls);
                collect_stmt_calls(then_body, calls);
                collect_stmt_calls(else_body, calls);
            }
            Stmt::While { condition, body } => {
                collect_expr_calls(condition, calls);
                collect_stmt_calls(body, calls);
            }
            Stmt::Loop { body } => collect_stmt_calls(body, calls),
            Stmt::Out { value, .. } => collect_expr_calls(value, calls),
            Stmt::Return(None) | Stmt::Break | Stmt::Continue | Stmt::Asm { .. } => {}
        }
    }
}

fn collect_place_calls(place: &Place, calls: &mut Vec<Vec<String>>) {
    match place {
        Place::Index { index, .. } | Place::Deref(index) => collect_expr_calls(index, calls),
        Place::Access(path) => collect_access_path_calls(path, calls),
        Place::Ident(_) | Place::Field { .. } => {}
    }
}

fn collect_expr_calls(expr: &Expr, calls: &mut Vec<Vec<String>>) {
    match expr {
        Expr::Array(values) => {
            for value in values {
                collect_expr_calls(value, calls);
            }
        }
        Expr::Index { index, .. } | Expr::AddressOfIndex { index, .. } => {
            collect_expr_calls(index, calls);
        }
        Expr::Access(path) | Expr::AddressOfAccess(path) => collect_access_path_calls(path, calls),
        Expr::StructInit { fields, .. } => {
            for (_, value) in fields {
                collect_expr_calls(value, calls);
            }
        }
        Expr::Deref(value) | Expr::Unary { expr: value, .. } | Expr::Cast { expr: value, .. } => {
            collect_expr_calls(value, calls);
        }
        Expr::Call { path, args } => {
            calls.push(path.clone());
            for arg in args {
                collect_expr_calls(arg, calls);
            }
        }
        Expr::Binary { left, right, .. } => {
            collect_expr_calls(left, calls);
            collect_expr_calls(right, calls);
        }
        Expr::Int(_)
        | Expr::TypedInt(_, _)
        | Expr::Bool(_)
        | Expr::Char(_)
        | Expr::String(_)
        | Expr::Ident(_)
        | Expr::In(_)
        | Expr::Field { .. }
        | Expr::AddressOfField { .. }
        | Expr::AddressOf(_) => {}
    }
}

fn collect_access_path_calls(path: &AccessPath, calls: &mut Vec<Vec<String>>) {
    for segment in &path.segments {
        if let AccessSegment::Index(index) = segment {
            collect_expr_calls(index, calls);
        }
    }
}

fn function_label(name: &str) -> String {
    format!("_{}", sanitize(name))
}

fn sanitize(name: &str) -> String {
    name.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(all(test, feature = "mos6502"))]
mod tests {
    use std::path::Path;

    use crate::{asm::AssemblyOptions, parser::parse_program, target::CpuFamily};
    use mos6502::{cpu::CPU, instruction::Nmos6502, memory::Bus, registers::StackPointer};

    use super::*;

    fn emit(source: &str) -> String {
        let program = parse_program(Path::new("test.ezra"), source).unwrap();
        emit_mos6502_assembly_with_options(
            &program,
            AssemblyOptions {
                cpu: CpuFamily::Mos6502,
                load_addr: crate::target::Address24::new(0x0200),
                entry_addr: crate::target::Address24::new(0x0200),
                code_base: crate::target::Address24::new(0x0200),
                stack_top: crate::target::Address24::new(0x01FF),
                ram_base: crate::target::Address24::new(0xA000),
                rodata_base: crate::target::Address24::new(0x8000),
                asset_base: crate::target::Address24::new(0xC000),
                default_sdk_symbols: false,
                ..AssemblyOptions::default()
            },
        )
        .unwrap()
    }

    struct TestBus {
        bytes: Box<[u8; 0x1_0000]>,
    }

    impl TestBus {
        fn new() -> Self {
            Self {
                bytes: Box::new([0; 0x1_0000]),
            }
        }

        fn byte(&self, address: u16) -> u8 {
            self.bytes[usize::from(address)]
        }
    }

    impl Bus for TestBus {
        fn get_byte(&mut self, address: u16) -> u8 {
            self.bytes[usize::from(address)]
        }

        fn set_byte(&mut self, address: u16, value: u8) {
            self.bytes[usize::from(address)] = value;
        }
    }

    fn run(source: &str, instruction_budget: usize) -> TestBus {
        let assembly = emit(source);
        let assembled = crate::vm::assemble_subset_with_symbols_at(
            crate::target::AssemblerCpu::Mos6502,
            &assembly,
            0x0200,
        )
        .unwrap();
        let exit = u16::try_from(
            assembled
                .symbols
                .iter()
                .find(|symbol| symbol.name == "__ezra_exit")
                .expect("emitter exit symbol")
                .addr,
        )
        .unwrap();
        let mut bus = TestBus::new();
        for (offset, byte) in assembled.bytes.iter().copied().enumerate() {
            bus.set_byte(0x0200 + offset as u16, byte);
        }
        let mut cpu = CPU::new(bus, Nmos6502);
        cpu.registers.program_counter = 0x0200;
        cpu.registers.stack_pointer = StackPointer(0xFF);
        for _ in 0..instruction_budget {
            if cpu.registers.program_counter == exit {
                return cpu.memory;
            }
            assert!(
                cpu.single_step(),
                "6502 stopped at ${:04X}\n{assembly}",
                cpu.registers.program_counter
            );
        }
        panic!(
            "6502 execution exceeded {instruction_budget} instructions at ${:04X}\n{assembly}",
            cpu.registers.program_counter
        );
    }

    #[test]
    fn omits_unused_public_functions() {
        let assembly = emit(
            r#"
                pub fn unused_sdk_helper() { }
                fn used_helper() { }
                fn main() { used_helper() }
            "#,
        );

        assert!(assembly.contains("_used_helper:"), "{assembly}");
        assert!(!assembly.contains("_unused_sdk_helper:"), "{assembly}");
    }

    #[test]
    fn emits_core_6502_source_constructs() {
        let assembly = emit(
            r#"
                volatile mmio SCREEN: ptr<u8> = 0xD020
                global counter: u16 = 1
                fn add(value: u16) -> u16 { return value + 2 }
                fn main() {
                    let i: u16 = add(counter)
                    *(SCREEN) = cast<u8>(counter)
                    while i < 10 {
                        counter += 1
                        i += 1
                    }
                }
            "#,
        );
        assert!(assembly.contains("; target: MOS 6502"), "{assembly}");
        assert!(assembly.contains("jsr _add"), "{assembly}");
        assert!(assembly.contains("sta ($F0),y"), "{assembly}");
        assert!(!assembly.contains("ld hl"), "{assembly}");
        crate::vm::assemble_subset_with_symbols_at(
            crate::target::AssemblerCpu::Mos6502,
            &assembly,
            0x0200,
        )
        .unwrap();
    }

    #[test]
    fn emitted_core_program_assembles() {
        let assembly = emit("global value: u8 = 1\nfn main() { value += 2 }");
        crate::vm::assemble_subset_with_symbols_at(
            crate::target::AssemblerCpu::Mos6502,
            &assembly,
            0x0200,
        )
        .unwrap();
    }

    #[test]
    fn complete_language_surface_emits_and_assembles() {
        let assembly = emit(
            r#"
                const COUNT: u8 = 3
                alias Word = u16
                struct Point { x: u8 y: Word }
                volatile mmio DEVICE: ptr<u8> = 0xD000
                embed data: bytes = bytes [1, 2, 3]
                global points: [Point; COUNT] = [
                    Point { x: 1, y: 0x0203 },
                    Point { x: 4, y: 0x0506 }
                ]
                global total: u24 = 0

                fn calculate(a: u16, b: u16) -> u16 {
                    let value: u16 = (a + b) * 2
                    if value > 10 { return value / 2 }
                    return value % 3
                }

                fn factorial(n: u8) -> u8 {
                    if n <= 1 { return 1 }
                    return n * factorial(n - 1)
                }

                interrupt fn irq() { asm volatile { "nop" } }
                naked fn raw() { asm volatile { "nop" "rts" } }

                fn main() {
                    let local: [u8; 3] = [1, 2, 3]
                    let local_copy: [u8; 3] = local
                    let point: Point = Point { x: local[1], y: calculate(4, 8) }
                    let point_copy: Point = point
                    let pointer: ptr<u8> = &point.x
                    *pointer = point.x + 1
                    *(pointer + 1) = factorial(4)
                    total = cast<u24>(point.y)
                    total <<= 1
                    total ^= 0x0000FF
                    if point.x != 0 && total >= 1 {
                        *(DEVICE) = *pointer
                    }
                    let i: u8 = 0
                    while i < COUNT { i += 1 }
                    loop { break }
                    mem.memset(&local[0], 0, 3)
                    mem.memcpy(&local[0], &local_copy[0], 3)
                    asm volatile(clobber a, clobber flags) { "nop" }
                }
            "#,
        );
        crate::vm::assemble_subset_with_symbols_at(
            crate::target::AssemblerCpu::Mos6502,
            &assembly,
            0x0200,
        )
        .unwrap();
    }

    #[test]
    fn executes_integer_arithmetic_and_signed_comparisons() {
        let memory = run(
            r#"
                volatile mmio RESULT0: ptr<u8> = 0xFF00
                volatile mmio RESULT1: ptr<u8> = 0xFF01
                volatile mmio RESULT2: ptr<u8> = 0xFF02
                volatile mmio RESULT3: ptr<u8> = 0xFF03
                fn main() {
                    let product: u16 = (7 + 5) * 3
                    *(RESULT0) = cast<u8>(product)
                    *(RESULT1) = cast<u8>(product / 5)
                    *(RESULT2) = cast<u8>(product % 5)
                    let negative: i16 = -20
                    *(RESULT3) = cast<u8>(negative < -3)
                }
            "#,
            50_000,
        );
        assert_eq!(memory.byte(0xFF00), 36);
        assert_eq!(memory.byte(0xFF01), 7);
        assert_eq!(memory.byte(0xFF02), 1);
        assert_eq!(memory.byte(0xFF03), 1);
    }

    #[test]
    fn executes_calls_and_recursion() {
        let memory = run(
            r#"
                volatile mmio RESULT: ptr<u8> = 0xFF00
                fn factorial(n: u8) -> u8 {
                    if n <= 1 { return 1 }
                    return n * factorial(n - 1)
                }
                fn main() { *(RESULT) = factorial(5) }
            "#,
            100_000,
        );
        assert_eq!(memory.byte(0xFF00), 120);
    }

    #[test]
    fn executes_nested_calls_without_clobbering_outer_arguments() {
        let memory = run(
            r#"
                volatile mmio RESULT: ptr<u8> = 0xFF00
                fn sum(left: u8, right: u8) -> u8 { return left + right }
                fn main() { *(RESULT) = sum(5, sum(2, 3)) }
            "#,
            20_000,
        );
        assert_eq!(memory.byte(0xFF00), 10);
    }

    #[test]
    fn executes_aggregates_pointers_and_memory_builtins() {
        let memory = run(
            r#"
                struct Pair { left: u8 right: u16 }
                volatile mmio RESULT0: ptr<u8> = 0xFF00
                volatile mmio RESULT1: ptr<u8> = 0xFF01
                fn main() {
                    let bytes: [u8; 4] = [1, 2, 3, 4]
                    let copy: [u8; 4] = bytes
                    let pair: Pair = Pair { left: copy[2], right: 0x1234 }
                    let pair_copy: Pair = pair
                    let pointer: ptr<u8> = &bytes[0]
                    *(pointer + 1) = pair_copy.left + 6
                    mem.memset(&copy[0], 0, 4)
                    mem.memcpy(&copy[0], &bytes[0], 4)
                    *(RESULT0) = copy[1]
                    *(RESULT1) = cast<u8>(pair_copy.right)
                }
            "#,
            100_000,
        );
        assert_eq!(memory.byte(0xFF00), 9);
        assert_eq!(memory.byte(0xFF01), 0x34);
    }

    #[test]
    fn executes_short_circuit_boolean_expressions() {
        let memory = run(
            r#"
                volatile mmio RESULT: ptr<u8> = 0xFF00
                global calls: u8 = 0
                fn called() -> bool { calls += 1 return true }
                fn main() {
                    let first: bool = false && called()
                    let second: bool = true || called()
                    *(RESULT) = calls
                }
            "#,
            20_000,
        );
        assert_eq!(memory.byte(0xFF00), 0);
    }

    #[test]
    fn executes_wide_and_signed_arithmetic() {
        let memory = run(
            r#"
                volatile mmio RESULT0: ptr<u8> = 0xFF00
                volatile mmio RESULT1: ptr<u8> = 0xFF01
                volatile mmio RESULT2: ptr<u8> = 0xFF02
                volatile mmio RESULT3: ptr<u8> = 0xFF03
                volatile mmio RESULT4: ptr<u8> = 0xFF04
                fn main() {
                    let wide: u24 = 0x010203 + 0x000102
                    *(RESULT0) = cast<u8>(wide)
                    *(RESULT1) = cast<u8>(wide >> 8)
                    *(RESULT2) = cast<u8>(wide >> 16)
                    let dividend: i16 = -20
                    let divisor: i16 = 3
                    *(RESULT3) = cast<u8>(dividend / divisor)
                    *(RESULT4) = cast<u8>(dividend % divisor)
                }
            "#,
            100_000,
        );
        assert_eq!(memory.byte(0xFF00), 0x05);
        assert_eq!(memory.byte(0xFF01), 0x03);
        assert_eq!(memory.byte(0xFF02), 0x01);
        assert_eq!(memory.byte(0xFF03), 0xFA);
        assert_eq!(memory.byte(0xFF04), 0xFE);
    }

    #[test]
    fn executes_dynamic_indexes_and_loop_control() {
        let memory = run(
            r#"
                struct Point { x: u8 y: u16 }
                volatile mmio RESULT0: ptr<u8> = 0xFF00
                volatile mmio RESULT1: ptr<u8> = 0xFF01
                fn main() {
                    let points: [Point; 2] = [
                        Point { x: 1, y: 0x0203 },
                        Point { x: 4, y: 0x0506 }
                    ]
                    let index: u8 = 1
                    let i: u8 = 0
                    let sum: u8 = 0
                    while i < 6 {
                        i += 1
                        if i == 2 { continue }
                        if i == 5 { break }
                        sum += i
                    }
                    mem.poke8(RESULT0, points[index].x)
                    mem.poke8(RESULT1, sum)
                }
            "#,
            100_000,
        );
        assert_eq!(memory.byte(0xFF00), 4);
        assert_eq!(memory.byte(0xFF01), 8);
    }

    #[test]
    fn executes_global_embed_and_string_initialization() {
        let memory = run(
            r#"
                embed data: bytes = bytes [0x11, 0x22, 0x33]
                global values: [u8; 3] = [4, 5, 6]
                volatile mmio RESULT0: ptr<u8> = 0xFF00
                volatile mmio RESULT1: ptr<u8> = 0xFF01
                volatile mmio RESULT2: ptr<u8> = 0xFF02
                fn main() {
                    let text: ptr<u8> = "OK"
                    *(RESULT0) = values[1]
                    *(RESULT1) = *(data.ptr + 1)
                    *(RESULT2) = *text
                }
            "#,
            20_000,
        );
        assert_eq!(memory.byte(0xFF00), 5);
        assert_eq!(memory.byte(0xFF01), 0x22);
        assert_eq!(memory.byte(0xFF02), b'O');
    }
}
