use std::collections::HashMap;

use crate::{
    asm::AssemblyOptions,
    ast::{BinaryOp, Declaration, Expr, Function, Place, Program, Stmt, Type, UnaryOp},
    diagnostic::Diagnostic,
    hir::HirProgram,
    target::CpuFamily,
    tbir::{
        TbirProgram,
        model::{SemanticModel, Storage},
    },
};

/// Emits a deliberately small, standalone TMS9900 program.
///
/// The generic target owns workspace >8300 and stores source-level scalar state
/// in the target RAM region. This keeps the initial ABI explicit rather than
/// assuming a TI-99/4A console workspace or ROM service.
pub fn emit_tms9900_assembly_with_options(
    program: &Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    if options.cpu != CpuFamily::Tms9900 {
        return Err(Diagnostic::new("TMS9900 emitter requires a TMS9900 target"));
    }
    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    let model = SemanticModel::from_program(
        &tbir.lowered_program,
        16,
        options.ram_base.get(),
        options.rodata_base.get(),
        options.asset_base.get(),
    )?;
    Emitter::new(model).emit(&tbir.lowered_program)
}

struct Emitter {
    model: SemanticModel,
    out: String,
    locals: HashMap<String, Storage>,
    labels: usize,
}

impl Emitter {
    fn new(model: SemanticModel) -> Self {
        Self {
            model,
            out: String::new(),
            locals: HashMap::new(),
            labels: 0,
        }
    }

    fn emit(mut self, program: &Program) -> Result<String, Diagnostic> {
        let main = program
            .main_function()
            .ok_or_else(|| Diagnostic::new("TMS9900 programs require a `main` function"))?;
        self.validate_declarations(program, main)?;
        self.line("; generated by ezrac");
        self.line("; target: standalone TMS9900");
        self.line("section .text");
        self.line("__ezra_start:");
        self.line("    lwpi >8300");
        for declaration in &program.declarations {
            if let Declaration::Global(global) = declaration {
                self.expr(&global.value, "r1")?;
                self.store(self.model.globals[&global.name], "r1");
            }
        }
        self.line("    bl @_main");
        self.line("__ezra_exit:");
        self.line("    jmp __ezra_exit");
        self.line("_main:");
        self.block(&main.body)?;
        self.line("    b *r11");
        self.line("section .rodata");
        self.line("section .data");
        self.line("section .bss");
        Ok(self.out)
    }

    fn validate_declarations(&self, program: &Program, main: &Function) -> Result<(), Diagnostic> {
        if !main.params.is_empty() || main.return_type.is_some() {
            return Err(Diagnostic::new("TMS9900 emitter supports only `fn main()`"));
        }
        for declaration in &program.declarations {
            match declaration {
                Declaration::Function(function) if function.name != "main" => {
                    return Err(Diagnostic::new(format!(
                        "TMS9900 emitter does not yet support function `{}`",
                        function.name
                    )));
                }
                Declaration::ExternAsmFunction(function) => {
                    return Err(Diagnostic::new(format!(
                        "TMS9900 emitter does not support extern function `{}`",
                        function.name
                    )));
                }
                Declaration::Global(global) => self.scalar_type(&global.ty)?,
                Declaration::Const(constant) => self.scalar_type(&constant.ty)?,
                Declaration::Import(_) | Declaration::Function(_) => {}
                _ => {
                    return Err(Diagnostic::new(
                        "TMS9900 emitter currently supports only scalar globals, constants, and `main`",
                    ));
                }
            }
        }
        Ok(())
    }

    fn block(&mut self, body: &[Stmt]) -> Result<(), Diagnostic> {
        for statement in body {
            self.stmt(statement)?;
        }
        Ok(())
    }

    fn stmt(&mut self, statement: &Stmt) -> Result<(), Diagnostic> {
        match statement {
            Stmt::Let { name, ty, value } => {
                self.scalar_type(ty)?;
                let storage = self.model.allocate_type(ty)?;
                self.expr(value, "r1")?;
                self.store(storage, "r1");
                self.locals.insert(name.clone(), storage);
            }
            Stmt::Assign {
                target: Place::Ident(name),
                op,
                value,
            } => {
                let storage = self.lookup(name)?;
                match op {
                    crate::ast::AssignOp::Set => self.expr(value, "r1")?,
                    crate::ast::AssignOp::Add
                    | crate::ast::AssignOp::Sub
                    | crate::ast::AssignOp::BitAnd
                    | crate::ast::AssignOp::BitOr => {
                        self.load(storage, "r1");
                        self.expr(value, "r2")?;
                        match op {
                            crate::ast::AssignOp::Add => self.line("    a r2, r1"),
                            crate::ast::AssignOp::Sub => self.line("    s r2, r1"),
                            crate::ast::AssignOp::BitAnd => {
                                self.line("    inv r2");
                                self.line("    szc r2, r1");
                            }
                            crate::ast::AssignOp::BitOr => self.line("    soc r2, r1"),
                            _ => unreachable!(),
                        }
                    }
                    _ => {
                        return Err(Diagnostic::new(
                            "TMS9900 emitter supports only =, +=, -=, &=, and |= assignments",
                        ));
                    }
                }
                self.store(storage, "r1");
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                self.expr(condition, "r1")?;
                let otherwise = self.label("if_else");
                let end = self.label("if_end");
                self.line("    ci r1, 0");
                self.line(&format!("    jeq {otherwise}"));
                self.block(then_body)?;
                self.line(&format!("    jmp {end}"));
                self.line(&format!("{otherwise}:"));
                self.block(else_body)?;
                self.line(&format!("{end}:"));
            }
            Stmt::Expr(expr) => {
                self.expr(expr, "r1")?;
            }
            Stmt::Return(None) => self.line("    b *r11"),
            _ => {
                return Err(Diagnostic::new(
                    "TMS9900 emitter does not yet support this statement",
                ));
            }
        }
        Ok(())
    }

    fn expr(&mut self, expr: &Expr, register: &str) -> Result<(), Diagnostic> {
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => self.immediate(*value, register),
            Expr::Bool(value) => self.immediate(i64::from(*value), register),
            Expr::Char(value) => self.immediate(i64::from(*value), register),
            Expr::Ident(name) if self.model.constants.contains_key(name) => {
                self.immediate(self.model.constants[name], register)
            }
            Expr::Ident(name) => self.load(self.lookup(name)?, register),
            Expr::Cast { expr, ty } => {
                self.scalar_type(ty)?;
                self.expr(expr, register)?;
            }
            Expr::Unary {
                op: UnaryOp::BitNot,
                expr,
            } => {
                self.expr(expr, register)?;
                self.line(&format!("    inv {register}"));
            }
            Expr::Unary {
                op: UnaryOp::Neg,
                expr,
            } => {
                self.expr(expr, register)?;
                self.line(&format!("    neg {register}"));
            }
            Expr::Binary { left, op, right } => self.binary(left, *op, right, register)?,
            _ => {
                return Err(Diagnostic::new(
                    "TMS9900 emitter supports only scalar literal, identifier, cast, unary, and binary expressions",
                ));
            }
        }
        Ok(())
    }

    fn binary(
        &mut self,
        left: &Expr,
        op: BinaryOp,
        right: &Expr,
        register: &str,
    ) -> Result<(), Diagnostic> {
        self.expr(left, register)?;
        let scratch = if register == "r1" { "r2" } else { "r1" };
        self.expr(right, scratch)?;
        match op {
            BinaryOp::Add => self.line(&format!("    a {scratch}, {register}")),
            BinaryOp::Sub => self.line(&format!("    s {scratch}, {register}")),
            BinaryOp::BitAnd => {
                self.line(&format!("    inv {scratch}"));
                self.line(&format!("    szc {scratch}, {register}"));
            }
            BinaryOp::BitOr => self.line(&format!("    soc {scratch}, {register}")),
            BinaryOp::Eq
            | BinaryOp::Ne
            | BinaryOp::Lt
            | BinaryOp::Le
            | BinaryOp::Gt
            | BinaryOp::Ge => {
                self.line(&format!("    c {scratch}, {register}"));
                let yes = self.label("compare_yes");
                let done = self.label("compare_done");
                let jump = match op {
                    BinaryOp::Eq => "jeq",
                    BinaryOp::Ne => "jne",
                    BinaryOp::Lt => "jlt",
                    BinaryOp::Le => "jle",
                    BinaryOp::Gt => "jgt",
                    BinaryOp::Ge => "jhe",
                    _ => unreachable!(),
                };
                self.line(&format!("    {jump} {yes}"));
                self.line(&format!("    li {register}, 0"));
                self.line(&format!("    jmp {done}"));
                self.line(&format!("{yes}:"));
                self.line(&format!("    li {register}, 1"));
                self.line(&format!("{done}:"));
            }
            _ => {
                return Err(Diagnostic::new(
                    "TMS9900 emitter supports only +, -, &, |, and comparison binary operators",
                ));
            }
        }
        Ok(())
    }

    fn scalar_type(&self, ty: &Type) -> Result<(), Diagnostic> {
        match self.model.resolved_type(ty)? {
            Type::Named(name) if name == "u16" || name == "i16" => Ok(()),
            _ => Err(Diagnostic::new(
                "TMS9900 emitter supports only u16 and i16 scalar storage",
            )),
        }
    }
    fn lookup(&self, name: &str) -> Result<Storage, Diagnostic> {
        self.locals
            .get(name)
            .copied()
            .or_else(|| self.model.globals.get(name).copied())
            .ok_or_else(|| Diagnostic::new(format!("unknown TMS9900 scalar `{name}`")))
    }
    fn immediate(&mut self, value: i64, register: &str) {
        self.line(&format!("    li {register}, >{:04X}", value as u16));
    }
    fn load(&mut self, storage: Storage, register: &str) {
        self.line(&format!("    mov @>{:04X}, {register}", storage.address));
    }
    fn store(&mut self, storage: Storage, register: &str) {
        self.line(&format!("    mov {register}, @>{:04X}", storage.address));
    }
    fn label(&mut self, stem: &str) -> String {
        let label = format!("__ezra_{stem}_{}", self.labels);
        self.labels += 1;
        label
    }
    fn line(&mut self, line: &str) {
        self.out.push_str(line);
        self.out.push('\n');
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        asm::AssemblyOptions,
        parser::parse_program,
        target::{Address24, AssemblerCpu, CpuFamily},
        vm::assemble_subset_with_symbols_at,
    };
    use std::path::Path;

    #[test]
    fn emits_and_assembles_scalar_program() {
        let program = parse_program(
            Path::new("test.ezra"),
            r#"
            const step: u16 = 2
            global counter: u16 = 1
            fn main() { let value: u16 = counter + step; if value == 3 { counter += value } }
        "#,
        )
        .unwrap();
        let assembly = emit_tms9900_assembly_with_options(
            &program,
            AssemblyOptions {
                cpu: CpuFamily::Tms9900,
                ram_base: Address24::new(0xA000),
                ..AssemblyOptions::default()
            },
        )
        .unwrap();
        assert!(assembly.contains("lwpi >8300"), "{assembly}");
        assert!(assembly.contains("section .text"), "{assembly}");
        assemble_subset_with_symbols_at(AssemblerCpu::Tms9900, &assembly, 0).unwrap();
    }

    #[test]
    fn rejects_unsupported_statements() {
        let program = parse_program(Path::new("test.ezra"), "fn main() { while true {} }").unwrap();
        assert!(
            emit_tms9900_assembly_with_options(
                &program,
                AssemblyOptions {
                    cpu: CpuFamily::Tms9900,
                    ram_base: Address24::new(0xA000),
                    ..AssemblyOptions::default()
                }
            )
            .is_err()
        );
    }
}
