use std::collections::HashMap;

use crate::{
    asm::{AssemblyOptions, comments::with_readability_comments},
    ast::{AssignOp, BinaryOp, Declaration, Expr, Function, Place, Program, Stmt, Type, UnaryOp},
    diagnostic::Diagnostic,
    hir::HirProgram,
    target::CpuFamily,
    tbir::{
        TbirProgram,
        model::{SemanticModel, Storage},
    },
};

/// Emit the initial TMS9900 source backend.
///
/// Scalar values are evaluated in `R0`; `R1` and `R2` are compiler scratch
/// registers. Arguments live in target-owned static slots. Calls preserve the
/// active function's static link and locals on the `R10` stack, which keeps the
/// simple static-slot ABI safe for recursive functions.
pub fn emit_tms9900_assembly_with_options(
    program: &Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    if options.cpu != CpuFamily::Tms9900 {
        return Err(Diagnostic::new("TMS9900 emitter requires a TMS9900 target"));
    }
    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    let model = SemanticModel::from_program(
        &tbir.lowered_program,
        16,
        options.ram_base.get(),
        options.rodata_base.get(),
        options.asset_base.get(),
    )?;
    Emitter::new(model, options.clone())
        .emit(&tbir.lowered_program)
        .map(|asm| with_readability_comments(asm, program, &options, "tms9900"))
}

#[derive(Clone)]
struct Binding {
    storage: Storage,
    ty: Type,
}

#[derive(Clone)]
struct LoopLabels {
    continue_label: String,
    break_label: String,
}

struct Emitter {
    model: SemanticModel,
    options: AssemblyOptions,
    out: String,
    labels: usize,
    scopes: Vec<HashMap<String, Binding>>,
    loops: Vec<LoopLabels>,
    return_labels: Vec<String>,
    return_types: Vec<Option<Type>>,
    link_slots: Vec<Storage>,
}

impl Emitter {
    fn new(model: SemanticModel, options: AssemblyOptions) -> Self {
        Self {
            model,
            options,
            out: String::new(),
            labels: 0,
            scopes: Vec::new(),
            loops: Vec::new(),
            return_labels: Vec::new(),
            return_types: Vec::new(),
            link_slots: Vec::new(),
        }
    }

    fn emit(mut self, program: &Program) -> Result<String, Diagnostic> {
        self.line("; generated by ezrac");
        self.line("; target: TMS9900");
        if self.options.load_addr.get() == 0x6000 {
            self.line("; TI-99/4A standard cartridge header and one menu entry.");
            self.line("section .header");
            self.line("    db 0xAA, 1, 1, 0");
            self.line("    dw 0, 0x6010, 0, 0, 0, 0");
            self.line("    dw 0, __ezra_start");
            self.line("    db 4, \"EZRA\", 0");
        }
        self.line("section .text");
        self.line("__ezra_start:");
        self.line("    lwpi >8300");
        self.line(&format!(
            "    li r10, >{:04X}",
            self.options.stack_top.get().min(0xFFFF) & !1
        ));
        self.emit_static_initializers(program)?;
        self.line("    bl @_main");
        self.line("__ezra_exit:");
        self.line("    b @__ezra_exit");
        for declaration in &program.declarations {
            if let Declaration::Function(function) = declaration
                && !function.name.contains('.')
            {
                // Imported qualified names are semantic aliases of the same
                // function. Calls lower to the short assembly label, so
                // emitting dotted aliases would duplicate inline-asm labels.
                self.emit_function(function)?;
            }
        }
        for section in [".header", ".rodata", ".data", ".bss", ".assets", ".scratch"] {
            self.line(&format!("section {section}"));
        }
        Ok(self.out)
    }

    fn emit_static_initializers(&mut self, program: &Program) -> Result<(), Diagnostic> {
        let embeds = self.model.embeds.values().cloned().collect::<Vec<_>>();
        for embed in embeds {
            for (offset, byte) in embed.bytes.iter().copied().enumerate() {
                self.load_immediate(i64::from(byte))?;
                self.store_r0_address(
                    embed.storage.address + offset as u32,
                    &Type::Named("u8".to_owned()),
                )?;
            }
        }
        for declaration in &program.declarations {
            let Declaration::Global(global) = declaration else {
                continue;
            };
            let storage = self.model.globals[&global.name];
            let ty = self.model.resolved_type(&global.ty)?;
            self.emit_expr(&global.value, &ty)?;
            self.store_r0(storage, &ty)?;
        }
        Ok(())
    }

    fn emit_function(&mut self, function: &Function) -> Result<(), Diagnostic> {
        let naked = function.attrs.iter().any(|attr| attr == "naked");
        if naked
            && function.body.iter().any(|stmt| {
                !matches!(stmt, Stmt::Asm { inputs, outputs, .. } if inputs.is_empty() && outputs.is_empty())
            })
        {
            return Err(Diagnostic::new(format!(
                "naked function `{}` may contain only asm blocks without operands",
                function.name
            )));
        }
        if function.attrs.iter().any(|attr| attr == "interrupt") {
            return Err(Diagnostic::new(
                "TMS9900 interrupt functions are not implemented; use a naked assembly wrapper",
            ));
        }

        self.line(&format!("{}:", function_label(&function.name)));
        if naked {
            for stmt in &function.body {
                let Stmt::Asm { lines, .. } = stmt else {
                    unreachable!("naked body was validated above");
                };
                for line in lines {
                    self.line(line);
                }
            }
            return Ok(());
        }

        let link_slot = self.model.allocate(2)?;
        let return_label = self.next_label(&format!("{}_return", function.name));
        self.scopes.push(HashMap::new());
        self.return_labels.push(return_label.clone());
        self.link_slots.push(link_slot);
        self.return_types.push(
            function
                .return_type
                .as_ref()
                .map(|ty| self.model.resolved_type(ty))
                .transpose()?,
        );
        self.line(&format!("    mov r11, @>{:04X}", link_slot.address));

        let signature = self.model.functions[&function.name].clone();
        for (param, slot) in function.params.iter().zip(signature.argument_slots) {
            let ty = self.model.resolved_type(&param.ty)?;
            let storage = self.model.allocate_type(&ty)?;
            self.bind(param.name.clone(), storage, ty.clone())?;
            self.load_r0(slot, &ty)?;
            self.store_r0(storage, &ty)?;
        }
        self.emit_block(&function.body)?;
        self.line(&format!("{return_label}:"));
        self.line(&format!("    mov @>{:04X}, r11", link_slot.address));
        self.line("    b *r11");
        self.return_types.pop();
        self.link_slots.pop();
        self.return_labels.pop();
        self.scopes.pop();
        Ok(())
    }

    fn emit_block(&mut self, body: &[Stmt]) -> Result<(), Diagnostic> {
        for stmt in body {
            self.emit_stmt(stmt)?;
        }
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<(), Diagnostic> {
        match stmt {
            Stmt::Let { name, ty, value } => {
                let ty = self.model.resolved_type(ty)?;
                let storage = self.model.allocate_type(&ty)?;
                self.bind(name.clone(), storage, ty.clone())?;
                self.emit_expr(value, &ty)?;
                self.store_r0(storage, &ty)?;
            }
            Stmt::Assign { target, op, value } => {
                let ty = self.place_type(target)?;
                if *op == AssignOp::Set {
                    self.emit_expr(value, &ty)?;
                } else {
                    self.load_place(target, &ty)?;
                    self.line("    mov r0, r1");
                    self.emit_expr(value, &ty)?;
                    self.emit_binary(assign_binary(*op), &ty)?;
                }
                self.store_place(target, &ty)?;
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                let then = self.next_label("if_then");
                let otherwise = self.next_label("if_else");
                let done = self.next_label("if_end");
                self.emit_expr(condition, &Type::Named("bool".to_owned()))?;
                self.line("    ci r0, 0");
                self.line(&format!("    jne {then}"));
                self.line(&format!("    b @{otherwise}"));
                self.line(&format!("{then}:"));
                self.emit_block(then_body)?;
                self.line(&format!("    b @{done}"));
                self.line(&format!("{otherwise}:"));
                self.emit_block(else_body)?;
                self.line(&format!("{done}:"));
            }
            Stmt::While { condition, body } => {
                let check = self.next_label("while_check");
                let body_label = self.next_label("while_body");
                let done = self.next_label("while_end");
                self.loops.push(LoopLabels {
                    continue_label: check.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{check}:"));
                self.emit_expr(condition, &Type::Named("bool".to_owned()))?;
                self.line("    ci r0, 0");
                self.line(&format!("    jne {body_label}"));
                self.line(&format!("    b @{done}"));
                self.line(&format!("{body_label}:"));
                self.emit_block(body)?;
                self.line(&format!("    b @{check}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Loop { body } => {
                let again = self.next_label("loop");
                let done = self.next_label("loop_end");
                self.loops.push(LoopLabels {
                    continue_label: again.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{again}:"));
                self.emit_block(body)?;
                self.line(&format!("    b @{again}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Break => self.jump_loop(false)?,
            Stmt::Continue => self.jump_loop(true)?,
            Stmt::Return(value) => {
                if let Some(value) = value {
                    let ty = self
                        .return_types
                        .last()
                        .and_then(Clone::clone)
                        .ok_or_else(|| Diagnostic::new("value return in void function"))?;
                    self.emit_expr(value, &ty)?;
                }
                let label = self
                    .return_labels
                    .last()
                    .expect("function return label")
                    .clone();
                self.line(&format!("    b @{label}"));
            }
            Stmt::Asm {
                inputs,
                outputs,
                lines,
                ..
            } => {
                if !inputs.is_empty() || !outputs.is_empty() {
                    return Err(Diagnostic::new(
                        "TMS9900 inline asm operands are not implemented; use compiler-owned RAM or a naked wrapper",
                    ));
                }
                for line in lines {
                    self.line(line);
                }
            }
            Stmt::Out { .. } => {
                return Err(Diagnostic::new(
                    "TMS9900 does not support separate port I/O; use TI-99/4A MMIO or CRU assembly",
                ));
            }
            Stmt::Expr(expr) => self.emit_expr(expr, &Type::Named("u16".to_owned()))?,
        }
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr, ty: &Type) -> Result<(), Diagnostic> {
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => self.load_immediate(*value)?,
            Expr::Bool(value) => self.load_immediate(i64::from(*value))?,
            Expr::Char(value) => self.load_immediate(i64::from(*value))?,
            Expr::Ident(name) => self.load_ident(name, ty)?,
            Expr::AddressOf(name) => {
                let storage = self
                    .model
                    .globals
                    .get(name)
                    .copied()
                    .or_else(|| self.model.embeds.get(name).map(|embed| embed.storage))
                    .ok_or_else(|| {
                        Diagnostic::new(format!(
                            "TMS9900 backend can only take the address of a global or embed, not `{name}`"
                        ))
                    })?;
                self.line(&format!("    li r0, >{:04X}", storage.address));
            }
            Expr::Deref(pointer) => {
                self.emit_expr(pointer, &Type::Ptr(Box::new(ty.clone())))?;
                self.load_indirect_r0(ty)?;
            }
            Expr::Call { path, args } => self.emit_call(path, args)?,
            Expr::Unary { op, expr } => {
                self.emit_expr(expr, ty)?;
                match op {
                    UnaryOp::Neg => self.line("    neg r0"),
                    UnaryOp::BitNot => self.line("    inv r0"),
                    UnaryOp::Not => {
                        let yes = self.next_label("not_true");
                        let done = self.next_label("not_done");
                        self.line("    ci r0, 0");
                        self.line(&format!("    jeq {yes}"));
                        self.line("    clr r0");
                        self.line(&format!("    b @{done}"));
                        self.line(&format!("{yes}:"));
                        self.line("    li r0, 1");
                        self.line(&format!("{done}:"));
                    }
                }
            }
            Expr::Binary { left, op, right } => {
                self.emit_expr(left, ty)?;
                self.line("    mov r0, r1");
                self.emit_expr(right, ty)?;
                self.emit_binary(*op, ty)?;
            }
            Expr::Cast { expr, .. } => self.emit_expr(expr, ty)?,
            Expr::Field { base, field } => self.load_ident(&format!("{base}.{field}"), ty)?,
            Expr::Access(_)
            | Expr::AddressOfAccess(_)
            | Expr::Index { .. }
            | Expr::AddressOfIndex { .. }
            | Expr::AddressOfField { .. }
            | Expr::String(_)
            | Expr::Array(_)
            | Expr::StructInit { .. }
            | Expr::In(_) => {
                return Err(Diagnostic::new(format!(
                    "TMS9900 expression `{expr:?}` is not implemented by the initial source backend"
                )));
            }
        }
        Ok(())
    }

    fn emit_call(&mut self, path: &[String], args: &[Expr]) -> Result<(), Diagnostic> {
        let name = path
            .last()
            .ok_or_else(|| Diagnostic::new("empty function call path"))?;
        let signature = self
            .model
            .functions
            .get(name)
            .ok_or_else(|| {
                Diagnostic::new(format!("unknown TMS9900 function `{}`", path.join(".")))
            })?
            .clone();
        if args.len() != signature.params.len() {
            return Err(Diagnostic::new(format!(
                "function `{name}` expects {} arguments, got {}",
                signature.params.len(),
                args.len()
            )));
        }
        if args.len() > 10 {
            return Err(Diagnostic::new(format!(
                "TMS9900 function `{name}` has {} arguments; the target ABI supports at most 10",
                args.len()
            )));
        }
        self.line("    dect r10");
        self.line("    mov r1, *r10");
        for ((arg, ty), slot) in args
            .iter()
            .zip(&signature.params)
            .zip(signature.argument_slots.iter().copied())
        {
            self.emit_expr(arg, ty)?;
            self.store_r0(slot, ty)?;
        }
        // Static argument slots keep ordinary EZRA functions simple. Loading
        // the same values into R0..R9 also provides a stable ABI for naked
        // platform wrappers, without exposing those slot addresses.
        for (index, (ty, slot)) in signature
            .params
            .iter()
            .zip(signature.argument_slots.iter().copied())
            .enumerate()
        {
            self.load_register(slot, ty, index as u8)?;
        }
        let mut frame = Vec::new();
        if let Some(link_slot) = self.link_slots.last().copied() {
            frame.push((link_slot, 2));
        }
        if let Some(scope) = self.scopes.last() {
            for binding in scope.values() {
                frame.push((binding.storage, scalar_width(&self.model, &binding.ty)?));
            }
        }
        frame.sort_by_key(|(storage, _)| storage.address);

        for (storage, width) in &frame {
            if *width == 1 {
                self.line("    clr r8");
                self.line(&format!("    movb @>{:04X}, r8", storage.address));
            } else {
                self.line(&format!("    mov @>{:04X}, r8", storage.address));
            }
            self.line("    dect r10");
            self.line("    mov r8, *r10");
        }
        self.line(&format!("    bl @{}", function_label(name)));
        self.line("    mov r0, r9");
        for (storage, width) in frame.iter().rev() {
            self.line("    mov *r10+, r8");
            if *width == 1 {
                self.line(&format!("    movb r8, @>{:04X}", storage.address));
            } else {
                self.line(&format!("    mov r8, @>{:04X}", storage.address));
            }
        }
        self.line("    mov *r10+, r1");
        self.line("    mov r9, r0");
        Ok(())
    }

    fn emit_binary(&mut self, op: BinaryOp, ty: &Type) -> Result<(), Diagnostic> {
        match op {
            BinaryOp::Add => {
                self.line("    a r0, r1");
                self.line("    mov r1, r0");
            }
            BinaryOp::Sub => {
                self.line("    s r0, r1");
                self.line("    mov r1, r0");
            }
            BinaryOp::BitAnd => {
                self.line("    inv r0");
                self.line("    szc r0, r1");
                self.line("    mov r1, r0");
            }
            BinaryOp::BitOr => {
                self.line("    soc r0, r1");
                self.line("    mov r1, r0");
            }
            BinaryOp::BitXor => {
                self.line("    xor r0, r1");
                self.line("    mov r1, r0");
            }
            BinaryOp::Shl | BinaryOp::Shr => {
                return Err(Diagnostic::new(
                    "variable shifts are not implemented by the initial TMS9900 source backend",
                ));
            }
            BinaryOp::Eq
            | BinaryOp::Ne
            | BinaryOp::Lt
            | BinaryOp::Le
            | BinaryOp::Gt
            | BinaryOp::Ge => {
                self.line("    c r0, r1");
                let jump = match op {
                    BinaryOp::Eq => "jeq",
                    BinaryOp::Ne => "jne",
                    BinaryOp::Lt => "jlt",
                    BinaryOp::Le => "jle",
                    BinaryOp::Gt => "jgt",
                    BinaryOp::Ge => "jhe",
                    _ => unreachable!(),
                };
                self.emit_boolean_from_jump(jump);
            }
            BinaryOp::And | BinaryOp::Or => {
                self.line("    ci r1, 0");
                let short = self.next_label("logical_short");
                let done = self.next_label("logical_done");
                let jump = if op == BinaryOp::And { "jeq" } else { "jne" };
                self.line(&format!("    {jump} {short}"));
                self.line("    ci r0, 0");
                self.emit_boolean_from_jump("jne");
                self.line(&format!("    b @{done}"));
                self.line(&format!("{short}:"));
                self.load_immediate(i64::from(op == BinaryOp::Or))?;
                self.line(&format!("{done}:"));
            }
            BinaryOp::Mul => self.multiply(type_is_signed(ty)),
            BinaryOp::Div | BinaryOp::Mod => self.divide(
                op == BinaryOp::Mod,
                type_is_signed(ty),
                scalar_width(&self.model, ty)? == 1,
            ),
        }
        if scalar_width(&self.model, ty)? == 1 {
            self.line("    andi r0, >00FF");
        }
        Ok(())
    }

    fn multiply(&mut self, signed: bool) {
        // MPY source, destination stores the high word in destination and the
        // low word in destination + 1. The source expression is in R1 and the
        // right expression is in R0, so R1:R2 receives the product.
        if signed {
            let left_nonnegative = self.next_label("mul_left_nonnegative");
            let right_nonnegative = self.next_label("mul_right_nonnegative");
            let product_nonnegative = self.next_label("mul_product_nonnegative");
            let done = self.next_label("mul_done");
            self.line("    clr r3");
            self.line("    ci r1, 0");
            self.line(&format!("    jhe {left_nonnegative}"));
            self.line("    neg r1");
            self.line("    ai r3, 1");
            self.line(&format!("{left_nonnegative}:"));
            self.line("    ci r0, 0");
            self.line(&format!("    jhe {right_nonnegative}"));
            self.line("    neg r0");
            self.line("    ai r3, 1");
            self.line(&format!("{right_nonnegative}:"));
            self.line("    mpy r0, r1");
            self.line("    andi r3, 1");
            self.line("    ci r3, 0");
            self.line(&format!("    jeq {product_nonnegative}"));
            self.line("    neg r2");
            self.line(&format!("    b @{done}"));
            self.line(&format!("{product_nonnegative}:"));
            self.line(&format!("{done}:"));
            self.line("    mov r2, r0");
        } else {
            self.line("    mpy r0, r1");
            self.line("    mov r2, r0");
        }
    }

    fn divide(&mut self, remainder: bool, signed: bool, byte: bool) {
        // DIV divides the unsigned R2:R3 dividend by its source, leaving the
        // quotient in R2 and remainder in R3. Expressions arrive as left in R1
        // and right in R0, so form a zero-extended 32-bit dividend first.
        if signed {
            if byte {
                self.line("    sla r1, 8");
                self.line("    sra r1, 8");
                self.line("    sla r0, 8");
                self.line("    sra r0, 8");
            }

            let left_nonnegative = self.next_label("div_left_nonnegative");
            let right_nonnegative = self.next_label("div_right_nonnegative");
            let result_nonnegative = self.next_label("div_result_nonnegative");
            self.line("    clr r4");
            self.line("    clr r5");
            self.line("    ci r1, 0");
            self.line(&format!("    jgt {left_nonnegative}"));
            self.line(&format!("    jeq {left_nonnegative}"));
            self.line("    neg r1");
            self.line("    li r5, 1");
            self.line("    ai r4, 1");
            self.line(&format!("{left_nonnegative}:"));
            self.line("    ci r0, 0");
            self.line(&format!("    jgt {right_nonnegative}"));
            self.line(&format!("    jeq {right_nonnegative}"));
            self.line("    neg r0");
            self.line("    ai r4, 1");
            self.line(&format!("{right_nonnegative}:"));
            self.line("    mov r1, r3");
            self.line("    clr r2");
            self.line("    div r0, r2");

            if remainder {
                self.line("    ci r5, 0");
                self.line(&format!("    jeq {result_nonnegative}"));
                self.line("    neg r3");
                self.line(&format!("{result_nonnegative}:"));
                self.line("    mov r3, r0");
            } else {
                self.line("    andi r4, 1");
                self.line("    ci r4, 0");
                self.line(&format!("    jeq {result_nonnegative}"));
                self.line("    neg r2");
                self.line(&format!("{result_nonnegative}:"));
                self.line("    mov r2, r0");
            }
        } else {
            self.line("    mov r1, r3");
            self.line("    clr r2");
            self.line("    div r0, r2");
            self.line(if remainder {
                "    mov r3, r0"
            } else {
                "    mov r2, r0"
            });
        }
    }

    fn emit_boolean_from_jump(&mut self, jump: &str) {
        let yes = self.next_label("comparison_true");
        let done = self.next_label("comparison_done");
        self.line(&format!("    {jump} {yes}"));
        self.line("    clr r0");
        self.line(&format!("    b @{done}"));
        self.line(&format!("{yes}:"));
        self.line("    li r0, 1");
        self.line(&format!("{done}:"));
    }

    fn load_ident(&mut self, name: &str, expected: &Type) -> Result<(), Diagnostic> {
        if let Some(binding) = self.binding(name) {
            return self.load_r0(binding.storage, &binding.ty);
        }
        if let Some(value) = self.model.constants.get(name) {
            return self.load_immediate(*value);
        }
        if let Some(storage) = self.model.globals.get(name) {
            let ty = self
                .model
                .global_types
                .get(name)
                .unwrap_or(expected)
                .clone();
            return self.load_r0(*storage, &ty);
        }
        if let Some((address, ty, _)) = self.model.mmio.get(name) {
            return self.load_address_r0(*address, &ty.clone());
        }
        Err(Diagnostic::new(format!("unknown TMS9900 value `{name}`")))
    }

    fn load_place(&mut self, place: &Place, ty: &Type) -> Result<(), Diagnostic> {
        match place {
            Place::Ident(name) => self.load_ident(name, ty),
            Place::Deref(pointer) => {
                self.emit_expr(pointer, &Type::Ptr(Box::new(ty.clone())))?;
                self.load_indirect_r0(ty)
            }
            _ => Err(Diagnostic::new(
                "this assignment target is not implemented by the initial TMS9900 source backend",
            )),
        }
    }

    fn store_place(&mut self, place: &Place, ty: &Type) -> Result<(), Diagnostic> {
        match place {
            Place::Ident(name) => {
                if let Some(binding) = self.binding(name) {
                    return self.store_r0(binding.storage, &binding.ty);
                }
                if let Some(storage) = self.model.globals.get(name) {
                    let ty = self.model.global_types.get(name).unwrap_or(ty).clone();
                    return self.store_r0(*storage, &ty);
                }
                if let Some((address, target_ty, _)) = self.model.mmio.get(name) {
                    return self.store_r0_address(*address, &target_ty.clone());
                }
                Err(Diagnostic::new(format!(
                    "unknown TMS9900 assignment target `{name}`"
                )))
            }
            Place::Deref(pointer) => {
                self.line("    mov r0, r1");
                self.emit_expr(pointer, &Type::Ptr(Box::new(ty.clone())))?;
                match scalar_width(&self.model, ty)? {
                    1 => {
                        self.line("    swpb r1");
                        self.line("    movb r1, *r0");
                    }
                    2 => self.line("    mov r1, *r0"),
                    _ => unreachable!("scalar_width accepts only one or two bytes"),
                }
                Ok(())
            }
            _ => Err(Diagnostic::new(
                "this assignment target is not implemented by the initial TMS9900 source backend",
            )),
        }
    }

    fn place_type(&self, place: &Place) -> Result<Type, Diagnostic> {
        match place {
            Place::Ident(name) => {
                if let Some(binding) = self.binding(name) {
                    return Ok(binding.ty);
                }
                if let Some(ty) = self.model.global_types.get(name) {
                    return self.model.resolved_type(ty);
                }
                if let Some((_, ty, _)) = self.model.mmio.get(name) {
                    return self.model.resolved_type(ty);
                }
                Err(Diagnostic::new(format!(
                    "unknown TMS9900 assignment target `{name}`"
                )))
            }
            Place::Deref(expr) => match self.model.resolved_type(&self.expr_type(expr)?)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
            _ => Err(Diagnostic::new(
                "this assignment target is not implemented by the initial TMS9900 source backend",
            )),
        }
    }

    fn expr_type(&self, expr: &Expr) -> Result<Type, Diagnostic> {
        match expr {
            Expr::Int(value) => Ok(if (0..=0xFF).contains(value) {
                Type::Named("u8".to_owned())
            } else {
                Type::Named("u16".to_owned())
            }),
            Expr::TypedInt(_, ty) | Expr::Cast { ty, .. } => self.model.resolved_type(ty),
            Expr::Bool(_) => Ok(Type::Named("bool".to_owned())),
            Expr::Char(_) | Expr::In(_) => Ok(Type::Named("u8".to_owned())),
            Expr::Ident(name) => self
                .model
                .constant_types
                .get(name)
                .cloned()
                .or_else(|| self.binding(name).map(|binding| binding.ty))
                .or_else(|| self.model.global_types.get(name).cloned())
                .ok_or_else(|| Diagnostic::new(format!("unknown value `{name}`"))),
            Expr::AddressOf(name) => self
                .model
                .global_types
                .get(name)
                .cloned()
                .map(|ty| Type::Ptr(Box::new(ty)))
                .ok_or_else(|| Diagnostic::new(format!("unknown value `{name}`"))),
            Expr::Field { base, field } => self
                .model
                .constant_types
                .get(&format!("{base}.{field}"))
                .cloned()
                .ok_or_else(|| Diagnostic::new(format!("unknown field `{field}`"))),
            Expr::Call { path, .. } => self
                .model
                .functions
                .get(&path.join("."))
                .or_else(|| path.last().and_then(|name| self.model.functions.get(name)))
                .and_then(|signature| signature.return_type.clone())
                .ok_or_else(|| Diagnostic::new("void function has no value")),
            Expr::Unary { expr, .. } | Expr::Binary { left: expr, .. } => self.expr_type(expr),
            Expr::Deref(expr) => match self.model.resolved_type(&self.expr_type(expr)?)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
            _ => Err(Diagnostic::new(
                "expression type is not implemented by the initial TMS9900 source backend",
            )),
        }
    }

    fn load_indirect_r0(&mut self, ty: &Type) -> Result<(), Diagnostic> {
        match scalar_width(&self.model, ty)? {
            1 => {
                self.line("    mov r0, r1");
                self.line("    clr r0");
                self.line("    movb *r1, r0");
                self.line("    swpb r0");
            }
            2 => self.line("    mov *r0, r0"),
            _ => unreachable!("scalar_width accepts only one or two bytes"),
        }
        Ok(())
    }

    fn load_r0(&mut self, storage: Storage, ty: &Type) -> Result<(), Diagnostic> {
        self.load_register(storage, ty, 0)
    }

    fn load_register(
        &mut self,
        storage: Storage,
        ty: &Type,
        register: u8,
    ) -> Result<(), Diagnostic> {
        self.load_address_register(storage.address, ty, register)
    }

    fn load_address_r0(&mut self, address: u32, ty: &Type) -> Result<(), Diagnostic> {
        self.load_address_register(address, ty, 0)
    }

    fn load_address_register(
        &mut self,
        address: u32,
        ty: &Type,
        register: u8,
    ) -> Result<(), Diagnostic> {
        let register = format!("r{register}");
        match scalar_width(&self.model, ty)? {
            1 => {
                self.line(&format!("    clr {register}"));
                self.line(&format!("    movb @>{address:04X}, {register}"));
                self.line(&format!("    swpb {register}"));
            }
            2 => self.line(&format!("    mov @>{address:04X}, {register}")),
            _ => return Err(Diagnostic::new("TMS9900 source values must fit in 16 bits")),
        }
        Ok(())
    }

    fn store_r0(&mut self, storage: Storage, ty: &Type) -> Result<(), Diagnostic> {
        self.store_r0_address(storage.address, ty)
    }

    fn store_r0_address(&mut self, address: u32, ty: &Type) -> Result<(), Diagnostic> {
        match scalar_width(&self.model, ty)? {
            1 => {
                self.line("    swpb r0");
                self.line(&format!("    movb r0, @>{address:04X}"));
                self.line("    swpb r0");
            }
            2 => self.line(&format!("    mov r0, @>{address:04X}")),
            _ => return Err(Diagnostic::new("TMS9900 source values must fit in 16 bits")),
        }
        Ok(())
    }

    fn load_immediate(&mut self, value: i64) -> Result<(), Diagnostic> {
        if !(-32768..=65535).contains(&value) {
            return Err(Diagnostic::new(format!(
                "TMS9900 immediate `{value}` is outside 16 bits"
            )));
        }
        self.line(&format!("    li r0, >{:04X}", value as u16));
        Ok(())
    }

    fn bind(&mut self, name: String, storage: Storage, ty: Type) -> Result<(), Diagnostic> {
        let scope = self
            .scopes
            .last_mut()
            .ok_or_else(|| Diagnostic::new("local binding outside function"))?;
        if scope
            .insert(name.clone(), Binding { storage, ty })
            .is_some()
        {
            return Err(Diagnostic::new(format!("duplicate local `{name}`")));
        }
        Ok(())
    }

    fn binding(&self, name: &str) -> Option<Binding> {
        self.scopes
            .iter()
            .rev()
            .find_map(|scope| scope.get(name).cloned())
    }

    fn jump_loop(&mut self, continue_loop: bool) -> Result<(), Diagnostic> {
        let labels = self
            .loops
            .last()
            .ok_or_else(|| {
                Diagnostic::new(if continue_loop {
                    "continue outside loop"
                } else {
                    "break outside loop"
                })
            })?
            .clone();
        self.line(&format!(
            "    b @{}",
            if continue_loop {
                labels.continue_label
            } else {
                labels.break_label
            }
        ));
        Ok(())
    }

    fn next_label(&mut self, stem: &str) -> String {
        let label = format!("__ezra_{stem}_{}", self.labels);
        self.labels += 1;
        label
    }

    fn line(&mut self, line: &str) {
        self.out.push_str(line);
        self.out.push('\n');
    }
}

fn scalar_width(model: &SemanticModel, ty: &Type) -> Result<u8, Diagnostic> {
    match model.type_width(ty)? {
        1 | 2 => model.type_width(ty),
        _ => Err(Diagnostic::new("TMS9900 source values must fit in 16 bits")),
    }
}

fn type_is_signed(ty: &Type) -> bool {
    matches!(ty, Type::Named(name) if name == "i8" || name == "i16")
}

fn assign_binary(op: AssignOp) -> BinaryOp {
    match op {
        AssignOp::Set => unreachable!("set assignments bypass binary lowering"),
        AssignOp::Add => BinaryOp::Add,
        AssignOp::Sub => BinaryOp::Sub,
        AssignOp::Mul => BinaryOp::Mul,
        AssignOp::Div => BinaryOp::Div,
        AssignOp::Mod => BinaryOp::Mod,
        AssignOp::BitAnd => BinaryOp::BitAnd,
        AssignOp::BitOr => BinaryOp::BitOr,
        AssignOp::BitXor => BinaryOp::BitXor,
        AssignOp::Shl => BinaryOp::Shl,
        AssignOp::Shr => BinaryOp::Shr,
    }
}

fn function_label(name: &str) -> String {
    format!(
        "_{}",
        name.replace(|ch: char| !ch.is_ascii_alphanumeric() && ch != '_', "_")
    )
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use libre99_core::{
        bus::{Bus, FlatRam},
        cpu::Cpu,
    };

    use super::*;
    use crate::{parser::parse_program, target::AssemblerCpu};

    fn emit(source: &str, options: AssemblyOptions) -> String {
        let program = parse_program(Path::new("test.ezra"), source).unwrap();
        emit_tms9900_assembly_with_options(&program, options).unwrap()
    }

    #[test]
    fn emits_and_executes_scalar_source_on_libre99() {
        let assembly = emit(
            "fn main() { let count: u16 = 41; count = count + 1 }",
            AssemblyOptions {
                cpu: CpuFamily::Tms9900,
                load_addr: crate::target::Address24::new(0x0100),
                entry_addr: crate::target::Address24::new(0x0100),
                code_base: crate::target::Address24::new(0x0100),
                ram_base: crate::target::Address24::new(0xA000),
                ..AssemblyOptions::default()
            },
        );
        let image =
            crate::vm::assemble_subset_with_symbols_at(AssemblerCpu::Tms9900, &assembly, 0x0100)
                .unwrap();
        let mut ram = FlatRam::new();
        ram.load(0x0100, &image.bytes);
        let mut cpu = Cpu::new();
        cpu.set_pc(0x0100);
        for _ in 0..12 {
            cpu.step(&mut ram);
        }

        // The function's static link is at >A000 and its first local follows.
        assert_eq!(ram.read_word(0xA002), 42);
    }

    #[test]
    fn emits_and_executes_unsigned_multiply_on_libre99() {
        let assembly = emit(
            "fn main() { let product: u16 = 123 * 456 }",
            AssemblyOptions {
                cpu: CpuFamily::Tms9900,
                load_addr: crate::target::Address24::new(0x0100),
                entry_addr: crate::target::Address24::new(0x0100),
                code_base: crate::target::Address24::new(0x0100),
                ram_base: crate::target::Address24::new(0xA000),
                ..AssemblyOptions::default()
            },
        );
        let image =
            crate::vm::assemble_subset_with_symbols_at(AssemblerCpu::Tms9900, &assembly, 0x0100)
                .unwrap();
        let mut ram = FlatRam::new();
        ram.load(0x0100, &image.bytes);
        let mut cpu = Cpu::new();
        cpu.set_pc(0x0100);
        for _ in 0..14 {
            cpu.step(&mut ram);
        }

        assert_eq!(ram.read_word(0xA002), 123 * 456);
    }

    #[test]
    fn emits_and_executes_signed_multiply_on_libre99() {
        let assembly = emit(
            "fn main() { let product: i16 = -123 * 456 }",
            AssemblyOptions {
                cpu: CpuFamily::Tms9900,
                load_addr: crate::target::Address24::new(0x0100),
                entry_addr: crate::target::Address24::new(0x0100),
                code_base: crate::target::Address24::new(0x0100),
                ram_base: crate::target::Address24::new(0xA000),
                ..AssemblyOptions::default()
            },
        );
        let image =
            crate::vm::assemble_subset_with_symbols_at(AssemblerCpu::Tms9900, &assembly, 0x0100)
                .unwrap();
        let mut ram = FlatRam::new();
        ram.load(0x0100, &image.bytes);
        let mut cpu = Cpu::new();
        cpu.set_pc(0x0100);
        for _ in 0..28 {
            cpu.step(&mut ram);
        }

        assert_eq!(ram.read_word(0xA002), (123u16 * 456).wrapping_neg());
    }

    #[test]
    fn preserves_static_frames_for_recursive_calls() {
        let assembly = emit(
            r#"
                global recursive_result: u16 = 0

                fn factorial(value: u16) -> u16 {
                    if value == 1 { return 1 }
                    return value * factorial(value - 1)
                }

                fn main() {
                    recursive_result = factorial(6)
                }
            "#,
            AssemblyOptions {
                cpu: CpuFamily::Tms9900,
                load_addr: crate::target::Address24::new(0x0100),
                entry_addr: crate::target::Address24::new(0x0100),
                code_base: crate::target::Address24::new(0x0100),
                stack_top: crate::target::Address24::new(0xFFFE),
                ram_base: crate::target::Address24::new(0xA000),
                ..AssemblyOptions::default()
            },
        );
        let image =
            crate::vm::assemble_subset_with_symbols_at(AssemblerCpu::Tms9900, &assembly, 0x0100)
                .unwrap();
        let mut ram = FlatRam::new();
        ram.load(0x0100, &image.bytes);
        let mut cpu = Cpu::new();
        cpu.set_pc(0x0100);
        for _ in 0..2000 {
            cpu.step(&mut ram);
        }

        assert_eq!(ram.read_word(0xA000), 720);
    }

    #[test]
    fn emits_and_executes_byte_pointer_access_on_libre99() {
        let assembly = emit(
            r#"
                fn main() {
                    let pointer: ptr<u8> = cast<ptr<u8>>(0x9001)
                    *pointer = 0x5A
                    let value: u8 = *pointer
                }
            "#,
            AssemblyOptions {
                cpu: CpuFamily::Tms9900,
                load_addr: crate::target::Address24::new(0x0100),
                entry_addr: crate::target::Address24::new(0x0100),
                code_base: crate::target::Address24::new(0x0100),
                ram_base: crate::target::Address24::new(0xA000),
                ..AssemblyOptions::default()
            },
        );
        let image =
            crate::vm::assemble_subset_with_symbols_at(AssemblerCpu::Tms9900, &assembly, 0x0100)
                .unwrap();
        let mut ram = FlatRam::new();
        ram.load(0x0100, &image.bytes);
        let mut cpu = Cpu::new();
        cpu.set_pc(0x0100);
        for _ in 0..50 {
            cpu.step(&mut ram);
        }

        assert_eq!(ram.read_byte(0x9001), 0x5A);
        assert_eq!(ram.read_byte(0xA004), 0x5A);
    }

    #[test]
    fn emits_and_executes_divide_and_remainder_on_libre99() {
        let assembly = emit(
            r#"
                fn main() {
                    let quotient: u16 = 1000 / 37
                    let remainder: u16 = 1000 % 37
                    let signed_quotient: i16 = -1000 / 37
                    let signed_remainder: i16 = -1000 % 37
                }
            "#,
            AssemblyOptions {
                cpu: CpuFamily::Tms9900,
                load_addr: crate::target::Address24::new(0x0100),
                entry_addr: crate::target::Address24::new(0x0100),
                code_base: crate::target::Address24::new(0x0100),
                ram_base: crate::target::Address24::new(0xA000),
                ..AssemblyOptions::default()
            },
        );
        let image =
            crate::vm::assemble_subset_with_symbols_at(AssemblerCpu::Tms9900, &assembly, 0x0100)
                .unwrap();
        let mut ram = FlatRam::new();
        ram.load(0x0100, &image.bytes);
        let mut cpu = Cpu::new();
        cpu.set_pc(0x0100);
        for _ in 0..200 {
            cpu.step(&mut ram);
        }

        assert_eq!(ram.read_word(0xA002), 1000 / 37);
        assert_eq!(ram.read_word(0xA004), 1000 % 37);
        assert_eq!(ram.read_word(0xA006), (-1000i16 / 37) as u16);
        assert_eq!(ram.read_word(0xA008), (-1000i16 % 37) as u16);
    }

    #[test]
    fn passes_naked_wrapper_arguments_in_registers() {
        let assembly = emit(
            r#"
                naked fn capture(first: u8, second: u8) {
                    asm volatile {
                        "mov r0, @>9000"
                        "mov r1, @>9002"
                        "b *r11"
                    }
                }
                fn main() { capture(0x12, 0x34) }
            "#,
            AssemblyOptions {
                cpu: CpuFamily::Tms9900,
                load_addr: crate::target::Address24::new(0x0100),
                entry_addr: crate::target::Address24::new(0x0100),
                code_base: crate::target::Address24::new(0x0100),
                ram_base: crate::target::Address24::new(0xA000),
                ..AssemblyOptions::default()
            },
        );
        let image =
            crate::vm::assemble_subset_with_symbols_at(AssemblerCpu::Tms9900, &assembly, 0x0100)
                .unwrap();
        let mut ram = FlatRam::new();
        ram.load(0x0100, &image.bytes);
        let mut cpu = Cpu::new();
        cpu.set_pc(0x0100);
        for _ in 0..40 {
            cpu.step(&mut ram);
        }

        assert_eq!(ram.read_word(0x9000), 0x0012);
        assert_eq!(ram.read_word(0x9002), 0x0034);
    }

    #[test]
    fn emits_a_bootable_ti99_cartridge_header() {
        let assembly = emit(
            "fn main() {}",
            AssemblyOptions {
                cpu: CpuFamily::Tms9900,
                load_addr: crate::target::Address24::new(0x6000),
                entry_addr: crate::target::Address24::new(0x6000),
                code_base: crate::target::Address24::new(0x6000),
                ram_base: crate::target::Address24::new(0xA000),
                ..AssemblyOptions::default()
            },
        );
        let image =
            crate::vm::assemble_subset_with_symbols_at(AssemblerCpu::Tms9900, &assembly, 0x6000)
                .unwrap();

        assert_eq!(
            &image.bytes[..16],
            &[0xAA, 1, 1, 0, 0, 0, 0x60, 0x10, 0, 0, 0, 0, 0, 0, 0, 0]
        );
        assert_eq!(
            &image.bytes[16..26],
            &[0, 0, 0x60, 0x1A, 4, b'E', b'Z', b'R', b'A', 0]
        );
    }
}
