use std::collections::{HashMap, HashSet};

use crate::{
    asm::{
        AssemblyOptions,
        comments::with_readability_comments,
        reachability::{RoutineProfile, strip_unreachable_generated_routines},
    },
    ast::{
        AccessPath, AccessSegment, AssignOp, BinaryOp, Declaration, Expr, Function, Place, Program,
        Stmt, Type, UnaryOp,
    },
    declaration::unwrapped_declaration,
    diagnostic::Diagnostic,
    hir::HirProgram,
    regalloc::{
        Location, PhysReg, PhysicalRegister, RegClass, RegUnit, RegisterClass, RegisterUnit,
        SpillClass, SpillClassId, Target,
        source::{SourceLocal, allocate_source_locals},
    },
    target::CpuFamily,
    tbir::{
        TbirProgram,
        model::{SemanticModel, Storage},
    },
};

/// Emit the initial TMS9900 source backend.
///
/// Scalar values are evaluated in `R0`; `R1` through `R5` are arithmetic
/// scratch registers. `R6` through `R8` hold allocated scalar locals but remain
/// volatile across calls and inline assembly. `R9` addresses word-aligned
/// function frames and `R10` is the descending stack pointer, so spills, nested
/// arguments, and recursive calls have independent storage.
pub fn emit_tms9900_assembly_with_options(
    program: &Program,
    options: AssemblyOptions,
) -> Result<String, Diagnostic> {
    if options.cpu != CpuFamily::Tms9900 {
        return Err(Diagnostic::new("TMS9900 emitter requires a TMS9900 target"));
    }
    let hir = HirProgram::from_ast(program)?;
    let tbir = TbirProgram::lower(&hir, program, &options)?;
    let model = SemanticModel::from_program(
        &tbir.lowered_program,
        16,
        options.ram_base.get(),
        options.rodata_base.get(),
        options.asset_base.get(),
    )?;
    Emitter::new(model, options.clone())
        .emit(&tbir.lowered_program)
        .map(|asm| {
            let asm = strip_unreachable_generated_routines(&asm, RoutineProfile::Tms9900);
            with_readability_comments(asm, program, &options, "tms9900", &tbir.source_comments)
        })
}

#[derive(Clone, Copy)]
enum BindingLocation {
    Frame(i16),
    Register(u8),
}

#[derive(Clone)]
struct Binding {
    location: BindingLocation,
    ty: Type,
}

struct FunctionFrame {
    locals: HashMap<String, Binding>,
    local_bytes: u16,
}

#[derive(Clone)]
struct LoopLabels {
    continue_label: String,
    break_label: String,
}

struct Emitter {
    model: SemanticModel,
    options: AssemblyOptions,
    out: String,
    labels: usize,
    scopes: Vec<HashMap<String, Binding>>,
    loops: Vec<LoopLabels>,
    return_labels: Vec<String>,
    return_types: Vec<Option<Type>>,
    local_plans: Vec<HashMap<String, Binding>>,
    runtime_strings: HashMap<String, Storage>,
    functions: HashMap<String, Function>,
    inline_stack: Vec<String>,
    recursive_functions: HashSet<String>,
}

impl Emitter {
    fn new(model: SemanticModel, options: AssemblyOptions) -> Self {
        Self {
            model,
            options,
            out: String::new(),
            labels: 0,
            scopes: Vec::new(),
            loops: Vec::new(),
            return_labels: Vec::new(),
            return_types: Vec::new(),
            local_plans: Vec::new(),
            runtime_strings: HashMap::new(),
            functions: HashMap::new(),
            inline_stack: Vec::new(),
            recursive_functions: HashSet::new(),
        }
    }

    fn emit(mut self, program: &Program) -> Result<String, Diagnostic> {
        self.functions = program
            .declarations
            .iter()
            .filter_map(|declaration| match unwrapped_declaration(declaration) {
                Declaration::Function(function) if !function.name.contains('.') => {
                    Some((function.name.clone(), function.clone()))
                }
                _ => None,
            })
            .collect();
        let reachable = reachable_function_names(program, &self.model);
        self.recursive_functions = recursive_function_names(program, &self.model);
        self.prepare_runtime_strings(program, &reachable)?;
        self.line("; generated by ezrac");
        self.line("; target: TMS9900");
        if self.options.load_addr.get() == 0x6000 {
            self.line("; TI-99/4A standard cartridge header and one menu entry.");
            self.line("section .header");
            self.line("    db 0xAA, 1, 1, 0");
            self.line("    dw 0, 0x6010, 0, 0, 0, 0");
            self.line("    dw 0, __ezra_start");
            self.line("    db 4, \"EZRA\", 0");
        }
        self.line("section .text");
        self.line("__ezra_start:");
        self.line("    lwpi >8300");
        self.line("    clr r9");
        self.line(&format!(
            "    li r10, >{:04X}",
            self.options.stack_top.get().min(0xFFFF) & !1
        ));
        self.emit_static_initializers(program)?;
        self.line("    bl @_main");
        self.line("__ezra_exit:");
        self.line("    b @__ezra_exit");
        for declaration in &program.declarations {
            if let Declaration::Function(function) = unwrapped_declaration(declaration)
                && !function.name.contains('.')
                && reachable.contains(&function.name)
                && (function.name == "main"
                    || !tms_compact_wrapper_candidate(function)
                    || self.recursive_functions.contains(&function.name))
            {
                // Imported qualified names are semantic aliases of the same
                // function. Calls lower to the short assembly label, so
                // emitting dotted aliases would duplicate inline-asm labels.
                self.emit_function(function)?;
            }
        }
        for section in [".header", ".rodata", ".data", ".bss"] {
            self.line(&format!("section {section}"));
        }
        if self.is_ti_cartridge() {
            self.emit_rom_embeds()?;
        } else {
            self.line("section .assets");
        }
        self.line("section .scratch");
        Ok(self.out)
    }

    fn is_ti_cartridge(&self) -> bool {
        self.options.load_addr.get() == 0x6000
    }

    fn emit_rom_embeds(&mut self) -> Result<(), Diagnostic> {
        self.line("section .assets");
        let mut embeds = self
            .model
            .embeds
            .iter()
            .map(|(name, embed)| (name.clone(), embed.clone()))
            .collect::<Vec<_>>();
        embeds.sort_by_key(|(_, embed)| embed.storage.address);
        let mut offset = 0u32;
        for (name, embed) in embeds {
            let embed_offset = embed
                .storage
                .address
                .checked_sub(self.options.asset_base.get())
                .ok_or_else(|| Diagnostic::new("TMS9900 embed is below the asset base"))?;
            if embed_offset > offset {
                self.line(&format!("    ds {}", embed_offset - offset));
            }
            self.line(&format!("{}:", embed_label(&name)));
            for bytes in embed.bytes.chunks(16) {
                let values = bytes
                    .iter()
                    .map(|byte| format!(">{byte:02X}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                self.line(&format!("    db {values}"));
            }
            self.line(&format!("{}:", embed_end_label(&name)));
            offset = embed_offset
                .checked_add(embed.storage.size)
                .ok_or_else(|| Diagnostic::new("TMS9900 embed section is too large"))?;
        }
        Ok(())
    }

    fn prepare_runtime_strings(
        &mut self,
        program: &Program,
        reachable: &HashSet<String>,
    ) -> Result<(), Diagnostic> {
        let mut values = HashSet::new();
        collect_program_strings(program, reachable, &mut values);
        let mut values = values.into_iter().collect::<Vec<_>>();
        values.sort();
        for value in values {
            let size = u32::try_from(value.len() + 1)
                .map_err(|_| Diagnostic::new("string literal is too large"))?;
            let storage = self.model.allocate(size)?;
            self.runtime_strings.insert(value, storage);
        }
        Ok(())
    }

    fn emit_static_initializers(&mut self, program: &Program) -> Result<(), Diagnostic> {
        if !self.is_ti_cartridge() {
            let embeds = self.model.embeds.values().cloned().collect::<Vec<_>>();
            for embed in embeds {
                for (offset, byte) in embed.bytes.iter().copied().enumerate() {
                    self.load_immediate(i64::from(byte))?;
                    self.store_r0_address(
                        embed.storage.address + offset as u32,
                        &Type::Named("u8".to_owned()),
                    )?;
                }
            }
        }
        let strings = self
            .runtime_strings
            .iter()
            .map(|(value, storage)| (value.clone(), *storage))
            .collect::<Vec<_>>();
        for (value, storage) in strings {
            for (offset, byte) in value.bytes().chain(core::iter::once(0)).enumerate() {
                self.load_immediate(i64::from(byte))?;
                self.store_r0_address(
                    storage.address + offset as u32,
                    &Type::Named("u8".to_owned()),
                )?;
            }
        }
        for declaration in &program.declarations {
            let Declaration::Global(global) = unwrapped_declaration(declaration) else {
                continue;
            };
            let storage = self.model.globals[&global.name];
            let ty = self.model.resolved_type(&global.ty)?;
            self.emit_expr(&global.value, &ty)?;
            self.store_r0(storage, &ty)?;
        }
        Ok(())
    }

    fn emit_function(&mut self, function: &Function) -> Result<(), Diagnostic> {
        let naked = function.attrs.iter().any(|attr| attr == "naked");
        if naked
            && function.body.iter().any(|stmt| {
                !matches!(stmt, Stmt::Asm { inputs, outputs, .. } if inputs.is_empty() && outputs.is_empty())
            })
        {
            return Err(Diagnostic::new(format!(
                "naked function `{}` may contain only asm blocks without operands",
                function.name
            )));
        }
        if function.attrs.iter().any(|attr| attr == "interrupt") {
            return Err(Diagnostic::new(
                "TMS9900 interrupt functions are not implemented; use a naked assembly wrapper",
            ));
        }

        self.line(&format!("{}:", function_label(&function.name)));
        if naked {
            for stmt in &function.body {
                let Stmt::Asm { lines, .. } = stmt else {
                    unreachable!("naked body was validated above");
                };
                for line in lines {
                    self.line(line);
                }
            }
            return Ok(());
        }

        let frame = plan_function_frame(function, &self.model)?;
        let return_label = self.next_label(&format!("{}_return", function.name));
        self.scopes.push(HashMap::new());
        self.local_plans.push(frame.locals);
        self.return_labels.push(return_label.clone());
        self.return_types.push(
            function
                .return_type
                .as_ref()
                .map(|ty| self.model.resolved_type(ty))
                .transpose()?,
        );

        self.line("    dect r10");
        self.line("    mov r11, *r10");
        self.line("    dect r10");
        self.line("    mov r9, *r10");
        self.line("    mov r10, r9");
        self.adjust_stack(-i32::from(frame.local_bytes));

        for (index, param) in function.params.iter().enumerate() {
            let ty = self.model.resolved_type(&param.ty)?;
            let offset = 4i16
                .checked_add(i16::try_from(index * 2).map_err(|_| {
                    Diagnostic::new("TMS9900 function parameter frame is too large")
                })?)
                .ok_or_else(|| Diagnostic::new("TMS9900 function parameter frame is too large"))?;
            self.bind(
                param.name.clone(),
                Binding {
                    location: BindingLocation::Frame(offset),
                    ty,
                },
            )?;
        }
        self.emit_block(&function.body)?;
        self.line(&format!("{return_label}:"));
        self.line("    mov r9, r10");
        self.line("    mov *r10+, r9");
        self.line("    mov *r10+, r11");
        self.line("    b *r11");
        self.return_types.pop();
        self.return_labels.pop();
        self.local_plans.pop();
        self.scopes.pop();
        Ok(())
    }

    fn emit_block(&mut self, body: &[Stmt]) -> Result<(), Diagnostic> {
        for stmt in body {
            self.emit_stmt(stmt)?;
        }
        Ok(())
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> Result<(), Diagnostic> {
        match stmt {
            Stmt::Let { name, ty, value } => {
                let ty = self.model.resolved_type(ty)?;
                let binding = self
                    .local_plans
                    .last()
                    .and_then(|locals| locals.get(name))
                    .cloned()
                    .ok_or_else(|| Diagnostic::new(format!("missing frame slot for `{name}`")))?;
                self.bind(name.clone(), binding.clone())?;
                self.emit_expr(value, &ty)?;
                self.store_binding_r0(&binding)?;
            }
            Stmt::Assign { target, op, value } => {
                let ty = self.place_type(target)?;
                if *op == AssignOp::Set {
                    self.emit_expr(value, &ty)?;
                } else {
                    self.load_place(target, &ty)?;
                    self.line("    dect r10");
                    self.line("    mov r0, *r10");
                    self.emit_expr(value, &ty)?;
                    self.line("    mov *r10+, r1");
                    self.emit_binary(assign_binary(*op), &ty)?;
                }
                self.store_place(target, &ty)?;
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                let then = self.next_label("if_then");
                let otherwise = self.next_label("if_else");
                let done = self.next_label("if_end");
                self.emit_expr(condition, &Type::Named("bool".to_owned()))?;
                self.line("    ci r0, 0");
                self.line(&format!("    jne {then}"));
                self.line(&format!("    b @{otherwise}"));
                self.line(&format!("{then}:"));
                self.emit_block(then_body)?;
                self.line(&format!("    b @{done}"));
                self.line(&format!("{otherwise}:"));
                self.emit_block(else_body)?;
                self.line(&format!("{done}:"));
            }
            Stmt::While { condition, body } => {
                let check = self.next_label("while_check");
                let body_label = self.next_label("while_body");
                let done = self.next_label("while_end");
                self.loops.push(LoopLabels {
                    continue_label: check.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{check}:"));
                self.emit_expr(condition, &Type::Named("bool".to_owned()))?;
                self.line("    ci r0, 0");
                self.line(&format!("    jne {body_label}"));
                self.line(&format!("    b @{done}"));
                self.line(&format!("{body_label}:"));
                self.emit_block(body)?;
                self.line(&format!("    b @{check}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Loop { body } => {
                let again = self.next_label("loop");
                let done = self.next_label("loop_end");
                self.loops.push(LoopLabels {
                    continue_label: again.clone(),
                    break_label: done.clone(),
                });
                self.line(&format!("{again}:"));
                self.emit_block(body)?;
                self.line(&format!("    b @{again}"));
                self.line(&format!("{done}:"));
                self.loops.pop();
            }
            Stmt::Break => self.jump_loop(false)?,
            Stmt::Continue => self.jump_loop(true)?,
            Stmt::Return(value) => {
                if let Some(value) = value {
                    let ty = self
                        .return_types
                        .last()
                        .and_then(Clone::clone)
                        .ok_or_else(|| Diagnostic::new("value return in void function"))?;
                    self.emit_expr(value, &ty)?;
                }
                let label = self
                    .return_labels
                    .last()
                    .expect("function return label")
                    .clone();
                self.line(&format!("    b @{label}"));
            }
            Stmt::Asm {
                inputs,
                outputs,
                lines,
                ..
            } => {
                if !inputs.is_empty() || !outputs.is_empty() {
                    return Err(Diagnostic::new(
                        "TMS9900 inline asm operands are not implemented; use compiler-owned RAM or a naked wrapper",
                    ));
                }
                for line in lines {
                    self.line(line);
                }
            }
            Stmt::Out { .. } => {
                return Err(Diagnostic::new(
                    "TMS9900 does not support separate port I/O; use TI-99/4A MMIO or CRU assembly",
                ));
            }
            Stmt::Expr(expr) => self.emit_expr(expr, &Type::Named("u16".to_owned()))?,
        }
        Ok(())
    }

    fn emit_expr(&mut self, expr: &Expr, ty: &Type) -> Result<(), Diagnostic> {
        match expr {
            Expr::Int(value) | Expr::TypedInt(value, _) => self.load_immediate(*value)?,
            Expr::Bool(value) => self.load_immediate(i64::from(*value))?,
            Expr::Char(value) => self.load_immediate(i64::from(*value))?,
            Expr::String(value) => {
                let storage = self
                    .runtime_strings
                    .get(value)
                    .copied()
                    .ok_or_else(|| Diagnostic::new("missing TMS9900 string storage"))?;
                self.load_immediate(i64::from(storage.address))?;
            }
            Expr::Ident(name) => self.load_ident(name, ty)?,
            Expr::AddressOf(name) => {
                if let Some(binding) = self.binding(name) {
                    let BindingLocation::Frame(offset) = binding.location else {
                        return Err(Diagnostic::new(format!(
                            "address-taken local `{name}` was allocated to a register"
                        )));
                    };
                    self.line("    mov r9, r0");
                    self.line(&format!("    ai r0, >{:04X}", offset as u16));
                } else if self.is_ti_cartridge() && self.model.embeds.contains_key(name) {
                    self.line(&format!("    li r0, {}", embed_label(name)));
                } else {
                    let storage = self
                        .model
                        .globals
                        .get(name)
                        .copied()
                        .or_else(|| self.model.embeds.get(name).map(|embed| embed.storage))
                        .ok_or_else(|| {
                            Diagnostic::new(format!(
                                "TMS9900 backend can only take the address of a global or embed, not `{name}`"
                            ))
                        })?;
                    self.line(&format!("    li r0, >{:04X}", storage.address));
                }
            }
            Expr::Deref(pointer) => {
                self.emit_expr(pointer, &Type::Ptr(Box::new(ty.clone())))?;
                self.load_indirect_r0(ty)?;
            }
            Expr::BankedPointer { pointer, .. } => self.emit_expr(pointer, ty)?,
            Expr::Call { path, args } => self.emit_call(path, args)?,
            Expr::Unary { op, expr } => {
                self.emit_expr(expr, ty)?;
                match op {
                    UnaryOp::Neg => self.line("    neg r0"),
                    UnaryOp::BitNot => self.line("    inv r0"),
                    UnaryOp::Not => {
                        let yes = self.next_label("not_true");
                        let done = self.next_label("not_done");
                        self.line("    ci r0, 0");
                        self.line(&format!("    jeq {yes}"));
                        self.line("    clr r0");
                        self.line(&format!("    b @{done}"));
                        self.line(&format!("{yes}:"));
                        self.line("    li r0, 1");
                        self.line(&format!("{done}:"));
                    }
                }
            }
            Expr::Binary { left, op, right } => {
                if matches!(op, BinaryOp::And | BinaryOp::Or) {
                    self.emit_logical_expr(left, *op, right)?;
                } else {
                    let operand_ty = if matches!(
                        op,
                        BinaryOp::Eq
                            | BinaryOp::Ne
                            | BinaryOp::Lt
                            | BinaryOp::Le
                            | BinaryOp::Gt
                            | BinaryOp::Ge
                    ) {
                        self.model.resolved_type(&self.expr_type(left)?)?
                    } else {
                        ty.clone()
                    };
                    self.emit_expr(left, &operand_ty)?;
                    self.line("    mov r0, r1");
                    if matches!(op, BinaryOp::Shl | BinaryOp::Shr)
                        && let Some(count) = constant_shift_count(right)?
                    {
                        self.emit_shift(*op, &operand_ty, Some(count))?;
                    } else {
                        self.line("    dect r10");
                        self.line("    mov r0, *r10");
                        self.emit_expr(right, &operand_ty)?;
                        self.line("    mov *r10+, r1");
                        self.emit_binary(*op, &operand_ty)?;
                    }
                }
            }
            Expr::Cast { expr, .. } => self.emit_expr(expr, ty)?,
            Expr::Field { base, field } => self.load_ident(&format!("{base}.{field}"), ty)?,
            Expr::Access(path)
                if path
                    .segments
                    .iter()
                    .all(|segment| matches!(segment, AccessSegment::Field(_))) =>
            {
                let mut name = path.root.clone();
                for segment in &path.segments {
                    let AccessSegment::Field(field) = segment else {
                        unreachable!()
                    };
                    name.push('.');
                    name.push_str(field);
                }
                self.load_ident(&name, ty)?;
            }
            Expr::Access(_)
            | Expr::AddressOfAccess(_)
            | Expr::Index { .. }
            | Expr::AddressOfIndex { .. }
            | Expr::AddressOfField { .. }
            | Expr::Array(_)
            | Expr::StructInit { .. }
            | Expr::In(_) => {
                return Err(Diagnostic::new(format!(
                    "TMS9900 expression `{expr:?}` is not implemented by the initial source backend"
                )));
            }
        }
        Ok(())
    }

    fn emit_call(&mut self, path: &[String], args: &[Expr]) -> Result<(), Diagnostic> {
        let name = path
            .last()
            .ok_or_else(|| Diagnostic::new("empty function call path"))?;
        if args.is_empty() && self.try_emit_inline_call(name)? {
            return Ok(());
        }
        let signature = self
            .model
            .functions
            .get(name)
            .ok_or_else(|| {
                Diagnostic::new(format!("unknown TMS9900 function `{}`", path.join(".")))
            })?
            .clone();
        if args.len() != signature.params.len() {
            return Err(Diagnostic::new(format!(
                "function `{name}` expects {} arguments, got {}",
                signature.params.len(),
                args.len()
            )));
        }
        if args.len() > 9 {
            return Err(Diagnostic::new(format!(
                "TMS9900 function `{name}` has {} arguments; the target ABI supports at most 9",
                args.len()
            )));
        }
        let argument_bytes = i32::try_from(args.len() * 2)
            .map_err(|_| Diagnostic::new("TMS9900 argument frame is too large"))?;
        self.line("    dect r10");
        self.line("    mov r1, *r10");
        self.adjust_stack(-argument_bytes);
        for (index, (arg, ty)) in args.iter().zip(&signature.params).enumerate() {
            self.emit_expr(arg, ty)?;
            let offset = u16::try_from(index * 2)
                .map_err(|_| Diagnostic::new("TMS9900 argument frame is too large"))?;
            self.line(&format!("    mov r0, @>{offset:04X}(r10)"));
        }
        // Compiled functions read arguments from their stack frame. Mirroring
        // the first nine values in R0..R8 preserves the naked SDK wrapper ABI.
        for index in 0..args.len() {
            let offset = u16::try_from(index * 2)
                .map_err(|_| Diagnostic::new("TMS9900 argument frame is too large"))?;
            self.line(&format!("    mov @>{offset:04X}(r10), r{index}"));
        }
        self.line(&format!("    bl @{}", function_label(name)));
        self.adjust_stack(argument_bytes);
        self.line("    mov *r10+, r1");
        Ok(())
    }

    fn try_emit_inline_call(&mut self, name: &str) -> Result<bool, Diagnostic> {
        let Some(function) = self.functions.get(name).cloned() else {
            return Ok(false);
        };
        let Some(body) = inline_void_body(&function) else {
            return Ok(false);
        };
        if !tms_compact_wrapper_candidate(&function)
            || self.recursive_functions.contains(name)
            || self.inline_stack.iter().any(|active| active == name)
        {
            return Ok(false);
        }

        self.inline_stack.push(name.to_owned());
        let result = self.emit_block(body);
        self.inline_stack.pop();
        result?;
        Ok(true)
    }

    fn emit_logical_expr(
        &mut self,
        left: &Expr,
        op: BinaryOp,
        right: &Expr,
    ) -> Result<(), Diagnostic> {
        let short = self.next_label("logical_short");
        let done = self.next_label("logical_done");
        self.emit_expr(left, &Type::Named("bool".to_owned()))?;
        self.line("    ci r0, 0");
        let jump = if op == BinaryOp::And { "jeq" } else { "jne" };
        self.line(&format!("    {jump} {short}"));
        self.emit_expr(right, &Type::Named("bool".to_owned()))?;
        self.line("    ci r0, 0");
        self.emit_boolean_from_jump("jne");
        self.line(&format!("    b @{done}"));
        self.line(&format!("{short}:"));
        self.load_immediate(i64::from(op == BinaryOp::Or))?;
        self.line(&format!("{done}:"));
        Ok(())
    }

    fn emit_binary(&mut self, op: BinaryOp, ty: &Type) -> Result<(), Diagnostic> {
        match op {
            BinaryOp::Add => {
                self.line("    a r0, r1");
                self.line("    mov r1, r0");
            }
            BinaryOp::Sub => {
                self.line("    s r0, r1");
                self.line("    mov r1, r0");
            }
            BinaryOp::BitAnd => {
                self.line("    inv r0");
                self.line("    szc r0, r1");
                self.line("    mov r1, r0");
            }
            BinaryOp::BitOr => {
                self.line("    soc r0, r1");
                self.line("    mov r1, r0");
            }
            BinaryOp::BitXor => {
                self.line("    xor r0, r1");
                self.line("    mov r1, r0");
            }
            BinaryOp::Shl | BinaryOp::Shr => self.emit_shift(op, ty, None)?,
            BinaryOp::Eq
            | BinaryOp::Ne
            | BinaryOp::Lt
            | BinaryOp::Le
            | BinaryOp::Gt
            | BinaryOp::Ge => {
                self.line("    c r1, r0");
                let signed = type_is_signed(ty);
                match (op, signed) {
                    (BinaryOp::Eq, _) => self.emit_boolean_from_jump("jeq"),
                    (BinaryOp::Ne, _) => self.emit_boolean_from_jump("jne"),
                    (BinaryOp::Lt, true) => self.emit_boolean_from_jump("jlt"),
                    (BinaryOp::Le, true) => self.emit_boolean_from_jumps(&["jlt", "jeq"]),
                    (BinaryOp::Gt, true) => self.emit_boolean_from_jump("jgt"),
                    (BinaryOp::Ge, true) => self.emit_boolean_from_jumps(&["jgt", "jeq"]),
                    (BinaryOp::Lt, false) => self.emit_boolean_from_jump("jl"),
                    (BinaryOp::Le, false) => self.emit_boolean_from_jump("jle"),
                    (BinaryOp::Gt, false) => self.emit_boolean_from_jump("jh"),
                    (BinaryOp::Ge, false) => self.emit_boolean_from_jump("jhe"),
                    _ => unreachable!(),
                }
            }
            BinaryOp::And | BinaryOp::Or => {
                unreachable!("logical expressions are emitted before evaluating the right operand")
            }
            BinaryOp::Mul => self.multiply(type_is_signed(ty)),
            BinaryOp::Div | BinaryOp::Mod => self.divide(
                op == BinaryOp::Mod,
                type_is_signed(ty),
                scalar_width(&self.model, ty)? == 1,
            ),
        }
        if scalar_width(&self.model, ty)? == 1 {
            self.line("    andi r0, >00FF");
        }
        Ok(())
    }

    fn emit_shift(
        &mut self,
        op: BinaryOp,
        ty: &Type,
        constant_count: Option<u16>,
    ) -> Result<(), Diagnostic> {
        let right = op == BinaryOp::Shr;
        let signed = type_is_signed(ty);
        let byte = scalar_width(&self.model, ty)? == 1;

        if right && signed && byte {
            self.line("    sla r1, 8");
            self.line("    sra r1, 8");
        }

        if let Some(count) = constant_count {
            if count == 0 {
                self.line("    mov r1, r0");
            } else if count < 16 {
                let mnemonic = if right && signed {
                    "sra"
                } else if right {
                    "srl"
                } else {
                    "sla"
                };
                self.line(&format!("    {mnemonic} r1, {count}"));
                self.line("    mov r1, r0");
            } else if right && signed {
                self.line("    sra r1, 15");
                self.line("    mov r1, r0");
            } else {
                self.line("    clr r0");
            }
            return Ok(());
        }

        let zero = self.next_label("shift_zero");
        let overflow = self.next_label("shift_overflow");
        let done = self.next_label("shift_done");
        self.line("    ci r0, 0");
        self.line(&format!("    jeq {zero}"));
        self.line("    ci r0, 15");
        self.line(&format!("    jh {overflow}"));
        // Per the TI TMS9900 Programmer's Guide, a zero instruction count takes
        // the count from the low four bits of R0. Expression evaluation already
        // places the value in R1 and the runtime count in R0.
        let mnemonic = if right && signed {
            "sra"
        } else if right {
            "srl"
        } else {
            "sla"
        };
        self.line(&format!("    {mnemonic} r1, 0"));
        self.line("    mov r1, r0");
        self.line(&format!("    b @{done}"));
        self.line(&format!("{zero}:"));
        self.line("    mov r1, r0");
        self.line(&format!("    b @{done}"));
        self.line(&format!("{overflow}:"));
        if right && signed {
            self.line("    sra r1, 15");
            self.line("    mov r1, r0");
        } else {
            self.line("    clr r0");
        }
        self.line(&format!("{done}:"));
        Ok(())
    }

    fn multiply(&mut self, signed: bool) {
        // MPY source, destination stores the high word in destination and the
        // low word in destination + 1. The source expression is in R1 and the
        // right expression is in R0, so R1:R2 receives the product.
        if signed {
            let left_nonnegative = self.next_label("mul_left_nonnegative");
            let right_nonnegative = self.next_label("mul_right_nonnegative");
            let product_nonnegative = self.next_label("mul_product_nonnegative");
            let done = self.next_label("mul_done");
            self.line("    clr r3");
            self.line("    ci r1, 0");
            self.line(&format!("    jhe {left_nonnegative}"));
            self.line("    neg r1");
            self.line("    ai r3, 1");
            self.line(&format!("{left_nonnegative}:"));
            self.line("    ci r0, 0");
            self.line(&format!("    jhe {right_nonnegative}"));
            self.line("    neg r0");
            self.line("    ai r3, 1");
            self.line(&format!("{right_nonnegative}:"));
            self.line("    mpy r0, r1");
            self.line("    andi r3, 1");
            self.line("    ci r3, 0");
            self.line(&format!("    jeq {product_nonnegative}"));
            self.line("    neg r2");
            self.line(&format!("    b @{done}"));
            self.line(&format!("{product_nonnegative}:"));
            self.line(&format!("{done}:"));
            self.line("    mov r2, r0");
        } else {
            self.line("    mpy r0, r1");
            self.line("    mov r2, r0");
        }
    }

    fn divide(&mut self, remainder: bool, signed: bool, byte: bool) {
        // DIV divides the unsigned R2:R3 dividend by its source, leaving the
        // quotient in R2 and remainder in R3. Expressions arrive as left in R1
        // and right in R0, so form a zero-extended 32-bit dividend first.
        let zero = self.next_label("div_zero");
        let done = self.next_label("div_done");
        self.line("    ci r0, 0");
        self.line(&format!("    jeq {zero}"));
        if signed {
            if byte {
                self.line("    sla r1, 8");
                self.line("    sra r1, 8");
                self.line("    sla r0, 8");
                self.line("    sra r0, 8");
            }

            let left_nonnegative = self.next_label("div_left_nonnegative");
            let right_nonnegative = self.next_label("div_right_nonnegative");
            let result_nonnegative = self.next_label("div_result_nonnegative");
            self.line("    clr r4");
            self.line("    clr r5");
            self.line("    ci r1, 0");
            self.line(&format!("    jgt {left_nonnegative}"));
            self.line(&format!("    jeq {left_nonnegative}"));
            self.line("    neg r1");
            self.line("    li r5, 1");
            self.line("    ai r4, 1");
            self.line(&format!("{left_nonnegative}:"));
            self.line("    ci r0, 0");
            self.line(&format!("    jgt {right_nonnegative}"));
            self.line(&format!("    jeq {right_nonnegative}"));
            self.line("    neg r0");
            self.line("    ai r4, 1");
            self.line(&format!("{right_nonnegative}:"));
            self.line("    mov r1, r3");
            self.line("    clr r2");
            self.line("    div r0, r2");

            if remainder {
                self.line("    ci r5, 0");
                self.line(&format!("    jeq {result_nonnegative}"));
                self.line("    neg r3");
                self.line(&format!("{result_nonnegative}:"));
                self.line("    mov r3, r0");
            } else {
                self.line("    andi r4, 1");
                self.line("    ci r4, 0");
                self.line(&format!("    jeq {result_nonnegative}"));
                self.line("    neg r2");
                self.line(&format!("{result_nonnegative}:"));
                self.line("    mov r2, r0");
            }
        } else {
            self.line("    mov r1, r3");
            self.line("    clr r2");
            self.line("    div r0, r2");
            self.line(if remainder {
                "    mov r3, r0"
            } else {
                "    mov r2, r0"
            });
        }
        self.line(&format!("    b @{done}"));
        self.line(&format!("{zero}:"));
        self.line("    clr r0");
        self.line(&format!("{done}:"));
    }

    fn emit_boolean_from_jump(&mut self, jump: &str) {
        self.emit_boolean_from_jumps(&[jump]);
    }

    fn emit_boolean_from_jumps(&mut self, jumps: &[&str]) {
        let yes = self.next_label("comparison_true");
        let done = self.next_label("comparison_done");
        for jump in jumps {
            self.line(&format!("    {jump} {yes}"));
        }
        self.line("    clr r0");
        self.line(&format!("    b @{done}"));
        self.line(&format!("{yes}:"));
        self.line("    li r0, 1");
        self.line(&format!("{done}:"));
    }

    fn load_ident(&mut self, name: &str, expected: &Type) -> Result<(), Diagnostic> {
        if let Some(binding) = self.binding(name) {
            return self.load_binding_r0(&binding);
        }
        if self.is_ti_cartridge() {
            if let Some(embed_name) = name.strip_suffix(".ptr")
                && self.model.embeds.contains_key(embed_name)
            {
                self.line(&format!("    li r0, {}", embed_label(embed_name)));
                return Ok(());
            }
            if let Some(embed_name) = name.strip_suffix(".end")
                && self.model.embeds.contains_key(embed_name)
            {
                self.line(&format!("    li r0, {}", embed_end_label(embed_name)));
                return Ok(());
            }
        }
        if let Some(value) = self.model.constants.get(name) {
            return self.load_immediate(*value);
        }
        if let Some(storage) = self.model.globals.get(name) {
            let ty = self
                .model
                .global_types
                .get(name)
                .unwrap_or(expected)
                .clone();
            return self.load_r0(*storage, &ty);
        }
        if let Some((address, ty, _)) = self.model.mmio.get(name) {
            return self.load_address_r0(*address, &ty.clone());
        }
        Err(Diagnostic::new(format!("unknown TMS9900 value `{name}`")))
    }

    fn load_place(&mut self, place: &Place, ty: &Type) -> Result<(), Diagnostic> {
        match place {
            Place::Ident(name) => self.load_ident(name, ty),
            Place::Deref(pointer) => {
                self.emit_expr(pointer, &Type::Ptr(Box::new(ty.clone())))?;
                self.load_indirect_r0(ty)
            }
            _ => Err(Diagnostic::new(
                "this assignment target is not implemented by the initial TMS9900 source backend",
            )),
        }
    }

    fn store_place(&mut self, place: &Place, ty: &Type) -> Result<(), Diagnostic> {
        match place {
            Place::Ident(name) => {
                if let Some(binding) = self.binding(name) {
                    return self.store_binding_r0(&binding);
                }
                if let Some(storage) = self.model.globals.get(name) {
                    let ty = self.model.global_types.get(name).unwrap_or(ty).clone();
                    return self.store_r0(*storage, &ty);
                }
                if let Some((address, target_ty, _)) = self.model.mmio.get(name) {
                    return self.store_r0_address(*address, &target_ty.clone());
                }
                Err(Diagnostic::new(format!(
                    "unknown TMS9900 assignment target `{name}`"
                )))
            }
            Place::Deref(pointer) => {
                self.line("    mov r0, r1");
                self.emit_expr(pointer, &Type::Ptr(Box::new(ty.clone())))?;
                match scalar_width(&self.model, ty)? {
                    1 => {
                        self.line("    swpb r1");
                        self.line("    movb r1, *r0");
                    }
                    2 => self.line("    mov r1, *r0"),
                    _ => unreachable!("scalar_width accepts only one or two bytes"),
                }
                Ok(())
            }
            _ => Err(Diagnostic::new(
                "this assignment target is not implemented by the initial TMS9900 source backend",
            )),
        }
    }

    fn place_type(&self, place: &Place) -> Result<Type, Diagnostic> {
        match place {
            Place::Ident(name) => {
                if let Some(binding) = self.binding(name) {
                    return Ok(binding.ty);
                }
                if let Some(ty) = self.model.global_types.get(name) {
                    return self.model.resolved_type(ty);
                }
                if let Some((_, ty, _)) = self.model.mmio.get(name) {
                    return self.model.resolved_type(ty);
                }
                Err(Diagnostic::new(format!(
                    "unknown TMS9900 assignment target `{name}`"
                )))
            }
            Place::Deref(expr) => match self.model.resolved_type(&self.expr_type(expr)?)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
            _ => Err(Diagnostic::new(
                "this assignment target is not implemented by the initial TMS9900 source backend",
            )),
        }
    }

    fn expr_type(&self, expr: &Expr) -> Result<Type, Diagnostic> {
        match expr {
            Expr::Int(value) => Ok(if (0..=0xFF).contains(value) {
                Type::Named("u8".to_owned())
            } else {
                Type::Named("u16".to_owned())
            }),
            Expr::TypedInt(_, ty) | Expr::Cast { ty, .. } => self.model.resolved_type(ty),
            Expr::Bool(_) => Ok(Type::Named("bool".to_owned())),
            Expr::Char(_) | Expr::In(_) => Ok(Type::Named("u8".to_owned())),
            Expr::String(_) => Ok(Type::Ptr(Box::new(Type::Named("u8".to_owned())))),
            Expr::Ident(name) => self
                .model
                .constant_types
                .get(name)
                .cloned()
                .or_else(|| self.binding(name).map(|binding| binding.ty))
                .or_else(|| self.model.global_types.get(name).cloned())
                .ok_or_else(|| Diagnostic::new(format!("unknown value `{name}`"))),
            Expr::AddressOf(name) => self
                .binding(name)
                .map(|binding| binding.ty)
                .or_else(|| self.model.global_types.get(name).cloned())
                .map(|ty| Type::Ptr(Box::new(ty)))
                .ok_or_else(|| Diagnostic::new(format!("unknown value `{name}`"))),
            Expr::Field { base, field } => self
                .model
                .constant_types
                .get(&format!("{base}.{field}"))
                .cloned()
                .ok_or_else(|| Diagnostic::new(format!("unknown field `{field}`"))),
            Expr::Call { path, .. } => self
                .model
                .functions
                .get(&path.join("."))
                .or_else(|| path.last().and_then(|name| self.model.functions.get(name)))
                .and_then(|signature| signature.return_type.clone())
                .ok_or_else(|| Diagnostic::new("void function has no value")),
            Expr::Unary { expr, .. } | Expr::Binary { left: expr, .. } => self.expr_type(expr),
            Expr::Deref(expr) => match self.model.resolved_type(&self.expr_type(expr)?)? {
                Type::Ptr(inner) => Ok(*inner),
                _ => Err(Diagnostic::new("dereference requires pointer")),
            },
            _ => Err(Diagnostic::new(
                "expression type is not implemented by the initial TMS9900 source backend",
            )),
        }
    }

    fn load_indirect_r0(&mut self, ty: &Type) -> Result<(), Diagnostic> {
        match scalar_width(&self.model, ty)? {
            1 => {
                self.line("    mov r0, r1");
                self.line("    clr r0");
                self.line("    movb *r1, r0");
                self.line("    swpb r0");
            }
            2 => self.line("    mov *r0, r0"),
            _ => unreachable!("scalar_width accepts only one or two bytes"),
        }
        Ok(())
    }

    fn load_binding_r0(&mut self, binding: &Binding) -> Result<(), Diagnostic> {
        match binding.location {
            BindingLocation::Frame(offset) => self.load_frame_r0(offset, &binding.ty),
            BindingLocation::Register(register) => {
                self.line(&format!("    mov r{register}, r0"));
                if scalar_width(&self.model, &binding.ty)? == 1 {
                    self.line("    andi r0, >00FF");
                }
                Ok(())
            }
        }
    }

    fn store_binding_r0(&mut self, binding: &Binding) -> Result<(), Diagnostic> {
        match binding.location {
            BindingLocation::Frame(offset) => self.store_frame_r0(offset, &binding.ty),
            BindingLocation::Register(register) => {
                if scalar_width(&self.model, &binding.ty)? == 1 {
                    self.line("    andi r0, >00FF");
                }
                self.line(&format!("    mov r0, r{register}"));
                Ok(())
            }
        }
    }

    fn load_frame_r0(&mut self, offset: i16, ty: &Type) -> Result<(), Diagnostic> {
        self.line(&format!("    mov @>{:04X}(r9), r0", offset as u16));
        if scalar_width(&self.model, ty)? == 1 {
            self.line("    andi r0, >00FF");
        }
        Ok(())
    }

    fn store_frame_r0(&mut self, offset: i16, ty: &Type) -> Result<(), Diagnostic> {
        if scalar_width(&self.model, ty)? == 1 {
            self.line("    andi r0, >00FF");
        }
        self.line(&format!("    mov r0, @>{:04X}(r9)", offset as u16));
        Ok(())
    }

    fn adjust_stack(&mut self, amount: i32) {
        if amount != 0 {
            self.line(&format!("    ai r10, >{:04X}", amount as i16 as u16));
        }
    }

    fn load_r0(&mut self, storage: Storage, ty: &Type) -> Result<(), Diagnostic> {
        self.load_register(storage, ty, 0)
    }

    fn load_register(
        &mut self,
        storage: Storage,
        ty: &Type,
        register: u8,
    ) -> Result<(), Diagnostic> {
        self.load_address_register(storage.address, ty, register)
    }

    fn load_address_r0(&mut self, address: u32, ty: &Type) -> Result<(), Diagnostic> {
        self.load_address_register(address, ty, 0)
    }

    fn load_address_register(
        &mut self,
        address: u32,
        ty: &Type,
        register: u8,
    ) -> Result<(), Diagnostic> {
        let register = format!("r{register}");
        match scalar_width(&self.model, ty)? {
            1 => {
                self.line(&format!("    clr {register}"));
                self.line(&format!("    movb @>{address:04X}, {register}"));
                self.line(&format!("    swpb {register}"));
            }
            2 => self.line(&format!("    mov @>{address:04X}, {register}")),
            _ => return Err(Diagnostic::new("TMS9900 source values must fit in 16 bits")),
        }
        Ok(())
    }

    fn store_r0(&mut self, storage: Storage, ty: &Type) -> Result<(), Diagnostic> {
        self.store_r0_address(storage.address, ty)
    }

    fn store_r0_address(&mut self, address: u32, ty: &Type) -> Result<(), Diagnostic> {
        match scalar_width(&self.model, ty)? {
            1 => {
                self.line("    swpb r0");
                self.line(&format!("    movb r0, @>{address:04X}"));
                self.line("    swpb r0");
            }
            2 => self.line(&format!("    mov r0, @>{address:04X}")),
            _ => return Err(Diagnostic::new("TMS9900 source values must fit in 16 bits")),
        }
        Ok(())
    }

    fn load_immediate(&mut self, value: i64) -> Result<(), Diagnostic> {
        if !(-32768..=65535).contains(&value) {
            return Err(Diagnostic::new(format!(
                "TMS9900 immediate `{value}` is outside 16 bits"
            )));
        }
        self.line(&format!("    li r0, >{:04X}", value as u16));
        Ok(())
    }

    fn bind(&mut self, name: String, binding: Binding) -> Result<(), Diagnostic> {
        let scope = self
            .scopes
            .last_mut()
            .ok_or_else(|| Diagnostic::new("local binding outside function"))?;
        if scope.insert(name.clone(), binding).is_some() {
            return Err(Diagnostic::new(format!("duplicate local `{name}`")));
        }
        Ok(())
    }

    fn binding(&self, name: &str) -> Option<Binding> {
        self.scopes
            .iter()
            .rev()
            .find_map(|scope| scope.get(name).cloned())
    }

    fn jump_loop(&mut self, continue_loop: bool) -> Result<(), Diagnostic> {
        let labels = self
            .loops
            .last()
            .ok_or_else(|| {
                Diagnostic::new(if continue_loop {
                    "continue outside loop"
                } else {
                    "break outside loop"
                })
            })?
            .clone();
        self.line(&format!(
            "    b @{}",
            if continue_loop {
                labels.continue_label
            } else {
                labels.break_label
            }
        ));
        Ok(())
    }

    fn next_label(&mut self, stem: &str) -> String {
        let label = format!("__ezra_{stem}_{}", self.labels);
        self.labels += 1;
        label
    }

    fn line(&mut self, line: &str) {
        self.out.push_str(line);
        self.out.push('\n');
    }
}

const TMS_LOCAL_REGISTERS: [u8; 3] = [6, 7, 8];
const TMS_SCALAR_WORD_CLASS: RegClass = RegClass(0);
const TMS_STACK_SPILL_CLASS: SpillClassId = SpillClassId(0);

fn tms_local_target() -> Target {
    Target {
        units: TMS_LOCAL_REGISTERS
            .iter()
            .map(|register| RegisterUnit::new(format!("r{register}")))
            .collect(),
        registers: TMS_LOCAL_REGISTERS
            .iter()
            .enumerate()
            .map(|(unit, register)| {
                PhysicalRegister::new(format!("r{register}"), vec![RegUnit(unit)])
            })
            .collect(),
        register_classes: vec![RegisterClass::new(
            "scalar-word",
            (0..TMS_LOCAL_REGISTERS.len()).map(PhysReg).collect(),
        )],
        spill_classes: vec![
            SpillClass::new("stack", None, 1)
                .with_base_alignment(2)
                .for_register_classes(vec![TMS_SCALAR_WORD_CLASS]),
        ],
    }
}

fn plan_function_frame(
    function: &Function,
    model: &SemanticModel,
) -> Result<FunctionFrame, Diagnostic> {
    let mut source_locals = Vec::new();
    let mut local_types = HashMap::new();
    collect_frame_locals(&function.body, model, &mut source_locals, &mut local_types)?;

    let clobbers = (0..TMS_LOCAL_REGISTERS.len())
        .map(PhysReg)
        .collect::<Vec<_>>();
    let planned = allocate_source_locals(
        &tms_local_target(),
        &source_locals,
        &function.body,
        &clobbers,
    )
    .map_err(|diagnostics| {
        Diagnostic::new(
            diagnostics
                .into_iter()
                .map(|diagnostic| diagnostic.message)
                .collect::<Vec<_>>()
                .join("; "),
        )
    })?;

    let spill_bytes = planned
        .allocation
        .spill_slots
        .iter()
        .map(|slot| slot.offset.saturating_add(slot.size))
        .max()
        .unwrap_or(0);
    let local_bytes = u16::try_from(spill_bytes)
        .map_err(|_| Diagnostic::new("TMS9900 function frame is too large"))?;
    let mut locals = HashMap::new();
    for (name, ty) in local_types {
        let vreg = planned
            .locals
            .vreg(&name)
            .ok_or_else(|| Diagnostic::new(format!("missing allocation for local `{name}`")))?;
        let location = match planned.allocation.location(vreg) {
            Some(Location::Register(register)) => {
                let register = *TMS_LOCAL_REGISTERS.get(register.0).ok_or_else(|| {
                    Diagnostic::new(format!("invalid TMS9900 local register for `{name}`"))
                })?;
                BindingLocation::Register(register)
            }
            Some(Location::Spill(slot_index)) => {
                let slot = planned
                    .allocation
                    .spill_slots
                    .get(slot_index)
                    .ok_or_else(|| Diagnostic::new(format!("invalid spill slot for `{name}`")))?;
                debug_assert_eq!(slot.class, TMS_STACK_SPILL_CLASS);
                let end = slot
                    .offset
                    .checked_add(slot.size)
                    .ok_or_else(|| Diagnostic::new("TMS9900 function frame is too large"))?;
                let offset = i16::try_from(end)
                    .ok()
                    .and_then(|end| end.checked_neg())
                    .ok_or_else(|| Diagnostic::new("TMS9900 function frame is too large"))?;
                BindingLocation::Frame(offset)
            }
            Some(Location::Unused) | None => {
                return Err(Diagnostic::new(format!(
                    "source allocator did not place local `{name}`"
                )));
            }
        };
        locals.insert(name, Binding { location, ty });
    }

    Ok(FunctionFrame {
        locals,
        local_bytes,
    })
}

fn collect_frame_locals(
    body: &[Stmt],
    model: &SemanticModel,
    locals: &mut Vec<SourceLocal>,
    local_types: &mut HashMap<String, Type>,
) -> Result<(), Diagnostic> {
    for stmt in body {
        match stmt {
            Stmt::Let { name, ty, .. } => {
                let ty = model.resolved_type(ty)?;
                let aggregate = matches!(&ty, Type::Array { .. })
                    || matches!(&ty, Type::Named(name) if model.structs.contains_key(name));
                let size = if aggregate {
                    model
                        .type_size(&ty)?
                        .checked_add(1)
                        .map(|size| size & !1)
                        .ok_or_else(|| Diagnostic::new("TMS9900 function frame is too large"))?
                        .max(2)
                } else {
                    scalar_width(model, &ty)?;
                    2
                };
                if local_types.insert(name.clone(), ty).is_some() {
                    return Err(Diagnostic::new(format!("duplicate local `{name}`")));
                }
                locals.push(
                    SourceLocal::new(name.clone(), size, 2, TMS_SCALAR_WORD_CLASS)
                        .with_spill_classes(vec![TMS_STACK_SPILL_CLASS])
                        .with_force_memory(aggregate),
                );
            }
            Stmt::If {
                then_body,
                else_body,
                ..
            } => {
                collect_frame_locals(then_body, model, locals, local_types)?;
                collect_frame_locals(else_body, model, locals, local_types)?;
            }
            Stmt::While { body, .. } | Stmt::Loop { body } => {
                collect_frame_locals(body, model, locals, local_types)?;
            }
            _ => {}
        }
    }
    Ok(())
}

fn reachable_function_names(program: &Program, model: &SemanticModel) -> HashSet<String> {
    let mut graph = HashMap::new();
    let mut roots = vec!["main".to_owned()];
    for declaration in &program.declarations {
        match declaration {
            Declaration::Function(function) => {
                let mut calls = Vec::new();
                collect_stmt_calls(&function.body, &mut calls);
                graph.insert(
                    function.name.clone(),
                    calls
                        .into_iter()
                        .filter_map(|path| resolve_called_function(&path, model))
                        .collect::<Vec<_>>(),
                );
            }
            Declaration::Global(global) => {
                let mut calls = Vec::new();
                collect_expr_calls(&global.value, &mut calls);
                roots.extend(
                    calls
                        .into_iter()
                        .filter_map(|path| resolve_called_function(&path, model)),
                );
            }
            _ => {}
        }
    }

    let mut reachable = HashSet::new();
    let mut pending = roots;
    while let Some(name) = pending.pop() {
        if !reachable.insert(name.clone()) {
            continue;
        }
        if let Some(calls) = graph.get(&name) {
            pending.extend(calls.iter().cloned());
        }
    }
    reachable
}

fn recursive_function_names(program: &Program, model: &SemanticModel) -> HashSet<String> {
    let mut graph = HashMap::new();
    for declaration in &program.declarations {
        if let Declaration::Function(function) = declaration {
            let mut calls = Vec::new();
            collect_stmt_calls(&function.body, &mut calls);
            graph.insert(
                function.name.clone(),
                calls
                    .into_iter()
                    .filter_map(|path| resolve_called_function(&path, model))
                    .collect::<Vec<_>>(),
            );
        }
    }

    let mut recursive = HashSet::new();
    for (caller, callees) in &graph {
        for callee in callees {
            if function_reaches(callee, caller, &graph) {
                recursive.insert(caller.clone());
                recursive.insert(callee.clone());
            }
        }
    }
    recursive
}

fn function_reaches(start: &str, destination: &str, graph: &HashMap<String, Vec<String>>) -> bool {
    let mut visited = HashSet::new();
    let mut pending = vec![start];
    while let Some(function) = pending.pop() {
        if function == destination {
            return true;
        }
        if !visited.insert(function) {
            continue;
        }
        if let Some(callees) = graph.get(function) {
            pending.extend(callees.iter().map(String::as_str));
        }
    }
    false
}

fn resolve_called_function(path: &[String], model: &SemanticModel) -> Option<String> {
    path.last()
        .filter(|name| model.functions.contains_key(*name))
        .cloned()
}

fn collect_stmt_calls(stmts: &[Stmt], calls: &mut Vec<Vec<String>>) {
    for stmt in stmts {
        match stmt {
            Stmt::Let { value, .. } | Stmt::Return(Some(value)) | Stmt::Expr(value) => {
                collect_expr_calls(value, calls);
            }
            Stmt::Assign { target, value, .. } => {
                collect_place_calls(target, calls);
                collect_expr_calls(value, calls);
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                collect_expr_calls(condition, calls);
                collect_stmt_calls(then_body, calls);
                collect_stmt_calls(else_body, calls);
            }
            Stmt::While { condition, body } => {
                collect_expr_calls(condition, calls);
                collect_stmt_calls(body, calls);
            }
            Stmt::Loop { body } => collect_stmt_calls(body, calls),
            Stmt::Out { value, .. } => collect_expr_calls(value, calls),
            Stmt::Return(None) | Stmt::Break | Stmt::Continue | Stmt::Asm { .. } => {}
        }
    }
}

fn collect_place_calls(place: &Place, calls: &mut Vec<Vec<String>>) {
    match place {
        Place::Index { index, .. } | Place::Deref(index) => collect_expr_calls(index, calls),
        Place::Access(path) => collect_access_path_calls(path, calls),
        Place::Ident(_) | Place::Field { .. } => {}
    }
}

fn collect_expr_calls(expr: &Expr, calls: &mut Vec<Vec<String>>) {
    match expr {
        Expr::Array(values) => {
            for value in values {
                collect_expr_calls(value, calls);
            }
        }
        Expr::Index { index, .. } | Expr::AddressOfIndex { index, .. } => {
            collect_expr_calls(index, calls);
        }
        Expr::Access(path) | Expr::AddressOfAccess(path) => collect_access_path_calls(path, calls),
        Expr::StructInit { fields, .. } => {
            for (_, value) in fields {
                collect_expr_calls(value, calls);
            }
        }
        Expr::Deref(value)
        | Expr::BankedPointer { pointer: value, .. }
        | Expr::Unary { expr: value, .. }
        | Expr::Cast { expr: value, .. } => {
            collect_expr_calls(value, calls);
        }
        Expr::Call { path, args } => {
            calls.push(path.clone());
            for arg in args {
                collect_expr_calls(arg, calls);
            }
        }
        Expr::Binary { left, right, .. } => {
            collect_expr_calls(left, calls);
            collect_expr_calls(right, calls);
        }
        Expr::Int(_)
        | Expr::TypedInt(_, _)
        | Expr::Bool(_)
        | Expr::Char(_)
        | Expr::String(_)
        | Expr::Ident(_)
        | Expr::In(_)
        | Expr::Field { .. }
        | Expr::AddressOfField { .. }
        | Expr::AddressOf(_) => {}
    }
}

fn collect_access_path_calls(path: &AccessPath, calls: &mut Vec<Vec<String>>) {
    for segment in &path.segments {
        if let AccessSegment::Index(index) = segment {
            collect_expr_calls(index, calls);
        }
    }
}

fn collect_program_strings(
    program: &Program,
    reachable: &HashSet<String>,
    values: &mut HashSet<String>,
) {
    for declaration in &program.declarations {
        match declaration {
            Declaration::Function(function) if reachable.contains(&function.name) => {
                collect_stmt_strings(&function.body, values);
            }
            Declaration::Global(global) => collect_expr_strings(&global.value, values),
            _ => {}
        }
    }
}

fn collect_stmt_strings(body: &[Stmt], values: &mut HashSet<String>) {
    for stmt in body {
        match stmt {
            Stmt::Let { value, .. } | Stmt::Return(Some(value)) | Stmt::Expr(value) => {
                collect_expr_strings(value, values);
            }
            Stmt::Assign { target, value, .. } => {
                match target {
                    Place::Index { index, .. } | Place::Deref(index) => {
                        collect_expr_strings(index, values);
                    }
                    Place::Access(path) => collect_access_path_strings(path, values),
                    Place::Ident(_) | Place::Field { .. } => {}
                }
                collect_expr_strings(value, values);
            }
            Stmt::If {
                condition,
                then_body,
                else_body,
            } => {
                collect_expr_strings(condition, values);
                collect_stmt_strings(then_body, values);
                collect_stmt_strings(else_body, values);
            }
            Stmt::While { condition, body } => {
                collect_expr_strings(condition, values);
                collect_stmt_strings(body, values);
            }
            Stmt::Loop { body } => collect_stmt_strings(body, values),
            Stmt::Out { value, .. } => collect_expr_strings(value, values),
            Stmt::Return(None) | Stmt::Break | Stmt::Continue | Stmt::Asm { .. } => {}
        }
    }
}

fn collect_expr_strings(expr: &Expr, values: &mut HashSet<String>) {
    match expr {
        Expr::String(value) => {
            values.insert(value.clone());
        }
        Expr::Array(items) => {
            for item in items {
                collect_expr_strings(item, values);
            }
        }
        Expr::Index { index, .. } | Expr::AddressOfIndex { index, .. } => {
            collect_expr_strings(index, values);
        }
        Expr::Access(path) | Expr::AddressOfAccess(path) => {
            collect_access_path_strings(path, values);
        }
        Expr::StructInit { fields, .. } => {
            for (_, value) in fields {
                collect_expr_strings(value, values);
            }
        }
        Expr::Deref(value)
        | Expr::BankedPointer { pointer: value, .. }
        | Expr::Unary { expr: value, .. }
        | Expr::Cast { expr: value, .. } => {
            collect_expr_strings(value, values);
        }
        Expr::Call { args, .. } => {
            for arg in args {
                collect_expr_strings(arg, values);
            }
        }
        Expr::Binary { left, right, .. } => {
            collect_expr_strings(left, values);
            collect_expr_strings(right, values);
        }
        Expr::Int(_)
        | Expr::TypedInt(_, _)
        | Expr::Bool(_)
        | Expr::Char(_)
        | Expr::Ident(_)
        | Expr::In(_)
        | Expr::Field { .. }
        | Expr::AddressOfField { .. }
        | Expr::AddressOf(_) => {}
    }
}

fn collect_access_path_strings(path: &AccessPath, values: &mut HashSet<String>) {
    for segment in &path.segments {
        if let AccessSegment::Index(index) = segment {
            collect_expr_strings(index, values);
        }
    }
}

fn scalar_width(model: &SemanticModel, ty: &Type) -> Result<u8, Diagnostic> {
    match model.type_width(ty)? {
        1 | 2 => model.type_width(ty),
        _ => Err(Diagnostic::new("TMS9900 source values must fit in 16 bits")),
    }
}

fn type_is_signed(ty: &Type) -> bool {
    matches!(ty, Type::Named(name) if name == "i8" || name == "i16")
}

fn constant_shift_count(expr: &Expr) -> Result<Option<u16>, Diagnostic> {
    let value = match expr {
        Expr::Int(value) | Expr::TypedInt(value, _) => *value,
        _ => return Ok(None),
    };
    u16::try_from(value).map(Some).map_err(|_| {
        Diagnostic::new(format!(
            "TMS9900 shift count {value} is outside supported range 0..=65535"
        ))
    })
}

fn assign_binary(op: AssignOp) -> BinaryOp {
    match op {
        AssignOp::Set => unreachable!("set assignments bypass binary lowering"),
        AssignOp::Add => BinaryOp::Add,
        AssignOp::Sub => BinaryOp::Sub,
        AssignOp::Mul => BinaryOp::Mul,
        AssignOp::Div => BinaryOp::Div,
        AssignOp::Mod => BinaryOp::Mod,
        AssignOp::BitAnd => BinaryOp::BitAnd,
        AssignOp::BitOr => BinaryOp::BitOr,
        AssignOp::BitXor => BinaryOp::BitXor,
        AssignOp::Shl => BinaryOp::Shl,
        AssignOp::Shr => BinaryOp::Shr,
    }
}

fn inline_void_body(function: &Function) -> Option<&[Stmt]> {
    if !function.params.is_empty()
        || function.return_type.is_some()
        || function
            .attrs
            .iter()
            .any(|attr| attr == "naked" || attr == "interrupt")
    {
        return None;
    }
    let body = if matches!(function.body.last(), Some(Stmt::Return(None))) {
        &function.body[..function.body.len() - 1]
    } else {
        &function.body
    };
    body.iter()
        .all(|stmt| matches!(stmt, Stmt::Expr(_)))
        .then_some(body)
}

fn tms_compact_wrapper_candidate(function: &Function) -> bool {
    let Some(body) = inline_void_body(function) else {
        return false;
    };
    body.is_empty()
        || matches!(
            body,
            [Stmt::Expr(Expr::Call { args, .. })] if args.is_empty()
        )
}

fn sanitize_label(name: &str) -> String {
    name.replace(|ch: char| !ch.is_ascii_alphanumeric() && ch != '_', "_")
}

fn function_label(name: &str) -> String {
    format!("_{}", sanitize_label(name))
}

fn embed_label(name: &str) -> String {
    format!("__ezra_embed_{}", sanitize_label(name))
}

fn embed_end_label(name: &str) -> String {
    format!("{}_end", embed_label(name))
}

#[cfg(test)]
mod tests;
