id = "ezra"
name = "Ezra"
version = "0.1.2"
schema_version = 1
authors = ["Ezra contributors"]
description = "Ezra language support."
repository = "https://github.com/isaiahpettingill/ezrac"

[grammars.ezra]
repository = "https://github.com/isaiahpettingill/ezrac"
rev = "af76af767ef0227d93fe714d8771b02c730f7b27"
path = "editors/tree-sitter-ezra"

[grammars.ezra_asm]
repository = "https://github.com/isaiahpettingill/ezrac"
rev = "af76af767ef0227d93fe714d8771b02c730f7b27"
path = "editors/tree-sitter-ezra-asm"

[language_servers.ezra-lsp]
name = "EZRA Language Server"
languages = ["Ezra", "Ezra Assembly"]
