[project]
name = "Arduboy PNG Assets"

[build]
target = "arduboy-atmega32u4"
output = "hex"
executable = "PNGASSET"
input = "src/main.ezra"

[[assets.images]]
path = "assets/ship.png"
kind = "sprite"
