id = "ezra"
name = "Ezra"
version = "0.1.0"
schema_version = 1
authors = ["Ezra contributors"]
description = "Ezra language support."
repository = "https://github.com/isaiahpettingill/ezrac"

[grammars.ezra]
repository = "https://github.com/isaiahpettingill/ezrac"
rev = "cfbeb43f9d09cd44e37b7d7ea32338a109406393"
path = "editors/tree-sitter-ezra"

[language_servers.ezra-lsp]
name = "EZRA Language Server"
languages = ["Ezra"]
