[project]
name = "gameboy-color-input"

[build]
input = "src/main.ezra"
target = "gameboy-color-lr35902"
output = "gb"

[assets]
section = ".assets"
align = 16

[assets.targets."gameboy-*"]
section = ".rodata"
align = 16
